pytorch/test-infra

.github/workflows/update_slow_tests.yml
Based on the working https://github.com/janeyx99/test-infra/blob/main/.github/workflows/update_slow_tests.yml.
This workflow will place the `.pytorch-slow-tests` file in a `stats` folder.
=> Add GHA to update slow test stats

.github/workflows/update_slow_tests.yml
Would resolve a broken run such as: https://github.com/pytorch/test-infra/actions/runs/720431754
Bigger question: is there a team email/team git user we could use?
=> Fix update slow tests GHA workflow by using legit username/email

fbossci-aws-lambas/us-east-1/github-status-webhook-handler/lambda_function.py
Currently, [the HUD](https://ezyang.github.io/pytorch-ci-hud/build2/pytorch-master) has a bunch of columns (whose names are those of GHA jobs without their workflow names) that are empty except for a bunch of yellow question marks:
It looks like this is caused because the lambda somehow fails to get the workflow name for some jobs that have not yet finished (although not for all such jobs, since there are still some question marks in the correct columns). This PR disables pushing to S3 when the workflow name can't be found, to get rid of those near-empty columns.
=> Drop GHA jobs unless workflow name is found

clang-tidy-checks/README.md, clang-tidy-checks/potential-unbounded-loop-check.diff, clang-tidy-checks/setup.sh
Summary:
This PR provides a setup script that patches LLVM (v11) with a `potential-unbounded-loop check`
- Diff that adds a `potential-unbounded-loop` check to `clang-tidy`
- Setup script that clones, builds, and patches LLVM
Test Plan:
- The diff includes two test files
- `clang-tools-extra/test/clang-tidy/misc-potential-unbounded-loop.cpp`: Autogenerated using a python script (`clang-tools-extra/clang-tidy/misc/gen_potential_unbounded_loop_test.py`
- `clang-tools/extra/test/clang-tidy/misc-potential-unbounded-loop-extra.cpp`: Tests for false positives
=> Add potential-unbounded-loop check patch and setup script

fbossci-aws-lambas/us-east-1/github-status-webhook-handler/lambda_function.py
html_url should give a link to the overall workflow instead of just the
job page. the overall workflow should give us a better idea of things
that have failed / passed
=> prefer html_url over details_url

.github/workflows/push_ci_docker_base.yml, ci-docker-base/Dockerfile.cilint-clang-tidy
Add a ci-clang-tidy base docker image to speed up the CI Lint. This shortens 8mins to 4mins.
Previous docker build with PR `GITHUB_TOKEN` permission failed at the last step of pushing the image to github container registry, will verify if it works when merged into master
https://github.com/pytorch/test-infra/runs/2671207595?check_suite_focus=true
By default, the permissive action's default `GITHUB_TOKEN` should be able to write to the github container registry from `master` branch.
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
=> Add docker base push job

.github/workflows/deploy_checks_lambda.yml, .gitignore, fbossci-aws-lambas/us-east-1/checks-cron/Makefile, fbossci-aws-lambas/us-east-1/checks-cron/lambda_function.py, fbossci-aws-lambas/us-east-1/checks-cron/requirements.txt
This lambda is intended to be run on a CloudWatch event that fires every few minutes or so, the lambda itself handles debouncing so it does not write data sooner than 5 minutes from the previous entry. It will append to a single `status.json` file the latest results from GitHub's workflows API. It crawls through pages of results from GitHub until it sees that all the jobs on that page are `completed` and records the counts of each into `status.json`.
=> Add lambda to store GitHub Actions status

clang-tidy-checks/max-tokens-check.diff
Summary:
This PR adds FixIt hints to the max-tokens-check.
Notes:
- The fix is suggested only if the file has a `#pragma clang max_tokens_{here,total}` defined.
- Running `clang-tidy` with `--export-fixes` also includes warnings. We can use a script to parse the yaml file and pre-pend the pragmas in the necessary files for cases in which auto-fixing doesn't work
=> Add FixItHint to max-tokens-check

.github/workflows/push_ci_docker_base.yml
Summary:
This fix should (fingers crossed) make the `push_ci_docker_base` action to successfully run again
=> Update github workflow to use clang-tidy-checks dir

.gitignore, auth.pytorch.org/README.md, auth.pytorch.org/files/docker-compose.yml, auth.pytorch.org/files/http.conf, auth.pytorch.org/install.yml, auth.pytorch.org/provision.tf
See the README for details. This adds a simple server to proxy OAuth tokens for hud.pytorch.org. The setup flow is:
1. terraform creates instance
2. ansible installs docker, builds gatekeeper image, runs it
It's already up at [auth.pytorch.org](https://auth.pytorch.org)
=> Add auth.pytorch.org setup scripts

ci-docker-base/Dockerfile.cilint-clang-tidy
GHA requires git version >= 2.18 to clone correctly.
This PR attempts to fix the following lint failure (https://github.com/pytorch/pytorch/runs/2822676682?check_suite_focus=true)
=> Install higher git version on docker image

.github/workflows/update_disabled_tests.yml
Move the update-disabled-tests workflow to test-infra to alleviate queuing problems on pytorch.
Tested on a PR: https://github.com/pytorch/test-infra/pull/38/checks?check_run_id=2824103075
=> Move update-disabled-tests workflow to test-infra

ci-docker-base/Dockerfile.cilint-clang-tidy
This change installs pytorch's python dependencies into the Docker image. It does this by downloading [requirements.txt](https://raw.githubusercontent.com/pytorch/pytorch/master/requirements.txt) from master, and then pip installing from it. 
Relevant python packages, and why we `apt-get` them:
- `python3-setuptools`
Doesn't come pre-installed when we apt-get python. Some requirements fail to build if we do not install this beforehand.
- `python3-wheel`
`error: invalid command 'bdist_wheel'` surfaces without this package. It doesn't cause the build to fail however.
=> Install python deps inside Docker image

ci-docker-base/Dockerfile.cilint-clang-tidy, clang-tidy-checks/verify.sh
This change will link the clang-tidy binary in a way that it correctly access system headers.
Relevant links:
https://clang.llvm.org/docs/LibTooling.html#builtin-includes - Where clang tooling expects the headers to be at
=> Link clang-tidy so that it has access to missing system headers

ci-docker-base/Dockerfile.cilint-clang-tidy
PyTorch's distributed library imports `omp.h` a bunch so we need that header around for clang-tidy. `libomp-dev` provides it, so this adds that to the `apt install` of the Docker image. Once we merge this and land https://github.com/pytorch/pytorch/pull/60225, we can update the image tag in `lint.yml` and re-enable clang-tidy on master since all the errors we saw should be addressed.
Tested by running the clang command in the Docker image, seeing a failure, installing `libomp-dev`, running again and seeing no failure.
```bash
docker run -it test /bin/bash
clang-tidy -p build -config '{"InheritParentConfig": true, "Checks": " bugprone-*, -bugprone-forward-declaration-namespace, -bugprone-macro-parentheses, -bugprone-lambda-function-name, -bugprone-reserved-identifier, cppcoreguidelines-*, …
```
=> Install omp in clang-tidy docker image

ci-docker-base/Dockerfile.cilint-clang-tidy
See https://github.com/pytorch/pytorch/pull/60297
This one has to land and build on master before that PR can be tested + landed
=> Add unidiff to clang-tidy Dockerfile

ci-docker-base/Dockerfile.cilint-clang-tidy
This PR bumps the base image of the clang-tidy Dockerfile to use `cuda-11.2` and `ubuntu-20.04`. The advantage is that we'll have python 3.8 by default.
This fixes #45
One consequence of the update is that `libomp-dev` doesn't install its headers at `/usr/include`. It instead does it at `/usr/lib/llvm-11/include/openmp`. We will need to update the job in clang-tidy to include this path (which can now be done easily with the [`-I` option](https://github.com/pytorch/pytorch/pull/60745))
=> Bump docker base image

clang-tidy-checks/setup.sh
* #49 [test][do not merge] Test publishing clang-tidy binaries to s3 bucket
* #48 Modify job to publish clang-tidy binaries on S3
* **#47 Statically link clang-tidy binary**
This PR creates a statically linked `clang-tidy` binary. This will allow us to avoid having to worry about missing shared libraries when users download it.
Test Plan:
1. Build the docker image
```bash
docker build . --tag clang-tidy-static --file ./ci-docker-base/Dockerfile.cilint-clang-tidy
```
2. Copy the binary out of the image
```bash
image_id=$(docker create clang-tidy-static)
docker cp $image_id:/clang-tidy-checks/build/bin/clang-tidy ./clang-tidy
docker rm -v $image_id
```
3. Check if its a dynamic executable
```bash
ldd ./clang-tidy
```
Expected Output: …
=> Statically link clang-tidy binary

.github/workflows/update_disabled_tests.yml
There shouldn't be a label requirement for disabling tests. Currently, some tests aren't successfully disabled because they don't have `module: flaky-test` as a label, e.g., https://github.com/pytorch/pytorch/issues/61201
This will also allow us to disable other tests that aren't necessarily flaky, like for forward fixing in the future.
=> Remove label requirement for disabled tests

ci-docker-base/Dockerfile.cilint-clang-tidy, clang-tidy-checks/setup.sh
Summary:
This PR opts in to using v11.1.0 of clang's builtin includes. It does this by copying (instead of symlinking) our custom build clang-tidy binary. As per [this document](https://clang.llvm.org/docs/FAQ.html#id3), clang looks for its builtin includes relative to the location of the binary. By copying it into `/usr/bin`, we ensure that it cannot pick up our custom built headers which are located at `/clang-tidy-checks/build/lib/include/clang/11.0.0/include`. The clang-tidy runner script ensures that it will pick up the v11.1.0 header files.
Test Plan:
1. Build a docker image, and start an interactive session
```bash
docker build . -t ct-no-header-conflicts -f ci-docker-base/Dockerfile.cilint-clang-tidy
docker run -it ct-no-header-conflicts /bin/bash
```
2. Clone pytorch and run …
=> Fix clang header conflicts

clang-tidy-checks/setup.sh
* #58
* **#57**
This PR adds better support for compiling clang-tidy binaries on MacOS. Notably, the `-static` flag causes `clang` to fail when attempting to build on a Mac. This has been replaced with `-static-libgcc` and `-static-libstdc++`. 
Statically linking binaries on MacOS is [not straightforward](https://developer.apple.com/library/archive/qa/qa1118/_index.html) and Apple makes no guarantees on that front. Therefore, I opt into shipping a dynamically linked executable instead.
=> Add better support for building clang-tidy binaries on osx

.github/workflows/deploy_lambda_checks_cron.yml, .github/workflows/deploy_lambda_github_status_webhook_handler.yml, .github/workflows/deploy_lambda_scribe_proxy.yml, fbossci-aws-lambas/us-east-1/scribe-proxy/lambda_function.py
Related to https://github.com/pytorch/pytorch/issues/61632, this pr adds a lambda function that adds the `access_token` to the scribe api
=> Add scribe proxy lambda

.github/workflows/clang-tidy-macos.yml
This PR fixes the failed upload step of the MacOS clang-tidy build.
It won't cause the linux build to trigger (due to [workflow guards](https://github.com/pytorch/test-infra/blob/master/.github/workflows/clang-tidy-linux.yml)), and it won't affect the clang-tidy job on pytorch/pytorch (since we don't use the MacOS binary).
=> Fix path issue during aws upload of macos binary

.github/workflows/clang-tidy-linux.yml, .github/workflows/clang-tidy-macos.yml
Right now it builds on every PR even if the relevant files haven't changed
=> Filter paths on pull_request for clang-tidy

.github/workflows/metrics_pytorch_org.yml, .gitignore, aws/websites/metrics.pytorch.org/README.md, aws/websites/metrics.pytorch.org/files/dashboards/lambda_status.json, aws/websites/metrics.pytorch.org/files/docker-compose.yml, aws/websites/metrics.pytorch.org/files/grafana-provisioning/dashboards/dashboards.yml, aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/cloudwatch.yml, aws/websites/metrics.pytorch.org/files/grafana.ini, aws/websites/metrics.pytorch.org/files/http.conf, aws/websites/metrics.pytorch.org/install.yml, aws/websites/metrics.pytorch.org/provision.tf
This adds the provisioning steps for metrics.pytorch.org, which for now is a Docker Swarm with Nginx -> Grafana. See the README.md for details.
Tested deployment workflow in: https://github.com/pytorch/test-infra/pull/65/checks?check_run_id=3088283895 (`git push -f` deleted this check's output but it completed successfully)
=> Add metrics.pytorch.org

.gitattributes, aws/websites/squid-proxy/.gitignore, aws/websites/squid-proxy/.terraform.lock.hcl, aws/websites/squid-proxy/README.md, aws/websites/squid-proxy/main.tf, aws/websites/squid-proxy/squid/outputs.tf, aws/websites/squid-proxy/squid/squid.tf, aws/websites/squid-proxy/squid/user-data.sh, aws/websites/squid-proxy/squid/variables.tf, aws/websites/squid-proxy/variables.tf
Related to https://github.com/pytorch/pytorch/issues/61793
We are creating a simple squid cache proxy with terraform and aws resources that can help caching the common filetype of http egress traffic in pytorch CI.
=> Add squid proxy

.github/workflows/lambda_scribe_proxy.yml
The payload sometime is huge, increasing the memory from default (128 MB) to 256 MB.
Fix rare exception events like
```
Error: Runtime exited with error: signal: killed
Runtime.ExitError
```
=> Increase gh-ci-scribe-proxy memory size

aws/websites/metrics.pytorch.org/files/docker-compose.yml, aws/websites/metrics.pytorch.org/files/email_template.html, aws/websites/metrics.pytorch.org/files/grafana-provisioning/notifiers/email.yml, aws/websites/metrics.pytorch.org/files/grafana.ini, aws/websites/metrics.pytorch.org/install.yml
* #77
* #76
* **#75**
This adds the config for an SMTP server for notifications. For the actual usage it gets sent from a random gmail I made to my work email, which Butterfly sends to the chat group for [this group](https://fb.prod.workplace.com/groups/1125997287887834), so we can get notifications like we do other Butterfly alerts.
=> Add email notifications to metrics.pytorch.org

aws/websites/metrics.pytorch.org/README.md, aws/websites/metrics.pytorch.org/files/dashboards/lambda_status.json, aws/websites/metrics.pytorch.org/files/dashboards/squid_proxy_status.json
Steps to add or change grafana dashboards:
- Go to https://metrics.pytorch.org
- Edit the dashboards, or alerts directly within the dashboard
- Go to the settings page, and save the JSON
- Setup a PR and commit
This PR adds 3 alerts
- squid-proxy unhealth instances count (if >10 within 5min at 1min interval check)
- pytorch-probot errors count (if >10 within 5min at 1min interval check)
- scribe-proxy errors count (if >10 within 5min at 1min interval check)
=> Add alerts and modify the dashboards

tools/scripts/download-lambdas.py
To skip lambdas which are not stored on S3
=> Fix download-lambdas.py

.github/workflows/clang-tidy-linux.yml, .github/workflows/clang-tidy-macos.yml, .github/workflows/lambda_scribe_proxy.yml, .github/workflows/lint_actions.yml, README.md
This integrates [https://github.com/rhysd/actionlint](https://github.com/rhysd/actionlint) which checks workflow files for syntactic validity plus some extra GitHub Action specific semantics. If it sees that ShellCheck is installed it will also pull out each `run:` block and check it, so this integrates that as well.
Example failure: https://github.com/pytorch/test-infra/runs/3186195613
We can copy-paste this pretty much verbatim into pytorch/pytorch since actionlint finds workflow files automatically.
=> Lint actions

aws/websites/metrics.pytorch.org/files/dashboards/lambda_status.json, aws/websites/metrics.pytorch.org/files/dashboards/squid_proxy_status.json
- Use a slightly longer monitoring interval (from 30s to 1m) so that we can pull longer range of the graphs. E.g. 2 days or 7 days.
- Add network out metrics for runners
- Add nat gateway bytes out information
=> Fix dashboard intervals

.github/workflows/update_grafana_dashboards.yml, aws/websites/metrics.pytorch.org/update_dashboards.py
This adds a script that will check Grafana every 15 minutes and auto-push any dashboard changes. This is only there so we can keep our running Grafana instance and what we have in the repo in sync. If something is broken in the UI, we can still roll back by finding a good JSON in the git history then setting that on Grafana.
Tested by adding `on_pull_request:` and removing the `git push` from the final step: https://github.com/pytorch/test-infra/pull/88/checks?check_run_id=3185571549
=> Automate dashboard updates

.github/workflows/lambda_github_webhook_rds_sync.yml, .gitignore, aws/lambda/github-webhook-rds-sync/Makefile, aws/lambda/github-webhook-rds-sync/generate_schema.py, aws/lambda/github-webhook-rds-sync/lambda_function.py, aws/lambda/github-webhook-rds-sync/test_lambda.py, aws/lambda/github-webhook-rds-sync/utils.py, aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/mysql.yml
This is a webhook that can receive all GitHub webhooks for a repo and write them into a MySQL DB (the code is mostly db agnostic but uses a MySQL-specific feature to update rows in place).
The webhook handler assumes that the schema is already present in the DB, so if not then `python generate_schema.py` should be used. This reads in a bunch of hooks (the lambda has a flag to gather them to S3).
```bash
cd aws/lambda/github-webhook-rds-sync
mkdir -p hooks
aws s3 sync hooks s3://gha-artifacts/pytorch/pytorch/webhooks/<year>-<month>-<day>
export db_host=...
export db_user=...
export db_password=...
export gh_secret=abc
python generate_schema.py
```
After that the lambda has all it needs to work. The data itself is split into tables based on what GitHub tags as objects. Some items in a …
=> Add lambda to write webhooks to RDS

.github/workflows/update_disabled_tests.yml
Fixes #93
Test plan:
A snippet of the current disabled_tests.json getting sorted would be:
```
{
"incomplete_results": false,
"items": [
{
"active_lock_reason": null,
"assignee": null,
"assignees": [],
"author_association": "CONTRIBUTOR",
"body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/169923/workflows/d66ca278-d55c-462b-96cb-55623ce713f7/jobs/5472514/steps\r\n\r\n```\r\nMay 14 07:37:27 =================================== FAILURES ===================================\r\nMay 14 07:37:27 ______________ ParallelWorkersTest.testParallelWorkersShutdownFun ______________\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 self = <caffe2.python.parallel_workers_test.ParallelWorkersTest testMethod=testParallelWorkersShutdownFun>\r\nMay 14 07:37:27 \r\nMay 14 07:37:27     def …
=> Sort disabled_tests.json to reduce commits

.gitattributes, .github/scripts/generate_ci_workflows.py, .github/templates/deploy_lambda.yml.j2, .github/workflows/generated-checks-cron.yml, .github/workflows/generated-github_webhook_rds_sync.yml, .github/workflows/generated-rds-proxy.yml, .gitignore, aws/lambda/github-webhook-rds-sync/generate_schema.py, aws/lambda/github-webhook-rds-sync/lambda_function.py, aws/lambda/github-webhook-rds-sync/utils.py, aws/lambda/rds-proxy/Makefile, aws/lambda/rds-proxy/lambda_function.py
This adds a lambda to handle reading / writing to our RDS MySQL instance that we can access from the EC2 runners in CI. Similar to scribe-proxy, this means we can write on pull requests without a secret and also run queries to plan tests / etc.
This API has 3 functions:
1. `create`: register a new table with a particular schema. if a new `create` comes along with a different schema then the table will be updated to be the union of the two.
2. `write`: insert a record into a table
3. `read`: run a simple query that follows a regular pattern (`select X from Y limit Z`) or run a hardcoded, more complex query by name.
Sadly you can't parameterize parts of queries over schemas, so we're stuck doing raw string interpolation before running things on the DB. Risk is mitigated here by some …
=> Add RDS proxy lambda

aws/lambda/github-webhook-rds-sync/utils.py
Unlike most other URLs that GitHub's webhooks return, the status webhook's `target_url` cannot be constructed after the fact, so we need to be saving them instead of throwing them away.
Test Plan:
Deployed this to AWS, altered `status_event` db schema, see that https://fburl.com/w8cuccuo has data for `target_url`
=> Save URL for status events

aws/ami/windows/README.md, aws/ami/windows/scripts/Installers/Install-CUDA-Toolkit.ps1, aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1, aws/ami/windows/variables.pkr.hcl, aws/ami/windows/windows.pkr.hcl
Basically just a rewrite of this: https://github.com/pytorch/builder/blob/master/windows/internal/cuda_install.bat in powershell
TODO:
=> Add cuda install to base windows AMIs

.github/workflows/sync_pytorch_canary.yml
Our workflows (https://github.com/pytorch/test-infra/runs/3603114635?check_suite_focus=true) are failing with 
```
To github.com:pytorch/pytorch-canary
! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'github.com:pytorch/pytorch-canary'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
Because I locally pushed those changes when testing. Are we okay with doing a force push here?
=> Fix sync-pytorch-canary by using force push

.github/scripts/generate_ci_workflows.py, .github/templates/common.yml.j2, .github/templates/metrics_pytorch_org.yml.j2, .github/templates/update_grafana_dashboards.yml.j2, .github/workflows/generated-metrics-pytorch-org.yml, .github/workflows/generated-update-grafana-dashboards.yml
Without this step we have the risk of re-deploying dashboards before they get updated to the repo if they were updated in the last 15 minutes and a deploy is triggered. This also consolidates these down to templates
=> Update dashboards before deploying

tools/self-hosted-runner-utils/README.md, tools/self-hosted-runner-utils/check_runners_state.py, tools/self-hosted-runner-utils/clear_offline_runners.py
Adds a utility script to check the status of all self hosted runners
available on Github Actions for a particular repository
Output should look like:
```
❯ python check_runners_state.py pytorch/pytorch
Repository stats for pytorch/pytorch
129 total runners
129/129 online runners
Number of online runners per label
31 (24)% linux.8xlarge.nvidia.gpu
48 (37)% linux.2xlarge
37 (28)% windows.4xlarge
12 ( 9)% windows.8xlarge.nvidia.gpu
1 ( 0)% linux.16xlarge.nvidia.gpu
```
=> tools: Add check_runners_state.py

aws/websites/metrics.pytorch.org/install.yml
This was colliding when using auto-assignment for EC2 instances in the gh-ci-vpc
=> Fix subnet assignment for swarm

.github/workflows/lint.yml, .gitignore, aws/lambda/github-status-sync/Makefile, aws/lambda/github-status-sync/README.md, aws/lambda/github-status-sync/lambda_function.py, aws/lambda/github-status-sync/requirements.txt, mypy.ini
This re-writes the status lambda to use the GitHub API rather than webhooks. This makes it much easier to debug and work on and simpler to execute (we don't have to worry about concurrency anymore). This also makes it configurable via environment variables so we can run it for any repo (e.g. `vision`) and get that from the HUD in a predictable way.
Fixes #125
=> Add lambda to use GitHub API to get job statuses

.github/workflows/sync_pytorch_canary.yml
ShipIt is enabled for pytorch-canary now so we don't need to keep this workflow https://www.internalfb.com/intern/opensource/github/repo/1672688976258095/repo_settings/shipit/
=> Remove `master` from sync workflow

aws/websites/metrics.pytorch.org/update_dashboards.py
This was surfaced with the torch/benchmark dashboard, the filename just needs to be changed to something without a slash
=> Fix bug with `/` in filenames for updating dashboards

aws/websites/metrics.pytorch.org/files/docker-compose.yml, aws/websites/metrics.pytorch.org/files/http.conf
Remedy for Grafana issue https://grafana.com/blog/2021/11/03/grafana-8.2.3-released-with-medium-severity-security-fix-cve-2021-41174-grafana-xss/
=> Upgrade to Grafana 8.2.3

.github/workflows/update_disabled_tests.yml
The default for the query is 30, but we have ~73 disabled tests. Honestly, I'm not sure how we didn't catch this sooner :/ 
I will write a more robust query for the GHA after this PR, but this is an immediate fix.
=> Fix query for disabled tests

.github/scripts/update_disabled_tests.py, .github/workflows/update_disabled_tests.yml
Before, we had a one liner legacy query that was not able to handle more than 100 issues, which is a problem for our disable bot as we're nearing 100 issues!
=> Scale up disable bot to detect more than 100 issues

torchci/lib/bot/ciflowBot.ts, torchci/lib/bot/index.ts, torchci/package.json, torchci/test/ciflowBot.test.ts
Now that the push trigger is rolled out, we can take the opportunity to significantly simplify the ciflow bot logic. In particular:
- We do not need the dispatch or signaling stuff anymore, as the dispatch is handled through the push trigger.
- We do not need ciflow command parsing or handling anymore, since adding a label is sufficient to trigger workflow runs.
So what is retained is:
- User configuration handling; ciflow will populate initial labels based on configuration. Honestly, we could get rid of this; the tracking issue has only a single config. But keeping it for now.
- CIFlow comment is nice because it tells you what labels you need to add, so that stays.
- Now, if you try to give ciflow a command, it'll respond telling you not to bother.
=> Simplify ciflow bot

torchci/pages/minihud.tsx
Before, if you gave someone a link like torch-ci.com/minihud#4899572403 it would not set the highlighted style correctly. Fixing that.
=> Properly set highlighting when you first go to a link with a hash.

torchci/lib/types.ts, torchci/lib/useHudData.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[page].tsx, torchci/pages/minihud.tsx
Adding name filter to the route naively was triggering a refetch of the data, because the memoization key for requests had changed. This is unnecessary because the data fetched is the same regardless of name filter. Fix this by splitting our utils for formatting URLs into two kinds, URLs for routes (which need the name filter applied), and URLs for fetch (which don't care about name filter)
=> Fix hud reloading when you set name filter

torchci/lib/fetchCommit.ts, torchci/lib/fetchHud.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[page].tsx
Previously, we were only showing the head commit of a push, since that's what we run CI on. However, it's useful to see all commits in a push, just so we can see all commits on master and notice if there is a problem.
=> show stacked PRs in hud

torchci/lib/fetchHud.ts, torchci/lib/github.ts, torchci/lib/types.ts, torchci/package.json, torchci/yarn.lock
@malfet pointed out that the release/1.1 branch was totally borked after he force pushed it. This is because our Rockset query reconstructs the branch from the history of `push` webhooks. This works for master, which is append-only, but breaks for a branch that was force-pushed to.
We could probably fix this with fancy rockset queries, but it seems simpler to just ask GitHub for the branch history directly, and query rockset just for the SHAs we care about.
We use the PyTorch Bot app to authenticate GH requests. This is nice because:
- We have the same permissions as the bot, which we use to receive webhooks to populate our job data anyway.
- We have better rate limits without requiring user login, as GitHub Apps are allotted extra rate limits per user per repo they are installed to (see …
=> [hud] query GitHub to get branch information

torchci/pages/api/hud/[repoOwner]/[repoName]/[branch]/[page].ts
* __->__ #197
In certain cases (like the nightly branch), the payload size can get large enough that it breaks AWS Lambda's response size limit (6mb). Fortunately this data compresses extremely well, so just compress it in the lambda before sending the payload.
=> [hud] gzip hud api endpoint

torchci/lib/fetchFlakyTests.ts
this is a lambda update:
```
SELECT 
flaky_tests.name,
flaky_tests.suite,
flaky_tests.file,
flaky_tests._event_time,
sum(flaky_tests.num_green) AS "num_green",
sum(flaky_tests.num_red) AS "num_red",
ARRAY_AGG(flaky_tests.workflow_id) AS workflow_ids,
ARRAY_AGG(workflow.name) as workflow_names,
FROM commons.flaky_tests flaky_tests JOIN commons.workflow_run workflow on CAST(flaky_tests.workflow_id as int) = workflow.id
>>>>>>>>>>>>>>>>>>>>>>>>>>> THIS LINE CHANGED
WHERE flaky_tests._event_time > (CURRENT_DATE() - HOURs(:num_hours))
<<<<< TO THIS LINE
WHERE flaky_tests._event_time > (CURRENT_TIME() - HOURs(:num_hours))
>>>>>>>>>>>>>>>>>>>>>>>>>>> 
GROUP BY name, suite, file, _event_time
```
Fixes the problem where the bot kept picking up the same instance of flaky test in different cron …
=> Update flaky test lambda

torchci/pages/api/flaky-tests/disable.ts
* __->__ #201
Currently it looks like this https://github.com/pytorch/pytorch/issues/72892 because we accidentally are indenting. This fixes
=> fix indentation in flaky test bot message

torchci/lib/fetchFlakyTests.ts
Realized I was getting results for the query even after expanding to 24 hours and then realized this mistake.
this is another lambda update:
```
SELECT 
flaky_tests.name,
flaky_tests.suite,
flaky_tests.file,
flaky_tests._event_time,
sum(flaky_tests.num_green) AS "num_green",
sum(flaky_tests.num_red) AS "num_red",
ARRAY_AGG(flaky_tests.workflow_id) AS workflow_ids,
ARRAY_AGG(workflow.name) as workflow_names,
FROM commons.flaky_tests flaky_tests JOIN commons.workflow_run workflow on CAST(flaky_tests.workflow_id as int) = workflow.id
>>>>>>>>>>>>>>>>>>>>>>>>>>> THIS LINE CHANGED
WHERE flaky_tests._event_time > (CURRENT_TIME() - HOURs(:num_hours))
<<<<< TO THIS LINE
WHERE flaky_tests._event_time > (CURRENT_TIMESTAMP() - HOURs(:num_hours))
>>>>>>>>>>>>>>>>>>>>>>>>>>> 
GROUP BY name, suite, …
```
=> CURRENT_TIME is not the same as CURRENT_TIMESTAMP

torchci/components/GroupHudTableHeaders.tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[page].tsx
- This fixes issue #199 with making jobs searchable when doing the grouped view. It doesn't automatically expand it but will show you the groupings that contain the jobs
- Fixes an issue with hovering on a group/workflow. Now has a pointer instead of a cursor when hovering over a group (just swapped around)
See that I searched mac and "other" and "macOS Github Action" groups show up.
=> Fix job filter for grouped view

torchci/lib/fetchFlakyTests.ts, torchci/lib/types.ts, torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Following discussion in TreeHuggers, it is wisest to limit the bot's functionality for now to only disable trunk instances. Added unit tests for new functions
The stats will still contain info for all instances, though.
=> Only disable trunk flaky tests

torchci/components/GroupJobConclusion.tsx, torchci/components/NavBar.module.css, torchci/components/NavBar.tsx, torchci/lib/types.ts, torchci/pages/_app.tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This just adds a new nav bar, similar to the one found on the CI HUD. Major changes include:
- new nav bar
- going to /hud/pytorch/pytorch/master won't 404 anymore, and will default to the first page
- some css adjustments
Some additional features that I think we might want in the feature are:
- quick go to links for commits/prs
- logos?
-
=> [torch ci] Add a new Nav Bar 

torchci/lib/fetchFlakyTests.ts
This is mostly a query change:
```
SELECT 
flaky_tests.name,
flaky_tests.suite,
flaky_tests.file,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
flaky_tests._event_time,
<<<<<<<<<<<< DELETED
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sum(flaky_tests.num_green) AS "num_green",
sum(flaky_tests.num_red) AS "num_red",
ARRAY_AGG(flaky_tests.workflow_id) AS workflow_ids,
ARRAY_AGG(workflow.name) as workflow_names,
ARRAY_AGG(workflow.head_branch) as branches,
FROM commons.flaky_tests flaky_tests JOIN commons.workflow_run workflow on CAST(flaky_tests.workflow_id as int) = workflow.id
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
WHERE flaky_tests._event_time > (CURRENT_TIMESTAMP() - HOURs(:num_hours))
GROUP BY name, suite, file, _event_time
<<<<<<<<<<<< MODIFIED
WHERE 
flaky_tests._event_time > (CURRENT_TIMESTAMP() - HOURs(:num_hours)) …
```
=> Use upgraded query to allow for a view

torchci/lib/fetchFlakyTests.ts
The old query outputted things in snake case, so after my change in #209, flaky test bot has not been receiving the right stats. :c 
This would fix that. 
```
SELECT 
flaky_tests.name,
flaky_tests.suite,
flaky_tests.file,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sum(flaky_tests.num_green) AS num_green,
sum(flaky_tests.num_red) AS num_red,
ARRAY_AGG(flaky_tests.workflow_id) AS workflow_ids,
ARRAY_AGG(workflow.name) as workflow_names,
<<<<<<<<<<<<<< MODIFIED
sum(flaky_tests.num_green) AS numGreen,
sum(flaky_tests.num_red) AS numRed,
ARRAY_AGG(flaky_tests.workflow_id) AS workflowIds,
ARRAY_AGG(workflow.name) as workflowNames,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARRAY_AGG(workflow.head_branch) as branches,
FROM commons.flaky_tests flaky_tests JOIN commons.workflow_run …
```
=> Match query outputs with camelCase change

torchci/components/AnnouncementBanner.module.css, torchci/components/AnnouncementBanner.tsx, torchci/components/SevReport.module.css, torchci/lib/useTableFilter.ts, torchci/next.config.js, torchci/pages/_app.tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This does a few fixes in preparation for launching:
1. Add announcement banner on hud2 to redirect users back  
2. Add null checks for title so that it doesn't show Pytorch CI HUD (undefined/undefined: undefined) on page.tsx
3. Add a redirect for /ci/repoOwner/repoName/branch. Don't need to worry about paging cause old hud doesn't have paging 
4. Fix group view unchecked when filter is nonnull on page load
Check that view works with the given example of `/ci/pytorch/pytorch/nightly?name_filter=ci/circleci:%20binary_windows`. Only difference is some naming differences between hud and hud2 (we don't prefix it with circle_ci).
=> [torchci] Add missing paths

torchci/lib/bot/webhookToDynamo.ts
This adds ingestion of new webhook events for PR reviews since we need this data to get some metrics like 
P0: Time for a PR to be reviewed for external contributors under 2 business days 
P0: Time for a PR to be reviewed for the org is under 2 business days 
And maybe some of the PR merge stuff although maybe not.
=> [metrics] added ingestion of data related to PRs

torchci/scripts/checkRockset.mjs
Adding a secret to GHA doesn't work for workflows that run from forked
pull requests. To fix this, I created an API token with super-restricted
access to Rockset for use only in this CI workflow. It can only list
resources, it can't write to or even query our rockset instances.
=> fix checkRockset for forked PRs

torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/prodVersions.json
pytorch/pytorch was hardcoded, don't do that!
=> fix bad circleci job url

torchci/scripts/downloadQueryLambda.mjs
- If you don't specify a version number, the script will download the latest version.
- Some bugfixes for the case where we are downloading an entirely new query lambda
=> Improvements to download query lambda script

torchci/components/VersionControlLinks.tsx
When commit does not have a differential revision
Before the change [PyTorchCommit-21a82f5)(https://hud.pytorch.org/pytorch/pytorch/commit/21a82fb5194d2a079c752215a8f87e36ddc2f6b6) contained a link to `https://www.internalfb.com/diff/null`
=> Do not display "null" phab link

torchci/components/GroupHudTableHeaders.tsx, torchci/components/hud.module.css, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This just adds some additional padding in between the columns to make it more readable and also fixes some unused variables in the header.
Going forward, we should try to make any usages of px divisible by 4 to follow CSS standards from FB.
=> [torchci] Padding fixes to columns

torchci/lib/bot/ciflowPushTrigger.ts, torchci/lib/bot/index.ts
* __->__ #257
* #258
Three changes in this PR:
1. Disable the CIFlow comment, to reduce noise. I don't think it's very useful anymore, because:
- The labels have been drastically simplified
- The info is static for every PR and inferrable by just looking at the relevant workflow.
- The information has been inaccurate for weeks and no one noticed lol (it says binary builds are default-triggered when they are not)
2. Disable some of the smaller parts of CIFlow functionality: adding ciflow/default (which hasn't done anything for a while), disable automatic label adding based on the issue (functionality only used by a single person, who I will reach out to).
3. Tell people if they use an obsolete tag and give them a list of working …
=> bot changes for workflow consolidation.

torchci/components/CommitStatus.tsx, torchci/components/VersionControlLinks.tsx, torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
Also, render https://github.com/pytorch/vision commits as `TorchVision commit` and so on
Test Plan: Open [vision@1af20e8c](https://hud.pytorch.org/pytorch/vision/commit/1af20e8c232c7769b3875804e31e3e11cfddef39) and click on "GitHub" link
=> [HUD] Post correct GitHub link in commit view

torchci/lib/github.ts, torchci/lib/types.ts, torchci/lib/useHudData.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/commons/__sql/original_pr_hud_query.sql, torchci/rockset/prodVersions.json
For author names, use the GH commit data instead of plumbing author info through the original pr hud query
=> [ci] make author name per commit

torchci/lib/fetchS3Links.ts
As we have a lot of `artifacts.zip` in one workflow right now
Test plan: Open https://torchci-git-malfet-add-folder-name-to-artifacts-torchci.vercel.app/pytorch/pytorch/commit/1dab71ab258df5168bb635530a820625f9d4b522
=> [HUD] Add folder name to `artifacts.zip`

torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
Add link to the github pr on the pr page
Before:
After:
=> [hud] add link to github pr on pr page

torchci/components/NavBar.tsx, torchci/components/hud.module.css, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
See title. Also moving MiniHUD link to the top left so that repos/branches are all together.
=> [torch ci][ez] resize and move minihud link

torchci/lib/bot/mergeBot.ts, torchci/test/mergeBot.test.ts
Mentioning merge/revert command in the middle of sentence (and
specifically quoting it) should not trigger bot
Fixes https://github.com/pytorch/test-infra/issues/278
=> [MergeBot] Restrict merge/revert cmd scope

torchci/components/AnnouncementBanner.tsx
Remove announcement for HUD deprecation. On April 4th, we will:
1. Land this change
2. Remove HUD2 from netlify / remove DNS mapping
3. Archive hud project
Check that there's no banner:
=> [torch ci] remove announcement

torchci/lib/JobClassifierUtil.ts, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/__sql/original_pr_hud_query.sql, torchci/rockset/prodVersions.json
During the transition to the consolidated workflow setup, we mapped, e.g. `pull / mytest` to `mytest` so that naming would be consistent across the transition. Now that we are fully migrated over, revert to reporting workflow and name normally.
=> [hud] revert naming change

torchci/pages/api/flaky-tests/disable.ts, torchci/pages/flakytest.tsx, torchci/rockset/commons/__sql/flaky_test_query.sql, torchci/rockset/prodVersions.json, torchci/test/disableFlakyBot.test.ts
Also addresses some other stuff in https://github.com/pytorch/pytorch/issues/71005#issuecomment-1062216629
- % to `<any>`
- Delete #green and #red since those are misleading and unuseful so far
- Use workflow job names
- Use workflow job URLs
Yes, it still looks meh but one small step at a time!
=> [torchci] [flakytest] Change flaky test view to link to job instead of workflow

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/__sql/original_pr_hud_query.sql, torchci/rockset/prodVersions.json
If a workflow is triggered from `workflow_run`, it's `sha` is set to the current master SHA, regardless of the original workflow that triggered it. That makes it seem like that the workflow ran *on* that SHA which is misleading. Exclude such jobs from our HUD queries.
We'll need to do the same for metrics. I guess that's yet another reason to move the metrics to the HUD where it's easy to update everything at once.
=> Exclude workflow_run-triggered workflows from HUD queries

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/master_commit_red.sql, torchci/rockset/prodVersions.json
As previously discussed, we want to include some notion of commit volume in this chart. This introduces a stacked bar chart where the y-axis is number of commits. The tooltip shows percents.
=> [metrics] visualize red commits as a stacked bar chart

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/master_commit_red.sql, torchci/rockset/metrics/master_commit_red.lambda.json, torchci/rockset/prodVersions.json
This always bothered me; the buckets on the "Commits red by day" chart
were always aggregated on UTC time. This is against the user
expectation, which is that times should reflect the local timezone. This
was not fixable in grafana, but can be here! Yay.
=> [metrics] small timezone fix

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/master_commit_red.sql, torchci/rockset/prodVersions.json
This chart was a little confusing--the most recent day tends to have
very few commits represented, since most jobs are still pending. This
adds a third bar in the stacked chart for "pending" commits.
Also some cleanups to make the sql a little nicer.
=> [metrics] add pending jobs to master commit red chart

torchci/components/LogViewer.tsx, torchci/package.json, torchci/tsconfig.json, torchci/yarn.lock
Quality of life improvement. Before we just displayed the escape
characters raw, now actually colorize (and make them bold, etc.)
properly!
Before: 
After:
=> [hud] handle ansi colors properly in log viewer

torchci/components/LogViewer.tsx, torchci/lib/JobClassifierUtil.ts
- Always show the log viewer on failures, even if we don't have a classification.
- Use folds to hide uninteresting log content (really helps with log readability)
=> [hud] more log improvements

torchci/rockset/metrics/__sql/queued_jobs.sql, torchci/rockset/prodVersions.json
This way we are more alarmed by our long queue times and things become more actionable
=> [metrics] Show queue times in descending order instead of ascending

torchci/components/NavBar.tsx
metrics.pytorch.org will eventually be deprecated and it was a surprise
to me that the metrics link in the navbar took me to it. This just
changes the hyperlink to point to metrics in the hud instead of grafana
=> torchci: Switch metrics to hud metrics

torchci/lib/bot/mergeBot.ts, torchci/test/mergeBot.test.ts
Turns out the . in regex doesn't cover line terminators! This causes undesired behavior like https://github.com/pytorch/pytorch/pull/74596#issuecomment-1113457935.
=> Fix revert reason regex

torchci/components/flakytest.module.css, torchci/pages/api/flaky-tests/flakytest.ts, torchci/pages/flakytest.tsx
Since people are most likely using flaky tests view for singular tests and not a bunch of tests, we should not use the table format. 
OLD
NEW
Next steps:
- Get the log viewer! (I think I know how to do this @suo)
=> [flaky test view] Optimize for singular flaky tests

.git-blame-ignore-revs
Adds an ignore revs file to make blame a bit easier to user after my big
formatting PR
=> be: Add blame ignore revs

torchci/rockset/metrics/__sql/queued_jobs_by_label.sql, torchci/rockset/prodVersions.json
The actual length of the queue is the maximum queueing time, not the
average. So report the max
=> [metrics] report queued jobs by max, not avg

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/__sql/original_pr_hud_query.sql, torchci/rockset/prodVersions.json
Those are usually triggered by probot and they have nothing to do with
the sha they are running on
=> Exclude `repository_dispatch` triggered workflows from HUD

torchci/README.md, torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/queued_jobs.sql, torchci/rockset/metrics/__sql/queued_jobs_by_label.sql, torchci/rockset/prodVersions.json, torchci/scripts/uploadQueryLambda.mjs
Our CI sometimes has labels like `[x]`, and sometimes like
`[self-hosted, x]`. The `[self-hosted, x]` formulation is recommended by
GitHub:
https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-self-hosted-runners-in-a-workflow
But they are equivalent from the perpsective of metrics. So clean things
up by unpacking the label so that `[x]` and `[self-hosted, x]` turn into
the same thing.
I also added a convenience script uploading your local SQL and syncing
`prodVersions.json` in one command.
=> [metrics] clean up machine type grouping

torchci/lib/bot/cliParser.ts, torchci/lib/bot/mergeBot.ts, torchci/test/mergeBot.test.ts
Test plan: Added test case that calls rebase with stable flag, which signals to mergebot to rebase to the viable/strict branch. This case registers the flag as true and all other mergebot tests pass.
=> Added flag for mergebot to rebase to viable/strict branch

torchci/rockset/metrics/__sql/queued_jobs.sql, torchci/rockset/metrics/__sql/queued_jobs_by_label.sql, torchci/rockset/prodVersions.json
We keep getting afflicted by incorrect results that GitHub's API is
returning, where some jobs are incorrectly marked as queueing forever.
I've filed a ticket for GH eng to investigate, but in the meantime this
workaround should filter out those bad jobs.
=> [metrics] improve queue time metrics

torchci/lib/bot/ciflowPushTrigger.ts
Remove this from the list of supported labels, and provide a message
explaining why.
=> [ciflow] remove ciflow/all as an option

torchci/log_classifier/classify_log.py, torchci/pages/api/classifier/rules.ts
Flaky tests rerun in logs, so match against one of the rerun lines.
This looks to be helpful in getting the log view to jump to the correct lines for flaky tests, but I'm not sure I wrote the rule 100% correctly.
=> Add flaky capture

torchci/lib/bot/cliParser.ts, torchci/lib/bot/mergeBot.ts, torchci/package.json, torchci/test/mergeBot.test.ts, torchci/yarn.lock
This brings a few benefits:
- shlex ensures that the command-line parsing is POSIX-compliant, which
conforms to people's expectations of what is allowed on a command line
(as an example, single-quoted strings should work).
- argparse is a more declarative way of specifying arguments, which
eliminates a lot of handwritten code for, e.g. required arguments,
choice allowlists, generating a help message, and so on.
- argparse also is more familiar to PyTorch in terms of syntax users, as
it is the conventional thing that Python programs use. (e.g. single dash
for short form, double dash for long form)
=> [mergeBot] port arg parsing logic to argparse+shlex

torchci/lib/bot/mergeBot.ts, torchci/test/mergeBot.test.ts
Only look at the line that starts with @pytorchbot when parsing
commands.
This breaks one of the existing tests, which explicitly inserted
newlines. But I think it's fine to regress this behavior.
=> [mergebot] fix case where there is other content in the bot comment

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/strict_lag_sec.sql, torchci/rockset/metrics/strict_lag_sec.lambda.json, torchci/rockset/prodVersions.json
Before we were measuring the last time the viable/strict branch was
pushed. But what we actually want to measure how far behind
viable/strict is from master, which is a higher order metric that
captures how long the strict promotion process takes.
=> [metrics] introduce viable/strict lag time metric

torchci/rockset/commons/__sql/flaky_tests.sql, torchci/rockset/commons/flaky_tests.lambda.json, torchci/rockset/prodVersions.json
Disclaimer: I don't think anything is wrong with my query, but this has returned fewer results than the OG flaky_test_query for the same inputs
The results look like for the past 48 hours:
```
[
{
"name": "test_forward_overlap",
"suite": "TestForwardOverlapWorldSizeOne",
"file": "distributed/fsdp/test_fsdp_overlap.py",
"numGreen": 4,
"numRed": 4,
"jobNames": [
"linux-bionic-rocm5.1-py3.7-distributed / test (distributed, 2, 2, linux.rocm.gpu)",
"linux-bionic-rocm5.1-py3.7-distributed / test (distributed, 2, 2, linux.rocm.gpu)"
],
"jobIds": [
6667611253,
6667611253
],
"workflowIds": [
2413793937,
2413793937
],
"workflowNames": [
"periodic",
"periodic"
],
"branches": [
"master",
"master"
],
"runAttempts": [
1,
2
]
}
]
```
=> Add flaky_tests SQL that queries test_run stats

torchci/rockset/commons/__sql/flaky_test_history.sql, torchci/rockset/commons/flaky_test_history.lambda.json, torchci/rockset/prodVersions.json
Originally, I had wanted one single query for querying 
1. flaky tests from the last _ hours (usually 3 or 6) for the disable bot https://github.com/pytorch/test-infra/pull/363
2. flaky test history for particular flaky tests (this PR)
The current flaky_tests_query does this and is able to query for all flaky tests in the last 30 days because it reads from a tiny collection. However, maintaining that collection has been tedious and sometimes inaccurate as it relies on individual calculations for every job run in CI. 
The new flaky_tests query has the potential of doing that IF we had a ton of machines and compute, as currently, it is incredibly slow as it queries and filters from our MASSIVE test_run data. We simply split this query into two very similar queries with different use cases. …
=> [flaky-test] Add SQL for flaky test history

torchci/components/LogViewer.tsx
This intercepts copy commands and replaces the selection text if it has escape characters with nothing.
Tried replacing the entire log string's escape characters but they're needed for formatting and such.
https://user-images.githubusercontent.com/34172846/172436512-6dc98e85-c35b-4288-bdb9-9c8c0bb8a0e0.mov
Addresses
https://github.com/pytorch/test-infra/issues/375
=> [hud] fix logviewer copying escape characters

torchci/lib/fetchFlakyTests.ts, torchci/lib/types.ts, torchci/pages/api/flaky-tests/flakytest.ts, torchci/pages/flakytest.tsx, torchci/rockset/commons/flaky_tests.lambda.json, torchci/rockset/prodVersions.json
Retire the old flaky test query for the new ones added in #363 and #391.
I verified that the views are not borked + that the query returns stuff, see https://torchci-git-fork-janeyx99-use-new-queries-torchci.vercel.app/flakytest?name=test_forward_overlap
=> [flaky-tests] Use new queries

torchci/lib/fetchFlakyTests.ts, torchci/lib/types.ts, torchci/pages/api/flaky-tests/flakytest.ts, torchci/pages/flakytest.tsx, torchci/rockset/commons/flaky_tests.lambda.json, torchci/rockset/prodVersions.json
Reverts pytorch/test-infra#394
It turns out my query is too slow for vercel so reverting to old query until I can speed up or mitigate this one. 
The disable test bot timed out for all its past runs since Vercel employs a 5s timeout :/ See https://github.com/pytorch/test-infra/actions/runs/2460572331 and https://stackoverflow.com/questions/68771480/nextjs-vercel-504-error-function-invocation-timeout
=> Revert "[flaky-tests] Use new queries"

torchci/lib/bot/cliParser.ts, torchci/lib/bot/mergeBot.ts, torchci/test/mergeBot.test.ts
- Make it accessible with the more conventional `-h, --help`.
- Add descriptions and examples to each command.
At this point, the information presented is the same as the wiki, which
is nice.
=> [mergeBot] improvements to help message

torchci/pages/api/classifier/rules.ts
When running the classification script on 6968080598: 
```
python ./log_classifier/classify_log.py 6968080598    
```
We get:
```
{
"job_id": 6968080598,
"rule": "Python RuntimeError",
"line": "RuntimeError: raised from 0",
"line_num": 19141,
"context": "\nGenerating XML reports...\nGenerated XML report: test-reports/python-unittest/distributed.fsdp.test_fsdp_misc/TEST-TestFSDPMisc-20220620161302.xml\nRunning distributed/elastic/multiprocessing/api_test ... [2022-06-20 16:13:49.221174]\nExecuting ['/opt/conda/bin/python', 'distributed/elastic/multiprocessing/api_test.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2022-06-20 16:13:49.221335]\nTest results will be stored in test-reports/python-unittest/distributed.elastic.multiprocessing.api_test\n\nRunning …
```
=> [classification] move flaky test instance higher

torchci/test/mergeBot.test.ts
Use requireDeepCopy everywhere. Require was messing things before where if we changed the object that we got from require, it might end up polluting other tests.
=> use requireDeepCopy

torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
When the bot finds the relevant module, it should add the triaged label. 
cc. @albanD
=> [flaky test bot] Triage module-marked issues, but not oncall ones

torchci/components/metrics/panels/TimeSeriesPanel.tsx, torchci/pages/metrics.tsx, torchci/pages/tts.tsx
Fix the range to the start/end specified by the user, instead of letting
the returned data determine it. Otherwise if we don't have data for some
period we will show a chart with a different range than the one
requested by the user
=> [metrics] fix TimeSeriesPanel range

torchci/lib/bot/drciBot.ts, torchci/test/drciBot.test.ts
**Overview:** Edited `formDrciComment` function to include static helpful links -- hud and office hours link
**Test Plan:** modified test case to check that both links are there. Example output of the comment:
=> Adding static links to Dr. CI bot comment

torchci/lib/bot/drciBot.ts
**Overview**: fixed the formatting of the Dr. CI comment -- added bullet list, fixed hud hyperlink and header format
Example output below:
=> Fixed output of Dr. CI bot's static links

torchci/lib/bot/drciBot.ts, torchci/test/drciBot.test.ts
**Overview:** Added static links for docs builds. I have not yet implemented an update comment script that will only add the link to the docs builds if their respective jobs have completed. 
**Example Output:**
**Test Plan:** Added an `expect` statement to check if the docs builds links are present.
=> Added static docs builds links to Dr. CI comment

torchci/lib/bot/drciBot.ts, torchci/test/drciBot.test.ts
**Overview:** Added a test case to check that the Dr. CI bot edits an existing comment if one is present. And added emojis!
**Example Output:**
**Test Plan:** ensure that all tests pass, `context.log` statements show that a comment was updated and not created
=> Add test case for Dr. CI bot to edit existing comments

.github/workflows/update_slow_tests.yml, torchci/rockset/commons/__sql/slow_tests.sql, torchci/rockset/commons/slow_tests.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/updateSlowTests.mjs
This recreates the query that we do manually today in rockset, and uses
that directly to write the slow-tests.json
One difference is that we only look at the 3 most recent viable/strict
commits instead of the last 10, to cut down on query time.
Here is the diff of what's produced:
https://www.diffchecker.com/rES6z0ls. I think the differences are largely
due to partial data in the new test_run_s3 dataset, so they should converge
(I will check this).
=> [test stats] switch slow tests to use rockset

tools/scripts/analyze_ci_workflows.py
Adds a script to analyze different ci workflows to extract statistics on
how we support specific operating systems
Example output:
```
❯ tools/scripts/analyze_ci_workflows.py ~/work/pytorch/.github/workflows/trunk.yml ~/work/pytorch/.github/workflows/pull.yml ~/work/pytorch/.github/workflows/periodic.yml 
= By Operating System / Hardware Accelerator =
3 android   
6 ios       
11 linux_cpu (build)
7 linux_cpu (test)
8 linux_cuda (build)
6 linux_cuda (test)
3 linux_rocm (build)
3 linux_rocm (test)
1 macos (build)
2 macos (test)
1 windows_cpu (build)
1 windows_cpu (test)
3 windows_cuda (build)
2 windows_cuda (test)
= By Compiler =
13 clang     
15 gcc       
4 visual studio
```
=> tools: Add tool to analyze pytorch ci

.github/workflows/update-test-times.yml, torchci/rockset/commons/__sql/test_time_per_file.sql, torchci/rockset/commons/test_time_per_file.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/updateTestTimes.mjs
Right now we perform sharding on a per-job basis. The setup looks like:
- Build job downloads the most recent test reports from S3 and parses
them according to sum duration by file and build environment
- Build job packages resulting data as a json along with the rest of the
build artifacts
- Test jobs use this json to make sharding decisions.
We want to:
1. Eliminate the dependence on manual parsing and aggregation of test
stats in S3 in favor of using Rockset, to improve maintainability
2. Compute test statistics globally instead of per-build-job, to avoid
tests jumping around shards too frequently.
This PR does the first part: it downloads the test stats from rockset
and makes them available in GH, similar to what we do with slow tests.
This happens every day in the night time.
There …
=> [test stats] Upload test times

torchci/lib/types.ts, torchci/rockset/commons/__sql/recent_pr_workflows_query.sql, torchci/rockset/prodVersions.json
**Overview**: Updated the `recent_pr_workflows_query` Rockset query [here](https://console.rockset.com/lambdas/details/commons.recent_pr_workflows_query?tab=summary) to include a reference to the repo and the PR owner, which are needed in the `drci.ts` script to retrieve and update the Dr. CI comment. Updated necessary fields and sql code on test-infra. 
**Testing**: N/A, ran the code on rockset to ensure that the new values are correct
=> Updated rockset query for Dr. CI

torchci/lib/fetchRecentWorkflows.ts, torchci/lib/types.ts, torchci/rockset/commons/__sql/recent_pr_workflows_query.sql, torchci/rockset/commons/recent_pr_workflows_query.lambda.json, torchci/rockset/prodVersions.json
**Overview**: modified Rockset query [here](https://console.rockset.com/lambdas/details/commons.recent_pr_workflows_query?tab=summary) to include not only the recently completed workflows from the last N minutes, but also all of the previous/pending workflow jobs that correspond to the same commit SHAs and PRs. The previous rockset query would make it difficult to compare how many jobs had already been completed or hadn't been completed. Now that all of the workflow jobs for a SHA are in the same place, this will make it easier to calculate the number of failing and pending workflow jobs for the Dr. CI comment.
**Test Plan**: example output, null for completed_at and conclusion means the workflow is still pending
=> Updated Rockset query for Dr. CI comment

torchci/lib/bot/drciBot.ts, torchci/lib/drciUtils.ts, torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts, torchci/test/drciBot.test.ts
Overview: Made a stub script for updating the Dr. CI comment with results from the rockset query of recently completed workflows. Implemented method to update comment, but haven't yet implemented the method that will calculate the workflow check results.
Test Plan: haven't implemented it fully yet, but I've thought of some test cases. The current integration tests will only look at the pr owner, since before rolling out the Dr. CI comment I only want to update comments on my PRs.
=> Stub script for adding workflow information to Dr. CI comment

torchci/lib/fetchHud.ts, torchci/lib/types.ts, torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Add a ui element that shows up when the test time has changed significantly, along with a basic ui that shows how much the test times have changed.  The hope is that this will help us be more aware of changes in test time/tts.
Notes:
* compares aggregate test time over shards to previous commit, if previous commit does not have available data (see next bullet point) then current commit also says N/A
* "N/A" can mean many things - pending, a shard failed, previous commit failed, previous commit is pending, previous commit doesn't have data
* colors chosen rather randomly - red = increase in test time, green = decrease in test time, I believe that any significant change in test time regardless of direction is important, so colors do not necessary indicate how "good" this change is
* …
=> tts on minihud

torchci/lib/bot/cliParser.ts, torchci/lib/bot/pytorchBot.ts, torchci/test/mergeCommands.test.ts
For example `@pytorchbot merge -f -m 'Flaky tests'`. Without a message, a `confused` emoji and the following message will be posted.
```
You need to provide a clear reason for using force merge, i.e. @pytorchbot merge -f -m 'Minor fixes. Expecting all PR tests to pass'
```
On the other hand, `@pytorchbot merge -f` will soon be recorded in dynamoDB/Rockset by https://github.com/pytorch/test-infra/pull/461. We will be able to easily audit the usage of merge -f querying the new `issue_comment` collection
`npm run test -- test/mergeCommands.test.ts`
https://github.com/pytorch/test-infra/issues/409
=> Require a reason when force merge with -f

torchci/lib/bot/drciBot.ts, torchci/lib/drciUtils.ts, torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts
**Overview:** I forgot to change the `body` parameter from the original comment (without failure info) to the update done. I also modified the comment formation process by splitting it up into the methods `formDrciHeader` and `formDrciComment`
**Test Plan:** the current GHA correctly identifies and updates my PR, but the comment body was not the correct one with pr workflow results.
=> Small fix for Dr. CI script's comment updating process

torchci/pages/api/classifier/rules.ts
add new classification rule for pytest failures now that pytest is run in CI
The rule should match things of the form:
`FAILED test_ops.py::TestTagsCPU::test_tags__refs_constant_pad_nd_cpu_float32`
where `FAILED` is at the beginning of the line.
Tested via `rules.json` as stated in the README, but because json requires a few changes for the regex, testing might not have been sufficient.
=> new classification rule for pytest failures

torchci/log_classifier/backfill.py
Previous version was old, updated the rockset query and put the new version in the python file.  
Tested by running `torchci/log_classifier/backfill.py` and checking that there were no more errors
=> update rockset query version for `unclassified`

torchci/pages/api/classifier/rules.ts
The regex actually needs to be broader than i thought it did
It should match things like 
`FAILED test_ops.py::TestCommonCPU::test_dtypes_H_cpu - assert 1 == 2`
`FAILED test/test_ops.py::TestOperatorsCUDA::test_vmap_autograd_grad___rmatmul___cuda_float32`
`FAILED test_ops.py::TestTagsCPU::test_tags__refs_constant_pad_nd_cpu_float32`
=> fix pytest classification regex

torchci/lib/bot/pytorchBot.ts, torchci/lib/bot/rolloutUtils.ts
We are enrolling everyone in Dev Infra into the land checks. If you need to land something immediately or don't want to wait, then use -f or if you want to get the old behavior, use -g. 
Test Plan:
Check that tests for the allowlist still works.
=> Land Check Rollout 1

torchci/pages/api/classifier/rules.ts
Change classification for pytest so that it jumps to the `===== FAILURES ======` line which is where the stack traces are located
=> jump to stack traces for pytest failures

torchci/lib/bot/pytorchBot.ts, torchci/lib/bot/pytorchBotHandler.ts, torchci/test/mergeCommands.test.ts
Make the pull_request_review support pytorchbot commands as well. 
This PR just makes all the handling common across the two and extracts it out into a different class
Test Plan:
Let tests run and and modified/added 2 tests to support this new functionality.
=> [mergebot] Port pytorchbot over to pull_request_review

torchci/lib/drciUtils.ts, torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts
**Overview**:  Added modifications to Dr. CI comment following the DevX sync. Put bullet list of failures into a collapsible section (which defaults to be opened), and also added alphabetical sorting for the failure names. 
**Example Output:**
**Test Plan**: Updated test cases to check that the order of failures are in alphabetical order.
=> Dr. CI Modifications -- collapse and sort failures

torchci/scripts/backfillJobs.mjs
Sometimes github's api is broken and doesn't update some fields so we think that a job is still queued even though it has run already, so I add a check that the steps array is empty.  If the steps array is not empty, then the job has actually started and is no longer queued.
=> backfill script check for steps 

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/job_duration_percentile.sql, torchci/rockset/metrics/__sql/tts_percentile.sql, torchci/rockset/metrics/job_duration_percentile.lambda.json, torchci/rockset/metrics/tts_percentile.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/checkRockset.mjs
Switch the rest of the HUD metrics page to percentile including job TTS and duration. I use p50 to make it consistent with the overall metrics.
~~There is an ongoing thread on which percentile to use. However, that can be addressed on a different PR~~ I'm working on the next PR to allow people to choose the percentile (and avg for backward compatibility). This should make the metrics easier to use in all cases. I'll submit it once this one this reviewed and merged to avoid merge conflicts.
There is no obvious changes in the top long poles when comparing with https://hud.pytorch.org/metrics. Only some changes their order slightly.
=> Tts percentiles per job

torchci/pages/metrics.tsx
Allow switching between `avg` and all the common percentiles (p50, p90, p95, p99, p100).
** p100 looks weird, it seems that there are some stuck job and the metrics reveals them **
=> Add TTS metric picker on HUD

torchci/pages/tts.tsx, torchci/rockset/metrics/__sql/tts_duration_historical_percentile.sql, torchci/rockset/metrics/tts_duration_historical_percentile.lambda.json, torchci/rockset/prodVersions.json
Now we can switch between avg and different percentiles on https://hud.pytorch.org/tts. 
I plan to submit another PR after this to link the jobs on [HUD metrics](https://hud.pytorch.org/metrics) with this page. So that people have more visibility of https://hud.pytorch.org/tts.
=> Add percentile picker to https://hud.pytorch.org/tts

torchci/components/metrics/panels/TablePanel.tsx, torchci/next.config.js, torchci/pages/metrics.tsx, torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
The [historical TTS page](https://hud.pytorch.org/tts) shows valuable information about the TTS of a job, but it's not linked anywhere from the more popular [HUD metrics page](https://hud.pytorch.org/metrics). This PR is to link the twos by allowing a clickable link from the jobs on [HUD metrics page](https://hud.pytorch.org/metrics) with its corresponding historical TTS page. The change to support this includes:
* Move https://hud.pytorch.org/tts to https://hud.pytorch.org/tts/[repoOwner]/[repoName]/[branchName]
* repoOwner and repoName are both `pytorch`
* branchName can be master or `%` for all branches
* https://hud.pytorch.org/tts will be route to `/tts/pytorch/pytorch/master`, as a landing page
* Tweak https://hud.pytorch.org/tts to set the job name via a query parameter, i.e. …
=> Link jobs on HUD metrics with its historical TTS page

torchci/lib/bot/cliParser.ts, torchci/lib/bot/pytorchBotHandler.ts
After [auditing force merge usage](https://github.com/pytorch/test-infra/issues/463#issuecomment-1201757297) in the 2 weeks from July 15th to Aug 1st, I want to improve the way the message is conveyed a bit:
* Use `-f MESSAGE` instead of the default `-f FORCE` generated by argparse. By default, argparse uses the flag name to refer to the parameter in the help message from `--help`. This is pretty confusing for the `--force` flag. I have seen people trying to use `@pytorchbot merge -f FORCE` literally before realizing that they need to provide a string message as the FORCE parameter. Changing the param name to MESSAGE is also consistent with the revert `-m MESSAGE` use case.
* Simplify force merge message by removing the explicit category, which is rarely used from contributors outside …
=> Improve force merge message usability

torchci/lib/drciUtils.ts
**Overview:** Modified `drciUtils.ts` header construction method to make the hud link clearer. Rather than linking the hug with 'here' the output now shoes the actual url for the HUD.
**Example Output:**
**Test Plan:** no tests should be affected and all pass.
=> Dr. CI Feedback: display full HUD link to improve clarity

torchci/lib/bot/cliParser.ts
TSIA. We had a person try to merge with a whitespace, but due to our regex not matching it, we didn't take that into account so this adds that. 
Test Plan:
Let tests run
=> [mergebot] Ignore whitespace in front of commands

torchci/components/NavBar.tsx, torchci/components/metrics/panels/TimeSeriesPanel.tsx, torchci/pages/kpis.tsx
Adds a KPI page to hud.pytorch.org/kpis. A Future PR will add more KPIs
The existing TimeSeriesPanel had a bug where it wouldn't correctly interpolate any data with a granularity greater than an hour (it tended to show all zeros for the data), especially if that data crossed a daylight savings time boundary.
This PR also fixes that bug and also hides the legend when we're not grouping the data into multiple lines.
Also updated the navbar link to the metrics page to be a relative link so that the dev server links to the dev server and not the prod metrics page
Manually tested on local machine and validated that the /metrics page wasn't updated
=> Add first KPI and update TimeSeriesPanel to handle them

.github/workflows/build_wheels_linux_reusable.yml, .github/workflows/lint_actions.yml
`actionlint` check is failing on the reusable workflow introduced in https://github.com/pytorch/test-infra/pull/460. This PR fixes the failures by.
- Upgrading `actionlint` to the [latest release binary](https://github.com/rhysd/actionlint/releases) which understands reusable workflow keywords like `workflow_call` and `inputs`.
- Add `description` field for reusable workflow inputs.
```
go install github.com/rhysd/actionlint/cmd/actionlint@97ad72abf96ba516f4a49f2da567165eaebf7e5a
/Users/niravmehta/go/bin/actionlint
```
=> Fix actionlint error on reusable GHA workflow

torchci/log_classifier/README.md, torchci/log_classifier/backfill.py, torchci/rockset/commons/__sql/unclassified.sql, torchci/rockset/commons/unclassified.lambda.json, torchci/rockset/prodVersions.json
Today, I synced the AWS lambda with classify_log.py so that it would start classifying succeeding jobs too. 
With this change, I am explaining why we are doing that + why we are NOT switching backfill.py to broaden its search to succeeding jobs too.
It would be ideal if CI with flaky tests could set the output of a check to be "neutral" or something other than passed so that we can still shield devs and still be able to single out these checks in our flaky test infra.
=> Add versioning to unclassified lambda, clean up backfill.py

torchci/pages/api/flaky-tests/disable.ts, torchci/pages/flakytest.tsx
Make debugging instructions for flaky tests more prominent by
* moving the debugging instructions to the top on the hud flaky test view (first pic)
* add debugging instructions when the issue is made (second pic)
=> flaky tests - make debugging instructions more prominent

torchci/components/LogViewer.tsx, torchci/pages/api/classifier/rules.ts, torchci/pages/api/flaky-tests/flakytest.ts
This would enable flaky test view to have log viewers! 
A few steps had to happen for this to occur:
1. the actual aws lambda had to start categorizing the logs of succeeding jobs (done on 8/12 manually)
2. the capture we supposed had to match the capture that was captured as a part of the classification --> this PR does this
3. the LogViewer would reveal itself if there is a failureLine associated with a job --> this PR does this
Test plan: please checkout the preview! https://torchci-git-fork-janeyx99-use-better-capture-flaky-torchci.vercel.app/flakytest?name=test_no_cyclic_references
=> [flakytest bot] use better capture for flaky unittests

torchci/lib/bot/acceptBot.ts, torchci/test/acceptBot.test.ts
Once someone accepts, we remove the label to prevent it from running again. Another solution is adding another label and checking if that exists before kicking off merge from here, but we'd need to worry about deleting that label as well in trymerge if it fails. 
Test Plan: 
Let tests run
=> [accept2ship] Don't Rerun on Multiple Accepts

torchci/rockset/commons/__sql/test_time_per_file_periodic_jobs.sql, torchci/rockset/commons/test_time_per_file_periodic_jobs.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/updateTestTimes.mjs
as in title, so that periodic jobs can be sharded properly (at least, i think)
<details><summary>snippet of file </summary>
```
"linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck": {
"default": {
"backends/xeon/test_launch": 2.1216666666666666,
"benchmark_utils/test_benchmark_utils": 2.9416666666666664,
"distributions/test_distributions": 68.079,
"lazy/test_reuse_ir": 1.6843333333333337,
"lazy/test_ts_opinfo": 0.25566666666666665,
"test_ao_sparsity": 8.661,
"test_autocast": 1.6963333333333328,
"test_autograd": 59.615000000000045,
"test_binary_ufuncs": 197.18666666664592,
"test_bundled_inputs": 2.556666666666666,
"test_complex": 0.009666666666666667,
"test_cpp_api_parity": 21.73700000000004,
"test_cpp_extensions_aot_ninja": 0.4913333333333334,
"test_cpp_extensions_aot_no_ninja": 0.496, …
```
=> add periodic jobs to test times json

.github/workflows/build_conda_linux_reusable.yml
Creating a reusable workflow for building conda binaries for linux. A follow-up PR in torchaudio will call this to build the conda binaries by calling this workflow.
For now, this can expect separate pre/post build scripts from the linux wheels workflow. In the future, we can try to unify them into a single thing that leverages @seemethere 's pkg-helpers python cli.
=> [Nova] Adding reusable workflow for building linux conda binaries

torchci/lib/bot/acceptBot.ts, torchci/test/acceptBot.test.ts
Previously, if there was already an accept on the PR, and you added accept2run, it wouldn't do anything, which was kind of annoying. Now, if the label added is accept2run/accept2ship, we check if it's been accepted and then apply the ciflow labels if it is. 
Test Plan:
Let tests run
=> [accept2ship] Run/Ship when label is applied and there's an accept

.github/scripts/update_disabled_tests.py, .github/workflows/update_disabled_tests.yml
condense the disabled-tests.json because it is huge and we don't use the information from most of it
This will help us get a better sense of what is disabled and also what is actually used in CI.
I'll make a followup PR in pytorch for corresponding changes if this ends up being merged
Changes
* usually the tuple is (link, platforms) but now its (issue number, link, platforms) because the ci needs to know the pr number in order to re enable tests
Test Plan
go to  https://github.com/pytorch/test-infra/blob/generated-stats/stats/disabled-tests-condensed.json to see what it looks like
=> condensed disabled tests

torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
I find myself frequently looking for the link to specific jobs on TTS page so that I can share them on doc, chat, etc.  So this is an easy tweak to have the link available right away in the TTS page. We have the same link on HUD metric page, but they are kind of harder to find.
=> Add link to job names in TTS page

torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Test file info does not work for files not in the test folder (because they contain `../`, I think, but I don't know) and we can almost always differentiate tests by suite + name anyway so we might as well just not include it.
Discovered with functorch test links not working unless you delete the file part.
=> [flaky test bot] don't incorporate file info into flaky test link

torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Usually for rocm, we also mark linux as a platform for which to skip the test, but that is wrong. We should isolate rocm to only disable tests for rocm only.
=> [flaky test bot] when rocm, only triage rocm

torchci/lib/bot/ciflowPushTrigger.ts
This is to support the new set of `ciflow/test-config` labels for manual test selection in https://github.com/pytorch/pytorch/pull/83690
=> Add ciflow/test-config into the list of valid ciflow labels

.github/workflows/build_wheels_linux_reusable.yml
Every domain library will have some custom steps in building binaries unique to it. As part of this PR, we want to add steps to run `pre_build_script` and `post_build_script` to the reusable workflow. These script files will be provided by the domain library.
Integrated with `pytorch-pkg-helpers` for the common logic in building wheels binary.
Using PR in audio library: https://github.com/pytorch/audio/pull/2548/ to test building wheels binary.
=> [Nova] Add steps for pre and post build in reusable workflow

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/prodVersions.json
The classification join was really slow, so force using a lookup join.
This roughly doubles the speed of the commit jobs query. The hud query
is mostly the same but should scale better over time.
=> [hud] optimize hud and commit queries

torchci/scripts/check_alerts.py
Previously, we didn't do anything if there were updates to the alert if some jobs got fixed or more jobs failed. Now, we compare the old alert to the new one and if there's any updates, we edit the comment. 
Also, we start raising for the request fetches instead of silently failing/failing later when we try to access the responses. 
Test Plan: 
ran it locally and saw that it updated https://github.com/pytorch/test-infra/issues/571
=> [alerts] Edit alert if conditions change

torchci/components/CommitStatus.tsx, torchci/components/WorkflowBox.tsx, torchci/lib/JobClassifierUtil.ts
This sorts the the commit view data in two ways:
- Sort workflows so that workflows with failing jobs are listed first
- Within each workflows, put failing jobs 
Screenshots show before and after examples of the build status (using [this in progress commit](https://hud.pytorch.org/pytorch/pytorch/commit/3a9ae518f2c9424251eae13fb23db6ea571cfce1) as an example)
You had to scroll past the successful workflows to find the ones that are failing.
And then you have to search within the list to see which workflows actually failed, which are still pending, etc. 
First we see all failing workflows, then we see workflows that have jobs still pending
=> Sort workflows and jobs by conclusion

tools/scripts/generate_binary_build_matrix.py
Adding runner type to generate build matrix so that we can use it in the validation workflow
=> Adding runner type to generate build matrix

torchci/pages/api/auth/[...nextauth].js
We should just need the repo scope for doing managing stuff like reverts and such on HUD. Don't need emails and such.
=> Remove workflow and user scopes

.github/scale-config.yml
g4dn.12xlarge has 4 T4 GPUs, using it as an architectural upgrade to 4x Maxwell instances
=> Add T4 config

.github/actions/setup-miniconda/README.md, .github/actions/setup-miniconda/action.yml, .github/workflows/test-setup-minconda.yml
Adds a setup-miniconda action for us to use in our macOS workflows to
give us a working version of setup-miniconda that can be re-used amongst
even non-ephemeral runners in general
=> ci: Add setup-miniconda action for use with macOS

README.md
Our Vercel project moved to a new team (Meta Open Source). 
Update the link to point to it's new home
=> Point instructions to the new vercel page

torchci/components/WorkflowBox.tsx
Fixes https://github.com/pytorch/test-infra/issues/606
Before:
After:
Flaky test view still has the info
=> Don't show logviewer on green

.github/actions/setup-miniconda/README.md, .github/actions/setup-miniconda/action.yml, .github/workflows/test-setup-minconda.yml
Adds hooks to do both conda install and conda build from the provided
setup-miniconda environment
=> ci: Add env file flag, add install/build commands, remove default numpy install

torchci/lib/bot/pytorchBotHandler.ts, torchci/test/labelCommands.test.ts
As `ciflow` labels alter the flow of events, they should only be assigned by regular contributors
=> PyTorchBot: Restrict ciflow labels to writers

tools/scripts/generate_binary_build_matrix.py
Adding install command to matrix
conda:
```
(.venv) [atalman@devvm214.ftw0 ~/local/test-infra/tools/scripts (adding_install_command_to_matrix)]$ python3 generate_binary_build_matrix.py --package-type conda --channel nightly
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/conda-builder:cpu", "package_type": "conda", "build_name": "conda-py3_7-cpu", "validation_runner": "ubuntu-20.04", "channel": "nightly", "installation": "conda install pytorch torchvision torchaudio cpuonly -c pytorch-nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "10.2", "desired_cuda": "cu102", "container_image": "pytorch/conda-builder:cuda10.2", "package_type": "conda", "build_name": …
```
=> Adding install command to matrix

torchci/lib/bot/autoLabelBot.ts
A lot of PRs actually modify files under tools/autograd because it concerns codegen in general 
See: https://github.com/pytorch/pytorch/pulls?q=is%3Apr+label%3A%22release+notes%3A+autograd%22
=> [autolabel] Remove tools/autograd pattern

torchci/scripts/check_alerts.py
Assigning the issue to me interferes with the butterfly/open source bots. It should assign it to the Oncall but open source bot keeps getting reassigned to me since I am the owner of the issue on Github. Hopefully this should fix it.
=> [alerts][ez] Remove assignment for Alerts

torchci/components/metrics/panels/TimeSeriesPanel.tsx, torchci/pages/kpis.tsx, torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/strict_lag_historical.sql, torchci/rockset/pytorch_dev_infra_kpis/strict_lag_historical.lambda.json
add a viable/strict historical chart, graphing how far behind viable/strict was before it got updated, averaged daily and per minute, which should be granular enough to be equivalent to per commit
also changed a lot of stuff in tts page to take advantage of the minute granularity not interpolating
Notes
* max yaxis of 7 b/c some days were very large
* lag is calculated by _event_time - commit timestamp
=> hud kpis - add viable strict historical chart

.github/workflows/revert-tracker.yml, torchci/rockset/commons/__sql/reverted_prs_with_reason.sql, torchci/rockset/commons/reverted_prs_with_reason.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/github_analyze.py, torchci/scripts/reverts.py
Make a periodic job to generate a list of reverts categorized with links to the revert reason, to be used for convenience when creating oncall shift summaries.  The hope is to make this as close to simply copy pasting it into the shift summary or just using the generated md file when presenting.
Example of the output: https://github.com/pytorch/test-infra/blob/csl/reverttest/reverts/reverts.md
"Not through pytorchbot" = starts with "Revert" or "Backout" but cannot find a @pytorchbot revert comment 
Two versions - one is short the other is long
Periodic job is set to Monday at 9:30am PT ish.  It should list all the revert commits happening from the previous Monday at 6:30am PT to the currently Monday at 6:30am PT as this is the official time the oncall shift starts.  It lists 
If this PR …
=> auto revert tracker helper

tools/scripts/generate_binary_build_matrix.py
Adding the support for MacOS x86_64 to generate wheels and conda packages configuration matrix. 
Use "macos-arm64" to target ARM-based Mac 
Use "macos-x86_64" to target X86_64 based Mac
=> Add MacOS x86_64 support when generating binary matrix

tools/scripts/generate_binary_build_matrix.py
Just putting this PR up as an RFC. We can exclude 3.11 builds from the build workflows but this is a nice place to exclude from all the workflows in one place. It also makes this code a little cleaner. If we don't want this script to diverge from the corresponding script in pytorch/pytorch, we can close this PR and go with a different approach.
Synced with @atalman about this approach as well
=> [Nova] Do not add 3.11 to Domains build matrix

tools/pkg-helpers/pytorch_pkg_helpers/conda.py, tools/pkg-helpers/tests/test_conda.py
We found that the handling of `CONDA_CUDATOOLKIT_CONSTRAINT` in https://github.com/pytorch/test-infra/pull/660 resulted in conda builds on CUDA failing due to being unable to parse the meta.yaml config file. The config depends on the env var, and pytorch-pkg-helpers handling of the env var differed from the pkg-helpers.bash files (https://github.com/pytorch/audio/blob/main/packaging/pkg_helpers.bash) in the domain repos. This change makes pytorch-pkg-helpers handle `CONDA_CUDATOOLKIT_CONSTRAINT` the same way as the bash script, and also results in successful conda builds.
Will need to do a release of the pytorch-pkg-helpers library before removing this logic from the workflow.
=> [Nova] Fix CONDA_CUDATOOLKIT_CONSTRAINT handling in pytorch-pkg-helpers

.github/workflows/build_conda_linux.yml, .github/workflows/test_build_conda_linux.yml
This PR uses the new single-repo format for building Linux Conda binaries. Apart from migrating the workflow over, we also must explicitly handle setting `CONDA_CUDATOOLKIT_CONSTRAINT` correctly, since the current implementation in pytorch-pkg-helpers does not yield a successful build (fails to parse the conda meta.yaml file). In a follow-up PR, I plan to add more thorough handling of `CONDA_CUDATOOLKIT_CONSTRAINT` to the pytorch-pkg-helpers library, so that it's more closely aligned with the pkg_helpers bash script in the domain repos.
=> [Nova] Use the new single-repo format for building Linux Conda

tools/pkg-helpers/pytorch_pkg_helpers/conda.py, tools/pkg-helpers/tests/test_conda.py
Most domains set CUDATOOLKIT_CHANNEL=nvidia as an additional channel during conda builds. We currently handle this in a custom fashion in the workflow, but it's more modular to do this in pkg-helpers.
=> [Nova] Add support for CUDATOOLKIT_CHANNEL in pytorch-pkg-helpers

.github/workflows/update_disabled_tests.yml
18.04 is getting deprecated so here's the small fix
=> Use nondeprecated instance for upload_disabled_tests

torchci/pages/kpis.tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/time_to_signal.sql, torchci/rockset/pytorch_dev_infra_kpis/time_to_signal.lambda.json
The old TTS metric included the TTS from failed workflows, which would introduce variable noice and incorrectly lower the TTS number.
We now only look at workflows which passed all jobs. Since we're not excluding the low-TTS failed jobs, our official TTS numbers have of course increased slightly 
This also changes the KPI chart to only look at the past 6 months of data (which is all that's relevant in each half).
The chart still isn't perfect yet. It still averages in data for workflows like nightly, periodic.  Future task is to figure out how to filter out that data from here as well
Old chart:
New chart:
=> Fix TTS to ignore failed workflows

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/failure_samples_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/__sql/unclassified.sql, torchci/rockset/prodVersions.json
This makes use of the new dynamodb mutation implemented in #674 to do
the queries.
This makes the queries ridonkulously fast. `commit_jobs_query` takes
sub-50ms (down from several seconds), and `hud_query` takes ~150ms (down
from 5+ seconds).
We should be able to reduce our VM size after these changes.
The data is already backfilled and consistent, so we can merge this
whenever to get the speed boost.
=> [hud] last set of query optimizations

tools/pkg-helpers/pyproject.toml
Published the 0.1.3 release of pytorch-pkg-helpers to PyPI: https://pypi.org/project/pytorch-pkg-helpers/0.1.3/. This PR reflects the version changes in `pyproject.toml`.
The library reflects the expected changes: 
```
$ CU_VERSION=cu113 PACKAGE_TYPE=conda python -m pytorch_pkg_helpers
export BUILD_VERSION='0.13.0.dev20220908'
export CMAKE_USE_CUDA='1'
export CONDA_BUILD_VARIANT='cuda'
export CONDA_CUDATOOLKIT_CONSTRAINT='- cudatoolkit >=11.3,<11.4 # [not osx]'
export CONDA_PYTORCH_BUILD_CONSTRAINT='- pytorch==1.13.0.dev20220907'
export CONDA_PYTORCH_CONSTRAINT='- pytorch==1.13.0.dev20220907'
export CUDATOOLKIT_CHANNEL=nvidia
export CUDA_HOME='/usr/local/cuda-11.3'
export FORCE_CUDA=1
export PATH="/usr/local/cuda-11.3/bin:${PATH}"
export PYTORCH_VERSION='1.13.0.dev20220907'
export …
```
=> [Nova] Bump pytorch-pkg-helpers to 0.1.3

.github/actions/setup-binary-builds/action.yml, .github/workflows/build_conda_linux.yml
This does 2 things:
1. Bumps the usage in setup-binary-builds action to the latest version (0.1.3) of the package helpers library.
2. Cleans up previous case statements and env vars that were patched before the latest version release.
=> [Nova] Use latest pytorch-pkg-helpers in Linux Conda Builds

.github/actions/setup-miniconda/action.yml
This leverages `setup-miniconda` to print out the disk usage and throw an error when the available space is less than a certain amount (3GB)
This PR doesn't attempt to clean up disk space pending some discussion on https://github.com/pytorch/pytorch/issues/84841
=> Get disk space usage and throw an error for low disk space

.github/actions/setup-miniconda/action.yml
When using CONDA_RUN to execute MacOS test, I learn that conda will capture the subprocess output to stdout/stderr and print everything at the end. This has 2 drawbacks:
* The minor drawback is that I need to wait until the end of the command to see the test output.  This comes as a surprise to me because I expect to see the output right away. There should be no different between `conda run python test_mps.py` and `python test_mps.py`
* Another problem is that the command could hang sometimes, i.e. [4868437777](https://github.com/pytorch/pytorch/actions/runs/3025570812/jobs/4868437777).  In this example, nothing is printed out which makes debugging very tricky. This is just an example and not related to this PR.
The simple fix is to not capture stdout/stderr when using CONDA_RUN so that …
=> Print live output to stdout/stderr when using conda run

torchci/rockset/commons/__sql/failure_samples_query.sql, torchci/rockset/commons/failure_samples_query.lambda.json, torchci/rockset/prodVersions.json
The HUD failures page is currently broken since it got synced to a bad version of the query which accidentally left out a table (it keeps loading forever while rockset returns 500s)
This PR:
1. Fixes the query to add that table back in
2. Lets the failure page to show tests that only match part of the requested error text (e.g. "timeout")
=> Fix HUD failures page

torchci/lib/bot/autoLabelBot.ts, torchci/test/autoLabelBot.test.ts
This will enable repos such as pytorch/tau to also have their PRs autolabled.
Current support is pretty rudimentary: All labels corresponding to a file path modified in that PR will be added to the PR
We can evolve this implementation as we get requests from other repos
=> Enabling adding custom tags for repos beyond pytorch/pytorch

.github/workflows/build_conda_linux.yml, .github/workflows/test_build_conda_linux.yml
Upload the binaries to anaconda post-build. I'll make a similar PR for uploading wheels and another for conda uploads for macos once https://github.com/pytorch/test-infra/pull/685 is merged (waiting since that PR changes the workflow name and uses for both x86 and arm mac builds).
=> [Nova] Upload Linux Conda binaries to anaconda after building

torchci/scripts/check_alerts.py
If a nightly workflow fails two nights in a row, the alert bot sees that the workflow has been consistently failing and decides to alert on it. The next iteration, since the nightly workflow hasn't been retriggered yet, the bot continues to update the alert. 
Or it would have, but the bot also sees that the _current head_ is green, so it first clears all alerts (including the one for the nightly workflow), before it files a brand new alert, resulting in duplicate tickets being filed and the oncall getting re-paged 
Examples:
https://github.com/pytorch/test-infra/issues/726
https://github.com/pytorch/test-infra/issues/727
https://github.com/pytorch/test-infra/issues/728
https://github.com/pytorch/test-infra/issues/729
https://github.com/pytorch/test-infra/issues/730 …
=> Prevent bot from auto clearing nightly alerts

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/last_successful_jobs.sql, torchci/rockset/metrics/last_successful_jobs.lambda.json, torchci/rockset/prodVersions.json
The doc push job names now include another dimension after https://github.com/pytorch/pytorch/pull/83957, so [HUD](https://hud.pytorch.org/metrics) wrongly reports that docs haven't been updated since a 23+ days.  Also switch to a semicolon-separate list of job names because comma can be part of the GHA job name
yarn dev
=> Fix doc push job names

torchci/components/JobLinks.tsx, torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/prodVersions.json
Adding this timestamp is useful when looking at the historical failures view ([like this one](hud.pytorch.org/failure/test_compute_bucket_assignment_by_size_sparse_error_with_logger)) to know just how old the similar looking test examples are
Next to the duration, the failure results now also tell you when a given workflow was started.
```
linux-bionic-cuda11.6-py3.10-gcc7 / test (distributed, 1, 3, linux.8xlarge.nvidia.gpu)
Raw logs | more like this | Duration: 47m 6s | Started: Wed, Sep 14 | 
```
Screenshots:
Old
New
While this does also affect the commit view, it's added to a spot of low enough prominence to not interfere with existing flows
=> List when individual workflows were started

.github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml
If this keeps all the builds green, I'm going to merge this, make a PR in audio that renames the scripts to just `pre/post_build_script`, and make a PR here that uses those new names. The conda builds script effectively does the same thing as the wheels script apart from exporting a number of environment variables that don't propagate to this action anyways.
=> [Nova] Every test workflow should use a consistent build script

torchci/docs/architecture.md
circleci isn't present on some repositories so we shouldn't make it a requirement for adding a new repository to torchci
=> Add note about circleci requirement (or lack-thereof) for `torchci`

.github/scale-config.yml
Yesterday jobs where throttled due to hitting the max runners allowed for `linux.g4dn.12xlarge.nvidia.gpu`. As the peak seems to be legitimate, a increase in the max number of runners is required.
=> increasing max runners to 25 for linux.g4dn.12xlarge.nvidia.gpu

.github/workflows/test_build_conda_linux.yml, .github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml, .github/workflows/test_build_wheels_linux.yml, .github/workflows/test_build_wheels_m1.yml, .github/workflows/test_build_wheels_macos.yml, .github/workflows/test_build_wheels_windows.yml
This is going to break all the builds until https://github.com/pytorch/audio/pull/2695 is merged. Just putting this up so we can test afterwards.
=> [Nova] Update scripts names in test workflows after audio update

.github/scale-config.yml
Which are equipped with NVIDIA A10G GPU, which has compute capability sm8.6
=> Add `g5.4xlarge` instances

torchci/lib/bot/cliParser.ts, torchci/lib/bot/pytorchBotHandler.ts
Currently merbot rebases PRs onto the master branch by default, which is not ideal since that branch can have broken tests.
This PR changes mergebot behavior to default to the viable/strict branch instead.
It adds a new parameter to mergebot "-m" for those who really want to rebase onto the latest master branch.  The old -s parameter is sticking around for backwards compat, but it's effectively a no-op now.
Announce the change on PyTorch Dev Discussions (I'm going to wait for the current sevs to be over before submitting/announcing this change)
=> Rebase onto viable/strict by default

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml
This ensures we will not search for a file explicitly names "dist/*.whl" and return a "No such file or directory" error.
=> [Nova] Nit fix to wheel upload

.github/workflows/lambda-release-runners.yml, .github/workflows/lambda-release-tag-runners.yml, .github/workflows/lambda-runners.yml, .github/workflows/tflint.yml
Adds a workflow to tag versions in the format `v$DATE-$TIME` that only completes if tests are successful;
Adds a workflow that when a tag named `v.*` is created, it uploads a new release of lambda runners to the repo
=> Adds a deployment workflow for runners lambda

.github/workflows/build_wheels_linux.yml, .github/workflows/test_build_conda_linux_without_cuda.yml, .github/workflows/test_build_wheels_linux_with_cuda.yml
Creates a new input for the reusable build workflow called build-type. This can take values: development, nightly, and release. Development is used from the test_build_* workflows for testing. Nightly and Release are used accordingly when build is trigged from the domain repos.
=> [Nova] Change when the upload is triggered by passing from caller

tools/pkg-helpers/pytorch_pkg_helpers/__main__.py, tools/pkg-helpers/pytorch_pkg_helpers/macos.py, tools/pkg-helpers/tests/test_macos.py
Added constant `CONDA_EXTRA_BUILD_CONSTRAINT` to pkg helper for MacOS.
=> Extend pkg helper for mac os

.github/workflows/revert-tracker.yml, torchci/rockset/commons/__sql/reverted_prs_with_reason.sql, torchci/rockset/prodVersions.json
make the regex for the revert tracker slightly broader
it was causing the workflow to fail https://github.com/pytorch/test-infra/actions/runs/3128929655/jobs/5077381984 
as a side note, im not a big fan of how we've gone back to regex for parsing
=> [revert tracker] fix regex 

.github/workflows/build_wheels_linux.yml
If the conda env is not used, the upload step will fail with `pip not found`.
=> [NOVA] Use Conda Env when pip installing awscli

tools/pkg-helpers/pytorch_pkg_helpers/__main__.py
Fixed a typo in the parameters list for `pkg_helper`.
=> Fixed typo

torchci/lib/bot/cliParser.ts, torchci/lib/bot/pytorchBotHandler.ts, torchci/test/mergeCommands.test.ts
restrict rebase and merge to only viable/strict and master to prevent rebasing onto <other branch> and merging <other branch>'s unapproved changes
=> [mergebot] rebase and merge only viable/strict or master

.github/workflows/build_wheels_linux.yml, .github/workflows/test_build_wheels_linux_with_cuda.yml, .github/workflows/test_build_wheels_linux_without_cuda.yml
In the current workflow, credentials cannot be found when doing `aws s3 cp`. Trying to pass the credentials from the caller workflow in audio to this reusable workflow here. 
Also simplify trigger on whether to upload or not based on the event_name.
=> [Nova] Secrets passed from caller workflow for uploading

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_windows.yml, .github/workflows/test_build_wheels_windows.yml
This PR introduces `inputs.env-script`, this is needed to specify visual c++ compiler variables. `pre-script` can not be reused for this, because the scripts don't export the variables and need to be run in the same command line as `python setup.py bdist_wheel`, not before it.
Also this PR adds smoke tests copied from Linux builds.
=> Add text to win wheels

torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
In the HUD home screen, let the "group by" check box become checked if you hit either the check box or the text associated with it.
Previously, you had to click the checkbox itself
Video before shows before & after behavior
https://user-images.githubusercontent.com/4468967/193086401-2d12bcac-4438-4dc5-a463-22a3e70a9078.mov
=> Expand clickable area to include text

torchci/pages/kpis.tsx
Removes the `Avg Time To Signal - Builds only` and the `% Jobs Red` charts from the KPI page.  Neither of those are that directly relevant to the KPI and offer more noise than signal on the KPI page
=> Remove charts without KPI level signal

torchci/components/JobLinks.tsx, torchci/components/JobSummary.tsx, torchci/components/WorkflowBox.tsx, torchci/lib/types.ts, torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/commit_jobs_query.lambda.json, torchci/rockset/prodVersions.json
Make it easier to tell how long a job has been queued for and how long it ran for from the commit page.
This should be especially handy as we keep track of the increasing ROCm queue times.  (Optionally, we could later remove the queue time if we ever feel like it's no longer a concern)
The effect: It adds subtle stats to the pending & completed workflow jobs
=> Add duration and queue time info to commit summary

.github/scale-config.yml
linux.large GHA runners don't have a lot of disk available, what might cause a breakage in future changes, to avoid that, I am increasing it slightly.
=> GHA scale-config.yml - increase linux.large (c5.large) disk size to 15GiB

torchci/rockset/commons/__sql/flaky_tests.sql, torchci/rockset/prodVersions.json
The test_run collection doesn't exist anymore (possibly migrated to test_run_s3 or deleted entirely in favor of test_run_s3?) so the query is broken
=> [flakybot] fix rockset query using old collection

torchci/lib/types.ts, torchci/pages/api/drci/drci.ts, torchci/rockset/commons/__sql/recent_pr_workflows_query.sql, torchci/rockset/prodVersions.json, torchci/test/drci.test.ts
Recently, I realize that Dr. CI doesn't take the results of retrying jobs into account and this leads to a discrepancy between Dr. CI comment, HUD, and GitHub signal box. This is an example https://github.com/pytorch/pytorch/pull/85313 where Dr. CI reports a failing job while none is showed in https://hud.pytorch.org/pr/85313 or GitHub signal box.  The failed jobs was retried successfully.
Also cleaning up the `recent_pr_workflows_query` query a bit and adding `run_attempt` field.
=> Fix stale Dr. CI comment after retrying jobs

tools/scripts/list_prs_from_partners_by_label.py
Context:
We need a way to track the status and number of the opened PRs, especially those that come from our enterprise partners and are blocked by new CLA. Original request came from Jason Liang.
This script is a quick and dirty way to generate two html pages that aggregate and categorize open PRs in pytorch/pytorch repo by: author/company/feature/CLA status
Example output (pasted into spreadsheet):
Storing this script in test-infra for possible future reuse.
Possible future improvement:
* if we use this often enough, it could be scheduled as a job and it's output integrated into dashboard
=> Script that generates html pages that categorize currently opened PRs in pytorch/pytorch repo

.github/workflows/build_wheels_windows.yml, .github/workflows/test_build_wheels_windows.yml
To build torchaudio on Windows, new workflow parameter is added `inputs.build-params` - to put into command line after `python setup.py bdist_wheel`.
`pre-script` is apparently not needed, because we don't build ffmpeg on Windows.
The testing is done via `test_build_wheels_windows.yml` - it executes the worfklow, which runs "Run Primitive Smoke Tests" step.
=> Add torchaudio to Windows wheels

torchci/components/CommitStatus.tsx, torchci/components/FilteredJobList.tsx, torchci/components/GroupJobConclusion.tsx, torchci/components/JobAnnotationToggle.tsx, torchci/components/JobConclusion.module.css, torchci/components/JobConclusion.tsx, torchci/components/minihud.module.css, torchci/lib/JobClassifierUtil.ts, torchci/pages/api/auth/[...nextauth].js, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/annotations/[jobIds].ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Earlier, we had this but Michael removed it because it was too slow. Today, we add it back since the team wants to start classifying errors.  This PR basically just reverts some of the changes that Michael did, but we don't revert the query speed up. Instead of querying for errors on Rockset, we just check dynamoDB itself once the page has loaded and then fetch all the errors, which still preserves the speedup but makes the failure classifications a little slower but they'll get updated later on. 
Test Plan/User Scenario:
1. User goes to MiniHUD
2. User diagnoses error and selects a classification
3. Once all the errors have been classified, the X will turn a different shade. It will also turn that row into a different color (on refresh)
4. On the HUD page, if all the errors in a grouped …
=> [hud] Add Failure Classification to HUD

torchci/components/CommitStatus.tsx, torchci/components/FilteredJobList.tsx, torchci/components/GroupJobConclusion.tsx, torchci/components/JobAnnotationToggle.tsx, torchci/components/JobConclusion.module.css, torchci/components/JobConclusion.tsx, torchci/components/minihud.module.css, torchci/lib/JobClassifierUtil.ts, torchci/pages/api/auth/[...nextauth].js, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/annotations/[jobIds].ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Same as before https://github.com/pytorch/test-infra/pull/861 with an additional one-liner undefined check ```(data[job?.id ?? ""] && data[job?.id ?? ""]["annotation"]) ?? JobAnnotation.NULL```.  The API returns `{}` when there is no annotation, so `data[job?.id ?? ""]` can be undefined.
* The classification feature is disabled when not logged in
* [PR 86615](https://torchci-git-fork-huydhn-fix-hud-annotation-fbopensource.vercel.app/pr/86615) loads without any issue
* [A sample commit](https://torchci-git-fork-huydhn-fix-hud-annotation-fbopensource.vercel.app/pytorch/pytorch/commit/8f2dda5bf2451765cebeb111a97be40f70c95989) loads without any issue
=> Reland "[hud] Add Failure Classification to HUD" (#861)"

.github/workflows/linux_job.yml, .github/workflows/test_linux_job.yml
conda images are better since conda automatically comes with all of the python versions and people tend to like conda better for test environments
=> ci: Switch generic linux_job to use conda images

torchci/lib/bot/ciflowPushTrigger.ts
Summary: The label will be used to trigger inductor tests on torchbench/huggingface/timm models
=> Add a ciflow/inductor label

tools/scripts/generate_binary_build_matrix.py
Add python 3.11 to Linux wheels nightly so we can start smoke testing python 3.11 wheels
=> Add python 3.11 wheels to nightly and test

.github/scale-config.yml
Adds an ephemeral variant to our linux.4xlarge instances and also makes the name reflect the instance type used
=> ci: Add linux.c5.4xlarge.ephemeral

.github/scale-config.yml
And make them non-ephemeral to have a more reliable testing for sm86
=> Increase max number of `linux.g5.4xlarge` to 30

.github/workflows/test_build_conda_windows_without_cuda.yml
Can not run CUDA builds for now because the available Windows CUDA machine `windows-2019-m60` doesn't have WSL (unlike non-CUDA `windows-2019`), so bash can not be used.
=> Add no-CUDA Win Conda build for audio and vision

tools/scripts/generate_binary_build_matrix.py
Adding with Python 3.11 option
Calling by default:
```
python generate_binary_build_matrix.py
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_7-cpu", "validation_runner": "ubuntu-20.04", "installation": "pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", "desired_cuda": "cu116", "container_image": "pytorch/manylinux-builder:cuda11.6", "package_type": "manywheel", "build_name": "manywheel-py3_7-cuda11_6", "validation_runner": "ubuntu-20.04-m60", …
```
=> Adding with Python 3.11 option

.github/workflows/build_conda_linux.yml, .github/workflows/build_wheels_linux.yml
Ignore python 3.11 failures - these will be removed soon.
=> [Nova] Use the right runner depending on the GPU/CPU type of the build

.github/scale-config.yml
As those runners will be used by the following trunk job: https://github.com/pytorch/pytorch/pull/87228
=> Increase A10G runner max count to 100

torchci/README.md
The old one points to a disabled rule
=> Change link to task creation butterfly bot rule

.github/actions/setup-windows/action.yml, .github/actions/teardown-windows/action.yml, .github/workflows/test_windows_job.yml, .github/workflows/windows_job.yml
Adds a generic windows job that's similar to our generic linux job (#783)
Usage would be like:
```yaml
name: Test build/test windows cpu
on:
pull_request:
push:
branches:
- main
jobs:
build-test:
uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
with:
script: |
pip install -r requirements.txt
python setup.py develop
pytest tests/
```
=> ci: Add generic windows_job

torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts
Old one was a copy/pasta error which resulted in me getting a 401 when I tried to categorize a failure on the HUD commit page
New ID can be verified by going to https://api.github.com/users/ZainRizvi and checking the id
=> Use the correct github user id

torchci/lib/bot/autoCcBot.ts, torchci/test/autoCcBot.test.ts
Looks like GH changed REST API for updating pull request, not it should
look as follows:
https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request
=> Fix autoCC bot for pull request

terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
`removeGithubRunner[Org || Repo]` used to remove the EC2 instance, so no need to call `terminateRunner` again. This potentially could cause runners that failed to be unregistered from GHA to be terminated on EC2.
As a fix, `removeGithubRunner` won't terminate the instance, nor generate logs. This will enable `scaleDown` to control when to call `terminateRunner` and generate the proper logs and metrics. Avoiding having this issue in the future.
This bug also explains why we had in the past more EC2 instances being kept at its minimum time: instances with less than minimum time got unregistered and terminated without being tracked on main application metric. This is obvious when we compare the API calls to terminate and the count of app level termination.
Bug initially flagged on …
=> FIX: Don't remove EC2 instance when fails to remove githubRunner

.github/workflows/macos_job.yml, .github/workflows/test_macos_job.yml
Adds a generic macOS job that users can use to write actions with similar to our generic linux_job
This PR also adds a testing workflow to validate that this generic workflow will work on both x86 as well as M1.
One major benefit of this workflow is that it utilizes our own `setup-miniconda` action which sets up a temporary conda install in `RUNNER_TEMP` pushes that version of conda into our path meaning that users of this script should never have access to a conda install that doesn't get deleted at the end of each run.
Another potential benefit / addition later on is to add the cleanup steps that we do for maintenance to this workflow so it'll get run on every subsequent run.
```yaml
name: Test build/test macos
on:
pull_request:
push:
branches:
- main
jobs:
build-test:
uses: …
```
=> ci: Add generic macos_job

torchci/.env.example
If anyone moves an uncommented NEXTAUTH_URL= to their .env.local file without giving it a proper value, they'll get the below Invalid URL error.
Instead, keep it commented out unless it's actually being used
```
error - TypeError [ERR_INVALID_URL]: Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:371:5)
at onParseError (node:internal/url:552:9)
at new URL (node:internal/url:628:5)
at parseUrl (/Users/dberard/Documents/test-infra/torchci/node_modules/next-auth/utils/parse-url.js:17:16)
at Object.<anonymous> (/Users/dberard/Documents/test-infra/torchci/node_modules/next-auth/react/index.js:70:34)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load …
```
=> Fix .env.example template

torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/master_commit_red.sql, torchci/rockset/metrics/master_commit_red.lambda.json, torchci/rockset/prodVersions.json
Makes the `Commits red on master, by day` chart consistent with the other measurements of master redness, which are based on whether viable/strict upgrades are allowed (change rationale and impact described in https://github.com/pytorch/test-infra/pull/883)
Removing the invalid sources of redness results in a small but noticeable uptick in greenness
Old chart:
New chart:
=> Make "Commits red on master by day" chart consistent

.github/actions/setup-miniconda/action.yml, .github/workflows/generate_binary_build_matrix.yml, .github/workflows/lambda-release-tag-runners.yml, .github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/revert-tracker.yml, .github/workflows/windows_job.yml, aws/websites/metrics.pytorch.org/update_dashboards.py
set-output is set to be removed in the near future, see
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> be: Get rid of deprecated set-output

.gitignore, torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
If for any reason the flaky tests bot breaks, no issues will be created to report flaky tests. This PR monitors the number of issues (in pytorch/pytorch repo) created in the past 14 days that contains label `module: flaky-tests`.  If no issues with the above conditions is found, a new issue is filed on the test infra repository.
See a sample issue here: https://github.com/pytorch/test-infra/issues/908
=> Adds alert if the  flaky tests bot does not file issues for a long period

torchci/pages/flakyjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/commons/__sql/annotated_flaky_jobs.sql, torchci/rockset/commons/__sql/flaky_workflows_jobs.sql, torchci/rockset/commons/annotated_flaky_jobs.lambda.json, torchci/rockset/commons/flaky_workflows_jobs.lambda.json, torchci/rockset/prodVersions.json
Add page for flaky jobs and sql queries.  Takes any job that has been rerun and went from red -> green and any joy that has been annotated as not broken trunk
=> [hud] add page for flaky jobs

.github/scale-config.yml
=> Increase max_available for linux.g5.4xlarge.nvidia.gpu runners

aws/lambda/log-classifier/ruleset.toml, torchci/pages/api/classifier/rules.ts
In the pytorch test logs, prioritize the tasks that fail with SIGKILL or any SIG*error
Also adding an extra rule which should capture the test from the summary line in pytest unit tests like the one below. The [job](https://github.com/pytorch/pytorch/actions/runs/3290106686/jobs/5422888053) for this failed with a test failure, but none of the capture rules matched the logs in this file: https://hud.pytorch.org/pytorch/pytorch/commit/c4cf701889864dceba779569ae642cf95932538a 
The matching string is fairly generic looking, so keeping it as the lowest priority rule for now
```
2022-10-20T14:33:19.0437877Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2022-10-20T14:33:19.0438272Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/test_ops/ …
```
=> Raise priority of sig codes 

torchci/scripts/check_alerts.py
Fixing a bug that was introduced while adding the new [flaky-test bot alert](https://github.com/pytorch/test-infra/pull/910/files#diff-cc0c76fcb740ea4cb8ab9096c157ef05cbc1adfcf397be4b25f8615c933350e4L319)
The bug would result in flaky test bot alerts firing even when there was no underlying error ([example](https://github.com/pytorch/test-infra/issues/930)).  And the way the bot is setup right now, if the zero error issue was left unopened, later on when actual workflow failures happened the bot merely updated the existing issue to show the errors, which resulted in no alert actually being fired for the real errors.
Refactoring the test logic a bit to:
1. Fix the bug
2. Make it easier to add alerts going forward
3. Improve the logic for when we auto-resolve alerts
=> Fix broken alerts

torchci/components/JobConclusion.module.css
Change the color of the red 'X's to have more contrast once a failure is classified. The old color change was subtle enough that it would sometimes be hard to tell if the color was different or not
Old:
New:
=> Improve contrast

.gitignore, terraform-aws-github-runner/modules/runners/lambdas/runners/package.json, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/yarn.lock
Rethrow the octokit 'API rate limit exceeded' errors when fetching runner info on `scale-down` instead of consuming it.
Please see SEV  pytorch/pytorch#87500 for details.
Note: I've decided on the least invasive implementation (re-throwing only very specific class of exceptions) to avoid unintended side effects. Need to discuss with @jeanschmidt if all exceptions could be safely rethrown.
Testing:
* Unit tests
=> Fix runaway runner deletion on scale-down when API quota is hit

.github/actions/setup-miniconda/action.yml, .github/workflows/test-setup-miniconda-env-file, .github/workflows/test-setup-miniconda.yml
There are several bugs in setup-miniconda:
* `--file` flag is at the wrong position and it should come before the list of package. Specifically, `conda create --yes --prefix ~/debug/conda-python-3.9 --file FILENAME python=3.9 cmake=3.22` works while `conda create --yes --prefix ~/debug/conda-python-3.9 python=3.9 --file FILENAME cmake=3.22` as it stands right now doesn't and ends up with `unrecognized arguments: cmake=3.22` error
* The syntax `if: ${{ inputs.environment-file }} == 'SOME STRING'` is wrong and will always evaluate to true. The correct way is `if: inputs.environment-file == 'SOME STRING'`. I missed this subtlety
* The cache should be refreshed when either of `miniconda-env-cache-env-file` or `miniconda-env-cache` has cache miss. At the moment, it requires both have a cache …
=> Fix env file and caching logic bugs in setup-miniconda

torchci/rockset/commons/__sql/test_time_per_file.sql, torchci/rockset/prodVersions.json
Change test_times_per_file query to account for how test_distributed_spawn is split up among different shards now
The previous query caused test_distributed_spawn to show up 3 times in the end result, this query changes it so that the times are summed across shards and then averaged to get the total time
=> change to test times per file query

torchci/components/hud.module.css, torchci/pages/userbenchmark_view.tsx
Basic UI for viewing userbenchmark CSV results.
Usage: go to hud.pytorch.org/userbenchmark_view?url=[url]
where [url] is the path to the S3 csv, e.g.
```
https:%2F%2Fossci-metrics.s3.amazonaws.com%2Ftorchbench-pr-test%2Fpr84626%2Fresult.csv
```
These CSV results are generated on pytorch CI by the run_torchbench job, which runs if "RUN_TORCHBENCH: [userbenchmark name]" is added in the PR body. The userbenchmarks generate CSVs showing performance on a base revision and on the PR revision, for a number of metrics. The CSV is difficult to read on its own.
=> Add userbenchmark viewer

tools/scripts/generate_binary_build_matrix.py
Fix windows libtorch release matrix. Turn off some of the binaries that we currently don't support on windows
=> Fix windows libtorch release matrix

torchci/pages/metrics.tsx
This also uses the correct name for python and cpp docs. With the incorrect names, HUD couldn't find the jobs and reports the wrong last docs push status even though doc build jobs are ok now.
The Rockset query uses exact string matching for job names `AND ARRAY_CONTAINS(SPLIT(:jobNames, ';'), job.name)`.
=> Add functorch docs when checking for last doc push

torchci/rockset/commons/__sql/reverted_prs_with_reason.sql, torchci/rockset/commons/reverted_prs_with_reason.lambda.json, torchci/rockset/prodVersions.json
Fix a bug where the revert tracker doesn't detect the revert type if single quotes are used instead of double quotes, even though that's a valid input
Example of a command it currently fails to detect: `@pytorchbot revert -m "This caused. a failure" -c 'landrace'`
=> Fix regex for detecting revert type

torchci/pages/userbenchmark_view.tsx
All indices were set to 0 before. Updated them to their correct values.
I was probably running `yarn dev` in the wrong directory last time which would have been why I didn't catch this.
=> userbenchmark_view - fix column indices

torchci/pages/metrics.tsx
This modifies how we show the Y axis on the "Number of tests run" chart to ensure the most significant digit is visible
Old:
New:
=> Don't let digits get cutoff the "Number of tests run" chart

torchci/components/TimeUtils.tsx
Today, when you look at any of the Hud views, if the PR was submitted before the current day you loose information about the time it was submitted at, only getting the date
This change modifies the human readable time format to:
1. Show the day of the week & time for PRs (and any other time stamps) fall in the past 7 days
2. Show the date & time for timestamps for anything older
This new behavior makes it easy to see things like "this breaking change, and many PRs after it, were submitted after hours last night" (shown in the screenshots below).
It also improves the granularity in views like the [failure view](http://hud.pytorch.org/failure/ImportError%3A%20%2Fopt%2Fconda%2Flib%2Fpython3.8%2Fsite-packages%2Ftorch%2Flib%2Flibtorch_cuda.so%3A%20symbol%20cudaGraphInstantiateWithFlags%20versio …
=> [BE] Improve  human readable timestamp granularity

.github/scale-config.yml
Inductor+DDP/FSDP testing requires multiple GPUs of  recent architecture.
=> Add support for g5.12xlarge instance

.github/workflows/macos_job.yml, .github/workflows/test_macos_job.yml
I tried adding macos unittests using the generic mac job in https://github.com/pytorch/text/pull/1969 but ran into failures (https://github.com/pytorch/text/actions/runs/3341528363/jobs/5532831734) due to the target repository being used as the working-directory before it was checked out. This tries to fix that issue by doing the repo checkout before the step that uses it as a working directory. The other option is to simply not use the repo as a working-directory for that step (since that step just sets env vars and should be safe to do). 
Also added a few tests that pass the repo argument to the generic job.
=> [Nova] Fix Mac Job: Set Env Vars after repo checkout

.github/scale-config.yml
This will replace the Github Custom Hosted runners we were using previously to run merge bot operations
=> ci: Add linux.large.ephemeral SKU

torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts
If jobs are still pending, don't use a misleading ✅  icon to summarize the job status. Use a hourglass icon instead to show that jobs are still running
Folks have been getting confused while looking at the Dr. CI summary
Old:
New:
=> [BE] Change icon during pending runs to be an hourglass

torchci/components/JobSummary.tsx, torchci/lib/types.ts, torchci/pages/failure/[capture].tsx, torchci/rockset/commons/__sql/failure_samples_query.sql, torchci/rockset/prodVersions.json
* __->__ #969
Pytorch CI's [failure page](https://hud.pytorch.org/failure/test_aot_autograd) can show us failures dashboard for information. However, that page shows errors across all branches, spanning both master and private branches, and doesn't offer any hint of which branch a given failure occurred on. Knowing if failures are happening on the master branch or on private branches would help debug issues much faster.
This change on the failures page, will highlight failures that occurred on the master branch in barcharts so that we could easily see master branch's problem but also show the branch for the failure job detailed list.
This new view could help better identify master branch issues and also get a …
=> improved HUD (barcharts and joblist) failures page with branch information

.github/scale-config.yml
=> increase linux.g5.4xlarge.nvidia.gpu max_available to 300

torchci/components/TestInsights.tsx
MacOS and rocm are now supported after https://github.com/pytorch/pytorch/pull/87827 and https://github.com/pytorch/pytorch/pull/87947
=> Enable test insights page for macos and rocm

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/commit_jobs_query.lambda.json, torchci/rockset/commons/hud_query.lambda.json, torchci/rockset/prodVersions.json
https://hud.pytorch.org/ is currently showing lots of red signals right now but they are all invalid signals coming from this draft PR https://github.com/pytorch/pytorch/pull/88161. This looks like a bug in the way we associate job status with the head sha of the commit.  Take an example:
```
SELECT
job.head_sha as sha,
job.name as job_name,
workflow.name as workflow_name,
job.id,
job.conclusion,
job.html_url as html_url,
CONCAT(
'https://ossci-raw-job-status.s3.amazonaws.com/log/',
CAST(job.id as string)
) as log_url,
DATE_DIFF(
'SECOND',
PARSE_TIMESTAMP_ISO8601(job.started_at),
PARSE_TIMESTAMP_ISO8601(job.completed_at)
) as duration_s,
workflow.repository.full_name as repo,
job.torchci_classification.line,
job.torchci_classification.captures,
job.torchci_classification.line_num, …
```
=> Only show status from push event on trunk HUD

torchci/pages/metrics.tsx
This metric is currently unused. It used to be valuable 6 months ago, but the class of infra problems that it was helpful to track have been addressed now.
Given that we no longer use this metric let's remove it from the dashboard and free up real estate for a more relevant metric
=> Remove stale `% red jobs red on master` metric

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/commons/commit_jobs_query.lambda.json, torchci/rockset/commons/hud_query.lambda.json, torchci/rockset/prodVersions.json
Reverts pytorch/test-infra#992 to restore periodic job display on HUD
=> Revert "Only show status from push event on trunk HUD"

.github/workflows/check-alerts.yml, torchci/scripts/check_alerts.py
Add a comment every time the alert is changed in order to trigger a sync on the internal task, as simply changing the body and title will not trigger the internal task to change.
Then we can make a butterfly bot rule that triggers on comment made on task to message the oncall on workchat.  However, I still have not discovered a way to cause a UBN alert for the oncall aside from make a completely new task.
=> Comment on alert change

torchci/lib/bot/autoLabelBot.ts, torchci/lib/bot/pytorchBotHandler.ts, torchci/test/mergeCommands.test.ts
Makes it so that a user needs to input `@pytorchbot merge` for land validations to start instead of just doing it when a pull request is approved.
This is needed since we've observed that the number of trunk workflows has become equal to the number of pull workflows, which has lead to a high strain on our infrastructure as a whole.
Some constraints of this:
* Does not add the label if attempting a force merge
* Does not add the label if label is already applied
=> pytorchbot: Label with ciflow/trunk only when attempting to merge

terraform-aws-github-runner/main.tf, terraform-aws-github-runner/modules/runners/scale-up.tf
In order to have provisioned concurrency for AWS lambda, it is required to publish versions, and to avoid multiple provisioned versions, the correct approach would be using version aliases.
=> fix provisioned concurrency by pushing a version

torchci/scripts/check_alerts.py
The new butterfly rule works well, but the alert is a bit too spammy at the moment when it tries to send a new workplace chat message whenever the counting of the same alert increases. IMO, oncall doesn't really need to know how many times the same thing breaks as long as we know that it breaks. Keeping the message body the same when there is no new failure type makes this less spammy.
For example, https://github.com/pytorch/test-infra/issues/1002, instead of seeing,
> Within the last 50 commits, there are the following failures on the master branch of pytorch:
* [pull / linux-focal-py3.7-clang7-asan / test (default, 4, 5, linux.2xlarge)](https://hud.pytorch.org/minihud?name_filter=pull%20/%20linux-focal-py3.7-clang7-asan%20/%20test%20%28default%2C%204%2C%205%2C%20linux.2xlarge%29) failed …
=> Avoid spamming for the same alert when its count increases

.github/workflows/build_conda_macos.yml, .github/workflows/test_build_conda_linux_with_cuda.yml, .github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml, .github/workflows/test_build_conda_windows_without_cuda.yml, .github/workflows/test_build_wheels_linux_with_cuda.yml, .github/workflows/test_build_wheels_m1.yml, .github/workflows/test_build_wheels_macos.yml, .github/workflows/test_build_wheels_windows.yml
Pass Smoke Tests to test workflows. Also fix mac conda smoke tests and remove the double-installation of pytorch.
=> [Nova] Passing Torchvision Smoke Test to build workflow

torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/prodVersions.json
We were doing one request per failed row per job annotations, which is
inefficient and caused layout shift as requests raced each other.
Move the job annotation retrieval to the backend.
=> [hud] fix layout shift in HUD

torchci/pages/metrics.tsx
These names are now available after https://github.com/pytorch/pytorch/pull/88589. The old names were generated from the build matrix, i.e. `docs push / build-docs (cpp, linux.12xlarge, 180)`, and required updating whenever parameters like runner type or timeout value changed.
The new names are fixed at `build-docs-${{ DOC_TYPE }}-${{ PUSHED }}`.  The `PUSHED` parameter will always be true here because built docs are pushed to GitHub
https://torchci-git-fork-huydhn-use-fixed-name-for-ce09c0-fbopensource.vercel.app/metrics till https://hud.pytorch.org/pytorch/pytorch/commit/c77368d41615835e5124affe79f88feed93e8855 finishes
=> Use fixed names for docs build jobs

.github/workflows/windows_job.yml, tools/scripts/generate_binary_build_matrix.py
Use windows generic CI workers https://github.com/pytorch/test-infra/wiki/Writing-generic-CI-jobs for the Validation.
Change pywin version to 300 according to [conda issue 11503
](https://github.com/conda/conda/issues/11503)
=> Use generic ci windows runners

torchci/lib/bot/ciflowPushTrigger.ts
https://github.com/pytorch/pytorch/pull/26921 is a special PR and should not receive ciflow tags.
Discovered while debugging what is causing [`Build Docker Images`](https://github.com/pytorch/pytorch/actions/runs/3417468707/jobs/5688640075#step:8:34) job to fail
=> Exclude pytorch/pull/26921 from ciflow

.github/workflows/test_windows_job.yml, .github/workflows/windows_job.yml
This sets job name so that devs can acutally pass job name as a param for example: "win-py3.8-cpu", otherwise it displays as "job". This is specially important since we need to visualize output of this in HUD later
=> Add name parameter to windows ci worker

torchci/pages/tests.tsx
When I tried to find `test_torchinductor` on https://hud.pytorch.org/tests today to see its duration, I couldn't find it because this test takes less than 30m to run.  Originally, I have this parameter set at 30m or 1800s so that it's faster to load https://hud.pytorch.org/tests given that Dev Infra doesn't care much about short tests while we have longer poles to deal with.
* Reducing the threshold to 60s allows all test files taking longer than this to show up. This will include all inductor-related tests
* I don't want to set this to 0 just yet because it would make the size of the returning JSON from Rockset bigger than 4MB and Vercel would throw a perf warning (rightly so)
`test_torchinductor` now shows up correctly on https://torchci-git-fork-huydhn-show-inductor-test-e993f1-fbopenso …
=> Reduce the threshold to display test insights overview to 60s

.gitignore
.gitignore does not use regular expressions, which was the source of
my mistake.
=> fix requirements.txt enabling pattern in gitignore

aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1
This will put all the new dependencies recently added to Windows into the AMI and allow the clean up of Windows conda and pip dependencies
* Build the new AMI `packer build -var 'skip_create_ami=false' .` to generate the new AMI:
```
us-east-1: ami-09867229e1a23e4a4
us-east-2: ami-0d86430cb9c2aa0a8
```
* Launch canary runners with the new AMI `terraform apply -target=module.canary_runners`
* Testing on canary https://github.com/pytorch/pytorch-canary/pull/149
=> Update Windows pip dependencies for opt-einsum

.github/workflows/lint.yml, .github/workflows/tools-self-hosted-runner-utils.yml, tools/self-hosted-runner-utils/check_runners_state.py, tools/self-hosted-runner-utils/clear_offline_runners.py, tools/self-hosted-runner-utils/requirements.txt
Found we didn't actually have a script to do this before and PyGithub doesn't actually support this by default.
Also gives an improvement to the script to give a progress bar when removing the runners.
Distinguished by the lack of `/` in the name
```
python clear_offline_runners.py pytorch --include 'i-.*'
```
```
python clear_offline_runners.py pytorch/pytorch --include 'i-.*'
```
=> tools: Add ability to clear org runners

.github/actions/setup-miniconda/action.yml
This addresses https://github.com/pytorch/pytorch/issues/88968 by cleaning up `com.apple.coresymbolicationd` on macos whenever it runs out of space
Running the change manually on macos runner:
* Do-nothing case case
```
Print the available disk space for manual inspection
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk5s2s1  100Gi   14Gi   33Gi    31%  501138  342681360    0%   /
devfs           219Ki  219Ki    0Bi   100%     758          0  100%   /dev
/dev/disk5s5    100Gi  6.0Gi   33Gi    16%       6  342681360    0%   /System/Volumes/VM
/dev/disk5s3    100Gi  296Mi   33Gi     1%     700  342681360    0%   /System/Volumes/Preboot
/dev/disk1s2    500Mi  6.0Mi  393Mi     2%       1    4028080    0%   /System/Volumes/xarts
/dev/disk1s1    500Mi …
```
=> Clean up macos com.apple.coresymbolicationd

.github/workflows/test_build_conda_linux_with_cuda.yml, .github/workflows/test_build_conda_linux_without_cuda.yml, .github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml, .github/workflows/test_build_conda_windows_without_cuda.yml, .github/workflows/test_build_wheels_linux_with_cuda.yml, .github/workflows/test_build_wheels_linux_without_cuda.yml, .github/workflows/test_build_wheels_m1.yml, .github/workflows/test_build_wheels_macos.yml, .github/workflows/test_build_wheels_windows.yml, tools/scripts/generate_binary_build_matrix.py
This is first PR in consolidating release matrix script logic. Make sure test-infra script creates matrix compatible with pytorch/core
Test PR: https://github.com/pytorch/pytorch/pull/88997
Called regenerate.sh
(note: No generated workflows updated after calling regenerate.sh)
=> Modifying generate binary build matrix. Prepare to migrate Pytorch core to this script

tools/pkg-helpers/poetry.lock, tools/pkg-helpers/pyproject.toml
GitHub has identified a security vulnerability in "py". Since there is no fix, the [workaround](https://github.com/advisories/GHSA-w596-4wvx-j9j6) is to update pytest to a version that does not depend on py
- Repository: [pytorch/test-infra](https://github.com/pytorch/test-infra)
- Manifest file: [tools/pkg-helpers/poetry.lock](https://github.com/pytorch/test-infra/blob/main/tools/pkg-helpers/poetry.lock)
- Package name: py
- Affected versions: <= 1.11.0
- Fixed in version: (No fix version known)
- Severity: MODERATE
https://nvd.nist.gov/vuln/detail/CVE-2022-42969
https://github.com/pytest-dev/py/issues/287
https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316
https://pypi.org/project/py
https://github.com/advisories/GHSA-w596-4wvx-j9j6
=> Security update - remove dependency on py

terraform-aws-github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf, terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json, terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock, terraform-aws-github-runner/modules/webhook/webhook.tf
This PR contains two changes:
1. Fixes a security vuln with the minimatch package (identified by github). More details below
2. Upgrades the aws nodejs runtime past the now End-of-support nodejs12 runtime, which the tflint complained about after fixing the above security vuln
- Repository: [pytorch/test-infra](https://github.com/pytorch/test-infra)
- Manifest file: [terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock](https://github.com/pytorch/test-infra/blob/main/terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock)
- Package name: [minimatch](https://npmjs.com/package/minimatch)
- Affected versions: < 3.0.5
- Fixed in version: 3.0.5
- Severity: HIGH
https://nvd.nist.gov/vuln/detail/CVE-2022-3517 …
=> Upgrade to secure version of minimatch & upgrade deprecated lambda nodejs12 runtime

aws/lambda/log-classifier/ruleset.toml
This PR will result in better diagnosis for workflows that failed due to faulty ROCm runners.
It adds a ruleset for detecting faulty ROCm runners. When a ROCm runner does not have 2 or 4 GPUs, it's considered faulty and the workflow kills the GH action. This manifests in a generic "runner has received a shutdown signal." log line being highlighted in HUD
Example: In [this workflow](https://hud.pytorch.org/pytorch/pytorch/commit/6fe4ccc7cbd5e953e5888947229945f7590e3bfe) the job `linux-focal-rocm5.2-py3.8 / test (default, 2, 2, linux.rocm.gpu)` appeared to fail because of a Github initiated shutdown signal, when in fact the workflow had detected the runner was faulty and initiated the kill signal on it's own
=> Detect faulty ROCm runner in logs

aws/lambda/log-classifier/ruleset.toml
Follow up fix for https://github.com/pytorch/test-infra/pull/1092
Since the ROCm workflow logs include the entire command that would result in an echo _if_ there's a bad runner, the log classifier sees those `echo` lines and assumes that they're the error message we want
Tweaking the regex to not match the echo statements by ensuring the line starts with the error message
Example: https://hud.pytorch.org/pytorch/pytorch/commit/cf6003f0469ae1440d4a8585860c2c5f4c738707
```
Run ngpu=$(rocminfo | grep -c -E 'Name:.*\sgfx')
ngpu=$(rocminfo | grep -c -E 'Name:.*\sgfx')
if [[ "x$ngpu" != "x2" && "x$ngpu" != "x4" ]]; then
if [[ $ngpu -eq 0 ]]; then
echo "Error: Failed to detect any GPUs on the runner"
else
echo "Error: Detected $ngpu GPUs on the runner, when only 2 or 4 were expected"
fi
echo …
```
=> Don't match the echo command

aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1
Have yet another dependency to add to the AMI. This goes together with https://github.com/pytorch/pytorch/pull/89103
```
AMI Windows 2019 GHA CI - 20221116053835
us-east-1: ami-0bac16a0d43e93376
us-east-2: ami-05dc3b7d209fe36d8
```
=> Add pytest-flakefinder to Windows AMI

torchci/rockset/commons/__sql/flaky_tests.sql, torchci/rockset/prodVersions.json
There are some changes needed due to changes in common_utils as a result of rerun disabled tests
* the skipped message now looks like `"message": "{\"num_red\": 1, \"num_green\": 1, \"max_num_retries\": 3, \"rerun_disabled_test\": false, \"flaky\": true}"`
* we don't want to include anything coming from rerun_disabled_tests
=> Update flaky test query

torchci/lib/bot/retryBot.ts, torchci/test/retryBot.test.ts
So far we've limited retry bot to just the lint and pull workflows on the master branch as a way to limit the blast radius while experimenting with this new feature.
The logic seems to work well, so we'll extend this behavior to all workflows that block viable/strict upgrades (which should help reduce TTS).
As a future step, we can also start enabling retrys on PRs requests as well, except there we prob shouldn't retry the build step either.
=> Extend retrybot to trunk and *-binaries workflows

aws/lambda/log-classifier/ruleset.toml
Better identify failures caused by docker, especially docker daemon errors
Keeping the regex a bit generic in case docker has other error messages beyond `docker: Error response from daemon`
Example log that this will correctly classify: https://hud.pytorch.org/pytorch/pytorch/commit/98ecd06580b667441a45bfe7a67bc95ddb8a9353
```
2022-11-10T19:56:18.0780433Z ++ docker run --gpus all -e BUILD_ENVIRONMENT -e PR_NUMBER -e GITHUB_ACTIONS -e BASE_SHA -e BRANCH -e SHA1 -e AWS_DEFAULT_REGION -e IN_WHEEL_TEST -e SHARD_NUMBER -e TEST_CONFIG -e NUM_TEST_SHARDS -e PR_BODY -e COMMIT_MESSAGES -e PYTORCH_RETRY_TEST_CASES -e PYTORCH_OVERRIDE_FLAKY_SIGNAL -e PR_LABELS -e MAX_JOBS=14 -e SCCACHE_BUCKET -e SCCACHE_S3_KEY_PREFIX -e XLA_CUDA -e XLA_CLANG_CACHE_S3_BUCKET_NAME -e PYTORCH_TEST_CUDA_MEM_LEAK_CHECK …
```
=> Identify docker errors

terraform-aws-github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf, terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json, terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock, terraform-aws-github-runner/modules/webhook/webhook.tf
Reverts pytorch/test-infra#1090
this change is breaking webhook lambdas.
=> Revert "Upgrade to secure version of minimatch & upgrade deprecated lambda nodejs12 runtime"

aws/lambda/log-classifier/ruleset.toml
At the moment, the error points to `[error]Process completed with exit code 1` https://hud.pytorch.org/pytorch/pytorch/commit/8ebbd5a89a66bf84d7358f4d353ec2708d6c5429.  It should ideally point to `virtual memory exhausted: Cannot allocate memory` instead but that error is too specific, so I'm adding a rule to point to the very next line `Makefile:73: recipe for target '/var/lib/jenkins/cpp-build/caffe2/build/nccl/obj/collectives/device/devlink.o' failed`
```
2022-11-16T05:12:14.3418222Z virtual memory exhausted: Cannot allocate memory
2022-11-16T05:12:14.9425521Z Makefile:73: recipe for target '/var/lib/jenkins/cpp-build/caffe2/build/nccl/obj/collectives/device/devlink.o' failed
2022-11-16T05:12:14.9427141Z make[5]: *** [/var/lib/jenkins/cpp-build/caffe2/build/nccl/obj/collectives/device/d …
```
=> Add a log classfifier rule for makefile build failure

.github/actions/setup-ssh/action.yml, .github/actions/setup-ssh/index.js, .github/workflows/test-setup-ssh.yml, setup-ssh/src/main.ts
Needed to be able to provide better instructions on how to login into container and debug
Test plan: https://github.com/pytorch/test-infra/actions/runs/3499420140/jobs/5860961273#step:3:12
=> Add `instructions` parameter to setup-ssh

.github/workflows/lint.yml, mypy.ini
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1124).
* #1125
* __->__ #1124
* #1126
remove mypy disabling of warn_unused_ignores
Summary:
This makes sense for the pytorch/pytorch repo where we have a very
diverse band of committers using diverse hardware and setups, but it
makes less sense for pytorch/test-infra where we have a small core
team who have very similar hardware and all work for Meta.
We can all use a similar enough setup to avoid compatibility problems
with this setting.
Test Plan:
Rely on CI.
=> remove mypy disabling of warn_unused_ignores

.github/workflows/lint.yml, aws/lambda/github-status-sync/lambda_function.py, mypy.ini
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1125).
* __->__ #1125
* #1124
* #1126
use mypy --strict
Summary:
The advice for the pytorch/pytorch repo doesn't hold in
pytorch/test-infra because we don't have a heterogenous group of
developers. We can converge on a more modern version of mypy, and it
is already fixed in CI.
We eliminate any flags that are included in mypy --strict or that is
already set to the default.
=> use mypy --strict

.github/actions/setup-miniconda/action.yml
In hindsight, cleaning up disk space should be done at the very first step even before setting up conda.  Otherwise, there might be the case https://github.com/pytorch/pytorch/actions/runs/3494987382/jobs/5851601742 where there is not even enough space to setup conda properly
=> Check for disk space first before setting up conda

tools/scripts/generate_binary_build_matrix.py
Use pypi version for cuda 11.7 in release by default.
As per get started page  for CUDA 11.7 installs we should use for release channel:
```
pip3 install torch torchvision torchaudio
```
=> Use pypi version for cuda 11.7 in release by default

tools/scripts/generate_binary_build_matrix.py
Fix release install command to use pypi for following use cases:
Linux, cuda 11.7
CPU, Windows
CPU, MacOS
=> Add cpu, macos or windows and release channel to pypi default

tools/scripts/generate_binary_build_matrix.py
Fix passing gpu_arch_version to  get_wheel_install_command()
Test:
```
.venv) [atalman@devvm214.ftw0 /data/users/atalman/test-infra (fix_install_command)]$ python tools/scripts/generate_binary_build_matrix.py --operating-system windows --channel release
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "wheel", "build_name": "wheel-py3_7-cpu", "validation_runner": "windows.4xlarge", "installation": "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu", "channel": "release"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", "desired_cuda": "cu116", "container_image": …
```
=> Fix passing gpu_arch_version to  get_wheel_install_command()

tools/scripts/generate_binary_build_matrix.py
Pass os param to get_wheel_install_command()
Test:
```
python tools/scripts/generate_binary_build_matrix.py --operating-system linux --channel release
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_7-cpu", "validation_runner": "ubuntu-20.04", "installation": "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu", "channel": "release"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", "desired_cuda": "cu116", "container_image": "pytorch/manylinux-builder:cuda11.6", "package_type": "manywheel", "build_name": "manywheel-py3_7-cuda11_6", …
```
=> Pass os: str to get_wheel_install_command()

.github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1147).
* #1148
* __->__ #1147
group Python environment setup output into its own section
Summary:
This makes it easier to distinguish setup failures from actual command
failures.
Test Plan: Manually inspect workflow output.
=> group Python environment setup output into its own section

tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1140).
* #1143
* #1142
* #1141
* __->__ #1140
parameterize the api checker on head and base commits
=> parameterize the api checker on head and base commits

tools/scripts/generate_binary_build_matrix.py
Fix macos install instructions. Refer to following jobs:
https://github.com/pytorch/pytorch/actions/runs/3315856876/jobs/5478609124
Test:
```
python tools/scripts/generate_binary_build_matrix.py --operating-system macos --package libtorch --channel release
{"include": [{"gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "libtorch_variant": "shared-with-deps", "libtorch_config": "", "devtoolset": "pre-cxx11", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "libtorch", "build_name": "libtorch-cpu-shared-with-deps-pre-cxx11", "validation_runner": "macos-12", "installation": "https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.13.0.zip", "channel": "release"}, {"gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", …
```
=> Fix macos instructions for nightly and release

.github/workflows/linux_job.yml, .github/workflows/test_linux_job.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1156).
* __->__ #1156
allow customizing the linux_job docker image
Summary:
The pytorch/conda-builder image is massive and unnecessary for many
use-cases. Allowing a smaller image speeds up CI runs.
Test Plan: Tested with stronghold jobs in draft PR.
=> allow customizing the linux_job docker image

.github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1158).
* #1159
* #1148
* __->__ #1158
use smaller docker images for stronghold runs
Summary:
The smaller image takes 2s to download as opposed to 50s for
pytorch/conda-builder.
Test Plan: Verified in CI.
=> use smaller docker images for stronghold runs

.github/workflows/linux_job.yml, .github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1148).
* #1159
* __->__ #1148
* #1158
pass the GITHUB_STEP_SUMMARY to the custom script
Summary:
We have to pass both the environment variable and the file to the
container.
It is unknown why the environment variable is different inside the
container.
Test Plan: Verified with stacked PR.
=> pass the GITHUB_STEP_SUMMARY to the custom script

tools/scripts/generate_binary_build_matrix.py
Add stable version to matrix.
Use generic linux runners as per: https://github.com/pytorch/test-infra/wiki/Writing-generic-CI-jobs
=> Add stable version to matrix, use generic linux runners

torchci/pages/failure/[capture].tsx
Sort the `Failures by job` view in the failures page, sorting first by the frequency of the failure, then sorting alphabetically by job name.
Example using https://hud.pytorch.org/failure/RuntimeError%3A%20test_jit_cuda_fuser%20failed
Old view:
New view:
=> [BE] Sort the grouped failures in the failure view

tools/scripts/generate_binary_build_matrix.py
MacOS  Arm64 do not have libtorch builds. Ref HUD: https://hud.pytorch.org/hud/pytorch/pytorch/nightly
Test:
```
python generate_binary_build_matrix.py --operating-system macos-arm64 --package-type all
{"include": [{"python_version": "3.8", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "wheel", "build_name": "wheel-py3_8-cpu", "validation_runner": "macos-m1-12", "installation": "pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly", "stable_version": "1.13.0"}, {"python_version": "3.9", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", …
```
=> Macos arm64 libtorch fix

.github/scripts/update_disabled_tests.py, .github/workflows/update_disabled_tests.yml
Per title, this regenerates the list of non flaky tests that are still disabled.  The definition of a non flaky tests come from [commons.disabled_non_flaky_tests](https://console.rockset.com/lambdas/details/commons.disabled_non_flaky_tests):
* ~~Its last rerun is newer than 1 day, so there is no stale data~~ Check 1 week worth of rerun data
* No red signal
* The number of green signals is more than 50
The first batch includes 50 tests that can be closed safely https://paste.sh/tAdzOiTB#HGwyJeJQAN3CiMKJyoR-mXuT.  I will give folks a head up and do this manually for now.  Automation will come later,
(Also run ufmt linter on top of the script so there are some formatting changes here and there)
Run `/update_disabled_tests.py --dry-run` locally and confirm the output
=> Report all disabled tests that are not flaky anymore

tools/scripts/generate_binary_build_matrix.py
All the libtorch builds for windows maps to following 2 builds currently:
libtorch-win-shared-with-deps-debug-latest.zip
libtorch-win-shared-with-deps-latest.zip
Please refer to following builds:
https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=windows-binary-libtorch
=> Fix windows nightly libtorch

terraform-aws-github-runner/main.tf, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts, terraform-aws-github-runner/modules/runners/main.tf, terraform-aws-github-runner/modules/runners/scale-up.tf, terraform-aws-github-runner/modules/runners/variables.tf, terraform-aws-github-runner/variables.tf
AWS security groups need to be assigned to the correct VPC, with the new design of multiple VPCs there is a need to manage multiple SG and the hierarchical relationship for Region -> VPCs -> (subnet, sg);
=> Fixes to correctly assign the security group to the ec2 runner

.github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/windows_job.yml
This is important for validation workflow to continue and execute all the test plan. Hence adding this input param.
=> Add continue on error input param to generic jobs

.github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1164).
* __->__ #1164
* #1163
decrease runner size to linux.large for Stronghold CI
Summary:
Very lightweight jobs, don't need anything beefy.
=> decrease runner size to linux.large for Stronghold CI

.github/workflows/build_conda_macos.yml
I found that the path to the anaconda binary after manipulating the output of `conda info --base` does not seem to be correct, since the command gives us the path of the base environment. I tested removing this and just using the anaconda executable (which should be on the path). I've tried this on my local machine - would need some testing on an M1 machine.
=> [Nova] Fix call to anaconda during upload in Mac Conda builds

tools/scripts/generate_binary_build_matrix.py
Please refer to getting started page:
https://pytorch.org/get-started/locally/
For macos we don't include cpuonly flag.
Test
```
python generate_binary_build_matrix.py --operating-system macos --package conda
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/conda-builder:cpu", "package_type": "conda", "build_name": "conda-py3_7-cpu", "validation_runner": "macos-12", "channel": "nightly", "stable_version": "1.13.0", "installation": "conda install pytorch torchvision torchaudio  -c pytorch-nightly"}, {"python_version": "3.8", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/conda-builder:cpu", "package_type": "conda", "build_name": "conda-py3_8-cpu", …
```
=> Remove conda cpuonly flag for macos installs

tools/scripts/generate_binary_build_matrix.py
Fixes small issue:
```
conda install pytorch torchvision torchaudio  -c pytorch-nightly
```
should be 
```
conda install pytorch torchvision torchaudio -c pytorch-nightly
```
issue can be seen here: https://github.com/atalman/pytorch.github.io/pull/2/files
=> Remove extra space when no conda_package_type specified

.github/workflows/test_build_conda_linux_without_cuda.yml, .github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml, .github/workflows/test_build_conda_windows_without_cuda.yml, .github/workflows/test_build_wheels_linux_without_cuda.yml, .github/workflows/test_build_wheels_m1.yml, .github/workflows/test_build_wheels_macos.yml, .github/workflows/test_build_wheels_windows.yml
Torchtext now has a pre-script that installs torchdata as a dependency. This needs to be reflected in our test workflows.
=> [Nova] Torchtext pre-script

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
The upload artifact job is reasonably flaky and fails due to network error. We don't want this to kill the entire build workflow, so we should instead allow the workflow to continue.
Example of the upload failure: https://github.com/pytorch/vision/actions/runs/3579298451/jobs/6020356355
=> [Nova] Continue workflow even if upload artifact fails due to network error

.github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/windows_job.yml
To fix issues related to:
```
Error: fatal: No url found for submodule path 'test-infra' in .gitmodules
Error: The process '/usr/bin/git' failed with exit code 128
```
Also adds verbose output to the cleanup that's hidden behind a collapsible log group
This is a follow up to #1203 
=> fix: add cleanup step prior to checkout

.github/workflows/test_build_conda_windows_without_cuda.yml, .github/workflows/test_build_wheels_windows.yml
The recent changes to windows builds with the pre-script is causing windows builds for torchvision to break. I'm going to see if naively adding the pre-script will make these work. If not, I'm going to disable the Windows Vision tests on each PR and create a task for closing later, since we're not migrating Windows builds in the near future, and having clear signal on test-infra PR's is critical for us to smoothly complete the ongoing migrations for the other OS's.
=> Disable Windows Vision Test Workflows

tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/tests/api/test_ast.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1208).
* #1143
* #1142
* #1211
* #1210
* #1209
* __->__ #1208
track the line number where functions are defined
Summary:
We can use this to write our annotations to the GitHub UI.
=> track the line number where functions are defined

tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/src/api/compatibility.py, tools/stronghold/src/api/github.py, tools/stronghold/tests/api/test_ast.py, tools/stronghold/tests/api/test_compatibility.py, tools/stronghold/tests/api/test_github.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1210).
* #1143
* #1142
* #1211
* __->__ #1210
* #1209
* #1208
add a function to render a violation as a github warning
Summary:
When printed to the log, this will render a warning in the GitHub UI.
Test Plan: Visually inspect with downstream test PRs.
=> add a function to render a violation as a github warning

tools/scripts/generate_binary_build_matrix.py
Needed for https://github.com/pytorch/vision/pull/6955
=> Update scripts to ROCm5.3

.github/workflows/build_conda_linux.yml
This fixes errors during smoke test, like the ones can be seen on this PR: https://github.com/pytorch/vision/pull/7015
which are caused by package that normally should be smoke tested being overwritten by the package from prod
=> Do package install last

.github/scale-config.yml
In order to avoid limiting the number of instances artificially:
=> Increase max_available for linux.12xlarge to 350

aws/lambda/log-classifier/ruleset.toml
Example that this fixes:
In https://hud.pytorch.org/pr/90405 the real error is "ERROR ENCOUNTERED WHEN UPLOADING TO SCRIBE" but the regexes are matching an irrelevant error line
=> Correctly identify error logs for Scribe upload failures

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/test_build_conda_linux_with_cuda.yml, .github/workflows/test_build_conda_linux_without_cuda.yml, .github/workflows/test_build_conda_m1.yml, .github/workflows/test_build_conda_macos.yml
Uploading our built conda binaries from within the pre-existing conda environment caused failures of the following form:
```
+ ${CONDA_RUN} /opt/conda/bin/anaconda -t *** upload dist/linux-64/torchvision-0.15.0.dev20221207-py37_cpu.tar.bz2 -u pytorch-nightly --label main --no-progress --force
Using Anaconda API: https://api.anaconda.org/
Using "pytorch-nightly" as upload username
Processing 'dist/linux-64/torchvision-0.15.0.dev20221207-py37_cpu.tar.bz2'
Detecting file type...
File type is "Conda"
Extracting conda attributes for upload
Creating package "torchvision"
Creating release "0.15.0.dev20221207"
Error:  ('"torchvision" could not be found', 404)
```
When we create a fresh conda environment just to install the anaconda client and do the upload, they all seem to go through. While I …
=> [Nova] Fix Anaconda Upload Issue

aws/lambda/log-classifier/ruleset.toml
* `Any SIGKILL` keeps matching test names that have sigkill in them or skip test messages
* `RuntimeError: functorch/test_aotdispatch failed!` kept getting matched to `Python RuntimeError` but `Python Test File RuntimeError` is probably more accurate
* `Library not loaded` for an error I keep seeing on mac that looks like 
```
2022-12-06T04:06:15.0506380Z Testing custom script operators
2022-12-06T04:06:15.0506520Z + [[ 1 == 1 ]]
2022-12-06T04:06:15.0506640Z + test_libtorch
2022-12-06T04:06:15.0506860Z ~/runner/_work/pytorch/pytorch/test/custom_operator ~/runner/_work/pytorch/pytorch
2022-12-06T04:06:15.0507060Z + [[ 0 == \1 ]]
2022-12-06T04:06:15.0507190Z + test_custom_script_ops
2022-12-06T04:06:15.0507390Z + echo 'Testing custom script operators'
2022-12-06T04:06:15.0507580Z + pushd …
```
=> Change some log rules

tools/scripts/generate_binary_build_matrix.py
Fix release and test libtorch windows file names
Out of the whole matrix we only have these ones:
```
Download here (Release version):
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.13.0%2B<CUDA/CPU VERSION>.zip
Download here (Debug version):
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-1.13.0%2B<CUDA/CPU VERSION>.zip
```
=> Fix release and test libtorch windows file names

.github/actions/teardown-windows/action.yml
Useful if teardown-windows is used on stock GHA runners
=> Do not fail shutdown if no sshd is running

.github/workflows/test_linux_job.yml
Adding a few more checks for the GPU generic linux job to ensure that we can:
1. Create a torch tensor on GPU
2. Verify it's device affinity
3. Run `nvidia-smi`
=> [Nova] More tests for Generic Linux job

.github/workflows/stronghold.yml, tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1252).
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* #1256
* #1255
* #1253
* __->__ #1252
move the git fetch into the checker program
Summary:
When we push this to other repos, we'll want as much of the
implementation embedded in the binary as possible.
=> move the git fetch into the checker program

.github/workflows/stronghold.yml, tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1253).
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* #1256
* #1255
* __->__ #1253
* #1252
group and suppress the fetch output by default
Summary: This is noisy and uninteresting: hide it.
Test Plan: Verify visually in CI.
=> group and suppress the fetch output by default

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml, tools/pkg-helpers/pytorch_pkg_helpers/__main__.py, tools/pkg-helpers/pytorch_pkg_helpers/conda.py, tools/pkg-helpers/pytorch_pkg_helpers/wheel.py, tools/pkg-helpers/tests/test_macos.py, tools/pkg-helpers/tests/test_wheel.py, tools/scripts/generate_binary_build_matrix.py
For repositories that don't offer CUDA support we need a way to have representative binaries in the base bucket (which was the previous behavior from CircleCI). This PR makes it so that the s3 bucket path is derived from pkg_helpers and keys off of a matrix variable that we generate from generate_binary_build_matrix
=> tools: Add option to upload to base bucket

tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
Some 12/12 wheels weren't successfully uploaded due to this issue with the S3 upload path. 12/11 and before were uploaded successfully
=> Upload Path Fix

torchci/lib/bot/cliParser.ts
Fixes https://github.com/pytorch/pytorch/issues/90758
Corrects the `@pytorchbot rebase` help text
=> Fix rebase help text

torchci/rockset/commons/__sql/failure_samples_query.sql, torchci/rockset/commons/failure_samples_query.lambda.json, torchci/rockset/prodVersions.json
http://localhost:3000/failure/test_backward_symeig_cuda_float32
http://localhost:3000/failure/test_cublas_baddbmm_large_input_1_10000_10000_10000_cuda_float32%2CTestMatmulCudaCUDA 
should both work now
* uses the torchci_classifications column in the workflow_jobs table (which is populated after the log classifier got changed by suo?)
* commas get replaced with % so that the captures arrays can be used
=> Fix failures query

torchci/lib/bot/retryBot.ts, torchci/test/retryBot.test.ts
This PR introduces two changes:
1. It pairs with https://github.com/pytorch/pytorch/pull/90705 to avoid retrying linter steps which do the actual linting or building, limiting retrys to infra level steps which are actually likely to be flaky 
2. Extend retry mechanism to all PRs, not just trunk.
If a retryable step fails before a nonretryable step, the behavior will be determined by the if [the conditions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) defined on that step allow that step to run.  By default, steps get skipped if a previous step is skipped (and its conclusion will be `skipped`, which retry bot treats the same way as successful steps). This is the case for all the nonretryable steps today. However, if a step is set to run on …
=> RetryBot enhancements: Better retry logic & Extend retry mechanism to PRs

aws/lambda/log-classifier/ruleset.toml
After https://github.com/pytorch/test-infra/pull/1243, scribe error was added into the log classifier ruleset.  However, it has a higher priority than some actual failures such as https://hud.pytorch.org/pytorch/pytorch/commit/dcb73aa291816d0ee2d2e21b6b8a966da97945ad in which the job fails with a flaky SIGSEGV `RuntimeError: test_meta failed! Received signal: SIGSEGV`
This PR lowers the priority of this rule so that valid test failures can be shown on HUD
=> Lower the priority of scribe error in log classifier rule

torchci/lib/bot/retryBot.ts, torchci/test/retryBot.test.ts
can result in a weird race where someone pushes a commit -> trigger job 1 -> job 1 fails
push another commit -> trigger job 2
job 1 gets rerun -> job 2 gets cancelled
seems to be a pr exclusive problem b/c of concurrency group
=> Revert "RetryBot enhancements: Better retry logic & Extend retry mech… …anism to PRs (#1275)"

.github/workflows/build_conda_linux.yml
Nova / TorchData / Fix smoke tests
To be able to run smoke tests for TorchData, we need to install the portalocker library. Related PR https://github.com/pytorch/data/pull/921
=> Nova / TorchData / Fix smoke tests

aws/lambda/log-classifier/ruleset.toml
* scribe rule is not a real failure? or at least it happens on succeeding jobs as well
* xla tests dont include the time 
* eager_variation for a model fails on inductor
* reorder so that the test file error is higher
* rule specifically for job cancellation b/c it currently matches to the last rule, idk if it should be this high tho
=> More log classifier changes

tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/tests/api/test_ast.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1298).
* #1291
* #1221
* #1304
* #1303
* #1302
* #1301
* #1299
* __->__ #1298
track the line number where a parameter is defined
Summary:
This will allow us to propagate the line number to violations.
Test Plan:
Rely on CI.
=> track the line number where a parameter is defined

tools/stronghold/src/api/compatibility.py, tools/stronghold/tests/api/test_compatibility.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1302).
* #1291
* #1221
* #1304
* #1303
* __->__ #1302
simplify parameter reordering check
Summary:
The previous check was very noisy when a parameter was added. This will allow us to simplify it down the line.
=> simplify parameter reordering check

tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/src/api/compatibility.py, tools/stronghold/tests/api/test_ast.py, tools/stronghold/tests/api/test_compatibility.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1304).
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* __->__ #1304
* #1303
no longer track position for each parameter
Summary: This can be tracked by its order in the Parameters object.
=> no longer track position for each parameter

tools/stronghold/src/api/compatibility.py, tools/stronghold/tests/api/test_compatibility.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1303).
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* #1304
* __->__ #1303
use difflib to better detect changes to positional parameters
Summary:
Fundamentally, for parameters that may be passed positionally, we care
about which from the previous function correspond to the later
function. Diffing is a clean way to do that.
Test Plan: Rely on CI. Verify end-to-end in GitHub UI.
=> use difflib to better detect changes to positional parameters

tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/src/api/compatibility.py, tools/stronghold/tests/api/test_ast.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1312).
* #1291
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* __->__ #1312
[Reland] no longer track position for each parameter
Summary: This can be tracked by its order in the Parameters object.
=> [Reland] no longer track position for each parameter

tools/scripts/generate_binary_build_matrix.py
Add ability to use comma separated values for packages to generate matrix.
Test
```
python generate_binary_build_matrix.py --package-type conda,wheel
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/conda-builder:cpu", "package_type": "conda", "build_name": "conda-py3_7-cpu", "validation_runner": "linux.2xlarge", "channel": "nightly", "stable_version": "1.13.1", "installation": "conda install pytorch torchvision torchaudio cpuonly -c pytorch-nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", "desired_cuda": "cu116", "container_image": "pytorch/conda-builder:cuda11.6", "package_type": "conda", "build_name": "conda-py3_7-cuda11_6", "validation_runner": …
```
=> Add ability to use comma separated values for packages

torchci/lib/bot/pytorchBotHandler.ts, torchci/test/fixtures/pull_request_reviews.json, torchci/test/mergeCommands.test.ts
Get pytorchbot to check the approval status of a PR before it forwards a merge request to the trymerge workflow.
This allows devs to know sooner if their merge request is invalid (trymerge already checks the same things, but can take an extra few minutes before offering that feedback)
=> Require approval before attempting merges

aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1
Validated by logging into new AMI:
```
cat /c/Jenkins/Miniconda3/etc/profile.d/conda.sh                                       
export CONDA_EXE='C:/Jenkins/Miniconda3\Scripts\conda.exe'                                                                            
...
```
With conda 2.11.0
```
cat /c/Jenkins/Miniconda3/etc/profile.d/conda.sh                                       
export CONDA_EXE='/cygdrive/c/b/abs_67xozs_u6y/croot/conda_1670407450197/_h_env/Scripts/conda.exe'    
.....     
```
Test PR: https://github.com/pytorch/pytorch-canary/pull/153
=> Fix windows conda 22.11.0 regression

torchci/lib/bot/retryBot.ts, torchci/test/retryBot.test.ts
2nd attempt of https://github.com/pytorch/test-infra/pull/1275
This time we limit only cancelled jobs and workflows on the `master` branch. This approach will result in false negatives, where we won't retry some jobs on PRs which should be retried, but it's better than the current situation of never retrying on pulls and we can iterate on it going forward while still catching many kinds of infra flakes
=> RetryBot enhancements v2: Better retry logic & Extend retry mechanism to PRs

torchci/lib/types.ts, torchci/pages/api/drci/drci.ts, torchci/rockset/commons/__sql/recent_pr_workflows_query.sql, torchci/rockset/prodVersions.json
change sql query to get all workflows (previously got only the ones that didnt have any jobs), then the code that removes reruns removes the workflows that are rerun, then remove workflows if there is a job belonging to the workflow -> no double counting
=> [drci] fix cancelled workflows showing up

torchci/components/JobAnnotationToggle.tsx, torchci/components/NavBar.tsx, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[annotation].ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/failures/[queryParams].ts, torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/flakyjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/commons/__sql/flaky_workflows_jobs.sql, torchci/rockset/commons/flaky_workflows_jobs.lambda.json, torchci/rockset/prodVersions.json
This change groups failures in https://torchci-git-fork-huydhn-group-failure-classifier-fbopensource.vercel.app/flakyjobs/pytorch/pytorch/master not only by their annotations, but also by a combination of job name, workflow name, and the associated failure message.  The goal is to make is easier to classify similar failures in one go.
There is a long is of annotated and unannotated failures on https://hud.pytorch.org/flakyjobs/pytorch/pytorch/master.  Many of them are duplication.
Similar failures (same job name, workflow name, and failure message) are group into a single entry, https://torchci-git-fork-huydhn-group-failure-classifier-fbopensource.vercel.app/flakyjobs/pytorch/pytorch/master, represented by a randomly selected failure in the list.  In addition, the list of similar jobs can …
=> Classify groups of similar failures

torchci/pages/api/flaky-tests/disable.ts, torchci/rockset/commons/disabled_non_flaky_tests.lambda.json, torchci/rockset/prodVersions.json
This PR removes the 5% rollout threshold currently enforced whenever flaky bot runs given that this has been running without any issues for a few weeks.
@clee2000 Per our discussion, I have also raised the minimum number of green signals to 150 instead of the current 50 to ensure that there is no false positive.
=> Remove enabling non-flaky tests feature gating

.github/actions/export-matrix-variables/action.yml, .github/scripts/export_matrix_variables.py, .github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/test-export-matrix-variables.yml, .github/workflows/test_linux_job.yml, .github/workflows/windows_job.yml
Its based on @seemethere work here: https://github.com/pytorch/test-infra/pull/1201
Adds the ability for the workflow to export matrix variables as environment variables for our generic workflows. All environment variables will be reference like so:
```
MATRIX_${var_name}
```
With this we can remove all the environment initialization in the validation workflows, here is an example: https://github.com/pytorch/builder/blob/main/.github/workflows/validate-linux-binaries.yml#L54
=> ci: Add action to export matrix variables

torchci/pages/failure/[capture].tsx
In the "similar failures" view, sort the matches by recency (currently they're randomly ordered)
Example page: https://hud.pytorch.org/failure/test_fs_sharing%2CTestMultiprocessing
Old sorting, which shows months old results at the top:
New sorting, which shows todays failures up top:
=> [BE] Sort similar failures by recency

torchci/README.md, torchci/scripts/downloadQueryLambda.mjs
This PR has three changes:
1. Auto-update the sql version number in prodVersion.json when you download a rockset query (and update docs accordingly)
2. Fix a bug where if you try downloading a rockset query belonging to a new workspace, the download fails because its directory doesn't exist
3. Doc improvement to mention that the version number doesn't have to be specified if you're downloading the latest version (which most folks are!)
=> [BE] Streamline rockset query updating experience

.github/workflows/build_wheels_windows.yml, .github/workflows/test_build_wheels_windows_with_cuda.yml, .github/workflows/test_build_wheels_windows_without_cuda.yml
Use self-hosted runners windows.4xlarge and windows.8xlarge.nvidia.gpu instead of GitHub-hosted windows-2019.
Also add separate workflows to tests builds on GPU and non-GPU machines.
=> [Nova] Use windows.4xlarge and windows.8xlarge.nvidia.gpu for Windows wheel builds

torchci/scripts/pushRocksetTags.mjs
We have too many query lambdas, resulting in rate limits when we try to tag all of them as prod, so check if the prod tag is already there before tagging.  Rate limit for modifying is lower than just reading apparently.
<details><summary>tested by running locally</summary>
```
(forpytorch) csl@csl-mbp ~/zzzzzzzz/test-infra/torchci % yarn node scripts/pushRocksetTags.mjs 
yarn node v1.22.18
commons.annotated_flaky_jobs:1e7bd01a839ae4d1 already tagged as 'prod'
pytorch_dev_infra_kpis.number_of_force_pushes_historical:7f57dbe505878a81 already tagged as 'prod'
pytorch_dev_infra_kpis.strict_lag_historical:d2a09d13caf8b76a already tagged as 'prod'
metrics.workflow_duration_avg:b92d60f09ac39069 already tagged as 'prod'
metrics.log_captures_count:9cbd496ad254c3de already tagged as 'prod' …
```
=> Check if rockset version is already correct when tagging prod

torchci/components/CommitStatus.tsx, torchci/components/GroupJobConclusion.tsx, torchci/components/JobConclusion.module.css, torchci/components/JobConclusion.tsx, torchci/components/JobSummary.tsx, torchci/lib/JobClassifierUtil.ts, torchci/lib/jobUtils.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This provides a cleaner view on HUD for warning-only jobs such as `rerun_disabled_tests` failures where they only serve to provide signals to a specific group of devs, i.e. PyTorch Dev Infra.  In addition, some `rerun_disabled_tests` jobs are expected to fail or hang depending on the nature of the disabled tests.
Everything is shown as failed jobs on HUD, i.e.
* https://hud.pytorch.org/pytorch/pytorch/commit/5030929c5d124e68e4d73b8933973f754d2d5d43
* https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=rerun
Failures jobs from `rerun_disabled_tests` are only shown as warnings in their separate section and with a lighter red:
* https://torchci-git-fork-huydhn-better-jobs-view-fbopensource.vercel.app/pytorch/pytorch/commit/5030929c5d124e68e4d73b8933973f754d2d5d43
* …
=> Show rerun_disabled_tests failures as only warnings

torchci/lib/types.ts, torchci/pages/api/flaky-tests/disable.ts, torchci/rockset/commons/__sql/issue_query.sql, torchci/rockset/prodVersions.json, torchci/test/disableFlakyBot.test.ts, torchci/test/drci.test.ts
This is an annoying UX issue that I miss where PyTorch flaky bot keeps trying to resolve issues that it considers non-flaky according to the signals from Rockset, i.e. https://github.com/pytorch/pytorch/issues/67002.  The better approach is to leave the issue open for X days, seeing that there is no update, before closing them.  If closing a supposedly non-flaky issue leads to false positive and redness on HUD, re-opening them or putting a comment there should be sufficient to tell the flaky bot to leave it alone for the time being. The waiting period is 2 weeks (or 14 days)
=> Only close non-flaky issue if it hasn't been updated in 2 weeks

.github/actions/setup-binary-builds/action.yml
This most nightly wheel builds for vision and audio:
https://github.com/pytorch/vision/actions/runs/3800536129/jobs/6466764135
Please note torchrec builds are broken since 15.12.2022 : https://github.com/pytorch/torchrec/actions/runs/3704102590
Had to fix miniconda version as per: https://github.com/conda-incubator/setup-miniconda/issues/261
=> Pin miniconda version, fixes vision and audio binary wheel builds

torchci/pages/kpis.tsx
=> Have KPIs be annual for a fuller pic

.github/workflows/clang-tidy-linux.yml, .github/workflows/clang-tidy-macos.yml, tools/clang-tidy-checks/README.md, tools/clang-tidy-checks/setup.sh
Update version to 11.1.0 (because why not)
Skip `ld.lld64` checks on MacOS
To avoid regressions similar to https://github.com/pytorch/pytorch/pull/91008 upload new binaries to a different folder
Add concurrency limit to both linux and macos clang-tidy workflows
=> Build clang-tidy for both Intel and M1 Mac machines

.github/scale-config.yml
It looks like Windows G5 runners is running fine with the current AMI when testing with canary here https://github.com/pytorch/pytorch-canary/actions/runs/3840601762/jobs/6539860392.  The only required change is to build PyTorch with `sm_86` on Windows accordingly.
This PR actually adds some of these runners to PyTorch so that they can be tested there on PyTorch CI as canary code base is not fully in sync.  Running the final test on PyTorch CI also gives me a better estimation of the performance gain with the new runner v.s. the existing one `p3.2xlarge`
This is similar to https://github.com/pytorch/pytorch-canary/pull/156
=> Add some experiment Windows G5 runners for CI

.github/workflows/build_conda_linux.yml, tools/scripts/generate_binary_build_matrix.py
This adds CUDA 11.8 to release matrix.
We already support CUDA 11.8 in PyTorch nightly: https://hud.pytorch.org/hud/pytorch/pytorch/nightly
Please note: We don't need cudatoolkit installation anymore. It was used for CUDA 10.2, 11.3, 11.5 . For CUDA version 11.6 and forward we will be using pytorch-cuda package
=> Adding cuda 11.8 to matrix

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Only alerts if the jobs change (previously I think I was getting messages whenever the commit sha changed, which I think is much less important)
Change the message from just "updating alert" to ![image](https://user-images.githubusercontent.com/44682903/210650062-80e8f5f2-a760-49f0-a604-420a85386f40.png)
=> [alerts] More descriptive alert message

torchci/lib/fetchHud.ts, torchci/lib/types.ts, torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Filter out rerun_disabled_tests from minihud because they're not important signal and it results in a long list of failed jobs
=> [minihud] Filter out reruns

torchci/lib/bot/pytorchBotHandler.ts, torchci/test/mergeCommands.test.ts
This adds two changes:
1. Support pagination for when we read the PRs from github
2. Go back to the old behavior of mergebot where PRs can be merged if there's a single valid approver, regardless of if there's another PR that's requesting changes (we're prioritizing "trust the developer" for now)
=> Paginate Github PRs + prevent changes_requested from blocking PR approvals

terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/kms/index.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
Added expBackOff for GH API calls that could fail, avoiding both a crash and a retry-storm. 
The behaviour of abrupt stop for scaleDown is still maintained, as it is reasonable to avoid scaleDown when on a pinch
=> Fix edge cases on #938 'Fix runaway runner deletion on scale-down when API quota is hit'

.github/scripts/export_matrix_variables.py
This fixes bug with values setting.
For example:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
```
would be converted to:
```
pip3 install torch torchvision torchaudio __extra_index_url https://download.pytorch.org/whl/cpu
```
which is not correct
=> Fixes setting matrix env vars

.github/scale-config.yml
I have obtained good results when trying to run Windows CUDA tests on G5 runners https://github.com/pytorch/pytorch/pull/91727.  It's not only faster but also cheaper with a 25% job duration gain and 45% cost reduction.
So I'm looking forward to roll this out by increase the max capacity of Windows G5 to 150 (same as windows.8xlarge.nvidia.gpu).  Do we have any concern or limitation on the number of G5 runners on AWS us-east-1?
=> Increase max Windows G5 count to 150 (same as windows.8xlarge.nvidia.gpu)

.github/actions/export-matrix-variables/action.yml, .github/scripts/export_matrix_variables.py, .github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/test-export-matrix-variables.yml
Fixes an issue when using install command with MATRIX env var. Without this change only first word of install command is assigned to env var. For example if install is:
```
conda install pytorch torchvision torchaudio cpuonly -c pytorch
```
the MATRIX_INSTALL would be:
```
conda
```
With this fix, it should be resolved.
=> Fixes setting INSTALL command for env vars

.github/actions/setup-binary-builds/action.yml, .github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml
For all shell scripts in the Linux/Mac Wheels/Conda builds as well as the `setup-binary-builds` action, this PR adds `set -eax` for better handling in case of errors and debuggability.
=> [NovaX] set -eax in all build shell scripts for correctness/debuggability

.github/scripts/install_torch.sh, .github/workflows/lint_actions.yml, .github/workflows/linux_job.yml, .github/workflows/test-validate-domain-library.yml, .github/workflows/validate-domain-library.yml
This brings Validate Domain Library workflow to test-infra repo.
Please see wiki: https://github.com/pytorch/builder/wiki/Using-Validation-Framework
=> Migrate Validate Domain Library workflow

torchci/lib/bot/ciflowPushTrigger.ts
~~I call it `ciflow/experiment` to kind of water down its unstable nature.  Please feel free to suggest a better name if you have one in mind.~~
Also cleaning up the `ciflow/test-config-name` that I added a while back because we ends up not using `ciflow` for test config selection.
=> Add ciflow/unstable as a valid tag

torchci/lib/bot/utils.ts, torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Add retry function for retrieving the test file and add info on the issue to track better, since we've had some issues with labeling.
Reduce amount of logs b/c vercel cuts off logs that are too long https://github.com/vercel/community/discussions/1012
I spent a long time trying to figure out how to get retries using some other library but kept failing.  If someone figures out how to do it with another library, would be much appreciated.
=> [flakybot] Add retry for fetching file

torchci/rockset/commons/__sql/flaky_tests_across_jobs.sql, torchci/rockset/prodVersions.json
I noticed some tests didn't get flaky issues but the query seem to show them just fine, I forgot that that test stats don't get uploaded into rockset when the job finishes but rather when the workflow finishes, so the test for if the test was recent or not was using the wrong time
=> [flakybot] Fix for time diff between job complete and test uploading

torchci/pages/api/flaky-tests/disable.ts, torchci/pages/flakytest.tsx
I'm pretty sure no one was ever alarmed by a green CI
=> [BE] Fixing debugging messaging

torchci/lib/bot/autoLabelBot.ts, torchci/test/autoLabelBot.test.ts
torch/optim files should trigger a release notes: nn label
=> [autolabel] Add heuristic for optim to add nn

aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1
When cmake was unpinned and cmake version 3.23.0 came out, Windows and Ubuntu builds would break https://github.com/pytorch/pytorch/issues/74985. While this would eventually be fixed, it was determined that it would be safer to pin cmake to a known stable version, 3.22. Finally, it was decided that 3.22 be relaxed to 3.22.* https://github.com/pytorch/pytorch/pull/90307.
While `conda-forge` contains much more updated versions of cmake relative to conda's main channel https://github.com/pytorch/pytorch/pull/91739#discussion_r1062989028, it's been revealed that this channel isn't particularly stable https://github.com/pytorch/pytorch/issues/87208. This has lead to the decision to avoid the use of `conda-forge` unless it has been determined that this channel contains updates the main channel …
=> Consider pinning cmake and removing use of conda-forge

aws/lambda/log-classifier/ruleset.toml
For example, this build failed because it timed out while waiting for the sccache server to startup
https://github.com/pytorch/pytorch/actions/runs/3946315315/jobs/6754126326
Relevant logs:
```
sccache: Starting the server...
sccache: error: Timed out waiting for server startup
Error: Process completed with exit code 2.
```
=> Classify sccache errors

.github/scale-config.yml
* #1420
* __->__ #1419
Windows runners had a hardcoded --ephmeral flag in their setup so this
config value didn't actually mean anything
=> .github: Update scale-config to represent reality

torchci/scripts/backfillJobs.mjs
no clue why i only did master at first
```
(forpytorch) csl@csl-mbp ~/zzzzzzzz/test-infra/torchci % yarn node scripts/backfillJobs.mjs
```
=> [ez] Backfill PR logs as well

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Same as https://github.com/pytorch/test-infra/pull/1305, OSS oncall shouldn't need to get alerts from red unstable jobs, because they are unstable.
(Also run ufmt for the PyTorch script, so there are some formatting changes here and there)
=> Not sending alerts for unstable / forward-fixable jobs

torchci/components/CommitStatus.tsx, torchci/components/GroupJobConclusion.tsx, torchci/components/JobConclusion.module.css, torchci/components/JobSummary.tsx, torchci/lib/JobClassifierUtil.ts, torchci/lib/fetchHud.ts, torchci/lib/jobUtils.ts, torchci/lib/types.ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/failures/[queryParams].ts, torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Same as https://github.com/pytorch/test-infra/pull/1344 to show unstable failures as only warnings:
* Lighter red (#F8B88B)
* Group failed unstable job in a separate section from failed jobs
* Yarn format some files
* Hide unstable jobs by defaults
=> Show unstable failures as only warnings

aws/lambda/log-classifier/ruleset.toml
Given some recent issues:
* with Docker https://hud.pytorch.org/pytorch/pytorch/commit/afe6ea884fa21d424d614efff6bd3a75ec4357af (Docker daemon error)
* with ROCm https://hud.pytorch.org/pytorch/pytorch/commit/9c6433ce48c27f4b6ecf585bf6049176c217bbbe (out of space)
=> Add a log classifier rule for Docker failures

.github/workflows/check-alerts.yml, torchci/scripts/check_alerts.py
Adds the ability to check nightly for alerting as well as create separate issues for separate branches.
Also makes it so that this script isn't hardcoded to 'pytorch/pytorch' and adds a dry-run mode so that we can skip doing real work if you're just developing this script.
Base line functionality shouldn't change with this aside from the following:
* Removed code blocks when posting the update comment and instead replaced it with a link to hud (minihud) so that it's clickable
After this we'll need to create an internal butterfly rule to manage these internally.
<details>
<summary> Click me for dry run details </summary>
```
❯ python3 check_alerts.py --dry-run --repo pytorch/pytorch --branch nightly
The first green SHA was at index -1 at d80585d52dba17745a8eecb4dbdbfdcba5f254bband the …
```
=> torchci: Add ability to check nightly for alerts

torchci/lib/JobClassifierUtil.ts
Adds a periodic group so that it's easy to tell when periodic jobs are failing (otherwise it can easily be mistaken for a flaky test)
Also standardize the names for the Lint & Unstable job groups
=> [BE] Add periodic group

tools/scripts/generate_binary_build_matrix.py
The test and release channel still support python3.7 for now
=> Remove python 3.7 from nightly channel only

tools/scripts/generate_binary_build_matrix.py
This PR makes a change in `generate-binary-build-matrix.yml` so that the installation instructions generated in the build matrix JSON uses `--index-url` instead of `--extra-index-url`. 
Testing:
This PR in builder ensures all the libraries still install correctly with this change using the validation framework: https://github.com/pytorch/builder/pull/1279. All the wheels builds (which are the only ones affected by this change) are all green. Conda failures are unrelated.
Fixes: https://github.com/pytorch/pytorch/issues/92622
=> Wheel installation instructions: --extra-index-url -> --index-url

aws/ami/windows/scripts/Installers/Install-Miniconda3.ps1
We need to fix Miniconda3 to 3.9 (latest Miniconda3-py39_22.11.1-1-Windows-x86_64) instead of using Miniconda3-latest-Windows-x86_64.  The latter nows use Python3.10 which will causes conflicts when installing conda dependencies.
This also makes `python` and `python3` command available when SSM into Windows runners or when PowerShell is used in the CI.
Windows 2019 GHA CI - 20230117193537
us-east-1: ami-05762847639f4dd95
us-east-2: ami-0ed1deea6abeeed3b
https://github.com/pytorch/pytorch-canary/pull/158
=> Fix Windows Miniconda3 to Python3.9 latest Miniconda3-py39_22.11.1-1-Windows-x86_64

.github/actions/check-disk-space/action.yml, .github/actions/setup-miniconda/action.yml, .github/workflows/test-setup-miniconda.yml
This basically takes the step in `setup-miniconda` to check and clean up disk space on MacOS and puts it into a separate GitHub action so that it can be invokes in PyTorch to clean up the space AFTER the workflow finishes.
The context is that we are seeing disk space issues on MacOS M1, for example https://hud.pytorch.org/pytorch/pytorch/commit/d1807dc1f467a3abfbe866f1f0775d53a5964500.  While `setup-miniconda` checks and cleans up everything BEFORE running, the recent failures fail too early, not even being able to download the GitHub actions.  So, we would need to clean things up both BEFORE and AFTER the workflow run.
Note:  I realize that `setup-miniconda` and `check-disk-space` are better be in two separate GitHub actions because 1) GitHub doesn't know which paths to use between …
=> Create a new action to check and clean up disk space

aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
For cudnn-windows-x86_64-8.7.0.84_cuda11-archive libs are located under lib/x64
For cudnn-windows-x86_64-8.5.0.96_cuda11-archive libs are located under lib/
Failing test (without this fix):
https://github.com/pytorch/pytorch-canary/actions/runs/4027562763/jobs/6925900401
Successful test (with this fix):
https://github.com/pytorch/pytorch-canary/actions/runs/4027562763/jobs/6954158425
Test PR: 
https://github.com/pytorch/pytorch-canary/pull/161
AMI Update PR: 
https://github.com/fairinternal/pytorch-gha-infra/pull/107
=> Fix cudnn 11.8 lib path on windows AMI

tools/scripts/generate_binary_build_matrix.py
Remove cuda 11.6 
Following the Release readme here: https://github.com/pytorch/pytorch/blob/master/RELEASE.md#release-compatibility-matrix
=> Remove CUDA 11.6 from binary matrix

torchci/rockset/commons/__sql/reverted_prs_with_reason.sql, torchci/rockset/prodVersions.json
pytorch-bot makes the help and invalid command comments that get included in the revert tracker, so remove pytorch-bot comments from the sql query to make the revert tracker neater.
=> [ez] Remove pytorch-bot comments from revert generator

.github/actions/check-disk-space/action.yml
Fixes https://github.com/pytorch/pytorch/issues/84898
The test ran and failed because there was 4.1GB space left and it was just above the 4GB threshold.  Having a higher threshold here would force the runner to cleanup its space more often
I need to be more conservative in setting the threshold (**6GB** = current threshold + 2GB temp file generated by https://github.com/pytorch/pytorch/issues/84898) because MacOS M1 pet runners have tiny space, so at best there are only 10+ GB free space left.  We need a bigger disk space there eventually
Create an issue to fix this eventually https://github.com/pytorch/test-infra/issues/2101
=> Require at least 6GB on MacOS M1 runner

.github/actions/check-disk-space/action.yml
Desperate times call for desperate measures before https://github.com/pytorch/test-infra/issues/2101 is done.
=> Clear conda and pip cache when low disk space on MacOS M1 pet runners

.github/workflows/check-alerts.yml
The .env variable name should be the same as expected in https://github.com/pytorch/test-infra/blob/2c9f126bc39ba59625fb069b84b0f9d0c32cb0fd/torchci/scripts/check_alerts.py#L504
=> Fix typo in variable name WITH_FLAKY_TEST_ALERT in check-alerts.yml

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
As a prerequisite for pytorch/pytorch#93991 adding the possibility to specify a job name filter for the OSS alert generation mechanism.
The idea is to be able to specify `JOB_NAME_REGEX` in https://github.com/pytorch/test-infra/blob/e194edeb74080faf454ad302139a85ef91de2752/.github/workflows/check-alerts.yml#L28 to restrict alerting only to the desired set of jobs.
=> Support an optional job name filter (regex) in the OSS alerting

torchci/lib/rockset.ts, torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/master_commit_red_avg.sql, torchci/rockset/metrics/__sql/workflow_duration_avg.sql, torchci/rockset/metrics/__sql/workflow_duration_percentile.sql, torchci/rockset/metrics/master_commit_red_avg.lambda.json, torchci/rockset/metrics/workflow_duration_avg.lambda.json, torchci/rockset/metrics/workflow_duration_percentile.lambda.json, torchci/rockset/prodVersions.json
The new metric only counts the signal from the latest attempt (retry).  This would give us an approximated view on how much of the red signal is due to flaky and becomes greens after retrying.
I also consolidate the TTS KPI from pull and trunk into a single metric as we are only referring to that number.
Also run `yarn format` to format the file and lower the display threshold to 20% to match our current goal.
https://torchci-git-fork-huydhn-red-with-retry-fbopensource.vercel.app/metrics
=> Add a % red on trunk metric with retry

.github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/windows_job.yml
This allows `actions/checkout@v3` to have a different depth rather than the default depth of 1 as mentioned on their GitHub https://github.com/actions/checkout/tree/v3.  Specifically, this allows the depth of 0 to checkout all the history.
=> Add fetch-depth option to all jobs

.github/workflows/generate_binary_build_matrix.yml, tools/scripts/generate_binary_build_matrix.py
Restrict windows builds to one python one cuda version to save on workers
Test:
```
python generate_binary_build_matrix.py  --operating-system windows --limit-win-builds enable --channel nightly
{"include": [{"python_version": "3.8", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "wheel", "build_name": "wheel-py3_8-cpu", "validation_runner": "windows.4xlarge", "installation": "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly", "upload_to_base_bucket": "no", "stable_version": "1.13.1"}, {"python_version": "3.8", "gpu_arch_type": "cuda", "gpu_arch_version": "11.7", "desired_cuda": "cu117", "container_image": …
```
=> Restrict windows builds to one python one cuda version

.github/actions/setup-binary-builds/action.yml, tools/scripts/generate_binary_build_matrix.py
Removing 3.11 conda builds from the matrix since those are currently erroring out due to unsatisfiable deps. It may not be possible to resolve this at all for conda since some 3.11-compliant deps are not available, but will explore further using the conda-forge provided conda-build utility later.
=> Exclude Py 3.11 from Nova Conda builds for now

tools/scripts/generate_binary_build_matrix.py
This action https://github.com/pytorch/audio/actions/runs/4130125443/jobs/7136494848 shows 3.11 configs were generated twice if when with_py311 == ENABLE is used. 
We may need to deprecate this with_py311 in future but for now, change the code so that  3.11 is only applied to test channel and is no-op for nightly channel.
=> Remove duplicated 3.11 config from generated matrix

.github/workflows/generate_binary_build_matrix.yml, tools/scripts/generate_binary_build_matrix.py
Remove with py311 flag since python 3.11 was integrated
As a followup on : https://github.com/pytorch/test-infra/pull/2616
=> Remove with py311 flag since python 3.11 was integrated

tools/scripts/generate_binary_build_matrix.py
This make sure we use same logic for Python dict as CUDA dict. Also make sure when we need to provide matrix for multiple packages, we don't accidentally mutate the global dict.
Test
```
(fix_domain_library_conda_install_instructions)]$ python generate_binary_build_matrix.py --package-type conda,wheel
{"include": [{"python_version": "3.8", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/conda-builder:cpu", "package_type": "conda", "build_name": "conda-py3_8-cpu", "validation_runner": "linux.2xlarge", "channel": "nightly", "stable_version": "1.13.1", "installation": "conda install pytorch torchvision torchaudio cpuonly -c pytorch-nightly"}, {"python_version": "3.8", "gpu_arch_type": "cuda", "gpu_arch_version": "11.7", "desired_cuda": …
```
=> [generate binary matrix] Fix python logic

.github/scripts/install_torch.sh
Remove numpy from default install since not available for 3.11 python
=> Remove numpy from default install since not available for 3.11 python

.github/actions/setup-miniconda/README.md, .github/actions/setup-miniconda/action.yml, .github/workflows/test-setup-miniconda.yml
As it is only needed for binary builds, which are executed using their own `setup-binary-builds`
Updated documentation to highlight, that this is not the workflow to use for binary builds (it's almost sad that `setup-binary-builds` copy-pastes a lots of code rather than reuse it)
Bumped minimum version to 3.8 and maximum to 3.11, but added `-c pytorch-nightly` temp workaround for 3.11 installations.
Checked using https://cs.github.com/?scope=org%3Apytorch&scopeName=pytorch&q=setup-miniconda+NOT+conda-incubator that it's currently not used for binary builds
=> Remove `conda-build` from setup-miniconda action

torchci/pages/kpis.tsx
Is this possible to remove the viable/strict lag per commit chart on the KPI page?  It's not a big deal, but this chart is really hard to interpret because of its level of detail (per commit)
I couldn't think of any value keeping it there as I only look at the easier-to-understand daily viable/strict lag chart.  But I couldn't be very wrong here.
=> Remove viable/strict lag per commit chart

torchci/components/hud.module.css, torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx, torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/metrics/__sql/master_commit_red_percent_groups.sql, torchci/rockset/prodVersions.json
Several small tweaks from the team review:
* Highlight selected jobs on reliability and TTS pages
* Get rid of jobs with no failure during the selected period, i.e. 0% red
* Make the default period of 1 week, same as others
https://torchci-git-fork-huydhn-highlight-reliabili-8fe0d0-fbopensource.vercel.app/reliability/pytorch/pytorch?jobName=Lint%20%2F%20lintrunner
=> Highlight selected jobs on reliability metric page

.github/workflows/build_conda_linux.yml
Rather than guessing what is needed(and hardcoding dependencies in .yml file), make conda figure out it out from package dependencies.
Few quirks:
- A valid repository is needed to make local channel installation work, so I've created https://anaconda.org/distr and changed output folder to be distr
- Also, explicitly specify the repo we want to install from, by prefixing package name with `channel_name::`
As result, all explicit dependency installation could be removed
=> [Nova] Test conda package dependencies

.github/actions/setup-binary-builds/action.yml
To support the release, we must handle tagged pushes and RC branches. Using https://github.com/pytorch/vision/blob/09030c02ae88c87bbeafded72d27df7ea4213196/.github/workflows/build-m1-binaries.yml#L29 as a reference for how this was handled in the old M1 build job for vision.
This involves:
1. Adding the appropriate branches and tag regexes as `on:` triggers in the caller workflows (will be done in PR's in the domain repos).
3. Set `CHANNEL=test` for tagged pushes/releases using the same `if` conditions as the reference workflow, just using env vars instead of GHA-provided webhook variables (done in this PR).
4. Currently uploads occur when `github.event_name == 'push'`. Is this a sufficient condition? Looks like it should be because all the added `on:` triggers are push-based triggers.
5. …
=> Setting CHANNEL correctly for RC branches in Reusable Workflows

.github/workflows/check-alerts.yml
Quick mitigation for https://github.com/pytorch/test-infra/pull/2681#issuecomment-1428852859
Next steps: fix the check_alerts script.
=> Temporarily disable alert checking in builder/builder

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
This fixes a bug where the alert script will fetch and close all active alerts belonging to all repos and branches.  It should only need alerts from the selected repo and branch, i.e. `pytorch/pytorch` and `master`
Also `ufmt format` the script to beautify it.
* Builder (no active alert)
```
export REPO_TO_CHECK=pytorch/builder
export BRANCH_TO_CHECK=main
export WITH_FLAKY_TEST_ALERT=NO
export JOB_NAME_REGEX="nightly.pypi.binary.size.validation"
$ python3 torchci/scripts/check_alerts.py
Didn't find anything to alert on for pytorch/builder main
Clearing 0 alerts
```
* PyTorch master (1 active alert)
```
export REPO_TO_CHECK=pytorch/pytorch
export BRANCH_TO_CHECK=master
export WITH_FLAKY_TEST_ALERT=YES
export JOB_NAME_REGEX=""
$ python3 torchci/scripts/check_alerts.py
[{"id": …
```
=> Only fetch alerts belong to the target repo and branch

.github/workflows/check-alerts.yml
Reverts https://github.com/pytorch/test-infra/pull/3765, re-enabling the alerts in `pytorch/builder`, since the underlying issue is fixed in https://github.com/pytorch/test-infra/pull/3766.
=> Re-enable alert checking in pytorch/builder

.github/workflows/check-alerts.yml, torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Add alerts for cron/release validation workflows  (fixes pytorch/pytorch#84765)
Additionally, log all existing job names in the alerting script, to make writing job name filters easier.
=> Add alerts for cron/release validation workflows 

torchci/components/FilteredJobList.tsx, torchci/components/JobAnnotationToggle.tsx, torchci/components/metrics/panels/TablePanel.tsx, torchci/lib/metricUtils.ts, torchci/lib/types.ts, torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx, torchci/rockset/commons/__sql/master_commit_red_jobs.sql, torchci/rockset/commons/master_commit_red_jobs.lambda.json, torchci/rockset/prodVersions.json, torchci/test/metricUtils.test.ts
This uses simple heuristics to break down the failure % into smaller categories to provide further insight into the CI reliability:
* If the same failure occurs on N consecutive commits with `N >= 3`, the failure is consider a broken trunk
* Otherwise it's consider a flaky failure
In addition, if the commit has more than `N >= 10` failures, it's counted as an outage.  The threshold here can be tweaked.
https://torchci-git-fork-huydhn-ci-reliability-metr-519611-fbopensource.vercel.app/reliability
=> Breakdown CI reliability metric into categories

tools/pkg-helpers/pytorch_pkg_helpers/__main__.py, tools/pkg-helpers/pytorch_pkg_helpers/macos.py
Because 3.11 was release in 2022
=> [Nova] Don't constraint 3.11 builds to mkl=2021

.github/workflows/build_conda_macos.yml
Vision/Audio 3.11 Conda now working on MacOS and M1. Text failures unrelated.
=> No-test build for Mac 3.11 conda build to Enable Vision/Audio

.github/actions/setup-binary-builds/action.yml
Fix python 3.11 wheel builds.
Regression found for wheel builds:
https://github.com/pytorch/vision/actions/runs/4208207025/jobs/7303969466#step:13:116
We build with Python 3.11, but actual build name is python 3.8:
```
+ /__w/vision/vision/3/bin/conda run -p /__w/_temp/conda_environment_4208207025 aws s3 cp dist/torchvision-0.15.0+cu118-cp38-cp38-linux_x86_64.whl 
```
For python 3.11 we should build on Python 3.8 only for conda builds but not wheel.
=> Fix python 3.11 wheel builds

.github/workflows/disable-flaky-tests.yml
it's been failing as 18.04 is getting deprecated
e.g., https://github.com/pytorch/test-infra/actions/runs/4232797576
=> move disable flaky tests workflow to newer runner

torchci/lib/JobClassifierUtil.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Sorts the grouped jobs so that:
- Groups containing jobs that block viable/strict upgrades show up first
- Similar jobs and jobs that are less critical show up together
The goal is to make it easier for the DevX team to quickly glance at HUD and tell if important jobs are broken. For example, Inductor jobs (which used to be in the middle of viable/strict blocking jobs) are now moved far to the right
(Feel free to call out something that you thing should be sorted differently)
Old sorting:
New sorting:
=> [BE] Sort hud groups intelligently

torchci/components/GroupJobConclusion.tsx, torchci/lib/JobClassifierUtil.ts
Currently, you might have to look closely at jobs to tell if it's skipped or hud, since the dark green and grey can be hard to tell apart
Fix that by using a distinct symbol for skipped jobs. 
Old:
New:
=> [BE] Make skipped jobs more distinct from successful jobs

.github/scripts/test_update_disabled_issues.py, .github/scripts/update_disabled_issues.py, .github/workflows/update_disabled_tests.yml
Per yesterday discussion, I'm restricting the permission to disable jobs to only users with ~~admin~~ write permission to the repo (`pytorch/pytorch`).  ~~This is stricter than `write` permission.~~.  Check with @clee2000, switch to write permission like other bots.
This requires `GITHUB_TOKEN` secret ~~and octokit~~ to query the user permission.  Luckily, the secret is already in use in the workflow.
=> Only allow users with write permission to disable jobs

.github/actions/setup-linux/action.yml
[set-output command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). Where this is used in a workflow, you will see the following warning message.  
For example, You see this warning [here](https://github.com/pytorch/rl/actions/runs/4235232065).  
This change removes the use of `set-output` command from the [setup-linux actions](https://github.com/pytorch/test-infra/blob/main/.github/actions/setup-linux/action.yml#L66) and instead uses the `$GITHUB_OUTPUT` environment file [as recommended](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
=> set-output command is deprecated

tools/mirror-pypi/mirror_pytorch_triton_rocm.sh
Usage:
```bash
bash mirror_pytorch_triton_rocm.sh
```
Successful run:
```bash
❯ DRY_RUN=disabled bash mirror_pytorch_triton_rocm.sh
+ Downloading py37...done
+ Downloading py38...done
+ Downloading py39...done
+ Downloading py310...done
+ Downloading py311...done
+ Uploading whls to s3://pytorch/whl/test/
+ aws s3 sync --only-show-errors --acl public-read /var/folders/p5/967n9cg52c36k8cj82psn4w40000gn/T/tmp.b7o7DXaH/ s3://pytorch/whl/test/
+ Uploading whls to s3://pytorch/whl/nightly/
+ aws s3 sync --only-show-errors --acl public-read /var/folders/p5/967n9cg52c36k8cj82psn4w40000gn/T/tmp.b7o7DXaH/ s3://pytorch/whl/nightly/
```
For now this will be manual but perhaps we could automate this but this really should only be temporary
This also needs a follow up in `pytorch/builder` to allow …
=> tools: mirror pytorch-triton-rocm

.github/scripts/update_disabled_issues.py, .github/workflows/update_disabled_tests.yml
It looks like I'm using the wrong syntax here.  There are `Authorization: Bearer` and `Authorization: token`.  The latter should be used instead.  Let's try it out.
https://docs.github.com/en/rest/overview/other-authentication-methods?apiVersion=2022-11-28#authenticating-for-saml-sso
=> Use PyTorch bot token when checking for write permission

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
Fix conda and wheel upload logic for test channel.
We want to trigger uploads only when when tagging is performed in test channel.
=> Fix conda and wheel upload logic for test channel

torchci/scripts/backfillJobs.mjs
Part of the fix in https://github.com/pytorch/test-infra/pull/1332 regarding `w.repository.name = 'pytorch'` was wrong, discovered by an unusually long queue time showing up on the metrics page on hud.
Use the dynamo_key for the job in rockset as the key for putting the item back in the table
=> Fix backfill

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Address part of https://github.com/pytorch/test-infra/issues/1083.  The main change is to not count PENDING jobs as failure by replacing `if found_most_recent_failure and job["conclusion"] == "success"` with `if found_most_recent_failure and not is_job_failed(job)`
I need to confess that I have an OCD to run lintrunner on top of the Python script, thus there are some other cosmetic changes.  This only needs to be run once though.
I have another one coming up after this to not alert when job fails due to different reasons, i.e. flaky
* Unit test `test_no_alert_when_pending_job`
=> Do not send alerts when there are pending jobs in between

torchci/pages/kpis.tsx, torchci/pages/metrics.tsx, torchci/rockset/metrics/__sql/external_contribution_stats.sql, torchci/rockset/metrics/external_contribution_stats.lambda.json, torchci/rockset/prodVersions.json
* __->__ #3817
Adds dashboards to count unique external contributors and prs created by external contributors per day.
Image of dashboards (will add more data manually)
=> Add external metrics dashboard

torchci/pages/kpis.tsx, torchci/rockset/metrics/__sql/external_contribution_stats.sql, torchci/rockset/metrics/external_contribution_stats.lambda.json, torchci/rockset/prodVersions.json
* __->__ #3817
Adds dashboards to count unique external contributors and prs created by external contributors per day.
Image of dashboards (will add more data manually)
=> Add external metrics dashboard (#3817)

torchci/pages/api/drci/drci.ts
Suggest rebasing off of `viable/strict` when we see a PR is affected by a broken trunk
=> Suggest rebasing off of viable/strict

torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Address another part of https://github.com/pytorch/test-infra/issues/1083.  We don't want to send alert when job fails flakily because of different failure reasons.  It turns out that the script already has a nice function `get_unique_failures` to group failures by reason.
Also fix an issue with the `get_current_status` function. This returns the status of the latest job which could be pending.  This causes some alerts to be raise even though there is already a green signal.  The alert is clear when the pending signal turns green, i.e.
Unit testing `test_no_alert_when_different_failures`
=> Send no alert when job fails flakily because of different failure reasons

torchci/pages/kpis.tsx, torchci/rockset/metrics/__sql/external_contribution_stats.sql, torchci/rockset/prodVersions.json
Moves contributor metrics to a 7 day moving average, to make the graph a bit easier to parse + reduce noise from the weekends.
=> Move external contributor metrics to weekly moving average

aws/lambda/github-status-test/lambda_function.py, torchci/rockset/commons/__sql/hud_query.sql, torchci/rockset/prodVersions.json
Upload `pytorch/pytorch` logs to the same location, but all other logs are getting the full prefix.
Restrict log analyzer to pytorch/pytorch for the time being.
Tweak `hud_query.sql` to generate log URL accordingly (and test that it works in preview)
=> Extend log uploading to other repos

tools/scripts/generate_binary_build_matrix.py
Use larger instances for linux validation, required for torch.compile to pass
=> Use larger instances for linux validation, required for torch.compile to pass

torchci/rockset/commons/__sql/commit_jobs_query.sql, torchci/rockset/prodVersions.json
If repo is not `pytorch/pytorch`, then it's log must be prefixed with
repo full name.
Also, fix CircleCI select unions (although it looks like ingest for CircleCI jobs is currently broken)
Test plan: look at failure logs at https://torchci-git-malfet-fix-log-url-for-commit-fbopensource.vercel.app/pytorch/vision/commit/e3da44bb02cbcbb4e7269606905590b754b712e8
Followup after https://github.com/pytorch/test-infra/pull/3830
=> [HUD] Fix log URLs for commit views

torchci/components/JobLinks.tsx
Very small nit thing
When its negative, durationHuman tends to make it -1hr 59min
I assume it is fine to take max(x, 0) because that's what is done in https://github.com/pytorch/test-infra/pull/833
=> [hud][easy] Fix negative queue times in commit page

torchci/lib/correlation_matrix.json, torchci/rockset/metrics/__sql/correlation_matrix.sql, torchci/rockset/prodVersions.json, torchci/scripts/compute_correlation.py
Update the correlation script to use hamming distance to calculate the similarity between jobs instead of the default Peason correlation provided by pandas `df.corr()`.  The latter doesn't work for binary data like what we have `is_green: boolean`, so its correlation value didn't make no sense.
I also update the Rockset query to:
* Use the latest retry result to remove flakiness
* Remove untracked jobs like `rerun_disabled_tests`
* Sort by event time
Finally, I detect the GREEN RED GREEN pattern in the job results, and approximate the RED one as flaky.
The result shows a **~91%** correlation between MacOS x86-64 and arm64 `python scripts/compute_correlation.py --ignore-flaky` in the past 21 days
```
print(
correlation_matrix["macos-12-py3-x86-64 / test (default)"][
"macos-12-py3-arm64 / …
```
=> Update correlation script to use hamming distance and ignore flaky results

torchci/lib/bot/utils.ts, torchci/lib/drciUtils.ts
Enabled DR. CI for vision repo.
=> Enabled DR. CI for vision repo

.github/actions/setup-binary-builds/action.yml, .github/actions/setup-miniconda/action.yml
Otherwise, if channel-priority is set to strict, commands like `conda create -n tmp-nshulga python=3.9 pytorch=2.0 -c pytorch-test` will fail
=> Reset channel-priority before binary builds

.github/workflows/_prune-anaconda-packages.yml
Fixes the issue that pytorch-test anaconda channel prune job was doing cleanup with pytorch-nightly channel. 
See https://github.com/pytorch/test-infra/actions/runs/4382421428/jobs/7671448102#step:4:110
=> Fix anaconda-prune channel typo

.github/scripts/anaconda-prune/prune.sh, .github/workflows/anaconda-prune.yml
This link shows Anaconda server was complaining: 
https://github.com/pytorch/test-infra/actions/runs/4430341149/jobs/7771952185#step:4:108
Things seem to fail if we simultaneously delete from two different channels, e.g. things started to fail more often after this PR (https://github.com/pytorch/test-infra/pull/3861) gets merged, which actually fixes a bug that only operates on pytorch-nightly (should be pytorch-nightly and pytorch-test).
=> Update Anaconda Prune Job to Avoid Overwhelming the Server

.github/workflows/build_conda_macos.yml, tools/pkg-helpers/pytorch_pkg_helpers/macos.py
Remove mkl constraint to fix MacOS builds
This is used to fail, here is an example: https://github.com/pytorch/test-infra/actions/runs/4431671908/jobs/7774880091
=> Remove mkl in for MacOS builds

.github/scale-config.yml
During the past week, `linux.g5.4xlarge.nvidia.gpu` hit its max allowed runners, so I am increasing the number of available instances.
=> Increase max runners for linux.g5.4xlarge.nvidia.gpu to 400

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml
We are seeing smoke-test failures in Linux Wheels builds like the following: https://github.com/pytorch/vision/actions/runs/4500887549/jobs/7920603961?pr=7453.
They appear to error out at this line: https://github.com/pytorch/test-infra/blob/main/.github/workflows/build_wheels_linux.yml#L170.
This PR tries 2 things to address this:
1. Clean up the workspace prior to the build job in Linux Wheels like we do in MacOS Wheels, where we don't see any issues.
2. Use the `unzip -o` option to force unzipping to overwrite. It seems unzip requires user input to specify whether to replace or not, and since we do not provide any such input, it automatically chooses None.
=> Fix Linux Wheels Smoke Test Failures

torchci/lib/bot/retryBot.ts
Use `repository.default_branch` property of webhook instead
Also, fix small typo
=> [BE] Do not hardcode default branch in retryBot

torchci/lib/bot/cliParser.ts
I.e. `@pytorchbot --help merge` and `@pytorchbot merge --help` should
yield the same output
=> [Bot] Make `--help` position independent

aws/lambda/log-classifier/ruleset.toml
Replaces a less usefull "process exited with code" with a summary of graph-break failure or improvement.
See pytorch/benchmarks/dynamo/check_graph_breaks.py for source of these messages.
=> Parse graph-break failures in log-classifier

torchci/pages/metrics.tsx
Reduce the number of decimal places on our redness metrics. The extra precision isn't really helpful, and this lets the value appear more cleanly on half a monitor screen.
Before:
After:
=> Reduce metric width to fit on narrower window

.github/actions/setup-nvidia/action.yml
Doing it here rather than in PyTorch to make the shared runner consistent.  After https://github.com/pytorch/pytorch/pull/96904, I haven't seen the [CUDA not available](https://hud.pytorch.org/failure/RuntimeError%3A%20No%20CUDA%20GPUs%20are%20available) error again after the update which is a good sign.  On the other hand, we see a new group of issues about hanging process and Docker error today https://github.com/pytorch/pytorch/pull/97585.  So I'll try to use the latest production NVIDIA UNIX driver from https://www.nvidia.com/en-us/drivers/unix
https://hud.pytorch.org/pr/97840
=> Upgrade NVIDIA UNIX driver to latest prod 525.89.02

torchci/components/NavBar.module.css
Small, but it's really hard to click the links on the navbar in the hud main page because the job names get in the way.
Set z-index to be a very large number so that it's in front.
Set position because z-index has no effect if otherwise.
=> [hud] Set navbar links to be in front

torchci/pages/kpis.tsx
Make the kpi chart show data for just the past 6 months.
The 1 year view is helpful for seeing how far we've come, but to track how we're doing a 6 month view is better (plus it loads faster)
A toggle that lets you choose how far back the chart should go would be ideal, but that juice isn't worth the squeeze just yet.
=> Make kpi window smaller

torchci/pages/kpis.tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/num_reverts.sql, torchci/rockset/pytorch_dev_infra_kpis/num_reverts.lambda.json
Update the kpi metric to:
1. More easily show the portion of reverts relevant to the kpi: the non github first reverts
2. Change the metric to a 2 week rolling window to denoise weekly variations
**Before**:
**After**: 
lines are smoother and a new `non-ghfirst-total` entry now appears.  Not really in love with the name, but that seemed like the most descriptive option.  `kpi-total` seemed too vague, but open to suggestions here
=> Denoise revert kpi metric

.github/workflows/build_wheels_windows.yml, .github/workflows/test_build_wheels_windows_with_cuda.yml
This should enable windows vision wheels
=> [Nova] Windows vision wheels

torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/num_reverts.sql
I think this query looks wrong as it tries to compute the rolling average of 2 weeks but sums over a 3-week period (current week + the preceding 2 weeks).  As such, the number of reverts on https://hud.pytorch.org/kpis looks higher than the correct figure on https://hud.pytorch.org/metrics
=> Fix wrong rolling average for # of reverts KPI

.github/workflows/stronghold.yml, tools/stronghold/src/api/checker.py
Suppressing the linter failure via commit message may not be the most convenient option.
This change introduces a flag parameter `--suppressed` (false by default) that works exactly like the presence of the tag `#suppress-api-compatibility-check` in commit message.
Usage:
```
./check-api-compatibility --base-commit ... --head-commit ... --suppressed
```
---
Please note the seemingly unrelated docker image removal is related to the following failure:
https://github.com/pytorch/test-infra/actions/runs/4538297045/jobs/7997261316
Seems like the docker image used in that job previously is borked.
=> [Stronghold][bc-linter] add --suppressed flag as an alternative way to suppress linter

.github/actions/setup-nvidia/action.yml
As I learn today that `nvidia-smi` command returns successfully with return code 0 even in the case where the GPU has already crashed, for example https://github.com/pytorch/pytorch/actions/runs/4569152841/jobs/8065422319
```
nvidia-smi
Thu Mar 30 22:41:19 2023 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. | …
```
=> Fix setup-nvidia GPU healthcheck

torchci/lib/JobClassifierUtil.ts
This is now available on HUD after https://github.com/pytorch/pytorch/pull/98040.  It includes all slow tests that run periodically.  It can also be triggered by `ciflow/slow` on the PR.
As this is an easy fix, I also run `yarn format` on top the the file.
=> Add slow group that runs periodically

torchci/components/metrics.module.css, torchci/lib/types.ts, torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx, torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql, torchci/rockset/inductor/compilers_benchmark_performance.lambda.json, torchci/rockset/prodVersions.json
This PR includes a bunch of minor fixes based on recent feedbacks on the dashboard:
* If the accuracy remains the same, the cell won't be highlighted, i.e. `fail_to_run ← fail_to_run`
* If the speedup and memory compression ratio remains the same, the cell won't be highlighted
* Compilation latency is still highlighted if it takes longer than the fix threshold of 120 seconds
* Highlight the cell if the new speedup or memory compression ratio decrease "significantly".  Specifically, it means reducing by more than 0.95 for speedup and 0.9 for compression ratio
* Rename the dropdown commit list name to `New Commit` and `Base Commit` to tell explicitly which is newer and which is older.
* Query `job_id` so that a link to the shard log for each model can be shown.  Note that the link points to …
=> Fix TorchInductor dashboard threshold and add links to runner log for each model

.github/scale-config.yml
=> Increase the max number of runners for linux.12xlarge and windows.g5.4xlarge

torchci/lib/bot/retryBot.ts, torchci/test/retryBot.test.ts
I missed removing a check in https://github.com/pytorch/test-infra/pull/3989 to allow the bot to check the previous workflow to see if it's flaky when the current one succeeds.  At the moment, retry bot only kicks in when the current workflow fails.
=> Allow retry bot to check the previous workflow when the current one succeeds

torchci/pages/kpis.tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/ci_wait_time.sql, torchci/rockset/pytorch_dev_infra_kpis/ci_wait_time.lambda.json
Add two new charts to the KPI page:
1. Time Devs spent waiting on CI to complete per PR. This is bucketed by the when a PR's last CI job completed, which is presumably around when the PR was merged. (It only considers merged PRs)
2. Number of commits per PR, showing the number of CI iterations
This is part 2, continuing the work from https://github.com/pytorch/test-infra/pull/4009
Visual:
=> Add CI Wait Time kpi to dashboard

.github/actions/setup-linux/action.yml, .github/workflows/linux_job.yml, .github/workflows/test_linux_job.yml
Adds automatic uploading for docs previews by specifying a special directory for users to put there documentation in (RUNNER_DOCS_DIR) and then having the default linux job take those and upload them to S3.
Also adds a test to verify that we are doing the upload correctly.
Example:
```yaml
upload-docs:
uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
with:
runner: linux.2xlarge
script: |
echo "hello" > "${RUNNER_DOCS_DIR}/index.html"
```
=> ci: Add automatic uploading for docs previews

.github/scripts/compute_and_upload_ci_wait_time_metric.py, .github/scripts/test_compute_and_upload_ci_wait_time_metric.py, .github/workflows/update_ci_wait_time_metric.yml, torchci/rockset/metrics/__sql/completed_pr_jobs_aggregate.sql, torchci/rockset/metrics/completed_pr_jobs_aggregate.lambda.json, torchci/rockset/prodVersions.json
Stores the data for the CI Wait Time metric, which measures how much time a dev spent waiting on CI for every merged PR.
The flow:
1. Every day, kick off a chron job
2. The job triggers a script to download the raw data from Rockset. The Rockset query only provides a partial aggregation of the data, grouping all jobs run based on their final success status.  The logic we want to power this KPI is complicated enough that doing more than this in Rockset will result in unmaintainable and very slow SQL
3. Further processes the data locally, computing per PR stats
4. Upload the stats to dynamodb, which will in turn be ingested into a new Rockset table
5. A new chart on HUD's kpi page queries this data from the new Rockset table (implemented in https://github.com/pytorch/test-infra/pull/4011)
=> Compute and upload kpi metric

torchci/lib/jobUtils.ts, torchci/rockset/commons/__sql/flaky_workflows_jobs.sql, torchci/rockset/commons/flaky_workflows_jobs.lambda.json, torchci/rockset/prodVersions.json
As retry bot now starts to retry flaky test jobs in trunk, i.e. https://github.com/pytorch/pytorch/actions/runs/4641785459, I discover an edge in the use of workflow `workflow_run_attempt` as a condition in the query where it's set to be equal to 1.  This prevents some legit flaky test jobs from being retried.  
Here is how it happens:
1. Workflow A failed with two failed jobs in which one is a flaky test job and the other is a regular failure such as network flaky that retry bot could handle, i.e. https://github.com/pytorch/pytorch/actions/runs/4641652767/attempts/1
2. Retry bot retried only the regular failure.  The workflow run attempt was increased from 1 to 2.  The regular job run attempt was increased from 1 to 2.  The flaky test job run attempt remained the same (1), i.e. …
=> Use job run_attempt instead of workflow run_attempt in flaky_workflows_jobs

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx, torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/metrics.tsx, torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx, torchci/pages/tests.tsx, torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/inductor/__sql/compilers_benchmark_performance_branches.sql, torchci/rockset/inductor/compilers_benchmark_performance_branches.lambda.json, torchci/rockset/prodVersions.json
Based on various feedbacks on how folks use the dashboard, the list of change includes:
1. Add shareable links to snapshot the dashboard https://github.com/pytorch/pytorch/issues/96953#issuecomment-1503766492
1. Move dropdown menu to a new line so that it can be displayed better on a smaller screen https://github.com/pytorch/pytorch/issues/96953#issuecomment-1503927036
1. Swap left and right so that base commit  → new commit and base value  → new value
1. When selecting commits, the graph is zoomed in and out accordingly.  The first data point in the chart is from the selected base commit while the last data point is from the selected new commit (thank @wconstab for this suggestion)
1. Make sure that geomean calculation doesn't include zero speedup value
1. Display the data point value in …
=> Various fixes and improvements for TorchInductor performance dashboard

.github/workflows/rockset_autoscale.yml, tools/scripts/rockset_autoscale.py
Scale down rockset at 10pm PST instead of 8pm PST. Tweak made based on observing Rockset had high cpu for a bit after the scale down, likely due to jobs that were still running on CI
=> Push back rockset scale down

.github/actions/setup-miniconda/action.yml
After some debugging, I think I have found the potential root cause of the flaky missing dependencies on MacOS.  It is in the conda clone step in which only conda packages are copied over but not pip (untracked) files.
For example, in this failure example https://github.com/pytorch/pytorch/actions/runs/4692698401/jobs/8318918238 had:
```
Source:      /Users/ec2-user/runner/_work/_temp/conda-python-3.9.12
Destination: /Users/ec2-user/runner/_work/_temp/conda_environment_4692698401
Packages: 58
Files: 0 <--- Nothing here
```
And it used `/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda` as reported by `which conda`.  This conda is correct but old 4.12.0 (https://github.com/pytorch/test-infra/blob/main/.github/actions/setup-miniconda/action.yml#L15).
On the other hand, when working …
=> Upgrade MacOS conda to 23.1.0 and ensure that this version is used by the CI

.github/actions/setup-miniconda/action.yml
Annoyingly, the flaky missing `sympy` issue still pops up after https://github.com/pytorch/test-infra/pull/4028 as pip wrongly claims that all dependencies have been satisfied, for example https://github.com/pytorch/pytorch/actions/runs/4723337456/jobs/8379314646.  So I want to try again by forcing it to reinstall all the dependencies when cloning from conda fails. 
1. Running the command locally `conda run -p /Users/huydo/miniconda3/envs/py3.9 --no-capture-output python3 -mpip install --ignore-installed --no-cache-dir -r .github/requirements/pip-requirements-macOS.txt` on my laptop.
1. https://github.com/pytorch/pytorch/actions/runs/4725681892/jobs/8388919317
=> Force reinstall PIP dependencies when cloning fails

.github/workflows/check-alerts.yml, torchci/scripts/check_alerts.py, torchci/scripts/test_check_alerts.py
Due to the recent branch renaming, https://github.com/pytorch/test-infra/issues/4023 will be closed and another one reopen for `main`.   I will update the internal Butterfly rules after.
=> Switch OSS alert on pytorch/pytorch to main branch

torchci/rockset/commons/__sql/master_commit_red_jobs.sql, torchci/rockset/commons/master_commit_red_jobs.lambda.json, torchci/rockset/metrics/__sql/master_commit_red_percent_groups.sql, torchci/rockset/metrics/__sql/top_reds.sql, torchci/rockset/metrics/master_commit_red_percent_groups.lambda.json, torchci/rockset/metrics/top_reds.lambda.json, torchci/rockset/prodVersions.json
I just notice that https://hud.pytorch.org/reliability is showing some invalid job names for jobs from Lint workflow such as `Lint / lintrunner`, the correct name should be `Lint / lintrunner / linux-job` in the `% / % / %` format.  The wrong name only shows up when there is something wrong, thus it has 100% failure rate I think.  Historically, Lint job names was only `Lint / lintrunner` before I dockerized it.  It then follows Nova syntax since.
=> Remove wrong job names in HUD reliability metric page

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx
This includes several fixes:
* Fix the regex to match the new weekly benchmark with max autotune setting.  The job name has a new `_max_autotune` suffix, for example `inductor_huggingface_perf_max_autotune`.  This is the issue that broke the dashboard.
* Tweak the display of max autotune job on the dashboard when it has no previous run.
* Also increase the default view window to 7 days, as max autotune only runs weekly at the moment
* Fix https://github.com/pytorch/test-infra/issues/4054 to properly encode the view window start and stop time.
* On a run without max autotune https://torchci-git-fork-huydhn-handle-max-autotune-fbopensource.vercel.app/benchmark/compilers?startTime=Mon%2C%2017%20Apr%202023%2002%3A50%3A37%20GMT&stopTime=Mon%2C%2024%20Apr%202023%2002%3A50%3A37%20GMT&suite=torchb …
=> Handle the weekly max autotune run on TorchInductor dashboard

torchci/lib/bot/utils.ts
Adds pytorch-canary to dr. ci, so we can use it to debug dr. ci
=> Add pytorch canary to dr ci

torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql, torchci/rockset/prodVersions.json
The `speedup` value, which is expected to be a float or NULL, is set to the string `infra_error` introduced recently because of the burst of error on inductor workflow.  This makes https://hud.pytorch.org/benchmark/compilers fail to load at the moment because string couldn't be converted to float.
https://torchci-git-fork-huydhn-handle-infra-error-fbopensource.vercel.app/benchmark/compilers now loads successfully
=> Handle the recent burst of error on TorchInductor dashboard

.github/scale-config.yml
Evidence suggest that in the last month the following runners labels were not used:
* linux.2xlarge.amd
* linux.c5.4xlarge.ephemeral
* linux.large.ephemeral
* linux.p3.8xlarge.nvidia.gpu
* linux.p324xlarge.nvidia.gpu
* linux.p4d24xlarge.nvidia.gpu
so I am removing them from the configuration
=> remmove unused runners from scale-config.yml

.github/actions/set-channel/action.yml
`-l` probably makes sense for command that wants to run conda, but is a distraction for ones that just need to execute a few commands based purely based on the environment provided by the action.
Fixes https://github.com/pytorch/test-infra/issues/4105
=> Tweak set-channel not to read `.bashrc`

tools/stronghold/src/api/checker.py
Now either `#suppress-api-compatibility-check` or `#suppress-bc-linter` in the commit message will suppress BC-linter.
=> [stronghold][bc-linter] add #suppress-bc-linter as an alternative suppression tag

.github/workflows/build_conda_macos.yml
Temp Use conda-forge for release build
Already tested here: https://github.com/pytorch/test-infra/actions/runs/4887292374/jobs/8723703363
We are doing it to fix this issue: https://github.com/pytorch/audio/actions/runs/4887939314/jobs/8725107510
To be able to produce build for python 3.10 and maybe 3.11
=> Temp Use conda-forge for release build

torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql, torchci/rockset/prodVersions.json
By using `TRY_CAST` instead of `CAST()` to ignore string values not castable to float
=> Fix `compilers_benchmark_performance` query

.github/actions/bc-lint/action.yml
This PR extracts the BC-linter workflow from the PyTorch repository into a reusable GitHub Action in the `test-infra` repository. The rationale for this change is to simplify the management of the BC-linter workflow, promote code reusability, and make it easier to apply updates or improvements to the linter across multiple projects.
The new action can be found at `.github/actions/bc-lint/action.yml` in the `test-infra` repository.
To use the BC-linter action in your workflow, add the following step to your GitHub Actions workflow file:
```yaml
- name: Run BC Lint Action
uses: pytorch/test-infra/.github/actions/bc-lint@main
with:
repo: ${{ github.event.pull_request.head.repo.full_name }}
base_sha: ${{ github.event.pull_request.base.sha }}
head_sha: ${{ github.event.pull_request.head.sha }} …
```
=> [stronghold][bc-linter] Extract BC-linter workflow into a reusable action

torchci/lib/bot/verifyDisableTestIssueBot.ts, torchci/test/verifyDisableTestIssue.test.ts
Per title, this fixes https://github.com/pytorch/pytorch/issues/100327 by rejecting both unauthorized DISABLED test and job issues (previously done only in the latter).  The bot will then close the issue immediately if it's created by unauthorized user.
DISABLED test issues could be created automatically by `pytorch-bot`, AFAIK, the bot has full write permission to the repo.  Note that it's not a GitHub user, but an app.
=> Comment and close unauthorized DISABLED test and job issues

.github/workflows/build_conda_macos.yml
Reverts pytorch/test-infra#4112
Original issue, required conda-forge to resolve mkl dependency on macos x86 builds
Not required anymore, resolved by https://github.com/pytorch/audio/pull/3307
=> Revert "Temp Use conda-forge for release build"

.github/workflows/test_windows_job.yml, .github/workflows/windows_job.yml
The Linux job has these inputs to control the GPU support:
https://github.com/pytorch/test-infra/blob/92814dfe9af9ea152bf35df359934742387abb10/.github/workflows/linux_job.yml#L50-L57
They were missing before from the Windows job. Without them, users are forced to use [workarounds](https://github.com/pytorch/vision/blob/14553fb9eb78e053100e966feee6149905f9922c/.github/workflows/test-windows.yml#L44-L49).
This PR adds them to the Windows job as well. Since we have multiple versions of CUDA already present on the AMI, we only need to set some paths.
=> Enable GPU support for generic Windows job

.github/actions/setup-nvidia/action.yml
Currently, GPU_FLAGS is set to `--gpus all`.
This exposes all the runner GPUs to container with default capabilities which is `utility` and `compute`.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html
This does not expose GPU video encoder/decoder libraries, and attempting to use it will cause the error where the corresponding libraries are not found.
https://github.com/pytorch/audio/actions/runs/4899270270/jobs/8749113374#step:10:2022
This commit specified `capabilities=all`, so that non-default capability, including video become available.
=> Set GPU `capabilities=all` for Docker

aws/lambda/log-classifier/ruleset.toml
Much like the unittest flaky rule, this isn't a rule that points to a line that explains why the job failed, but makes it easier to find jobs that needed to do retries.  It's relatively near the bottom of the rules to make sure it doesn't interfere with the rules that do point to failing lines.
=> New rule for file level retries

.github/workflows/linux_job.yml, .github/workflows/test_linux_job.yml
#3917 was merged so we no longer need to upload to two paths. Note that the new scheme is `{OWNER}/{REPO}/{PR}` and this was dubbed "legacy". Thus, we are actually removing the other one and dropping the legacy label.
=> remove double doc upload after path unification

.github/actions/setup-nvidia/action.yml
This commit set Nvidia GPU driver capabilities to `all`.
Currently, attempting to use GPU video decoder/encoder with `linux_job` fails 
due to the corresponding driver libraries not exposed to Docker container (though they exist in host)
Example failure: https://github.com/pytorch/audio/actions/runs/4899270270/jobs/8749113374#step:10:2022
This is because, GPU is enabled with `--gpus all` flag, which set default drive capability to `utility` and `compute`.
To run GPU video decoder/encoder, `video` needs to be added or we can specify `all`.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities
According to https://github.com/NVIDIA/nvidia-container-runtime/issues/112#issuecomment-712312284, nowadays it should be fine to set `all`.
This change …
=> Set CUDA capabilities for

.github/workflows/build_conda_windows.yml
1. Use same procedure as Linux and MacOS upload
2. Upload only package, not intermediate vs2019_win-64-** files
=> Fix anaconda windows upload, upload only required package, use standard conda path

.github/actions/cleanup-runner/action.yml
The first use case is for Windows non-ephemeral runners.  This logic is copied from `_win_test.yml`
=> Add a new shareable GH action to clean up non-ephemeral runners

tools/flake8-torch/.flake8, tools/flake8-torch/.gitignore, tools/flake8-torch/flake8_torch/checker.py, tools/flake8-torch/flake8_torch/deprecated_symbols.yaml, tools/flake8-torch/pyproject.toml, tools/flake8-torch/tests/fixtures/deprecated_from_nn.py, tools/flake8-torch/tests/fixtures/deprecated_from_nn.txt, tools/flake8-torch/tests/fixtures/deprecated_qr.py, tools/flake8-torch/tests/fixtures/deprecated_qr.txt, tools/flake8-torch/tests/fixtures/removed_symeig.py, tools/flake8-torch/tests/fixtures/removed_symeig.txt, tools/flake8-torch/tests/test_flake8_torch.py
The big vision for the plugin is to flag (and for some auto fix) all kinds of problematic usages of PyTorch.
What it is doing so far is printing error messages for the functions from the deprecated_symbols.yaml.
Eventually this list will be in the pytorch/pytorch and also will be used for generating documentation about deprecated and removed functions.
The plugin is in a working state, there is an output from checking torchaudio:
```
flake8 --isolated --select=TOR
./examples/libtorchaudio/augmentation/create_jittable_pipeline.py:38:22: TOR101 Use of deprecated function torch.norm
./examples/tutorials/audio_data_augmentation_tutorial.py:193:14: TOR101 Use of deprecated function torch.norm
./test/torchaudio_unittest/transforms/transforms_test_impl.py:475:16: TOR101 Use of deprecated …
```
=> Prototype for PyTorch-specific flake8 plugin

torchci/lib/useTableFilter.ts
By moving logic from `handleSubmit` to `handleInput` callback and leaving `handleSubmit` a dummy no-op
Fixes https://github.com/pytorch/test-infra/issues/4151
=> [HUD] Apply job filter right away

torchci/lib/bot/verifyDisableTestIssueBot.ts, torchci/test/verifyDisableTestIssue.test.ts
Querying for permissions of pytorch-bot[bot] gives none but it should be allowed to disable tests and added corresponding test cases for this.
There were ~70 issues opened and and immediately closed yesterday due to this, noticed on the hud metrics page chart for number of opened disable tests
=> Fix disable bot authorization

torchci/components/hud.module.css, torchci/lib/fetchHud.ts, torchci/lib/types.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/rockset/commons/__sql/filter_forced_merge_pr.sql, torchci/rockset/commons/filter_forced_merge_pr.lambda.json, torchci/rockset/prodVersions.json
Now that we have the merges information on Rockset `merges` collection, we can correctly highlight force merges with failures on HUD.  This PR covers several things:
* It fixes the known issue in which a PR will always be highlight as a force merges once it was forced merges in the past.  For example, force merge -> revert -> merge again normally, the second merge would be highlighted wrongly as a force merge
* HUD shows all force merges ~~with failures~~ (`-f`, `--ignore-current`) ~~to stay consistent with our KPI metric~~
* Forcer merges with failures are highlight differently
https://torchci-git-fork-huydhn-fix-force-merge-highlight-fbopensource.vercel.app/ correctly highlight force merges for each commits.  Other cases on https://hud.pytorch.org/ are ok and won't be hightlighted
=> Correctly highlight force merges with failures on HUD

.github/actions/check-disk-space/action.yml
I notice one instance of MacOS ran out space in https://github.com/pytorch/pytorch/actions/runs/5017945771/jobs/8996845812 on `i-082dc48967fe3ba38`.  Logging into the runner reveals that the crash report directory was hooking up all the space.
```
(base) ec2-user@ip-10-0-3-73 WiFi % pwd
/System/Volumes/Data/Library/Logs/CrashReporter/CoreCapture/WiFi
(base) ec2-user@ip-10-0-3-73 CoreCapture % sudo du -sh .
31G	.
(base) ec2-user@ip-10-0-3-73 WiFi % ls -la | wc -l
51071
```
The error is `BCMWLAN Firmware Boot Failed~instance 1` and it comes from `com.apple.driver.AppleBCMWLANCoreV3.0` and `com.apple.iokit.IO80211Family`.  They are still happening on the runner, so I'll see if I can find any useful information from the crash report there.
In the meantime, adding a step to cleanup this folder …
=> [MacOS] Attempt to clean up crash reports when running out of space

torchci/lib/bot/autoLabelBot.ts, torchci/lib/useTableFilter.ts, torchci/pages/api/flaky-tests/disable.ts, torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[annotation].ts
Per title, the hardcode list doesn't make sense anymore, so I replace it with an API call to check the team membership (worth the price of an API call IMO and this API endpoint is only infrequently used)
=> Replace the hardcode list of DevX members with GitHub team

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
Looks like this:
Fixes https://github.com/pytorch/test-infra/issues/4190
=> Mark if a benchmark was newly added

aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1
Use single conda install statement for all conda dependencies 
Should fix issue of numpy being updated to  numpy>=1.23
=> Use single conda install statement for all conda dependencies

.github/actions/cleanup-runner/action.yml
I have been able to root cause this `rm: cannot remove 'C:\actions-runner\_work\pytorch\pytorch/build/win_tmp/bin': Device or resource busy` issue happening on Windows from time to time, for example https://github.com/pytorch/pytorch/actions/runs/5053644794/jobs/9067740477.  It turns out that the process hooking up that directory is `sccache`.  Here is how it happened:
1. A Windows build job was running, for example https://github.com/pytorch/pytorch/actions/runs/5053412501/jobs/9067234773
2. A new version of the PR was pushed, thus the job on step 1 was cancelled 
3. The process `sccache` wasn't terminated properly as `sccache --stop-server` wasn't run, so I saw ` "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe" ` in the list of processes
4. The next job would fail …
=> Cleanup sccache process on Windows runner

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx
Fixes https://github.com/pytorch/test-infra/issues/4196
* Update the geomean calculation to set the lower bound value to be `1.0` same as https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/runner.py#L760-L764.  The logic behind is that if the speed up is less than 1.0, one can use eager mode instead
* Use a higher scale when displaying speed up and memory compression ratio values on the model detail pages (4 digits after decimal)
* Run `yarn format` to reformat the files
* https://torchci-git-fork-huydhn-fix-geomean-calculation-fbopensource.vercel.app/benchmark/compilers?startTime=Mon%2C%2015%20May%202023%2017%3A09%3A51%20GMT&stopTime=Mon%2C%2022%20May%202023%2017%3A09%3A51%20GMT&suite=torchbench&mode=inference&dtype=amp&lBranch=main&lCommit=351c2ea2fbb09add93980e2942435f31b114 …
=> Fix geomean calculation by using the lower bound of 1.0

.github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/test_linux_job.yml
TorchRL requires some scripts to be run outside of the docker container. Previously, the generic linux_job requires all jobs to be run inside a conda-builder container. This PR introduces the option for scripts to be run on bare metal, but still fetches the docker container in case other scripts need to be run on the container.
=> Adding option to run without docker to linux generic job

torchci/lib/bot/drciBot.ts, torchci/rockset/commons/__sql/issue_query.sql, torchci/rockset/commons/issue_query.lambda.json, torchci/rockset/prodVersions.json
I originally considered adding pytorchbot as a special exception, but I think this is fine because issues are almost immediately closed if they don't have authorization.  
Also I'm a little worried that reopening an old issue that was created by someone without write permissions would not disable the test.  While this is acceptable since a new issue could also be created, I think it creates some confusion between which issues work and which don't.  Also not sure what happens to the author association in rockset when people leave/join pytorch.
=> Don't check for authorization in issue_query

.github/workflows/check-alerts.yml, torchci/scripts/queue_alert.py, torchci/scripts/test_queue_alert.py
Create an alert for long queues
The limit is 4 hours or 75 machines for most machines and a separate category for the gcp a100 runners since they generally have longer queue times but fewer machines.  The avg non zero queue seems to be about 2.5 hours and 40 machines for most machine types.
It uses a new label queue-alerts and attempts to re open issues when there is an issue with the queue-alert label if it is closed.
=> Alert for long machine queues

torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Dedup issues for disable bot to prevent bot from reopening a bunch of issues that have the same title, also auto close dup issues.
=> Dedup issues for disable bot

.github/workflows/check-alerts.yml, torchci/scripts/check_alerts.py, torchci/scripts/queue_alert.py, torchci/scripts/test_check_alerts.py, torchci/scripts/test_queue_alert.py
Prevent spam by opening most recently updated issue that matches.  If it can't find a issue, it will create a new one (hopefully this doesn't happen that often)
tested via running locally with dryrun, also not dry run for queue alert
=> Prevent alert issue spam

torchci/pages/benchmark/compilers.tsx
Fixes https://github.com/pytorch/test-infra/issues/4239.  Per the discussion with @ezyang, skipping failed models would invalidate the basis of aggregated speedup comparison because the lists aren't the same.  For the context, this logic came from https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/runner.py#L755-L756 where failed models with 0 speedup value was incorrectly removed.
https://torchci-git-fork-huydhn-fix-skipping-zero-s-064698-fbopensource.vercel.app/benchmark/compilers
=> Assign the speedup of 1.0 to failing models instead of skipping them

.github/scripts/test_update_disabled_issues.py, .github/scripts/update_disabled_issues.py, .github/workflows/update_disabled_tests.yml
This is the first step to be able to mark CI jobs as unstable automatically.  This is done in the same way as disabling CI jobs by creating issues in the following format `UNSTABLE [WORKFLOW_NAME] / [PLATFORM_NAME] / [JOB_NAME]`
Some issues for testing:
* https://github.com/pytorch/pytorch/issues/102299
* https://github.com/pytorch/pytorch/issues/102298
* https://github.com/pytorch/pytorch/issues/102297
* https://github.com/pytorch/pytorch/issues/102433
Export `GH_PYTORCHBOT_TOKEN` using my own token, run `python update_disabled_issues.py`, then verify that the list of unstable jobs is correct:
```
cat unstable-jobs.json
{
"linux-binary-manywheel / manywheel-py3_8-cuda11_8": [
"huydhn",
"102433",
"https://github.com/pytorch/pytorch/issues/102433",
"linux-binary-manywheel", …
```
=> Collect and publish the list of unstable jobs

aws/lambda/log-classifier/ruleset.toml
The PR updates `ruleset.toml` to locate the `KeyboardInterrupt` signal in jobs' logs on the HUD in case a test is timed out and gets keyboard interrupted.
Here is an [example](https://hud.pytorch.org/pytorch/pytorch/pull/100153?sha=684615d5376d7b23d4e14760daf6fbfd53de9895), the jobs that ran out of time are showing `RuntimeError: test_ops x/x failed!`, which can be improved to be more specific.
=> Update ruleset.toml to capture KeyboardInterrupt signal in case a test is timed out.

.github/scale-config.yml
as the limit is currently being exceeded by regular usage:
=> Increase max_available for linux.g5.4xlarge.nvidia.gpu runners to 550

tools/pkg-helpers/pytorch_pkg_helpers/macos.py
We're currently targeting MacOS 10.9, which is very old OS. Updating this to target 10.13
=> MACOSX_DEPLOYMENT_TARGET 10.9 -> 10.13

.github/workflows/linux_job.yml
small fix for running `linux_job` with the no-docker option
=> Nit fix for Generic Linux Job's no-docker option

tools/torchfix/tests/fixtures/checker/removed_symeig.txt, tools/torchfix/torchfix/torchfix.py
So it's like priority 0.
Deprecated but not removed functions have TOR101, priority 1.
=> [TorchFix] Use TOR001 for removed functions

.github/workflows/linux_job.yml
default the linux_job workflow to pull submodules recursively
Summary:
When trying to use this for the "codegen diff" job in PyTorch, I
noticed it was failing because we did not have submodules
available. After discussing with @seemethere, he suggested to just
make this the default.
Test Plan:
Verifying in local CI.
This can't be tested in the pytorch/pytorch repo because I this is
pushed to the dagitses/test-infra fork, which fails with the error:
> Called workflows cannot be queued onto self-hosted runners across
> organisations/enterprises. Failed to queue this job.
> Labels: 'linux.large'.
See https://github.com/pytorch/pytorch/actions/runs/5169464586/attempts/2
=> default the linux_job workflow to pull submodules recursively

.github/actions/cleanup-runner/action.yml
I think this is the root cause of this flaky issue on Windows https://github.com/pytorch/pytorch/actions/runs/5201383887/jobs/9381449915 in which the runner couldn't checkout the actions it needs, for example `The process cannot access the file 'C:\actions-runner\_work\_actions\pytorch\pytorch\main\caffe2\operators\quantized' because it is being used by another process.`
Looking at the previous job on the same runner https://github.com/pytorch/pytorch/actions/runs/5201112432/jobs/9380804301, the process that locks the file was `git`:
```
git.exe                            git.exe -c protocol.version=2 submodule update --init --force --recursive …
```
=> Clean up leftover git processes when tearing down Windows

torchci/components/metrics/panels/TablePanel.tsx, torchci/package.json, torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx, torchci/yarn.lock
Fixes https://github.com/pytorch/test-infra/issues/4270
* Skip all failing models with 0 speedup. This reverts https://github.com/pytorch/test-infra/pull/4240
* Calculate geomean using the actual speedup values instead of clipping them to `>= 1.0`
* Add a clickable help icon pointing to https://pytorch.org/docs/main/compile/performance-dashboard.html to explain metrics in the dashboard
https://torchci-git-fork-huydhn-unclip-geomean-fbopensource.vercel.app/benchmark/compilers
=> Skip failing models from geomean computation and don't clip passing ones to 1.0

tools/torchfix/tests/fixtures/codemod/range-arange.py, tools/torchfix/tests/fixtures/codemod/range-arange.py.out, tools/torchfix/torchfix/torchfix.py
The `torch.range` is deprecated, and in the replacement `torch.arange` the `end` parameter is not inclusive.
=> [TorchFix] Add range-arange codemod

aws/ami/windows/scripts/Installers/Install-VS.ps1, aws/ami/windows/windows.pkr.hcl
This adds VS 2022 to Windows AMI. The line with [https://aka.ms/](https://aka.ms/) link might be reverted once `vs16.11.21_BuildTools.exe` and `vs17.4.1_BuildTools.exe` files will be uploaded to [https://s3.amazonaws.com/ossci-windows/](https://s3.amazonaws.com/ossci-windows/.).
Note that there is a fix of [thread\_local causing fatal error LNK1161: invalid export specification on VS 2022 - Visual Studio Feedback](https://developercommunity.visualstudio.com/t/thread_local-causing-fatal-error-LNK1161/10199441) pending, required e.g. for pytorch/pytorch#89511, which will require another VS 2022 version update. Alternatively, the VS 2022 version installed by this change can be downgraded to 16.3.6 which does not suffer this issue.
This is needed to finish pytorch/pytorch#86591
=> Update VS 2019 and add VS 2022 to Windows AMI

torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Accidentally broke hud view for other repos + branches after https://github.com/pytorch/test-infra/pull/4269 due to unstable being included in the job names
=> Fix after #4269

torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts
Add oncall pt2 label for issues that have dynamo and inductor as groups.  Change rule for dynamo and inductor platforms so that they only get added if linux is not present since they are subsets of linux.
=> Add oncall pt2 label for dynamo and inductor disabled issues

torchci/lib/bot/cliParser.ts, torchci/lib/bot/pytorchBotHandler.ts, torchci/lib/useGroupingPreference.tsx, torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Fixes https://github.com/pytorch/test-infra/issues/4257
The high-lighting rules are now as follows:
1. Green (OK) if the new value improves more than 5% over the old value
1. Red (Not OK) if the new value regresses more than 5% when comparing with the old value
1. Yellow (warning) if both 1 and 2 don't hold and:
1. The new speedup value is still less than 0.95
2. ~~Or the new compilation time is till more than 120s~~ 
3. Or the new compression ratio is still less than 0.9
https://torchci-git-fork-huydhn-inductor-dashboard-82c51d-fbopensource.vercel.app/benchmark/torchbench/inductor_with_cudagraphs?startTime=Sat,%2003%20Jun%202023%2001:18:34%20GMT&stopTime=Sat,%2010%20Jun%202023%2001:18:34%20GMT&granularity=hour&mode=training&dtype=amp&lBranch=main&lCommit=2961ea80f5d5fbcb9ef86d95ce08f1fa60 …
=> Update PT2 dashboard high-lighting rules

aws/ami/windows/scripts/Installers/Install-VS.ps1, aws/ami/windows/windows.pkr.hcl
Fixes issue that the VS2022 Build Tools installation is removing VS2019 Build Tools installation. This is a follow up fix of already merged #1175.
=> Fix VS2022 Build Tools installation removing VS2019, fixes #1175

tools/torchfix/tests/fixtures/codemod/functorch.py, tools/torchfix/tests/fixtures/codemod/functorch.py.out, tools/torchfix/torchfix/deprecated_symbols.yaml, tools/torchfix/torchfix/torchfix.py
According to the https://pytorch.org/docs/main/func.migrating.html
The codemod doesn't try to remove `import functorch` because if it's not used, it can be removed by existing tolls like Ruff.
=> [TorchFix] Add functorch deprecation linter/codemod

aws/ami/windows/scripts/Helpers/Uninstall-WinDefend.ps1, aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1, aws/ami/windows/windows.pkr.hcl
Per title, this PR uninstalls Windows Defender.  I couldn't find any other ways to disable this service on CI.  Also piggy back this change with some new dependencies for Windows that are added recently.
* Build the new AMI
```
packer build -var 'skip_create_ami=false' .
us-east-1: ami-0e1d863a1d020eac3
us-east-2: ami-074ac5fc91f640663
```
* Update the AMI on canary https://github.com/fairinternal/pytorch-gha-infra/pull/192
* [TODO] Testing on canary
* [TODO] Update the AMI on PyTorch
=> Uninstall Windows Defender

torchci/pages/benchmark/compilers.tsx
It turns out that this calls updates the data structure and causes the page to refresh back to the base and new commits.  There is no need to augment the data here as it only contains branch and commits info for the dropdown list, not the actual benchmark data.
https://torchci-git-fork-huydhn-fix-pt2-dashboard-d-428da8-fbopensource.vercel.app/benchmark/compilers
=> Remove redundant AugmentData call that causes page to refresh

tools/scripts/rockset_autoscale.py
Fist of all, fix embarrassing `AttributeError: type object 'datetime.time' has no attribute 'sleep'`. (Hattip to @kit1980 for reporting)
Also, `def main()`  is declared as returning `None` so not point returning zeroes there
Fix all flake8 reported issues except E501
=> [BE] Fix autoscale

torchci/components/JobLinks.tsx, torchci/lib/bot/autoLabelBot.ts
The new button "Unstable job" is right next to the familiar "Disable test" button.  Here are how it works:
* The button only shows up when user login to HUD.  As this is mainly used by Dev Infra.
* The button only shows up for failed jobs
* Click the "Unstable job" will open a new issue with title `UNSTABLE JOB_NAME`
* The new UNSTABLE issue will be tagged with `module: ci` label to CC us and `unstable` label so that they can be searched quickly
* If a job has already been marked as unstable, a link to the existing unstable issue is provided instead with the text `Job is unstable`
* If a job was marked as unstable in the past, a link to the closed unstable issue is provided with the text `Previously unstable job`.  Reopening the issue will mark the job as unstable again
This process …
=> Add HUD button to mark a job as unstable

tools/torchfix/tests/fixtures/checker/functorch.py, tools/torchfix/tests/fixtures/checker/functorch.txt, tools/torchfix/torchfix/torchfix.py
Previously the same lint issue was being reported twice for things like `vmap(a)(b)` (but there was a guard already in the code changing path - just moved the guarding code to apply to linting also).
This may be an issue with LibCST https://github.com/Instagram/LibCST/issues/960, but it's easy to check in our code.
=> [TorchFix] Report the same issue once for higher order func calls

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx, torchci/pages/benchmark/compilers.tsx
Fixes https://github.com/pytorch/test-infra/issues/4304.  After https://github.com/pytorch/test-infra/pull/4292, the graph data for Torchbench is wrong while the summary table remain correct.
This PR also fixes:
* Some React warnings when running `yarn dev` locally about missing and duplicated `key` property
* Make `bfloat16` the default dtype in inference mode
https://torchci-git-fork-huydhn-inductor-dashboard-8fc60c-fbopensource.vercel.app/benchmark/compilers
=> Fix wrong TorchBench graph data on PT2 dashboard

torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This fixes some annoying warnings on HUD browser console log when running `yarn dev`:
* `Each child in a list should have a unique "key" prop` and
* `You provided a checked prop to a form field without an onChange handler. This will render a read-only field. If the field should be mutable use defaultChecked. Otherwise, set either onChange or readOnly`
=> Fix React warnings on HUD when running yarn dev

torchci/lib/fetchFlakyTests.ts, torchci/pages/api/flaky-tests/disable.ts
Auto disable flaky tests that were rerun on file level reruns.
Query for all failing test in last 3 hours, for each failing test, get one representative instance per job of where it got a file level rerun, query for workflow job info in a separate query so we don't have to join with test_run_s3 multiple times, put all this information together.
I don't know if the smaller queries are preferred or the one larger one, but its much faster (<100ms per test) to query separately than to a join on test_run_s3 (10s+ for 7 failing tests).
=> Disable flaky tests from file level reruns

.github/workflows/stronghold.yml, tools/stronghold/src/api/__init__.py, tools/stronghold/src/api/ast.py, tools/stronghold/src/api/compatibility.py, tools/stronghold/src/api/types.py, tools/stronghold/src/api/violations.py, tools/stronghold/tests/api/test_ast.py, tools/stronghold/tests/api/test_ast_param_compatibility.py, tools/stronghold/tests/api/test_ast_param_types.py, tools/stronghold/tests/api/test_compatibility.py
Adds basic extracting and checking for the change of types in function parameters.
The BC-linter failures are unrelated (the GH action test-infra is using is outdated and picking up base branch changes, to be fix in a separate PR).
Retroactive tested on 1000 recent PT, here are the NEW type-related failures:
| Commit Message |PR | Note |
| :--- |:--- |:--- |
| \[FSDP\]\[ez\] Type optimizer correctly \(#102637\)\\... | pytorch/pytorch#102637 | Legit type change |
| Make DataParallel generic \(#102455\)\\n\\nFixes #... | pytorch/pytorch#102455 | False-positive (linter doesn't understand that type was expanded in this case) |
=> [stronghold][bc-linter] Add basic typing support

tools/stronghold/src/api/compatibility.py
Because they are not packages as part of `PyTorch`
Also, make `tests` folder check more precise, as right now it matches `torch.testing.` package that is part of public API and should be BC-linted.
=> Exclude `benchmarks` from BC linter

tools/torchfix/torchfix/common.py, tools/torchfix/torchfix/torchfix.py, tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py, tools/torchfix/torchfix/visitors/deprecated_symbols/range.py
- Refactor `TorchDeprecatedSymbolsVisitor` into a separate class and dir
- Use `BatchableCSTVisitor` instead of `CSTVisitor` so several different visitors can run in parallel (but currently it's only one, `TorchDeprecatedSymbolsVisitor` )
=> [TorchFix] Refactor TorchDeprecatedSymbolsVisitor

tools/torchfix/tests/fixtures/misc/checker/require_grad.py, tools/torchfix/tests/fixtures/misc/checker/require_grad.txt, tools/torchfix/tests/fixtures/misc/codemod/require_grad.py, tools/torchfix/tests/fixtures/misc/codemod/require_grad.py.out, tools/torchfix/torchfix/torchfix.py, tools/torchfix/torchfix/visitors/misc/__init__.py
Find and fix common misspelling `require_grad` (instead of `requires_grad`).
This was reported as a common issue on PyTorch Slack by Stas Bekman from Huggingface.
=> [TorchFix] Add TorchRequireGradVisitor

tools/torchfix/tests/fixtures/deprecated_symbols/codemod/functorch.py, tools/torchfix/tests/fixtures/deprecated_symbols/codemod/functorch.py.out, tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
Before things like `from . import residue_constants as rc` crash.
=> [TorchFix] Fix crash with from . import

stats/test-times.json
@clee2000 We would like to skip ROCm5.5 upgrade and go straight to ROCm5.6 in CI. This changes helps enable sharding and prevent timeouts in the CI testing for the upgrade PR.
cc @huydhn
=> Add ROCm5.6 entry to test-times.json

torchci/components/WorkflowDispatcher.tsx
Per title, this is to cover the case when inductor workflow breaks on ghstack commits like trunk
Local `yarn dev` and inductor option shows up the bottom of the page for http://localhost:3000/pytorch/pytorch/commit/ffb526a2e42fcd63ff8a9111979efd25d966a76b
=> Add inductor into the list of workflows triggerable from HUD

.github/actions/setup-binary-builds/action.yml
Trying to fix conda related errors: https://github.com/pytorch/test-infra/issues/4155
Error happens during at the beginning of workflow
```
Prepare all required actions
Getting action download info
Download action repository 'conda-incubator/setup-miniconda@v[2](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:2).1.1' (SHA:[3](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:3)5d1[4](https://github.com/pytorch/test-infra/actions/runs/5448274683/jobs/9911282747?pr=4337#step:7:4)05e78aa3f784fe3ce9a2eb378d5eeb62169)
Run ./test-infra/.github/actions/setup-binary-builds
Run set -euxo pipefail
/github/home/.profile: line 22: conda: command not found
Error: Process completed with exit code 127.
```
And like …
=> Add retry mechanism before using conda for the first time

.github/actions/setup-binary-builds/action.yml
Follow up after: https://github.com/pytorch/test-infra/pull/4337
Still observed a failure with retry mechanism:
https://github.com/pytorch/vision/actions/runs/5443957557/jobs/9911563555
Please refer to this comment: https://github.com/pytorch/test-infra/pull/640#discussion_r961191667
We want to use ``bash -l {0}`` only after the step of conda-incubator/setup-miniconda
=> Don't use ``bash -l {0}`` for setup-binary-builds initial steps

.github/workflows/build_conda_linux.yml
For wheel builds we setup miniconda: https://github.com/pytorch/test-infra/blob/main/.github/workflows/build_wheels_linux.yml#L108
We want to do it for conda builds as well, so we can avoid use cases where conda is not found.
This should address issue: https://github.com/pytorch/test-infra/issues/4155
=> Setup miniconda for linux conda builds

torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
If a model used to run fine but now shows up as "0" because it started failing/we don't get results, we should highlight it as red.
=> PT2 dashboard: Highlight speedup as red if a model started failing to run

.github/workflows/linux_job.yml
Add no-sudo option to linux_job. Required for aarch64 builds.
See similar workflow: https://github.com/pytorch/pytorch/blob/main/.github/actions/checkout-pytorch/action.yml
=> Add no-sudo option to linux_job. Required for aarch64 builds

.github/workflows/build_wheels_linux.yml
Passing `--gpus all` as a docker runtime option ti ensure that, when gpus are available on the runner, the container has pass-through access to them. For instances, `nvidia-smi` will fail on a machine with CUDA devices when run inside a container if pass-through is not enabled.
=> Expose gpus from docker in cuda-based build pipelines

.github/workflows/trigger_nightly.yml
Trigger nightly builds (text only).
This is first step to deprecate pytorch.warm package. Trigger nightly builds from this workflow rather from the internal cron job: https://github.com/pytorch/text/pull/792
Tested in this commit: https://github.com/pytorch/text/commit/2c3b0b5d33dd283021fab7dc10aae9e55f5cfd95
=> Trigger nightly builds (text only)

torchci/components/WorkflowDispatcher.tsx
Per title.  The label is called `ciflow/inductor`, but it triggers both `inductor` and `inductor-periodic`
Use this to trigger `inductor-periodic` on https://hud.pytorch.org/pytorch/pytorch/commit/315a77a02d3648caaffa0b6fd56f35606c50aaef
=> Trigger inductor-periodic workflow on HUD

.github/actions/setup-nvidia/action.yml
Fixes failure in nightly conda test:
https://github.com/pytorch/pytorch/actions/runs/5505079662/jobs/10033840450
According to https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
We need to update to: CUDA 12.1 GA | >=530.30.02 | >=531.14
```
CUDA Toolkit | Toolkit Driver Version
  | Linux x86_64 Driver Version | Windows x86_64 Driver Version
CUDA 12.2 GA | >=535.54.03 | >=536.25
CUDA 12.1 Update 1 | >=530.30.02 | >=531.14
CUDA 12.1 GA | >=530.30.02 | >=531.14
CUDA 12.0 Update 1 | >=525.85.12 | >=528.33
CUDA 12.0 GA | >=525.60.13 | >=527.41
CUDA 11.8 GA | >=520.61.05 | >=520.06
```
Test Plan:
```
[ec2-user@ip-10-0-2-162 ~]$ nvidia-smi
Mon Jul 10 15:26:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17 …
```
=> Update linux cuda driver to 535.54.03

torchci/lib/bot/verifyDisableTestIssueBot.ts, torchci/pages/api/flaky-tests/disable.ts, torchci/test/disableFlakyBot.test.ts, torchci/test/verifyDisableTestIssue.test.ts
Some platforms have corresponding labels so add labels based on platform if there is only one set of relevant labels.  
Check labels when issue is opened or edited and correct labels if needed.
=> Disable bot to add labels based on platforms

torchci/lib/jobUtils.ts, torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts, torchci/test/jobUtils.test.ts
Fixes https://github.com/pytorch/test-infra/issues/4328
At the moment, Dr.CI uses the exact job name, i.e. `linux-bionic-cuda12.1-py3.10-gcc9-sm86 / test (default, 1, 5, linux.g5.4xlarge.nvidia.gpu)` when identifying broken trunk failures.  This approach has 2 issues:
* If the job failed due to a bad test, the same test could be run in a different shards between the PR and the base commit.  Thus, Dr.CI failed to capture this case.
* If it was an unstable job, it might or might not have the `unstable` suffix depending if the corresponding unstable issue still remained open or not.  It's fair to remove the suffix too, as it's only a decoration and does't change the job in anyway.
Note that, the logic where the capture failures are compared still applies, i.e. broken trunk = same name …
=> Remove shard ID and unstable suffix when comparing failed job names with the base commit

torchci/pages/nightlies.tsx, torchci/rockset/nightlies/__sql/docker_jobs_red.sql, torchci/rockset/nightlies/__sql/docker_jobs_red_past_day.sql, torchci/rockset/nightlies/docker_jobs_red.lambda.json, torchci/rockset/nightlies/docker_jobs_red_past_day.lambda.json, torchci/rockset/prodVersions.json
This
1. Adds docker failures to nightly page
2. Arranges the page in logical way having failure graph on the left and table with list of jobs failed for past 24hrs on the right
=> Add docker failures to nightly HUD page. Change org of nightly page

.github/workflows/trigger_nightly.yml
Make sure the nightly trigger executes on schedule.
This workflow is currently getting skipped: https://github.com/pytorch/test-infra/actions/runs/5515831720 during nightly but works on manual activation
=> Make sure the nightly trigger executes on schedule

torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts
[Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) iterates though all string-keyed property names in the object.  However, this works with `{}` but not with a `Map` object.  In fact, `Object.keys(mapObject)` returns an empty array.
Getting the empty list of base commit jobs means Dr.CI fails to detect broken trunk failures, i.e. https://github.com/pytorch/pytorch/pull/105145
This is a big gotcha moment for me, so I add an unit test for `getBaseCommitJobs` to properly test this
=> Fix the wrong use of Map with Object.keys in getBaseCommitJobs

aws/lambda/log-classifier/ruleset.toml
Currently its matching to a line saying `fail_accuracy` on both succeeding and failing jobs for a model that is expected to fail.
I assume model names fit `[A-Za-z0-9_]+`
The extra FAIL and IMPROVED should match https://github.com/pytorch/pytorch/blob/5837e95d303464141009b8072636bb4442e2fcb2/benchmarks/dynamo/check_accuracy.py#L24
<details>
<summary>Lines it should match</summary>
```
15059727721 pytorch_CycleGAN_and_pix2pix        FAIL:     accuracy=fail_accuracy, expected=pass
15052125440 attention_is_all_you_need_pytorch   FAIL:     accuracy=infra_error, expected=pass
15032425916 attention_is_all_you_need_pytorch   FAIL:     accuracy=infra_error, expected=pass
15005462402 pytorch_CycleGAN_and_pix2pix        FAIL:     accuracy=fail_accuracy, expected=pass
15004950473 moco …
```
=> [log classifier] Change inductor model regex

.github/actions/calculate-docker-image/action.yml
This refactors the logic in PyTorch https://github.com/pytorch/pytorch/blob/main/.github/actions/calculate-docker-image/action.yml to a shareable GHA.  Notably, the changes include:
* Accept a docker build directory input, i.e. `.ci/docker`, with a `build.sh` script entry.  The usage is `build.sh "${IMAGE_NAME}" -t "${DOCKER_IMAGE}"` as how it's used in PyTorch atm
* Accept a working directory input because Nova Linux job could checkout the repo in a different directory
* Simplify the list of configurable options to only 2 `always-rebuild` and `push` (set to true to push the image to ECR)
One hidden caveat is that `calculate-docker-image` requires a full checkout to work as it tries to figure out the Docker tag of the base commit.  This means that `fetch-depth: 0` is needed to use this …
=> [BE] Add shareable calculate-docker-image GHA

.github/workflows/linux_job.yml
Add a step in Linux job to calculate and build Docker image if needed.  This is similar to how PyTorch CI rebuilds its Docker images atm.
https://github.com/pytorch/pytorch/pull/105372, PyTorch Lint job uses Linux jobs.
=> Use shareable calculate-docker-image GHA

torchci/pages/benchmark/compilers.tsx
=> Make compiler names more concise and clear

.github/workflows/linux_job.yml, .github/workflows/macos_job.yml, .github/workflows/test_linux_job.yml, .github/workflows/test_macos_job.yml, .github/workflows/test_windows_job.yml, .github/workflows/windows_job.yml
Defaults to not checking out, similar to what https://github.com/actions/checkout does.
=> Add an option to init submodules when checking out in Nova jobs

terraform-aws-github-runner/modules/runners-instances/launch-template.tf
We were running into issues where the cloudwatch-agent-ctl was attempting to call out to nvidia-smi, but we actually install that as a later part of our workflow. Since we don't currently use the GPU statistics that we store in cloudwatch this is a temporary fix to get GPU instances unblocked.
Error experienced:
```
E! [telegraf] Error running agent: validate input plugin nvidia_smi failed because of Cannot get file's stat /usr/bin/nvidia-smi: no such file or directory
```
NOTE: This is a short term fix and should be treated as such, the longer term fix would be to have an AMI that has nvidia-smi pre-installed but that is a lot to ask for in an afternoon
=> infra: Switch nvidia template to utilize regular cloudwatch config

torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts
So we can use regex like `The process cannot access the file .+ because it is being used by another process` or substring like `The runner has received a shutdown signal` in the flaky rules https://github.com/pytorch/test-infra/blob/generated-stats/stats/flaky-rules.json.
There would be another PR on trymerge coming up next.
=> Add regex support to flaky rules

.github/workflows/build_wheels_linux.yml
This reverts commit 86b3577dda0e372fa55c0209aca8df6d813a1da1.
After https://github.com/pytorch/test-infra/pull/4430 we should be good to add GPU pass thru back.
=> Revert "Revert "Fix gpu pass-though" (#4389)"

aws/lambda/log-classifier/ruleset.toml
This hasn't been classified yet and show up as the generic `Process completed with exit code 1` on https://hud.pytorch.org/pytorch/pytorch/commit/78fffe890627bc020c9bd82a27a19d042f31695e
=> Add a rule to classify MacOS disk space failure

tools/torchfix/torchfix/__main__.py, tools/torchfix/torchfix/torchfix.py
No point in even parsing a file if it doesn't have "torch" string in it.
The change is in two places because one is for the standalone torchfix, and another one for the flake8 plugin.
The change gives significant speedup.
For huggingface/transformers on my machine, it goes from 
```
real	0m41.974s
user	34m7.410s
sys	0m13.530s
```
to 
```
real	0m33.837s
user	25m50.892s
sys	0m12.785s
```
The speedup will be even more if a directory has more files unrelated to PyTorch.
=> [TorchFix] Filter out files that don't have torch string

torchci/rockset/commons/__sql/weekly_force_merge_stats.sql, torchci/rockset/prodVersions.json
TSIA.  The 2 lines are wrongly swapped atm.  Also, I edit the latest version of the query instead of the slightly older version committed in https://github.com/pytorch/test-infra/pull/4441 as the former looks more correct having the inner join with `issue_comments` instead of having this part commented out.
=> Fix swapped force merge KPIs

torchci/rockset/commons/__sql/weekly_force_merge_stats.sql, torchci/rockset/prodVersions.json
improve  force merge kpi readability by making the names of the metrics shorter (allowing you to actually access the numbers for the current week).
=> improve  force merge kpi readability

.github/workflows/update-test-times.yml, torchci/components/NavBar.module.css, torchci/components/NavBar.tsx
Referenced css from https://blog.logrocket.com/how-create-multilevel-dropdown-menu-react/ and its source code at https://github.com/Ibaslogic/react-multilevel-dropdown-menu
On my smaller screen, the HUD header was becoming a bit full, so I added a dropdown and moved a lot of the dev infra links into it.  I left metrics in the bar since I think it is used frequently, but I am open to moving links around if people want fewer clicks for pages they visit often.  
The dropdown component is reusable so if we also want to add a lot of repositories and the header doesn't have space for that, we can move them all into a dropdown as well.  I have no idea how the dropdown reacts to having so many things in it it takes up the entire page but that's a problem for future me (probably either make it …
=> Add dropdown to hud header

aws/lambda/log-classifier/ruleset.toml
This will match this case https://github.com/pytorch/pytorch/pull/106562.  As we just migrate ASAN job from clang7 to clang12, I suspect that some folks will get this error on their PR if they don't have https://github.com/pytorch/pytorch/pull/106355 in their base.
=> Add a log classifiier rule to match ASAN LD_PRELOAD error

torchci/pages/metrics.tsx
Makes the following changes to the metrics page:
- Removes the irrelevant master jobs red chart, and moves the red commit chart into it's position. That chart had been more useful back when we'd randomly have large sets of jobs failing, over a year ago, but we now have much better metrics for this purpose and no one pays attention to this chart.
- Rearranges scalar stats to open make most important stats most prominent (none of these are removed)
- Makes the scalar stats more responsive, so the numbers remain readable as you shrink your browser window
- Reserves slots for key kpis for the half
Old vs New, when window width is smaller:
=> [BE] Make metrics page cleaner

torchci/pages/metrics.tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql, torchci/rockset/pytorch_dev_infra_kpis/ttrs_percentiles.lambda.json
Features:
- Updates the existing TTRS metric to make it compatible with both: the KPI page with historical results, and the metric page with the current time period's results.
- Benefit: If we change the query later, there's only one source of truth to remember to modify
- Adds the TTRS to the metrics page with both p75 and p90 results.
=> Add TTRS to metrics page

.github/workflows/build_wheels_linux.yml, .github/workflows/test_build_wheels_linux_aarch64_without_cuda.yml, tools/scripts/generate_binary_build_matrix.py
This is first PR  to automate aarch64 domains build. Starting with torchvision.
Following this script : 
https://github.com/pytorch/builder/blob/main/aarch64_linux/build_aarch64_wheel.py
cc @osalpekar @malfet @xncqr
=> Add aarch64 torchvision build

.github/scripts/run_docker_with_env_secrets.py, .github/workflows/tests.yml
This is to address the build failure https://github.com/pytorch/executorch/actions/runs/5814461344/job/15764455362?pr=52 where the cmake build expects the repo name in the include path, not `/work`
=> Mount repo to /repo instead of /work if the repo name is set

torchci/pages/api/drci/drci.ts, torchci/test/drci.test.ts, torchci/test/drciBot.test.ts
I don't know how helpful the average dev is going to find this, but it might be a good indicator for a rebase, and for us it is an easy shortcut to the merge base (previously it only showed up if there were broken trunk classification jobs).
I also added a helper function for `constructResultsComment` testing that populates it with default values so we don't have to keep changing every call in the tests whenever the function signature is changed.  Hopefully it also makes it clearer what parts of the function is being tested.
Old:
New:
=> Add merge base date to drci comment

aws/lambda/log-classifier/ruleset.toml
For example https://hud.pytorch.org/pytorch/pytorch/commit/4de5e1775ab4664a4bc9221132c979f059b94b51:
* `linux-jammy-cpu-py3.8-gcc11-inductor / test (inductor_torchbench_cpu_accuracy, 1, 1, linux.4xlarge)`
* or `linux-jammy-cpu-py3.8-gcc11-inductor / test (inductor_torchbench_dynamic_cpu_accuracy, 1, 1, linux.12xlarge)`
```
2023-08-16T09:22:09.7791143Z BERT_pytorch                       pass
2023-08-16T09:22:09.7791467Z Background_Matting                 pass_due_to_skip
2023-08-16T09:22:09.7791723Z LearningToPaint                    pass
2023-08-16T09:22:09.7794233Z Super_SloMo                        pass
2023-08-16T09:22:09.7794693Z alexnet                            pass
2023-08-16T09:22:09.7795039Z attention_is_all_you_need_pytorch  pass
2023-08-16T09:22:09.7795295Z basic_gnn_edgecnn …
```
=> Add infra_error to inductor model failure log classifier rule

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml
Misc cleanup, trying to remove anything domain-specific from these release workflows. Aarch test will fail until https://github.com/pytorch/vision/pull/7834 is merged. Commented out a couple lines to run tests, will delete before merging.
=> Cleanup Nova Release Workflows

torchci/rockset/commons/__sql/filter_forced_merge_pr.sql, torchci/rockset/prodVersions.json
This query is used by fetchHud to get the force merge status of the pull requests so that they can be highlighted on HUD. Specifically, force merges with failures are highlighted with a darker shade of orange while regular force merges due to impatience are marked with yellow. The logic needs to be in sync with the source of truth [weekly_force_merge_stats](https://github.com/pytorch/test-infra/blob/main/torchci/rockset/commons/__sql/weekly_force_merge_stats.sql) query and uses the recently added `ignore_current_checks` field for `merge -i`
I proof check all force merges on the first page of https://torchci-git-fork-huydhn-fix-hud-force-merge-76a8e4-fbopensource.vercel.app and compare them with https://hud.pytorch.org
=> Sync filter_forced_merge_pr with the newer weekly_force_merge_stats query

torchci/rockset/commons/__sql/filter_forced_merge_pr.sql, torchci/rockset/commons/__sql/weekly_force_merge_stats.sql, torchci/rockset/prodVersions.json
This is a proposal to remove no-op force merges masquerading as impatient force merges.  IMO, a legit force merge needs to satisfy one of the two conditions below:
1. `skip_mandatory_checks` is true (-f) and `failed_checks_count > 0` (with failures) or `pending_checks_count > 0` (impatience).  Under this condition, If a force merge (-f) is done when there is no failure and all jobs have finished, it's arguably just a regular merge in disguise. This is the main point of this proposal.  Here is an example of a no-op force merge https://github.com/pytorch/pytorch/pull/106912#issuecomment-1680999969 (out of many)
2. `ignore_current` is true (-i) and `is_failed` is false (indicating a successful merge) and `ignored_checks_count > 0` (with failures).  As `-i` still waits for all remaining jobs …
=> Remove no-op force merges masquerading as impatient force merges

.github/scale-config.yml
Increasing the number of `linux.g5.12xlarge.nvidia.gpu` as it hit the ceil for runners in a healthy state. Increasing for `linux.g4dn.12xlarge.nvidia.gpu` as the current value seems very low.
=> Increase max runners for 'linux.g4dn.12xlarge.nvidia.gpu' and 'linux.g5.12xlarge.nvidia.gpu' to 50

.github/scale-config.yml
Increase the max_available runners for `linux.g5.4xlarge.nvidia.gpu` from 550 to 600 and `linux.g5.12xlarge.nvidia.gpu` from 50 to 100.
=> increase max_available runners for linux.g5.4xlarge.nvidia.gpu and linux.g5.12xlarge.nvidia.gpu

torchci/pages/api/drci/drci.ts
Tweak the Dr. CI message to let devs know that they don't need to force merge if only unrelated failures are failing in CI.
This is quick-n-dirty attempt at nudging devs away from unnecessary force merges
=> Let Dr.CI message nudge folks towards a normal merge

.github/workflows/lintrunner_ci.yml
Updates the release flow for lintrunner to actually work.
Was tested using https://github.com/pytorch/test-infra/pull/4500
=> update release flow for lintrunner

torchci/lib/bot/retryBot.ts, torchci/rockset/commons/__sql/flaky_workflows_jobs.sql, torchci/rockset/commons/flaky_workflows_jobs.lambda.json, torchci/rockset/prodVersions.json, torchci/test/retryBot.test.ts
This is a small tweak to not retry unstable jobs as they are unstable anyway.  This helps with the ROCm queue atm when retrying doesn't help.  The job has been marked as unstable.
=> Do not retry unstable jobs

.github/workflows/update-test-times.yml, torchci/scripts/test_update_test_times.py, torchci/scripts/update_test_times.py
In https://github.com/pytorch/test-infra/pull/4476 I removed the code that allows us to edit the test times manually and have it mostly persist because I thought we didn't need it anymore but I was wrong.  This PR adds this ability back in.
This means the test times json never shrinks, but I think that's ok since we can manually edit it.
Also
* rename the job 
* move to ubuntu-latest
=> Maintain old test times

torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql
Per our discussion, let's exclude unstable jobs from TTR computation because they don't block merge.
https://torchci-git-fork-huydhn-remove-unstable-job-tts-fbopensource.vercel.app/metrics and https://torchci-git-fork-huydhn-remove-unstable-job-tts-fbopensource.vercel.app/kpis
=> Exclude unstable jobs from TTRS computation

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml
We will use a separate `CONDA_PYTORCHBOT_TOKEN_TEST` for using in a test environment
Fixes https://github.com/pytorch/test-infra/issues/4529
TODO:
1. Add the token to the other domain repos
2. Add to audio caller: https://github.com/pytorch/audio/pull/3582
3. Add to vision caller: https://github.com/pytorch/vision/pull/7900
=> Support for Test Conda Token

torchci/lib/searchUtils.ts
This is a bug in my search query where the newer records were preferred over more relevant ones.  Because there is a limit on the number of returned records, the query failed to find some legit similar failures, i.e. https://github.com/pytorch/pytorch/pull/107584 (both MacOS jobs failed in periodic).
This also explains the confusion I have where some irrelevant results are at the top.
* The current [HUD](https://hud.pytorch.org/api/search?failure=inductor/test_torchinductor.py::CpuTests::test_multilayer_var_cpu?startDate=2023-08-20T12:13:23.916Z&endDate=2023-08-25T15:11:10.000Z) returns mostly junks while https://torchci-git-fork-huydhn-fix-similar-failure-46268c-fbopensource.vercel.app/api/search?failure=inductor/test_torchinductor.py::CpuTests::test_multilayer_var_cpu?startDate=2023-08-2 …
=> Return most relevant similar failure first, not the newest one

tools/torchfix/README.md, tools/torchfix/torchfix/__main__.py
The whole "ignore stderr" is an ugly hack and should be eventually removed by resolving https://github.com/Instagram/LibCST/issues/944, but for now it's better to make the ignoring behavior default to don't confuse new TorchFix users.
=> [TorchFix] Ignore stderr by default

.github/scale-config.yml
This reverts commit b7ba5263f9c037153b179f552d77bcc34867953c.
It doesn't make sense to have dedicated GPU windows instances, as for now all the ephemeral GPU windows instances are only being used for the release process.
If this is not the case, makes more sense to update the usage on the tasks itself.
=> Revert "Dedicate windows GPU for the release process (#4535)"

.github/scale-config.yml
=> increase max_available runners for linux.arm64.2xlarge to 100

torchci/pages/benchmark/compilers.tsx
@penguinwu points out to me that there are new options for `aot_inductor` and `cudagraphs_freezing` showing up on the dashboard.  And they haven't been mapped to a more descriptive display name yet.  This is a small tweak to add their internal name to display name mappings
=> Add more display name mapping to inductor dashboard

.github/workflows/build_conda_linux.yml, .github/workflows/build_wheels_linux.yml
I don't think we can ssh into a container 
See https://github.com/pytorch/test-infra/issues/4546
=> Remove ssh from linux conda/wheel builds since they are in a container

.github/workflows/linux_job.yml
Executorch team reports a flaky issue on their PRs where the Linux job tries to upload non-existing docs artifacts and fails 
[T162571560](https://www.internalfb.com/intern/tasks/?t=162571560).  The upload logic wrongly counts empty directories, so this change fixes the issue by counting only actual files.
=> Upload docs artifacts only when there are files to upload

.github/workflows/build_wheels_linux.yml
Reverts pytorch/test-infra#4544
The ``--pre`` argument is not required anymore. This was resolved by following PRs: https://github.com/pytorch/builder/pull/1519 and https://github.com/pytorch/builder/pull/1520
=> Revert "Release only change temporary fix aarch64 builds"

tools/self-hosted-runner-utils/requirements.txt
Looks like the repository we were previously relying on has become non-existent and so we can rely on upstream PyGithub to supply the correct thing here.
=> tools: Update to require PyGithub directly

tools/torchfix/tests/fixtures/vision/checker/pretrained.py, tools/torchfix/tests/fixtures/vision/checker/pretrained.txt, tools/torchfix/tests/fixtures/vision/codemod/pretrained.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained.py.out, tools/torchfix/torchfix/common.py, tools/torchfix/torchfix/torchfix.py, tools/torchfix/torchfix/visitors/vision/__init__.py
For TorchVision models, `pretrained` and `pretrained_backbone` parameters have been deprecated in favor of "Multi-weight support API" - see https://pytorch.org/vision/0.15/models.html
This PR adds a checker/codemod for the deprecated parameters. As the new weights values needs to be imported first, this PR adds a generic mechanism to collect all needed imports and apply them after all local changes.
Also updated version to "0.0.3" as TorchFix 0.0.2 was released recently and this will be eventually released as 0.0.3
=> [TorchFix] Add TorchVision pretrained codemod

tools/torchfix/tests/fixtures/vision/checker/pretrained.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained.py.out, tools/torchfix/tests/fixtures/vision/codemod/pretrained_models_import.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained_models_import.py.out, tools/torchfix/tests/fixtures/vision/codemod/pretrained_none_import.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained_none_import.py.out, tools/torchfix/torchfix/common.py, tools/torchfix/torchfix/visitors/vision/__init__.py
A follow-up to https://github.com/pytorch/test-infra/pull/4559
Meta-internal autodeps feature has issues with imports like `from torchvision.models import MobileNet_V3_Large_Weights`, so changed the logic to just do `from torchvision import models` (if not yet imported) and then use full name from `models` for the weights.
=> [TorchFix] Change how weights are imported for TorchVision pretrained codemod

.github/workflows/build_wheels_linux.yml
Bump timeouts for this job to 120 minutes, since fbgemm build seems to take longer than 60. hopefully we can use caching/other techniques to speed up the build and revert this timeout bump.
=> Bump Timeout for Linux Wheels (temporarily)

.github/scale-config.yml
=> Increase the max_available for linux.g5.4xlarge.nvidia.gpu to 800

.github/workflows/lint.yml, .github/workflows/tests.yml, tools/torchfix/tests/fixtures/performance/checker/dataloader.py
Verify that TorchSynchronizedDataLoaderVisitor doesn't create noise when it's not possible to determine statically.
Also don't run Test tools / linux-job and lintrunner on TorchFix PRs.
=> [TorchFix] Add test for non-static SynchronizedDataLoader case

.github/scripts/get_merge_base_info.py, .github/scripts/rockset_utils.py, .github/workflows/update_test_file_ratings.yml, torchci/lib/fetchCommit.ts, torchci/lib/s3.ts, torchci/pages/api/drci/drci.ts, torchci/test/drciBot.test.ts
Put merge base date info into rockset, also query rockset for merge base info if possible to reduce number of github api calls.  If the info can't be found, it still uses the gh api
Dedup merge base table to fix errors that might happen
=> [dr ci] Use rockset for merge bases

torchci/lib/drciUtils.ts, torchci/lib/types.ts, torchci/pages/api/drci/drci.ts, torchci/rockset/commons/__sql/recent_pr_workflows_query.sql, torchci/rockset/prodVersions.json, torchci/test/drci.test.ts, torchci/test/drciUtils.test.ts
We have jobs with the same name but in different workflows sometimes (ex rocm and windows builds), and one will override the other in dr ci but still show up on hud (and mergebot)
=> [dr ci] Include workflow name in job name

torchci/pages/benchmark/compilers.tsx
In https://github.com/pytorch/pytorch/commit/88ef126a93234903e4af26d792160862ca54c38e, I bumped the torchbench version, which includes some model names updates:
- nanogpt_generate -> nanogpt (also supports train now)
- stable_diffusion -> stable_diffusion_text_encoder (now we've also added the unet part of the model: https://github.com/pytorch/benchmark/commit/9cbeee3b54981760e977bed0faaff15379a4adef)
We need to update the model names for blueberries dashboard to track the new models
=> rename models in benchmark dashboard's model mapping

tools/torchfix/tests/fixtures/vision/checker/pretrained.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained_submodule_import.py, tools/torchfix/tests/fixtures/vision/codemod/pretrained_submodule_import.py.out, tools/torchfix/torchfix/visitors/vision/__init__.py
Update the rule for `pretrained` torchvision models parameter to work when a model imported from a submodule, like `models.resnet.resnet101` instead of `models.resnet101` (which is the same model).
=> [TorchFix] Make pretrained rule work when a model imported from a submodule

.github/workflows/lintrunner_ci.yml
By pinning it to  https://github.com/PyO3/maturin-action/tree/v1.40.2
As it fails with https://github.com/PyO3/maturin-action/tree/v1.40.3 that was released 3 days ago
Also, run lintrunner_ci.yml on pull if yml itself is modified
=> Fix lintrunner MacOS builds

.github/workflows/update_test_file_ratings.yml, torchci/scripts/calculate_file_test_rating.py, torchci/scripts/test_calculate_file_test_rating.py
Exports historical correlations of which files caused which test classes to fail to test-infra.
Will use this to create a heuristic for test reordering
=> TD: Export TestClass correlations

torchci/lib/drciUtils.ts, torchci/lib/searchUtils.ts, torchci/pages/api/search.ts, torchci/test/drciUtils.test.ts
I notice this force merge today https://github.com/pytorch/pytorch/pull/110487 where a flaky ROCm periodic job shows up as actual an actual failure.  This shouldn't be the case because there is a similar failure from a nearby commit https://hud.pytorch.org/pytorch/pytorch/commit/efb73fe8e4413a0d6db078e85c7ed7c91f05ca5d.
It turns out that the query returns many similar results but they are all from `pull` or `trunk`.  When we limit only to the top 20 results, `periodic` has less chance to show up there as it runs less frequently.
This change, thus, makes the query more focus on relevant results by specifying the workflow name as an optional parameter.
Using https://github.com/pytorch/pytorch/pull/110487 as an example, Dr.CI nows classifies the flaky failure correctly:
* :page_facing_up: …
=> Add the workflow name as an optional search parameter

.github/workflows/linux_job.yml
Remove the use of linux.t4g.2xlarge as part of migrating t4g.2xlarge runners from pet instances.
=> Remove use linux.t4g.2xlarge

.github/workflows/linux_job.yml
Remove the use of linux.t4g.2xlarge as part of migrating t4g.2xlarge runners from pet instances.
=> Removed condition for linux.t4g.2xlarge

torchci/pages/kpis.tsx, torchci/rockset/prodVersions.json, torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql, torchci/rockset/pytorch_dev_infra_kpis/ttrs_percentiles.lambda.json
Reduces two sources of noise in the TTRS metric, which is supposed to measure how long the test step ran for before a failure occurred.
Changes being made are:
1. Removes noise from queuing times 
2. Only look at the pull workflow, since other workflows are run at a much more variable number of times.
The second one is a bit more controversial, so here's the reasoning:
1. The pull workflow makes up more than 85% of workflows run. 
2. The ratio of how often pull was run to other workflows varies from month to month based on user behavior, adding noise
3. If you look at TTRS rates for pull and trunk workflows separately, they have similar trend lines, making pull workflows a good representative for them all.
Old values:
New values:
Note that the spike in Old values p90 ttrs that goes away …
=> TD: Denoise TTRS metric

torchci/lib/drciUtils.ts, torchci/test/drci.test.ts
https://github.com/pytorch/pytorch/pull/111207 was merged because Dr.CI detects the lint failure as flaky.  This was an FP because it found an exact match of the same lint failure, on a different branch.  This happens because lint failure only prints the name of the broken file.
```
{
name: 'Lint / lintrunner / linux-job',
workflowName: 'Lint',
jobName: 'lintrunner / linux-job',
sha: '2b30b63b86ee277b3e70d39db6244ac0360c84c3',
id: 17653166474,
workflowId: 6499566593,
time: '2023-10-12T18:59:16Z',
conclusion: 'failure',
htmlUrl: 'https://github.com/pytorch/pytorch/actions/runs/6499566593/job/17653166474',
failureLine: '>>> Lint for torch/_dynamo/output_graph.py:',
failureLineNumber: 145946,
failureCaptures: [ '>>> Lint for torch/_dynamo/output_graph.py:' ]
}
```
In hindsight, lint jobs are …
=> Add an excluded list for flaky detection on Dr.CI

tools/torchfix/README.md, tools/torchfix/torchfix/torchfix.py
TorchFix has been used in GitHub CI for several Meta projects and has received its first non-Meta contribution recently, so let's update it to Beta status before the presentation on PyTorch Conference 2023.
The main change from 0.0.2 release is new rules for deprecated TorchVision APIs.
=> [TorchFix] Update version to 0.1.0

aws/lambda/log-classifier/fixtures/request.json, aws/lambda/log-classifier/src/main.rs, aws/lambda/log-classifier/src/rule_match.rs
I have this change to add the list of N (5) previous commands as optional context on log classifier.  This relies on GitHub console log convention to prefix a **bash** command with `+`.  This new `context` field should just become a new field on `workflow_job` for future query.
This is mainly an attempt to provide more context on GHA generic failures that are not well captured by the log classifier.
=> Add the list of previous commands as optional context on log classifier

.github/workflows/lint.yml, aws/lambda/github-webhook-rds-sync/generate_schema.py, aws/lambda/github-webhook-rds-sync/lambda_function.py, aws/lambda/github-webhook-rds-sync/test_lambda.py, aws/lambda/github-webhook-rds-sync/utils.py, aws/lambda/log-classifier/src/main.rs, aws/lambda/log-classifier/src/rule_match.rs, aws/lambda/rds-proxy/lambda_function.py, aws/lambda/usage-log-aggregator/lambda_function.py
My https://github.com/pytorch/test-infra/pull/4649 broke lint and I was surprise that lint didn't run on that PR.  I suspect that the reason is this caveat from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions:
> If you define a path with the ! character, you must also define at least one path without the ! character. If you only want to exclude paths, use paths-ignore instead
* Switch to `paths-ignore` on lint workflow
* Run `lintrunner -a aws/lambda/**/*.py` and `lintrunner -a aws/lambda/**/*.rs`
=> Apply lint to aws directory

torchci/pages/api/drci/drci.ts
I forgot (again) that Dr.CI could handle more than one PR at a times.  So, it prints all the results from the run, i.e. https://github.com/pytorch/pytorch/pull/110511/checks?check_run_id=17834281447, which is working but has too much redundant information.  And the summary field has an upper limit of 65535 characters.
Only the classification of the target PR is print and the redundant PR number is removed https://github.com/pytorch/pytorch/pull/111493/checks?check_run_id=17835502442
=> Only upload Dr.CI classification results for the target PR

torchci/lib/bot/autoLabelBot.ts, torchci/test/autoLabelBot.test.ts
This is needed after https://github.com/pytorch/pytorch/pull/111394.
=> Add an auto-label rule for ciflow/rocm

torchci/lib/fetchPR.ts, torchci/rockset/commons/__sql/pr_commits.sql, torchci/rockset/commons/pr_commits.lambda.json, torchci/rockset/prodVersions.json
Makes it so that the HUD's commit dropdown shows all commits that have had CI run against them, _even if that commit has been rebased past_
This makes it so that you don't loose CI data when you rebase your PR or amend and force push your latest commit.
As a tradeoff, commits that were only committed locally but didn't have CI run against them (e.g. they were pushed to github as part of a set) will no longer show up in that dropdown, but they weren't useful anyways so it's fine
Old list from https://hud.pytorch.org/pr/110578
Hud lost all my commits before I squashed and rebased
New list, showing all my old commits. The commits with the same name are from amended commits that were force pushed.
Source: https://torchci-git-zainr-rebase-proof-fbopensource.vercel.app/pr/110578
=> [BE] HUD can show jobs run on a PR against commits before it was rebased

torchci/components/WorkflowBox.tsx
Adds a new `Show artifacts` button/link that if clicked, shows the artifacts for that job.
Which artifacts are shown is based on job name, and it expects it to be in the form `<random stuff><either - or _><job id>.<file extension>`.  This is the current naming convention for test xmls, jsons, and log files.
Build artifacts generally look like `<build env, which is also usually the job name>/artifacts.zip`, so those also go under the corresponding build.
All artifacts are still visible at the bottom just in case.
=> [HUD] Group artifacts under job

torchci/lib/searchUtils.ts
As the name of the function `searchSimilarFailures` implies, the query shouldn't need to check for successful jobs
The new failure on https://github.com/pytorch/pytorch/pull/111596 should be marked as flaky instead as this is a known issue in trunk.
```
--url 'http://localhost:3000/api/drci/drci?prNumber=111596' \
{"111596":{"FAILED":[],"FLAKY":[{"workflowId":6579874873,"id":17877767763,"runnerName":"i-0c5ec556b639e35ef","name":"pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 5, 5, linux.g5.4xlarge.nvidia.gpu)","jobName":"linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 5, 5, linux.g5.4xlarge.nvidia.gpu)","conclusion":"failure","completed_at":"2023-10-19T23:22:50Z","html_url":"https://github.com/pytorch/pytorch/actions/runs/65 …
```
=> Only query for similar non-success jobs

.github/workflows/update_test_file_ratings.yml, .gitignore, torchci/scripts/get_merge_base_info.py, torchci/scripts/rockset_utils.py, torchci/scripts/td_heuristic_historical_edited_files.py, torchci/scripts/td_heuristic_profiling.py, torchci/scripts/utils.py, torchci/scripts/utils_td_heuristics.py
Add a heuristic based on profiling data and a heuristic based on historical edited files.
Addes caching for rockset queries and other functions.
=> [TD] Historical edited files and profiling heuristics

.github/workflows/update-test-times.yml, torchci/rockset/commons/__sql/test_time_per_class.sql, torchci/rockset/commons/__sql/test_time_per_class_periodic_jobs.sql, torchci/rockset/commons/test_time_per_class.lambda.json, torchci/rockset/commons/test_time_per_class_periodic_jobs.lambda.json, torchci/rockset/prodVersions.json, torchci/scripts/test_update_test_times.py, torchci/scripts/update_test_times.py
This will later be used by test class granularity heuristics.
Patterns are all based off of how we currently collect this data at the test file granularity level
=> [TD] Collect test class durations

torchci/components/WorkflowBox.tsx, torchci/lib/searchUtils.ts
Keep the number of hooks the same but hide the <a> tag if there is no artifacts.  This probably fixes the error reported on Tree Hugger when loading https://hud.pytorch.org/pr/111935 
Also we cannot use hook, i.e. `useState` in `WorkflowBox` because the number of jobs can change dynamically on PR or commit pages.
=> Fix the number of hooks conditionally rendered by hasArtifacts

tools/torchfix/tests/fixtures/security/checker/load.py, tools/torchfix/tests/fixtures/security/checker/load.txt, tools/torchfix/torchfix/torchfix.py, tools/torchfix/torchfix/visitors/security/__init__.py
See https://github.com/pytorch/pytorch/issues/31875 and https://github.com/pytorch/pytorch/issues/111806 for discussion.
=> [TorchFix] Add TorchUnsafeLoadVisitor

tools/torchfix/tests/fixtures/deprecated_symbols/codemod/aliased_import.py, tools/torchfix/tests/fixtures/deprecated_symbols/codemod/aliased_import.py.out, tools/torchfix/torchfix/common.py, tools/torchfix/torchfix/visitors/deprecated_symbols/chain_matmul.py, tools/torchfix/torchfix/visitors/deprecated_symbols/cholesky.py, tools/torchfix/torchfix/visitors/deprecated_symbols/qr.py
By introducing `torchfix.common.get_module_name(node: cst.Call)` and using it in deprecated symbols codemods
Fixes https://github.com/pytorch/test-infra/issues/4452
=> [TorchFix] Deprecated codemods to honor aliases

.github/scale-config.yml
=> Increase max runners for 'linux.arm64.2xlarge' to 200

torchci/lib/drciUtils.ts, torchci/lib/searchUtils.ts, torchci/pages/api/search.ts, torchci/test/drciUtils.test.ts
Expose `branchName` as an option to limit failures search to that specific branch, for example, only failures from `main`
Spot check on https://github.com/pytorch/pytorch/pull/111463 to make sure everything still works correctly
```
--url 'http://localhost:3000/api/drci/drci?prNumber=111463' \
```
=> Add an option to limit failures search to a specific branch

torchci/pages/benchmark/compilers.tsx
Reported by @xmfan where the dashboard counts models with 0 speedup (failed perf benchmark) as success.  They should be count as failures instead.
https://torchci-git-fork-huydhn-failed-benchmark-models-fbopensource.vercel.app/benchmark/compilers
=> Count models with 0 speedup as failures

torchci/pages/api/flaky-tests/disable.ts
Currently buggy due to tests jumping from shard to shard.
=> [bot] Remove flaky detection for flaky across jobs

torchci/pages/kpis.tsx, torchci/rockset/metrics/__sql/disabled_test_historical.sql, torchci/rockset/metrics/disabled_test_historical.lambda.json, torchci/rockset/prodVersions.json
This change completely reworks the `torchci/rockset/metrics/__sql/disabled_test_historical.sql` query to:
* Keep track of not only the daily `number_of_new_disabled_tests` but also `number_of_closed_disabled_tests`
* Add a new chart to keep track of the daily `number_of_open_disabled_tests` on KPIs page.  This is calculated by deducting the aggregated `total_number_of_closed_disabled_tests` from the aggregated `total_number_of_new_disabled_tests`
This also fixes a bug in the counting of `number_of_new_disabled_tests`.  Previously, it was counted using `_event_time` as follows:
```
FORMAT_ISO8601(
DATE_TRUNC(
:granularity,
issues._event_time AT TIME ZONE :timezone
)
) AS granularity_bucket,
COUNT(issues.title) as number_of_new_disabled_tests
```
This is wrong because the `_event_time` is …
=> Track the daily number of open disabled issues

.gitignore, torchci/scripts/td_rockset_analysis.py, torchci/scripts/utils.py
I think this includes everything on https://docs.google.com/document/d/10xIKxGDlUK2Z24CuxnaNEvWj2bXpIHxG-pn5jeQBw30/edit#heading=h.ucic3fw5x72k except `% of tests with a better result due to TD vs worse results`.
Does not do anything in particular better than the doc other than auto generating graphs, caching rockset results,  and that it doesn't need to specify every heuristic
* Create folder called `_logs` for random outputs.  I am open to better names
* Move caching folder into `_logs` folder so there are fewer files in repo root.
=> [td] Adds python script to analyze TD heuristics

.github/actions/setup-miniconda/action.yml
I rename the variable to CONDA_PREFIX in https://github.com/pytorch/test-infra/pull/4697 to match with what conda is using https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html, but it looks like the CONDA_ENV variable could still be used elsewhere by the callers https://github.com/search?type=code&q=org%3Apytorch+CONDA_ENV
=> Keep exporting CONDA_ENV

tools/scripts/generate_binary_build_matrix.py
As one can not really build pre-CXX11 binaries for MacOS, and to the best of my knowledge static-with-deps binaries were never generated
Test plan:
```
$ python3 tools/scripts/generate_binary_build_matrix.py --package-type libtorch --operating-system macos --channel nightly|jq
{
"include": [
{
"gpu_arch_type": "cpu",
"gpu_arch_version": "",
"desired_cuda": "cpu",
"libtorch_variant": "shared-with-deps",
"libtorch_config": "",
"devtoolset": "cxx11-abi",
"container_image": "pytorch/libtorch-cxx11-builder:cpu",
"package_type": "libtorch",
"build_name": "libtorch-cpu-shared-with-deps-cxx11-abi",
"validation_runner": "macos-12",
"installation": "https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip",
"channel": "nightly",
"stable_version": "2.1.0"
}
]
}
```
=> Limit MacOS libtorch to just one flavor

tools/torchfix/tests/fixtures/security/checker/load.py, tools/torchfix/tests/fixtures/security/checker/load.txt, tools/torchfix/torchfix/visitors/security/__init__.py
https://github.com/pytorch/test-infra/pull/4671 added linter-only `TorchUnsafeLoadVisitor`, but it turned out that the issue is so widespread that manual fixes would be tedious.
The codemod is somewhat unsafe correctness-wise because full pickling functionality may still be needed even without `pickle_module`, but I think it's OK because it fixes a security-related issue and the codemods need to be verified anyway.
Maybe later we should add something like Ruff's recently added `--unsafe-fixes`: https://docs.astral.sh/ruff/linter/#fix-safety
I used this for https://github.com/pytorch/vision/pull/8105
=> [TorchFix] Add codemod for unsafe load

.github/actions/setup-binary-builds/action.yml
Conda builds started failing since conda 23.10 hence pinning to conda 23.7.3.
Reference issue: https://github.com/conda/conda/issues/13304
=> Pin conda to 23.7.3 last working version

.github/workflows/build_conda_windows.yml
Pin conda to 23.7.3 before doing conda build in windows
Small code cleanup to remove commented out lines
=> Pin conda to 23.7.3 before doing conda build in windows

tools/scripts/generate_binary_build_matrix.py
This should use old libtorch file and fix validation error:
https://github.com/pytorch/builder/actions/runs/6801641578/job/18496782857
=> Use old libtorch package for test channel

tools/scripts/generate_binary_build_matrix.py
We should be testing particular version rather than latest
```
% python tools/scripts/generate_binary_build_matrix.py --operating-system macos --channel test --package-type libtorch|jq
{
"include": [
{
"gpu_arch_type": "cpu",
"gpu_arch_version": "",
"desired_cuda": "cpu",
"libtorch_variant": "shared-with-deps",
"libtorch_config": "",
"devtoolset": "cxx11-abi",
"container_image": "pytorch/libtorch-cxx11-builder:cpu",
"package_type": "libtorch",
"build_name": "libtorch-cpu-shared-with-deps-cxx11-abi",
"validation_runner": "macos-12",
"installation": "https://download.pytorch.org/libtorch/test/cpu/libtorch-macos-2.1.1.zip",
"channel": "test",
"stable_version": "2.1.1"
}
]
}
```
=> Better libtorch definitions for test channel

tools/torchfix/README.md, tools/torchfix/tests/fixtures/deprecated_symbols/checker/removed_solve.py, tools/torchfix/tests/fixtures/deprecated_symbols/checker/removed_solve.txt, tools/torchfix/torchfix/deprecated_symbols.yaml, tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
Add torch.solve as a removed function (I somehow missed it before and noticed after https://github.com/pytorch/tutorials/pull/2642).
Also added a mechanism to show reference links in the error messages.
=> [TorchFix] Add torch.solve as a removed function

torchci/lib/searchUtils.ts
The logs on the failures pages (linked to by the More like this buttons) didn't work: the link for raw logs didn't link anywhere, and the log viewer didn't show anything.
Fixed by adding the a logUrl to the output of the search
=> [ez][HUD] Add log url to opensearch output 

torchci/lib/bot/cancelWorkflowsOnCloseBot.ts, torchci/test/cancelWorkflowsOnCloseBot.test.ts
I thought the data would be returned in the form of { total_count: idk, workflow_runs: [list]} and that I had to unwrap it myself, but apparently it is already unwrapped into a list.
=> [bot][ez] Fix cancel workflows on close

aws/lambda/log-classifier/fixtures/request.json, aws/lambda/log-classifier/src/rule_match.rs
Log classifier fails on this job https://github.com/pytorch/pytorch/actions/runs/6618894647/job/17986337626.  The issue can  be reproduced by running, which ends up with an `Internal Server Error` error:
```
curl "https://vwg52br27lx5oymv4ouejwf4re0akoeg.lambda-url.us-east-1.on.aws/?job_id=17986337626"
```
It turns out that `log.lines.get(&i)` can be None while gathering the failure context.  This change handles the None value correctly.
=> [log-classifier] Handle None value when getting a log line

aws/lambda/log-classifier/ruleset.toml
As in title, it shows up a lot in the xla logs, but the xla job never fails because of it.  The test failure later on is the real failure, so reduce priority to below the tests.
=> [log classifier][ez] Reduce npm error priority

torchci/lib/bot/cancelWorkflowsOnCloseBot.ts, torchci/test/cancelWorkflowsOnCloseBot.test.ts
I forgot that people can make PRs with the head sha being a main branch commit.
Also restrict this to pytorch/pytorch since I don't know if other repos want it.
=> [ez][bot] Fix cancelWorkflowsOnClose when head sha actually belongs to main

tools/torchci/download_logs.py
This is the script I use to download logs if anyone wants it
It only downloads test logs right now but feel free to change the rockset query to suit your purposes
Usage either:
change the main function to whatever you want and call
`tools/torchci/download_logs.py <commit sha>`
Logs get downloaded to `repo root / _logs / ci_logs / commit sha`.  I like to use VSCode's search functionality as grep
=> Add log downloader

torchci/components/JobLinks.tsx, torchci/pages/failure.tsx
Got mildly annoyed at the number of clicks it took me to get to the hud commit page for a job on the more like this page, so add a link to the commit.
=> [ez][hud] Add commit link on more like this/failures page

torchci/pages/torchbench/userbenchmark.tsx, torchci/rockset/prodVersions.json, torchci/rockset/torchbench/__sql/torchbench_userbenchmark_list_commits.sql
Add the pytorch commit date time to the commit picker and metrics table header.
Demo screenshot:
=> Improve the userbenchmark dashboard with pytorch commit date

tools/torchfix/torchfix/torchfix.py
TorchFix 0.2.0 release
- TorchFix now depends on libcst-0.1.1 and thus can be installed from PyPI on Python 3.12 without requirement of Rust toolchain
- Added a rule to find and fix potentially unsafe usages of `torch.load`
- Codemods for deprecated functions now honor aliases for torch (`import torch as`)
- `torch.solve` added to the list of removed PyTorch functions
=> [TorchFix] Update version to 0.2.0

.github/actions/setup-binary-builds/action.yml
This causes following issues with M1 runners: 
https://github.com/pytorch/audio/actions/runs/6969147299/job/18977954592
Caused by system conda version being 23.10.
Conda and Conda build versions need to be advanced togeather. This makes sure our system conda version is the same as environment conda version we create.
=> Pin system conda version to 23.7.3

.github/actions/setup-binary-builds/action.yml
This causes following issues with M1 runners: 
https://github.com/pytorch/audio/actions/runs/6969147299/job/18977954592 Caused by system conda version being 23.10.
Conda and Conda build versions need to be advanced togeather. This makes sure our system conda version is the same as environment conda version we create.
=> Pin system conda version to 23.7.3 (#4752)

.github/actions/setup-binary-builds/action.yml, .github/workflows/build_conda_macos.yml
Follow up on https://github.com/pytorch/test-infra/pull/4752
Restrict to MacOS only. Pinning to 23.7.3 for everything causes failure in aarch64 builds here: https://github.com/pytorch/audio/actions/runs/6980246736/job/18995112761
=> Restrict conda pin to 23.7.3 to macos only

.github/actions/setup-binary-builds/action.yml, .github/workflows/build_conda_macos.yml
Follow up on https://github.com/pytorch/test-infra/pull/4752 Restrict to MacOS only. Pinning to 23.7.3 for everything causes failure in aarch64 builds here:
https://github.com/pytorch/audio/actions/runs/6980246736/job/18995112761
=> Restrict conda pin to 23.7.3 to macos only (#4754)

.github/actions/setup-binary-builds/action.yml, .github/workflows/build_conda_macos.yml
Move conda and conda builds to latest conda versions.
This failure I believe is pre existing issue in nightly : 
https://github.com/pytorch/test-infra/actions/runs/6984665829/job/19007831651?pr=4757
Here is nightly failure:
https://github.com/pytorch/vision/actions/runs/6980248443/job/18995117245#step:13:279
=> Move conda and conda-builds to latest conda versions

.github/workflows/macos_job.yml
This will allow repo to use different python version than 3.9 when using MacOS job.
=> Set python version in Nova MacOS jobs

.github/workflows/build_conda_macos.yml
MacOS smoke test started to fail with following error:
```
/opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_7018156083_smoke conda install --quiet --yes -c pytorch-nightly -c file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr distr::torchvision
PackagesNotFoundError: The following packages are not available from current channels:
- distr::torchvision
Current channels:
- https://conda.anaconda.org/pytorch-nightly
- file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr
- defaults
- https://conda.anaconda.org/distr <-- Here is the error
To search for alternate channels that may provide the conda package you're
looking for, navigate to
https://anaconda.org/
and use the search bar at the top of …
```
=> Remove distr prefix from macos builds

.github/workflows/build_conda_macos.yml
MacOS smoke test started to fail with following error:
```
/opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_7018156083_smoke conda install --quiet --yes -c pytorch-nightly -c file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr distr::torchvision
PackagesNotFoundError: The following packages are not available from current channels:
- distr::torchvision
Current channels:
- https://conda.anaconda.org/pytorch-nightly
- file:///Users/ec2-user/runner/_work/vision/vision/pytorch/vision/distr
- defaults
- https://conda.anaconda.org/distr <-- Here is the error
To search for alternate channels that may provide the conda package you're
looking for, navigate to
https://anaconda.org/
and use the search bar at the top of …
```
=> Remove distr prefix from macos builds (#4766)

aws/lambda/log-classifier/ruleset.toml
The log classifier keeps getting stuck on `npm ERR! code EEXIST` for XLA
=> [log classifier] Deprioritized npm error, new rule to capture xla cpp test failures

.github/actions/setup-binary-builds/action.yml
And default to python 3.10 as conda builds create their own environment
anyway
=> [Nova] Do not install conda-build for wheels

torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql, torchci/rockset/prodVersions.json
Summary: https://github.com/pytorch/pytorch/pull/114784/ introduces two more fail states, model_fail_to_load and eager_fail_to_run, and they should be excluded from calculating the pass rate.
=> [dashboard] Exclude model_fail_to_load and eager_fail_to_run

torchci/lib/drciUtils.ts, torchci/lib/jobUtils.ts, torchci/lib/searchUtils.ts, torchci/pages/api/failure.ts, torchci/test/drciUtils.test.ts, torchci/test/jobUtils.test.ts
This addresses the edge case in https://github.com/pytorch/pytorch/pull/113432 where the PR was reverted due to a land race failure.  Here is what happened:
1. PR was green and merged normally
2. The merge commit broke trunk due to landrace, and was reverted
3. PR was rebase.  The failure was reproducible on the PR, but Dr.CI classified it as flaky because it found similar failures from trunk commits from different authors
The fix here is to check if the failure comes from a previous merge commit of the PR, and if it does, do not mark it as flaky.  Here are the steps to achieve this:
1. When searching for similar results, return the oldest most relevant match first.  Previously, the timestamp didn't matter as long as there was a match
2. Using this sorted list, if the very first match …
=> Handle false positive flaky detection on reverted PRs

.github/actions/set-channel/action.yml, .github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml, .github/workflows/generate_binary_build_matrix.yml, tools/scripts/generate_binary_build_matrix.py
With 2 candidate RC in the test channel (2.1.2 and 2.2.0), we need to have a way to specify which PYTORCH_VERSION to use.  The issue surfaces when we are trying to cut RC3 for 2.1.2 today while there is already RC1 for 2.2.0 in place.  In the current state, `PYTHON_VERSION=3.11 PACKAGE_TYPE=conda CU_VERSION=cpu ARCH_NAME=arm64 CHANNEL=test python -m pytorch_pkg_helpers` will set `PYTORCH_VERSION` to 2.2.0 whenever domains are built
For example, https://github.com/pytorch/vision/actions/runs/7190086502/job/19582646141#step:6:743 build M1 conda for vision 0.16.2 and it's expected to use 2.1.2 there, not 2.2.0.
The fix here is to:
1. Correctly set the channel to `test` when building RC
2. If the channel is test, use the current candidate version as PYTORCH_VERSION.  The value is exposed via …
=> Specific PYTORCH_VERSION when building RC for test channel

.github/workflows/build_conda_linux.yml, .github/workflows/build_conda_macos.yml, .github/workflows/build_conda_windows.yml
Cherry Pick of: https://github.com/pytorch/test-infra/pull/4805
Fixes conda prioritizing latest version rather then required version
=> Add constraint for version to conda build when in test channel

torchci/lib/track.ts, torchci/pages/_app.tsx, torchci/pages/api/track.ts, torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Kind of an experiment to see if this works.  I have a similar PR using vercel to do this https://github.com/pytorch/test-infra/pull/4798 but I have no idea how vercel pricing is done.  (I also don't know how our rockset pricing is done, but I'm hoping to use this as a way to collect data on how much pages get loaded at the very least so we can know).  
I think in my ideal world this would upload to s3 (s3 as backup/storage and rockset pulling from s3 seems to be our general rule, and I think this would be the cheapest but who knows) instead but then I'd have to configure some permissions too and I just want a very quick trial right now.
=> [hud] Tracking experiment

torchci/scripts/backfillJobs.mjs
If this scripts fails for a while, GH API does not have the information about old jobs anymore, 
as it is not possible to gather this information, the best that can be accomplish at this stage is simply assume some status of a job in order to avoid inconsistent database status and consequent bad data captured from it.
so for now the best is to assume the job is cancelled.
=> fixing backfillJobs.mjs script, skipping entries that are too old to be retrieved in GH API

torchci/lib/bot/autoLabelBot.ts, torchci/lib/bot/pytorchBotHandler.ts, torchci/test/autoLabelBot.test.ts
Add ciflow/trunk to reviewed prs
Adds ciflow/trunk to reviewed prs in pytorch/pytorch. Specifically if they are codev / approved.
Specifically deals with the first bit of pytorch/pytorch#115594
Furthermore, we might expand this to non codev prs assuming we don't see a workflow spike.
See: https://github.com/pytorch/test-infra/issues/4811
=> Add ciflow/trunk to reviewed prs

.github/workflows/update-slow-tests.yml
Corresponding PR : https://github.com/pytorch-labs/pytorch-gha-infra/pull/307
Test in prod? (its already broken anyways)
=> [oidc] Update slow test workflow switch to oidc

.github/workflows/update-slow-tests.yml
Fix after https://github.com/pytorch/test-infra/pull/4802
Example: 
https://github.com/pytorch/test-infra/actions/runs/7225953817/job/19690485654
```
+ git push -u origin HEAD:generated-stats
remote: Permission to pytorch/test-infra.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/pytorch/test-infra.git/': The requested URL returned error: 403
```
=> Give slow tests update workflow write perms to repo contents

.github/workflows/pr-dependencies-check.yml
Add workflow call to pr dependencies check
Works to solve https://github.com/pytorch/test-infra/issues/4816
In conjunction with https://github.com/pytorch/pytorch/pull/115944 this pr should make it such that all ghstack prs kick off a job which is a mergability check.
=> Add workflow call to pr dependencies check

.github/scripts/install_torch.sh, .github/workflows/validate-domain-library.yml
This will allow any domain libraries like text to be able to specify the PyTorch version that they want to validate in their validation workflows.  This is the same as what we have on validation workflow on builder.
=> Allow specifing PyTorch version when validating domain libraries

.github/workflows/clang-tidy-linux.yml, .github/workflows/clang-tidy-macos.yml, tools/clang-tidy-checks/setup.sh
As clang-tidy is build automatically, same should be true of clang-format
=> [CI] Automate clang-format building

.github/workflows/pr-dependencies-check.yml
If a pr is not mergable pr-dependencies check will throw an error. This is useful for making the mergeability check blocking.
Testing:
Example of mergable pr: https://github.com/pytorch/test-infra/actions/runs/7227998564
Example of unmergable pr: https://github.com/pytorch/test-infra/actions/runs/7227966131 (note: I removed the debugging text from the FAIL if PR is Not Mergeable step)
=> let pr-dependencies-check throw an error if a pr is not mergable

torchci/lib/jobUtils.ts, torchci/package.json, torchci/test/jobUtils.test.ts, torchci/yarn.lock
Use Jaro-Winkler string matching to compare failure context.  This is a safe way to use fuzzy string matching IMO because comparing context is an additional comparison step added by https://github.com/pytorch/test-infra/pull/4776 when we already have exact matching failures.
This helps fix the wrong classifications when same tests are failing flakily on different shards, for examples:
* https://github.com/pytorch/pytorch/pull/115844
* https://github.com/pytorch/pytorch/pull/114895
The similarity threshold is set high at 0.95, but can be tweaked later.
Try it out locally with the above examples
```
--url "http://localhost:3000/api/drci/drci?prNumber=115844" \
--header "Authorization: TOKEN" \
```
classifies flaky failures correctly:
``` …
```
=> Support fuzzy string matching to compare failure context

tools/scripts/generate_binary_build_matrix.py
Follow up of: https://github.com/pytorch/test-infra/pull/4834
Make sure we have python 3.12 in test env
=> Add python 3.12 to test environment

torchci/components/JobLinks.tsx
After https://github.com/pytorch/test-infra/pull/4668, the failure API endpoint has changed, and the example URL needs to be updated accordingly.
I think I will need to update the links from existing DISABLED issues, but that can be done independently.  Basically, the link changes from `/failure/export%2Ftest_serialize.py%3A%3ATestSerialize%3A%3Atest_canonicalize` to include parameters such as job name and failures `/failure?failureCaptures=%5B"export%2Ftest_serialize.py%3A%3ATestSerialize%3A%3Atest_canonicalize"%5D`
=> Fix obsolete recent example links

.github/workflows/pr-dependencies-check.yml
Changes the wording to improve clarity when analyzing the PR that is already merged.
See the [test run](https://github.com/pytorch/test-infra/actions/runs/7333726730):
=> Improve wording in the dependencies check workflow

tools/scripts/generate_binary_build_matrix.py
Test ARM64:
```
python generate_binary_build_matrix.py  --channel test --package-type libtorch --operating-system macos-arm64
{"include": [{"gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "libtorch_variant": "shared-with-deps", "libtorch_config": "", "devtoolset": "cxx11-abi", "container_image": "pytorch/libtorch-cxx11-builder:cpu", "package_type": "libtorch", "build_name": "libtorch-cpu-shared-with-deps-cxx11-abi", "validation_runner": "macos-m1-12", "installation": "https://download.pytorch.org/libtorch/test/cpu/libtorch-macos-arm64-2.2.0.zip", "channel": "test", "stable_version": "2.2.0"}]}
```
Test x86:
```
python generate_binary_build_matrix.py  --channel test --package-type libtorch --operating-system macos
{"include": [{"gpu_arch_type": "cpu", …
```
=> Binary build matrix. Add macos arm64 libtorch builds. Fix macos x86 filename

torchci/lib/drciUtils.ts
When it fails, the check exits with a generic GHA error `Process completed with exit code 1`, i.e. 
https://github.com/pytorch/pytorch/pull/116942.  Like lint, we don't need flaky classification for this new check.
```
--url "http://localhost:3000/api/drci/drci?prNumber=116942" \
--header "Authorization: TOKEN" \
```
And pr-dependencies-check shows up correctly as a new failure on https://github.com/pytorch/pytorch/pull/116942.
=> Exclude pr-dependencies-check check from Dr.CI flaky classification

tools/scripts/backfill_events.py
Per request from @kiukchung, I wrote a script to backfill all missing `workflow_run` and `workflow_job` events for repo like https://hud.pytorch.org/hud/pytorch/torchx/main which didn't setup our GitHub webhook and now wants to onboard to HUD.
The script copies `workflow_run` and `workflow_job` events and  from GitHub to S3 and DynamoDB, then upload the raw log to S3 and invoke log classifier.
The script looks useful enough for other cases, so creating this PR to keep it around on test-infra.
I'm backfilling https://hud.pytorch.org/hud/pytorch/torchx/main with `python backfill_events.py --repo torchx --event workflow_run --branch main`.  This would take few hours to finish from what I see.
=> Add a script to backfill workflow_run events

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
Learn from the previous attempt https://github.com/pytorch/test-infra/pull/4842:
=> Switch Nova wheel builds to OIDC

torchci/lib/bot/pytorchBotHandler.ts, torchci/test/mergeCommands.test.ts
Limits the scope of the -i flag to specific users. Should ideally only affect a small amount of users.
=> torchci: Limit -i to users who have write permissions

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
Node20 used by v4 is too new for AmazonLinux2 and this causes the action to fail https://github.com/pytorch/vision/actions/runs/7495933674/job/20406996434. v3 should be fine as they are using Node16 https://github.com/aws-actions/configure-aws-credentials
=> Downgrade aws-actions/configure-aws-credentials to v3

.github/workflows/build_wheels_linux.yml, .github/workflows/test_build_wheels_linux_aarch64_without_cuda.yml, .github/workflows/test_build_wheels_linux_with_cuda.yml, .github/workflows/test_build_wheels_linux_without_cuda.yml, .github/workflows/test_build_wheels_m1.yml, .github/workflows/test_build_wheels_macos.yml, .github/workflows/test_build_wheels_windows_with_cuda.yml, .github/workflows/test_build_wheels_windows_without_cuda.yml
This needs to be add to the test workflows after https://github.com/pytorch/test-infra/pull/4865
=> Grant test build wheel workflows with correct permissions

.github/workflows/build_wheels_linux.yml
I know that the repo needs to be vision, but couldn't figure out what the ref condition looks like.  According to `aws-actions/configure-aws-credentials`, we could add this step to debug the OIDC info to use https://github.com/pytorch/vision/actions/runs/7495933674/job/20408831737
=> Temporarily add a debug message for OIDC in Nova workflow

.github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
Learn from the previous attempt
https://github.com/pytorch/test-infra/pull/4842:
=> [RELEASE-ONLY CHANGES] Branch Cut for Release 2.2
