pytorch/test-infra

- .github/workflows/update_slow_tests.yml
Unhides the file and adds json extension
Test plan:
https://github.com/janeyx99/gha-experiments/runs/2298565681?check_suite_focus=true run from my own repo successfully uploaded file
> rename slow tests stats file

- fbossci-aws-lambas/us-east-1/github-status-webhook-handler/lambda_function.py
This should make it much easier for people without admin access to [pytorch/pytorch](https://github.com/pytorch/pytorch) to understand the code for the github-status-webhook-handler lambda.
> Document the events that trigger the lambda

- fbossci-aws-lambas/us-east-1/github-status-webhook-handler/lambda_function.py
Resolves https://github.com/ezyang/pytorch-ci-hud/issues/35.
> Prefix GHA job names with the workflow name

- .github/workflows/deploy_lambda.yml
I created the AWS access key via my IAM user.
> Deploy Lambda via GitHub Actions

- fbossci-aws-lambas/us-east-1/github-status-webhook-handler/lambda_function.py
logging lines were not combined together, this json format makes it easy to correlate events and query in cloudwatch.
> Change to json logging

- hud-scripts/update_pending.py
Script downloads index.json, scans for pending statuses that correspond
to CircleCI builds and checks if on the CircleCI status is any different
> Add update_pending script

- .github/workflows/deploy_checks_lambda.yml
The name was wrong so the runs were failing, fixes #19
> Fix checks lambda deploy

- .github/workflows/update_slow_tests.yml
Relies on https://github.com/pytorch/pytorch/pull/59759 being merged.
> Use the option --ignore-small-diffs so we don't commit unnecessarily

- ci-docker-base/Dockerfile.cilint-clang-tidy
- clang-tidy-checks/setup.sh
* #35 [do not merge] Trigger docker image build on pr for testing
* **#34 Build llvm in release mode; remove llvm-project before applying**
> Build llvm in release mode; remove llvm-project before applying

- ci-docker-base/Dockerfile.cilint-clang-tidy
-11 doesn't exist in the repos used by the Docker image
> Fix omp version

- .github/workflows/update_slow_tests.yml
depends on https://github.com/pytorch/pytorch/pull/60473/
> Update to used rearranged tools files

- clang-tidy-checks/setup.sh
> Revert "Statically link clang-tidy binary"

- clang-tidy-checks/setup.sh
I accidentally squashed and merged a ghstack commit.
See approved PR #47
> Static build of clang-tidy

- aws/ami/windows/README.md
- aws/ami/windows/scripts/Helpers/Reset-UserData.ps1
- aws/ami/windows/scripts/Installers/Install-Choco.ps1
- aws/ami/windows/scripts/Installers/Install-Tools.ps1
- aws/ami/windows/scripts/Installers/Install-VS.ps1
- aws/ami/windows/user-data-scripts/bootstrap-winrm.ps1
- aws/ami/windows/windows.json
> Add scripts to build windows GHA AMIs

- aws/websites/metrics.pytorch.org/files/docker-compose.yml
- aws/websites/metrics.pytorch.org/files/email_template.html
- aws/websites/metrics.pytorch.org/files/grafana-provisioning/notifiers/email.yml
- aws/websites/metrics.pytorch.org/files/grafana.ini
- aws/websites/metrics.pytorch.org/install.yml
> Add email notifications to metrics.pytorch.org

- .github/workflows/update_disabled_tests.yml
Should fix failing workflow runs: https://github.com/pytorch/test-infra/actions/runs/1159669883
> fix typo in disabled-tests.json name

- aws/ami/windows/scripts/Installers/Install-Tools.ps1
- aws/ami/windows/scripts/Installers/Install-VS.ps1
- aws/ami/windows/windows.pkr.hcl
Gets all the changes from our internal repository onto this public
repository specifically for Window SDK issues
Most of this work was originally done by @janeyx99 
Basically just a copy over of https://github.com/fairinternal/pytorch-gha-infra/pull/6
> Fix windows SDK install for public packer scripts

- aws/websites/download.pytorch.org/README.md
- aws/websites/download.pytorch.org/pep503_whl_redirect.js
Downloaded using
`aws cloudfront get-function --name pep503_whl_redirect
pep503_whl_redirect.js`
> Add download.pytorch.org CloudFront function code

- .github/workflows/sync_pytorch_canary.yml
This would run every 15 minutes to sync pytorch-canary with pytorch master.
> Add GHA to sync pytorch-canary

- .github/workflows/sync_pytorch_canary.yml
Should fix failing scheduled jobs
> Fix to use nonbare clone

- .gitignore
- aws/lambda/rds-proxy/lambda_function.py
- aws/lambda/rds-proxy/requirements.txt
This adds some commonly used types `float` and `datetime` to rds proxy
> Add more types to rds-proxy

- .github/workflows/tools-self-hosted-runner-utils.yml
- tools/self-hosted-runner-utils/Makefile
- tools/self-hosted-runner-utils/README.md
- tools/self-hosted-runner-utils/clear_offline_runners.py
- tools/self-hosted-runner-utils/requirements.txt
> tools: Add clear_offline_runners utility

- aws/lambda/github-webhook-rds-sync/requirements.txt
- aws/lambda/github-webhook-rds-sync/utils.py
* Add missing requirements.txt
* Remove unused imports
> Clean up rds sync webhook

- tools/self-hosted-runner-utils/check_runners_state.py
Output now looks like:
```
Self Hosted stats for pytorch/pytorch
238 total runners
165/238 online runners
Number of busy/online runners per label
2/2 linux.16xlarge.nvidia.gpu
27/27 linux.2xlarge
70/70 linux.8xlarge.nvidia.gpu
18/48 windows.4xlarge
13/18 windows.8xlarge.nvidia.gpu
Workflow stats for pytorch/pytorch
50 queued workflows
122 in_progress workflows
```
> tools: Add num busy, queued workflows, in progress

- .gitignore
- aws/lambda/hud-query-proxy/Makefile
- aws/lambda/hud-query-proxy/lambda_function.py
- aws/lambda/hud-query-proxy/requirements.txt
The JSON is often out of date or missing (pop open the network tab to see many 404 errors), this replaces it with a direct DB query.
> Add lambda to replace status JSON in the HUD

- .github/scripts/generate_ci_workflows.py
- .github/workflows/generated-github-status-sync.yml
- aws/lambda/github-status-sync/lambda_function.py
This is a follow up to auto-deploy #135
> Add GitHub Action to deploy github-status-sync

- aws/lambda/github-status-sync/requirements.txt
> Upgrade aiohttp to 3.7.4

- aws/websites/metrics.pytorch.org/update_dashboards.py
This PR fixes the https://github.com/pytorch/test-infra/issues/146
> Add support for deletes in update_dashboards.py

- aws/websites/metrics.pytorch.org/files/docker-compose.yml
This commit trying to remedy Grafana vulnerabilities
> Upgrade to Grafana 8.3.3

- aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/github.yml
- aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/metrics.yml
This fixes issue with accessing DB for Grafana 8.2.3 and higher
> Fix for password tp Db inside secureJsonData

- .github/workflows/update_disabled_tests.yml
https://github.com/pytorch/test-infra/runs/4588342443?check_suite_focus=true
> Use new commit for copy-to-repo action to fix existing Docker issue 

- torchci/lib/bot/index.ts
oops, I included the handler file without actually adding to the trigger
> Actually run circleci workflow handler

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Building windows AMIs cudnn update for CUDA 11.5
> Building windows AMIs cudnn update for CUDA 11.5

- .github/workflows/update_disabled_tests.yml
- .github/workflows/update_slow_tests.yml
First step for https://github.com/pytorch/test-infra/issues/175
> Put slow and disabled tests JSON in slow-disabled-tests branch and main.

- aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/json-rockset.yml
- aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/rockset.yml
- aws/websites/metrics.pytorch.org/files/grafana.ini
> Rockset Itegration

- aws/websites/metrics.pytorch.org/install.yml
Install rockset data source plugins during setup
> Install rockset data source plugins during setup

- aws/websites/metrics.pytorch.org/install.yml
install rockset data source plugins
> install rockset data source plugins

- torchci/lib/types.ts
- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
This is a style fix across the disable bot workflow
> Use camel case for variables

- torchci/test/mergeBot.test.ts
Test that default comment is no op and `@pytorchbot merge this` triggers
dispatch
> [Probot] Add mergebot test

- torchci/lib/bot/mergeBot.ts
Move common actions into `dispatchEvent` and `reactOnComment` closures
> Refactor mergeBot

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Based on @rohan-varma's request!
> Don't add triaged as bots shouldn't do that anyway

- torchci/lib/bot/ciflowPushTrigger.ts
* __->__ #261
- Don't post the comment on `ciflow/binaries`
- Properly add newlines to bot comment
> fixes to ciflow bot

- torchci/test/disableFlakyBot.test.ts
Should land after https://github.com/pytorch/pytorch/pull/74555
> Remove irrelevant code following triage review updates

- torchci/components/GroupHudTableHeaders.tsx
- torchci/lib/types.ts
- torchci/lib/useHudData.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/rockset/commons/__sql/original_pr_hud_query.sql
- torchci/rockset/prodVersions.json
> [torchci] Add authors to HUD View

- torchci/components/LogViewer.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/pages/settings/useGroupingPreference.tsx
- torchci/yarn.lock
This persists the use grouping preference to local storage.
**Testing**
Check that it works:
https://user-images.githubusercontent.com/34172846/160156794-33977a32-e4aa-4fed-bff5-e853fefe340c.mov
> [torchci] Add group preference

- torchci/components/GroupHudTableHeaders.tsx
- torchci/components/hud.module.css
We are missing a column which messes up the grouping. Also we are resizing some of the numbers to be multiples of 4's.
> [torchci] Add missing Author Column and resize Cols

- torchci/components/minihud.module.css
- torchci/pages/minihud.tsx
Addresses #277 
Moved the links down to a new line since this top one is getting kind of crowded
> [torchci] added author

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
> Cuda 11.6 windows AMI

- torchci/components/metrics/panels/ScalarPanel.tsx
- torchci/components/metrics/panels/TablePanel.tsx
- torchci/pages/metrics.tsx
- torchci/yarn.lock
A refactor that pulls out some common panels so we can reuse them later.
- ScalarPanel: show a big value
- TablePanel: show a table
> [metrics] refactor common panel components

- torchci/package.json
- torchci/pages/metrics.tsx
- torchci/yarn.lock
- Add a dropdown for the most common time ranges
- You can still set a custom time range if you select it from the dropdown
- Previously the start and stop time were fixed, even after data refreshes. Now the stop time is always the current time, so that we show fresh data
> [hud/metrics] improvements to time picking

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
https://github.com/pytorch/pytorch/pull/76262 has more details
gatekeeping to only me to test, will roll out later
> rebase via comment

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
Enforce that people will put a revert reason when reverting through GH1.
note: there are lots of lint changes here cuz I autoformatted with vs code :/
> Enforce a reason is provided for revert command

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
allow more people to use rebase via comment, still testing though
> rebase via comment - allow more ppl

- torchci/lib/bot/mergeBot.ts
add edward to rebase via comment allow list
> rebase via comment - add edward to allow list

- torchci/lib/bot/mergeBot.ts
add david berard to rebase via comment allow list
> rebase via comment - add david to allow list

- torchci/lib/fetchS3Links.ts
fixes #312
encode special characters in url
> encode url components for artifacts

- torchci/lib/bot/ciflowBot.ts
- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/lib/bot/labelBot.ts
- torchci/lib/bot/mergeBot.ts
- torchci/lib/bot/triggerCircleCIWorkflows.ts
- torchci/test/common.ts
- torchci/test/disableFlakyBot.test.ts
- torchci/test/mergeBot.test.ts
> Format bots with typescript formatter

- torchci/lib/bot/mergeBot.ts
allow anyone to rebase their own PRs
> rebase via comment - allow people to rebase their own PRs

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
> fix punctuation breaks regex

- .github/workflows/update-queue-times.yml
- torchci/scripts/updateQueueTimes.mjs
See the comment in the file for details. This will give us historical
queueing data, which is nice.
> Add workflow to update queue times

- torchci/lib/fetchPR.ts
Check that it works on /pr/77343
> Paginate prs

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
see title. There was some confusion in https://github.com/pytorch/pytorch/pull/77719#issuecomment-1129565710 so we are updating it.
> Update Error Messages on Reverting

- torchci/rockset/metrics/__sql/job_duration_avg.sql
- torchci/rockset/metrics/__sql/tts_avg.sql
- torchci/rockset/prodVersions.json
Failing shouldn't improve our metrics :)
> [metrics] only measure successful jobs for TTS/duration

- torchci/components/CommitStatus.tsx
- torchci/components/FilteredJobList.tsx
> Add Job Links to PR view 

- torchci/lib/bot/mergeBot.ts
Added all the valid classifications so people don't have to reference the wiki.
> update classification message

- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
as in title, let everyone whos a pytorch org member to use rebase bot
> rebase via comment - allow pytorch org members to rebase

- torchci/components/CommitStatus.tsx
- torchci/package.json
- torchci/yarn.lock
By using `react-linkinfy-it` component
> Make links in commit message clickable

- torchci/components/JobAnnotationToggle.tsx
- torchci/lib/bot/webhookToDynamo.ts
- torchci/lib/dynamo.ts
- torchci/lib/types.ts
- torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts
- torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/rockset/commons/__sql/hud_query.sql
- torchci/rockset/prodVersions.json
Allows people to manually mark jobs as instances of infra flakiness (as
opposed to flaky tests). This should help us triage instances of
infra flakiness.
> [hud] add a button to mark whether a job was flaky in infra

- torchci/components/TimeUtils.tsx
- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/metrics.tsx
- torchci/rockset/metrics/__sql/queue_times_historical.sql
- torchci/rockset/metrics/__sql/workflow_load.sql
- torchci/rockset/metrics/queue_times_historical.lambda.json
- torchci/rockset/metrics/workflow_load.lambda.json
- torchci/rockset/prodVersions.json
Add these two panels, as well as a generic TimeSeriesPanel component we
can re-use for future things.
> [metrics] Add historical job queue and workflow load

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
pr in pytorch: https://github.com/pytorch/pytorch/pull/78772
> rebase via comment - rebase to any branch

- torchci/lib/bot/mergeBot.ts
To avoid issues like https://github.com/pytorch/pytorch/pull/78846#issuecomment-1146363818
> mergebot: Add pytorchmergebot as an ignored user

- torchci/pages/api/classifier/rules.ts
Consistent errors should have higher pri
> Lower flaky test classification priority

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Also adds a test case to ensure the URL is good
> [flaky-test] Redirect to flaky test view for disable bot created issues

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/mergeBot.ts
- torchci/test/mergeBot.test.ts
Adds some new args for land checks. Haven't hooked it up to pytorch/pytorch yet. will test it on canary.
> add some args for landtime

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/metrics.tsx
- torchci/pages/tts.tsx
- torchci/rockset/metrics/__sql/tts_duration_historical.sql
- torchci/rockset/metrics/tts_duration_historical.lambda.json
- torchci/rockset/prodVersions.json
hud.pytorch.org/tts
should look like this 
problems:
* not sure why its only showing ~3 months of data when i tell it get 6 months of data
* height, width, and some other things are hardcoded
> [hud] tts and job duration graphs 

- torchci/lib/fetchFailureSamples.ts
- torchci/pages/api/failure/[capture].ts
- torchci/pages/api/flaky-tests/flakytest.ts
- torchci/pages/flakytest.tsx
Adds a log viewer for flaky test history view!
https://torchci-pqabz1gie-torchci.vercel.app/flakytest?name=test_forward_overlap
> [flaky-test] Add log view flaky test

- torchci/lib/bot/drciBot.ts
- torchci/test/drciBot.test.ts
Relates to [#65485](https://github.com/pytorch/pytorch/issues/65485)
**Overview:** Starting the implementation of Dr. CI comment by first adding a blank comment to PRs in `pytorch/pytorch` only if the owner of the PR is swang392. 
**Test Plan:** Wrote two test cases to check if (1) the bot adds a comment when the owner of the PR is swang392, and (2) that no comment occurs otherwise.
> made Dr. CI bot that adds blank comment to swang392's PRs

- torchci/lib/bot/drciBot.ts
- torchci/lib/bot/index.ts
**Overview**: Added Dr. CI bot to `index.ts`, made modifications to drciBot to add more logging messages
**Test Plan**: ensured that previously written test cases for Dr Ci Bot were still working.
> Added more debugging messages to Dr. CI bot & enable Dr. CI bot

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
https://github.com/pytorch/pytorch/issues/80409 was failing to parse.
> [disable bot] Don't ban nested suites

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
CUDA 11.7 Windows AMI update
Testing: https://github.com/pytorch/pytorch-canary/runs/7354416255?check_suite_focus=true
> Migrating to CUDA 11.7

- torchci/lib/bot/webhookToDynamo.ts
This will enable us to track all commands made to pytorchmergebot, letting us more easily track reverts, force commits, etc.
We'll separately require more parameters to be sent to pytorchmergebot for those commands to get more details logged
> Export Issue Comments to Rockset

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/pytorchBot.ts
- torchci/test/mergeCommands.test.ts
This reverts commit 2a469f9d6842b311779751fb60991f8d68d4a5bc.
> Revert "[mergebot] Add a command for bot approval (#455)"

- torchci/lib/bot/acceptBot.ts
- torchci/lib/bot/index.ts
- torchci/lib/bot/pytorchBot.ts
- torchci/test/acceptBot.test.ts
- torchci/test/common.ts
- torchci/test/mergeCommands.test.ts
This adds a feature suggested in https://github.com/pytorch/test-infra/issues/448
I also thought of a few other ideas/alternatives in here: https://docs.google.com/document/d/1VON2X05Uz4PSfq-F1uq51bDb0IA_9ljLSILu5DeJw8w/edit#heading=h.bgd4fakia768
> [mergebot] Add Accept2Ship and Accept2Run

- torchci/lib/bot/acceptBot.ts
- torchci/test/acceptBot.test.ts
see title. 
Checked in rockset that it's actually lowercase
> [mergebot] fix up acceptbot

- torchci/lib/bot/acceptBot.ts
- torchci/test/acceptBot.test.ts
TSIA. ciflow/all doesn't exist anymore so changing it to trunk and releasing this feature to every repo. 
Test Plan:
Tested it on pytorch canary
https://github.com/pytorch/pytorch-canary/pull/131
https://github.com/pytorch/pytorch-canary/pull/130
> [mergebot] update label and remove gating check for accept2run/accept2ship

- README.md
Adding instructions for how to update HUD based on the walkthrough @zengk95 gave me
cc: @zengk95
> Explain how to make changes to HUD

- torchci/components/minihud.module.css
- torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Better alert for tts on the minihud
* makes background into stripes if theres a change
* add a checkbox for showing the duration info right on the commit
> minihud tts - better alert

- torchci/lib/bot/cliParser.ts
Realized we never specify what they are, which is not great.
> [bot] Improve messaging for land checks

- torchci/rockset/commons/__sql/commit_jobs_query.sql
- torchci/rockset/prodVersions.json
> fix quotes in sql query for circleci job

- .github/actionlint.yaml
- .github/workflows/build_wheels_m1.yml
- .github/workflows/lint_actions.yml
- .github/workflows/test_build_wheels_m1.yml
- .shellcheckrc
Uses pytorch_pkg_helpers to fill out relevant environment variables.
Part of the project NOVA tooling effort.
> ci: Add POC workflow to build m1 wheels

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Fixes https://github.com/pytorch/test-infra/issues/454
Culprit was that we now get the test file from the XML which has the .py
> Fix flaky triage portion

- torchci/lib/bot/ciflowPushTrigger.ts
Dependent on https://github.com/pytorch/pytorch/pull/83296
> Add `ciflow/mps` to list of valid labels

- .github/scripts/update_disabled_tests.py
Issue disabling workflow has been consistently failing https://github.com/pytorch/test-infra/actions/workflows/update_disabled_tests.yml?page=2
> Use == not is for value equality :facepalm:

- torchci/log_classifier/backfill.py
- torchci/rockset/commons/__sql/unclassified.sql
- torchci/rockset/commons/unclassified.lambda.json
- torchci/rockset/prodVersions.json
Improve backfill by:
- Actually using the n option
- Adding an option for inputting specific ids
Depend on #526
> Make backfill do what it says

- .github/workflows/pytorch-pkg-helpers.yml
- tools/pkg-helpers/poetry.lock
- tools/pkg-helpers/pyproject.toml
> Add support for python 3.7, add ci workflow

- torchci/README.md
> [torchci] Update instructions for modifying settings

- torchci/pages/api/hud/[repoOwner]/[repoName]/[branch]/[page].ts
See comments in the code for info.
> [hud] use stale-while-revalidate in hud API endpoint

- torchci/components/NavBar.tsx
> [hud] add tts to nav bar

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_wheels_m1.yml
- .github/workflows/lint_actions.yml
- .github/workflows/test_build_wheels_m1.yml
> ci: Add setup action, move test to matrix

- torchci/lib/bot/autoLabelBot.ts
This should not change any current behavior with the bot. This is intended to set up the code for allowing other labeling, e.g., with files changed and other labels.
e.g., this change will set the infra up for https://github.com/pytorch/test-infra/pull/564
> Refactor code to make future changes easier

- torchci/components/NavBar.tsx
The positioning on the Login is a bit off after rebasing. Put it to the last thing on the navbar.
> [torchci] fix positioning on login

- .github/workflows/build_wheels_m1.yml
- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/test_build_wheels_m1.yml
- tools/scripts/generate_binary_build_matrix.py
> ci: Add workflow to generate binary build matrix

- torchci/pages/api/flaky-tests/disable.ts
- torchci/pages/flakytest.tsx
> flaky test bot - fix typo

- torchci/components/NavBar.tsx
this has been irking me slightly for a bit
> Upper case the T in PyTorch in the navbar

- tools/scripts/generate_binary_build_matrix.py
Adding worker types to wheels and libtorch packages
> Adding worker types to wheels and libtorch packages

- .github/workflows/build_conda_m1.yml
- .github/workflows/test_build_conda_m1.yml
> ci: Add workflow to build m1 conda binaries

- tools/scripts/generate_binary_build_matrix.py
Adding channel to generate binary matrix, fix libtorch calling:
```
python3 generate_binary_build_matrix.py --package-type wheel --operating-system linux
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_7-cpu", "validation_runner": "ubuntu-20.04", "channel": "nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "10.2", "desired_cuda": "cu102", "container_image": "pytorch/manylinux-builder:cuda10.2", "package_type": "manywheel", "build_name": "manywheel-py3_7-cuda10_2", "validation_runner": "ubuntu-20.04-m60", "channel": "nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", …
```
> Adding channel to generate binary matrix, fix libtorch calling

- .github/workflows/generate_binary_build_matrix.yml
- tools/scripts/generate_binary_build_matrix.py
Adding channel as optional parameter to generate binary build matrix GHA
> Adding channel as optional parameter to generate binary build matrix GHA

- tools/scripts/generate_binary_build_matrix.py
Fix output of channel=all - make sure we output single list
> Fix output of channel=all - make sure we output single list

- torchci/lib/bot/rolloutUtils.ts
> [land check] Add Distributed to Rollout

- torchci/README.md
> [Docs] Add a blurb about how Alerts work

- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/utils.ts
- torchci/test/autoLabelBot.test.ts
> [autolabel] Limit release notes categorization to pytorch/pytorch

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Restrict force merges to users who have write access
> Limit force merges to users with write access

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_m1.yml
- .github/workflows/build_wheels_m1.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_wheels_m1.yml
Adds the ability to run a pre-script and post-script to our apple
silicon workflows
> ci: Add ability to run pre/post script

- tools/scripts/generate_binary_build_matrix.py
Fix libtorch and pip cpu install path in binary matrix
> Fix libtorch and pip cpu install path in binary matrix

- torchci/lib/bot/rolloutUtils.ts
> [land checks] Add Quansight to Rollout

- torchci/pages/kpis.tsx
- torchci/rockset/prodVersions.json
- torchci/rockset/pytorch_dev_infra_kpis/__sql/number_of_force_pushes_historical.sql
- torchci/rockset/pytorch_dev_infra_kpis/number_of_force_pushes_historical.lambda.json
Goes with https://github.com/pytorch/test-infra/pull/629 as a graph showing weekly trend in KPIs page.  The historical data looks flat because we only start tracking this since July-ish
> Add number of force merges graph

- tools/scripts/generate_binary_build_matrix.py
Adding pre for wheel nightly install instructions in binary matrix
> Adding pre for wheel nightly install instructions in binary matrix

- tools/scripts/generate_binary_build_matrix.py
Fix conda package names for installation instructions
> Fix conda package names for installation instructions

- torchci/components/CommitStatus.tsx
- torchci/components/WorkflowBox.tsx
So the anchor will be `encodeURIComponent(workflowName.toLowerCase())`, for example http://localhost:3000/pr/84324#pull and http://localhost:3000/pytorch/pytorch/commit/65f98eb47dbf75335d08f7676835a5e1f1fc3574#pull
This is to address the discussion thread in https://github.com/pytorch/pytorch/pull/84283#discussion_r959794563
> Add HUD workflow anchors

- torchci/lib/bot/pytorchBot.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/bot/pytorchbotLogger.ts
TSIA. Addressing https://github.com/pytorch/pytorch/issues/84060
> [pytorchbot] Add logging to PT Bot

- torchci/components/WorkflowBox.tsx
- torchci/pages/kpis.tsx
i think the artifacts section is too long
also fixed a chart title
> hud - hide artifacts

- torchci/lib/bot/pytorchBotHandler.ts
Forgot to add await to some of the logging.
> [ptbot][ez] Add Await

- .github/actions/setup-miniconda/action.yml
This reverts commit cba0f85a9ca4e2218d8b141c36be181031328136.
> Revert "Add conda cache for macOS (#655)"

- torchci/lib/bot/drciBot.ts
- torchci/test/drciBot.test.ts
Fix https://github.com/pytorch/test-infra/issues/668
> Fix drci spurious comment to old PRs

- torchci/lib/bot/drciBot.ts
- torchci/lib/bot/rolloutUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciBot.test.ts
The new Dr. CI bot is graduating and rolling out to the whole world.
Once this PR is merged, I'll disable the internal Dr. CI from [this page](https://www.internalfb.com/intern/opensource/github/repo/167825833786582/dr_ci)
> Rollout Dr. CI bot globally

- .github/scripts/update_disabled_tests.py
follow up for https://github.com/pytorch/test-infra/pull/545
i will delete the file on the branch if this gets merged
> get rid of not condensed version of disabled test list

- .github/workflows/update_disabled_tests.yml
- stats/README.md
fix for https://github.com/pytorch/test-infra/pull/669
> get rid of mentions of disabled-tests.json

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/kpis.tsx
- torchci/pages/metrics.tsx
- torchci/rockset/metrics/__sql/num_tests_run.sql
- torchci/rockset/metrics/num_tests_run.lambda.json
- torchci/rockset/prodVersions.json
add graph for number of tests run
deselecting the other workflows gives more detailed information
> [hud] graph for num tests run

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
Adding some easy heuristics for topic: not user facing
(This took less than my 10% of DevX a week! I promise!)
> Added preliminary heuristics for topic: not user facing

- .github/scale-config.yml
Add canary runners to be used in testing of new AMI
> Add canary runners to be used in testing of new AMI

- tools/scripts/generate_binary_build_matrix.py
Removing cuda 11.3 since no longer applicable
> Removing cuda 11.3 since no longer applicable

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
rebase and merge with one command (pytorchbot merge -r)
pytorch pr: https://github.com/pytorch/pytorch/pull/85028
> [mergebot] rebase + merge

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
Similar to https://github.com/pytorch/test-infra/pull/689, but uploading wheels for both linux and mac binaries.
> [Nova] Added wheels uploads to pytorch.org S3 bucket

- torchci/lib/bot/cliParser.ts
perhaps this is unnecessary, but it cant hurt
> [mergebot] slight clarification to help message

- torchci/lib/bot/pytorchbotLogger.ts
- torchci/lib/dynamo.ts
Unless we set these config values
> Dynamo chokes on null values

- torchci/lib/bot/rolloutUtils.ts
- torchci/test/mergeCommands.test.ts
Don't be case sensitive for the land checks rollout group
> GH usernames can be any case

- terraform-aws-github-runner/modules/runners/templates/user-data.sh
> Add debug logging to user data script

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
as in title, so we are consistent with the normal rebase behavior
> [mergebot] rebase and merge defaults to viable/strict

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/test_build_conda_macos.yml
- tools/pkg-helpers/pyproject.toml
- tools/pkg-helpers/pytorch_pkg_helpers/__main__.py
- tools/pkg-helpers/pytorch_pkg_helpers/macos.py
Moved logic regarding env variables from workflow to pkg helper.
> Moved logic for env variables to pkg helper

- torchci/lib/bot/acceptBot.ts
- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/botUtils.ts
- torchci/lib/bot/pytorchBotHandler.ts
* #804
* __->__ #803
Also use `addLabel` from autoLabelBot and acceptBot
> [BE] Move `hasWritePermissions` to botUtils

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
> Add `ciflow/trunk` label for reviewed PRs

- .github/workflows/build_conda_macos.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_build_wheels_macos.yml
Apply the latest changes to Mac workflows to make it production ready.
> Updated MacOS

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/test_build_conda_linux_with_cuda.yml
- .github/workflows/test_build_conda_linux_without_cuda.yml
Brings the changes we've made to the linux wheels workflow "in-prod" to the linux conda workflow.
> [Nova] Make Linux Conda prod-ready like Linux Wheels

- .github/workflows/build_wheels_linux.yml
- .github/workflows/test_build_conda_linux_with_cuda.yml
- .github/workflows/test_build_wheels_linux_with_cuda.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
Same Smoke Tests as CircleCI. Align USE_FFMPEG usage across cirlce/nova. Setting LD_LIBRARY_FLAGS to find locally installed ffmpeg to dynamically link to during smoke tests.
> Use custom smoke testing script

- tools/scripts/generate_binary_build_matrix.py
Remove cuda 10.2 from nightlies
> Remove cuda 10.2 from nightlies

- torchci/components/JobLinks.tsx
fixes https://github.com/pytorch/test-infra/issues/788
> [hud] add disable button for pytest failures

- torchci/components/CommitStatus.tsx
- torchci/components/FilteredJobList.tsx
- torchci/components/GroupJobConclusion.tsx
- torchci/components/JobAnnotationToggle.tsx
- torchci/components/JobConclusion.module.css
- torchci/components/JobConclusion.tsx
- torchci/components/minihud.module.css
- torchci/lib/JobClassifierUtil.ts
- torchci/pages/api/auth/[...nextauth].js
- torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts
- torchci/pages/api/job_annotation/[repoOwner]/[repoName]/annotations/[jobIds].ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
TSIA
See https://github.com/pytorch/test-infra/pull/861 for all the context.
> [hud] Change colors on X's and Rows when classified

- torchci/components/JobAnnotationToggle.tsx
- torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts
We have a [new feature](https://github.com/pytorch/test-infra/pull/861) to label job status. Making it more accessible to the wider team
> Add more of the team and tweak job annotations

- .github/workflows/build_conda_macos.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
Added a smoke tests step for the conda build MacOS workflow.
> Added a smoke tests step for the conda build workflow.

- torchci/lib/bot/retryBot.ts
- torchci/test/retryBot.test.ts
* lint is capitalized
* if there are more pages of jobs, get those too
> fix for retry bot

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
corresponding pr in pytorch https://github.com/pytorch/pytorch/pull/86701
> [flakybot] triage dynamo without linux

- tools/scripts/generate_binary_build_matrix.py
Fix issue with same cuda version being used in nightly, test and release channel
> Fix issue with same cuda version being used in nightly, test and release channel

- .github/workflows/test_linux_job.yml
Tests the functionality for upload / download artifact for `linux_job.yml` to ensure we don't break backwards compat
> ci: Add test for uploading / downloading of artifacts

- tools/scripts/generate_binary_build_matrix.py
> Add python 3.11 builds

- torchci/rockset/commons/__sql/flaky_tests.sql
- torchci/rockset/prodVersions.json
honestly not a great idea, but there are so many flaky issues being created and its quite spammy
> [flakybot] require at least 2 flaky runs before marking as flaky

- .github/workflows/build_wheels_linux.yml
Ignore python 3.11 build failures - these will be removed soon
> [Nova] Build clean for Linux Before building wheel

- .github/workflows/generate_binary_build_matrix.yml
Adding with-py311 option to action
> Adding with-py311 option to action

- torchci/lib/bot/autoCcBot.ts
- torchci/package.json
- torchci/yarn.lock
Record repo slug + minor refactors
> More logging to autoCCBot

- .github/workflows/linux_job.yml
- .github/workflows/test_linux_job.yml
> ci: Add test for linux_job with matrix

- .github/actions/setup-ssh/action.yml
- .github/workflows/linux_job.yml
- .github/workflows/windows_job.yml
> ci: Explicitly pass github.token for generic jobs

- .github/workflows/build_conda_macos.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
Set env variables (USE_FFMPEG and USE_OPENMP) depends on the domain library.
> Set env variables depends on the domain library

- tools/scripts/generate_binary_build_matrix.py
Adjust release matrix for 1.13 release
> Adjust release matrix for 1.13 release

- torchci/lib/drciUtils.ts
- torchci/lib/fetchRecentWorkflows.ts
Should help with https://github.com/pytorch/pytorch/issues/87868
30 minutes is probably overkill, but I think thats ok
> [drci] Change to query from past 15 min to 30 min

- torchci/components/GroupJobConclusion.tsx
- torchci/components/JobConclusion.module.css
- torchci/components/JobConclusion.tsx
- torchci/lib/JobClassifierUtil.ts
- torchci/lib/fetchHud.ts
- torchci/lib/types.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
F instead of O when a job failed a previous run 
It is still hard to notice, but it's better than not having it at all
> [hud] show f for flaky

- torchci/components/GroupJobConclusion.tsx
- torchci/lib/JobClassifierUtil.ts
- torchci/lib/types.ts
- torchci/lib/useHudData.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Add mem_leak_check as a persistent group in the hud
Other changes:
* use more maps/dictionaries
> add persistent grouping

- .gitignore
* #1025
* #1018
* #1024
* #1023
* #1022
* #1021
* __->__ #1020
> simplify pattern to include requirements.txt files in Git

- .github/workflows/lint.yml
* #1025
* #1018
* #1024
* #1023
* __->__ #1022
* #1021
* #1020
This includes any change to the mypy version itself.
> run mypy if any requirements files change

- torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Similar change as https://github.com/pytorch/test-infra/pull/1015 but
for minihud
> [hud] fix layout shift in minihud

- .gitignore
Reverts pytorch/test-infra#1020
> Revert "simplify pattern to include requirements.txt files in Git"

- .github/actions/setup-linux/action.yml
- .github/workflows/test_linux_job.yml
Includes the bump to 515.76 and the latest changes from @huydhn 
We should probably eventually consolidate this as well
> ci: Update setup-linux to include latest driver install

- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/test_linux_job.yml
- .github/workflows/test_macos_job.yml
Adding custom job name to workflows
Same as https://github.com/pytorch/test-infra/pull/1050
> Adding name parameter macos and linux ci workers

- tools/scripts/generate_binary_build_matrix.py
Adding ability to get all the packages at once for validation workflows
Test:
```
python generate_binary_build_matrix.py --package-type all --channel nightly
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_7-cpu", "validation_runner": "ubuntu-20.04", "installation": "pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu", "installation_pypi": "", "channel": "nightly"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", "desired_cuda": "cu116", "container_image": "pytorch/manylinux-builder:cuda11.6", "package_type": "manywheel", …
```
> Adding all option to get all the packages at once

- .github/workflows/stronghold.yml
- tools/stronghold/requirements.txt
This will allow us to eventually make the checks more stringent.
> run customized mypy for stronghold

- .github/workflows/stronghold.yml
- tools/stronghold/pyproject.toml
- tools/stronghold/requirements.txt
- tools/stronghold/tests/api/test_compatibility.py
- run mypy with --strict
- fix mypy violations by adding missing types to parameters
- fix mispelled kwargs
> run mypy with --strict

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/drciBot.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/drciUtils.ts
- torchci/test/drciBot.test.ts
Adds a `@pytorchbot drci` command which triggers a manual update to the Dr. CI comment.
This will help mitigate times when Dr. CI is stuck displaying stale information
Fixes https://github.com/pytorch/pytorch/issues/88231
> Add way to refresh Dr. CI results from HUD

- torchci/lib/JobClassifierUtil.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
The new set of jobs will show up after https://github.com/pytorch/pytorch/pull/88646 is merged.  Thank @clee2000 for making it so easy to add a new persistent group to HUD
> Add a new persistent group for rerunning disabled tests

- tools/scripts/generate_binary_build_matrix.py
Following improvements/modifications are done:
Related to this PR:
https://github.com/pytorch/pytorch/pull/88997
1. Adopt to use passs arguments via main so we can call the script in this way:
```
for osys in OperatingSystem:
release_matrix[osys] = {}
for package in PackageType:
command=["--channel", CHANNEL, "--operating-system", osys.value,  "--package-type", package.value]
if osys == OperatingSystem.MACOS_ARM64 and package == PackageType.LIBTORCH:
continue
elif osys == OperatingSystem.LINUX and package == PackageType.WHEEL:
command+=["--with-py311", ENABLE, "--with-pypi-cudnn", ENABLE]
f = io.StringIO()
with redirect_stdout(f):
generate_binary_build_matrix.main(command)
release_matrix[osys][package] = json.loads(f.getvalue())["include"]
```
2. Pass with-pypi-cudnn and with-py311 only …
> Adopt generate binary build matrix to call via main

- .github/scale-config.yml
Let's see if we can run our CPU tests on AMD runners
> Add linux.2xlarge.amd runner time

- .github/workflows/lint.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1126).
* #1125
* #1124
* __->__ #1126
run the lint job if mypy.ini is modified
Summary:
This controls the mypy settings so it very well ought to run if
changed.
> run the lint job if mypy.ini is modified

- tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1127).
* #1128
* __->__ #1127
add program to run the API compatibility check
Summary:
Test Plan:
> add program to run the API compatibility check

- tools/stronghold/bin/.gitignore
- tools/stronghold/bin/build-check-api-compatibility
- tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1128).
* __->__ #1128
* #1127
add program to build the check-api-compatibility program
> add program to build the check-api-compatibility program

- .github/actions/setup-ssh/index.js
- setup-ssh/src/add-github-ssh-key.ts
See https://nodejs.org/api/deprecations.html#DEP0147
> [setup-ssh][BE] Get rid of deprecated `rmdirSync`

- tools/stronghold/bin/analyze-history
- tools/stronghold/src/api/compatibility.py
- tools/stronghold/src/api/git.py
- tools/stronghold/tests/api/test_git.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1132).
* #1143
* #1142
* #1141
* #1140
* #1139
* #1138
* __->__ #1132
replace check_commit with check_range
Summary:
GitHub pull requests may consist of multiple commits.
Test Plan:
Rely on CI.
> replace check_commit with check_range

- tools/stronghold/src/api/git.py
- tools/stronghold/tests/api/test_git.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1138).
* #1143
* #1142
* #1141
* #1140
* #1139
* __->__ #1138
eliminate git.Repository.get_commit_info
> eliminate git.Repository.get_commit_info

- .github/workflows/stronghold.yml
- tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1141).
* #1143
* #1142
* __->__ #1141
* #1140
run the API compatibility check on the stronghold project
Test Plan:
Verify this works with an illegal change.
> run the API compatibility check on the stronghold project

- tools/scripts/generate_binary_build_matrix.py
Fix if statement for libtorch nightly linux and windows installs
> Fix if statement for libtorch nightly linux and windows installs

- torchci/pages/flakyjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
No idea why the rest of the pages don't face this issue, but this should help with this one
> Stop flakyjobs page from refreshing all the time

- tools/scripts/generate_binary_build_matrix.py
Fix typo from previous PR:
https://github.com/pytorch/test-infra/pull/1181
> Fix windows nightly libtorch

- tools/scripts/generate_binary_build_matrix.py
Fix ident in if statement made by previous commit (typo)
> Fix ident in if statement made by previous commit (typo)

- torchci/lib/JobClassifierUtil.ts
corresponds to https://github.com/pytorch/pytorch/pull/89504
> Fix mem leak check group 

- .github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1163).
* #1164
* __->__ #1163
use a smaller image for the api compatibility check
Summary:
This reduces the latency of CI.
Test Plan: Verify in CI.
> use a smaller image for the api compatibility check

- .github/workflows/stronghold.yml
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1159).
* __->__ #1159
write to GITHUB_STEP_SUMMARY in stronghold commands
Summary:
Test Plan: Manually inspect summary page.
> write to GITHUB_STEP_SUMMARY in stronghold commands

- .github/actions/setup-nvidia/action.yml
Example action: https://github.com/pytorch/pytorch/actions/runs/3578895594/jobs/6019943524#step:6:542
> Extend setup-nvidia action to support gcp ubuntu20.04 instance

- .github/workflows/update_disabled_tests.yml
test: https://github.com/pytorch/test-infra/actions/runs/3594864471/jobs/6053660086
> Fix disabled tests workflow

- tools/stronghold/src/api/__init__.py
- tools/stronghold/src/api/ast.py
- tools/stronghold/src/api/compatibility.py
- tools/stronghold/tests/api/test_ast.py
- tools/stronghold/tests/api/test_compatibility.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1209).
* #1143
* #1142
* #1211
* #1210
* __->__ #1209
* #1208
track the line number where violations occur
Summary:
We'll be able to use this to render them in the GitHub UI.
> track the line number where violations occur

- tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1211).
* #1143
* #1142
* __->__ #1211
render violations in the GitHub UI
Summary:
This ties everything together.
Test Plan: Visually inspect with test PRs.
> render violations in the GitHub UI

- .github/workflows/build_conda_macos.yml
- .github/workflows/build_wheels_macos.yml
Mimic https://github.com/pytorch/test-infra/pull/1205 but for mac build workflows
> [Nova] Try to fix flaky checkout issues in binary builds

- torchci/rockset/commons/__sql/reverted_prs_with_reason.sql
- torchci/rockset/prodVersions.json
- torchci/scripts/reverts.py
Long version is pretty much the same, also if you want to make edits it gets inconvenient 
* add num reverts 
* make sql query slightly more accurate
> Remove short revert printer and small bug fix

- torchci/lib/fetchHud.ts
- torchci/rockset/commons/__sql/flaky_workflows_jobs.sql
- torchci/rockset/prodVersions.json
makes the flaky jobs query used for https://hud.pytorch.org/flakyjobs/pytorch/pytorch/master more broad
> Fix for flaky marker on hud and change flaky jobs query

- tools/scripts/generate_binary_build_matrix.py
We need to use same approach for ROCM as for CUDA.
When new versions of ROCM get introduced, they introduced first in Nightly.
Hence we need to specify one set of versions for nightly and one set of versions for release
Test
```
python generate_binary_build_matrix.py 
{"include": [{"python_version": "3.7", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_7-cpu", "validation_runner": "linux.2xlarge", "installation": "pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly", "stable_version": "1.13.0"}, {"python_version": "3.7", "gpu_arch_type": "cuda", "gpu_arch_version": "11.6", …
```
> Use channel to specify ROCM versions

- .github/workflows/build_conda_macos.yml
Same as : https://github.com/pytorch/test-infra/pull/1235
> Use package install last for macos

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
CUDA 11.8 Windows AMI update
Similar to: https://github.com/pytorch/test-infra/pull/452
> Migrating to cuda 11.8

- .github/actions/setup-linux/action.yml
- .github/workflows/linux_job.yml
Trying to see if this can help solve https://github.com/pytorch/vision/actions/runs/3649640523/jobs/6164578315 where cuda tests are skipped. 
Pending on test results here: https://github.com/pytorch/vision/actions/runs/3651595408/jobs/6168988816
> Tweak scripts to support nvidia filtering on A10G instance

- tools/scripts/generate_binary_build_matrix.py
Fix missing variable in previous commit
> Fix missing variable in previous commit

- .github/workflows/stronghold.yml
- tools/stronghold/src/api/checker.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1255).
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* #1256
* __->__ #1255
* #1253
* #1252
add support for suppressing api compatibility check violations
Summary: This will allow users to say that their changes are OK.
Test Plan: Verify with sample PR.
> add support for suppressing api compatibility check violations

- .github/workflows/test_linux_job.yml
> add more instance types to test gpu

- tools/scripts/generate_binary_build_matrix.py
Add stable vs candidate version for test vs release channel.
To be able to allow candiate version testing, during the release.
> Add stable vs candidate version for test vs release channel

- tools/stronghold/src/api/__init__.py
- tools/stronghold/src/api/ast.py
- tools/stronghold/src/api/compatibility.py
- tools/stronghold/tests/api/test_ast.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1299).
* #1291
* #1221
* #1304
* #1303
* #1302
* #1301
* __->__ #1299
* #1298
use the parameter line number for the moved param check
Test Plan: Verified in test PR.
> use the parameter line number for the moved param check

- tools/stronghold/src/api/__init__.py
- tools/stronghold/src/api/ast.py
- tools/stronghold/src/api/compatibility.py
- tools/stronghold/tests/api/test_ast.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1301).
* #1291
* #1221
* #1304
* #1303
* #1302
* __->__ #1301
* #1299
* #1298
extract requiredness check to a single function
Summary: This was previously duplicated across two checks.
> extract requiredness check to a single function

- tools/stronghold/src/api/__init__.py
- tools/stronghold/src/api/ast.py
- tools/stronghold/src/api/compatibility.py
- tools/stronghold/tests/api/test_ast.py
- tools/stronghold/tests/api/test_compatibility.py
Reverts pytorch/test-infra#1304
Merged before its parent, oops.
> Revert "no longer track position for each parameter"

- .github/templates/common.yml.j2
- .github/templates/deploy_lambda.yml.j2
- .github/templates/metrics_pytorch_org.yml.j2
- .github/workflows/backfill-workflow-job.yml
- .github/workflows/check-alerts.yml
- .github/workflows/clang-tidy-linux.yml
- .github/workflows/clang-tidy-macos.yml
- .github/workflows/generated-github-webhook-rds-sync.yml
- .github/workflows/generated-metrics-pytorch-org.yml
- .github/workflows/generated-rds-proxy.yml
- .github/workflows/generated-update-grafana-dashboards.yml
- .github/workflows/github-status-test-lambda.yml
- .github/workflows/lambda-runners.yml
- .github/workflows/lambda-webhook.yml
- .github/workflows/lambda_github_status_webhook_handler.yml
- .github/workflows/lambda_scribe_proxy.yml
- .github/workflows/lint.yml
- .github/workflows/lint_actions.yml
- .github/workflows/log-classifier-lambda.yml
- .github/workflows/push-rockset-query-lambda-tags.yml
- .github/workflows/sync_pytorch_canary.yml
- .github/workflows/test-setup-ssh.yml
- .github/workflows/tflint.yml
- .github/workflows/tools-self-hosted-runner-utils.yml
- .github/workflows/torchci.yml
- .github/workflows/update-drci-comments.yml
- .github/workflows/update-queue-times.yml
- .github/workflows/update_disabled_tests.yml
As v2 is based on node14 which is deprecated
> [BE] `checkout@v2`->`checkout@v3`

- tools/stronghold/src/api/compatibility.py
- tools/stronghold/tests/api/test_compatibility.py
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/1315).
* #1291
* #1227
* #1226
* #1225
* #1224
* #1223
* #1221
* __->__ #1315
test and fix that adding optional parameters is ok
> test and fix that adding optional parameters is ok

- tools/stronghold/src/api/compatibility.py
- tools/stronghold/src/api/github.py
- tools/stronghold/src/api/violations.py
- tools/stronghold/tests/api/test_compatibility.py
- tools/stronghold/tests/api/test_github.py
* __->__ #1331
Maps Violations to invdividual classes, planning on adding full
documentation within the docstrings of each Violation and then will take
those docstrings and render them into a markdown page for consumption on
Github
> tools: Map Violations to individual classes

- .github/actions/setup-ssh/index.js
- setup-ssh/__tests__/add-github-ssh-key.test.ts
- setup-ssh/__tests__/get-ip.test.ts
- setup-ssh/__tests__/github-utils.test.ts
- setup-ssh/src/main.ts
After all the dependabot updates
> Run yarn-all

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Use the pagination API octokit offers
> Improve pagination for listing PRs

- .github/workflows/backfill-workflow-job.yml
- torchci/scripts/backfillJobs.mjs
Bug fix for the backfill job has been failing recently https://github.com/pytorch/test-infra/actions/runs/3878048219/jobs/6613784126 since the sql query returns things other than just pytorch/pytorch jobs
Add backfill for logs
> [backfill] Bug fix and add backfill for log classifier 

- terraform-aws-github-runner/main.tf
- terraform-aws-github-runner/variables.tf
Improve retry dynamic control for scale-up sqs
> improving retry dynamic for scale-up sqs because of the ephemeral runners

- .github/workflows/build_conda_macos.yml
- .github/workflows/build_wheels_macos.yml
Similar to https://github.com/pytorch/test-infra/pull/1297, but adds support for user-specific env vars in the MacOS Wheels and Conda builds.
> [NovaX] Custom Env Var support for MacOS builds

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/bot/utils.ts
- torchci/test/mergeCommands.test.ts
And add `ciflow/trunk` on merges only to `pytorch/pytorch`.
Tweak tests quite a lot to distinguish between the two scenarios.
> Limit PR must be reviewed check to pytorch org

- torchci/lib/bot/botUtils.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/fixtures/known_labels.json
- torchci/test/labelCommands.test.ts
- torchci/test/mergeCommands.test.ts
idk if this is the right definition of first time contributor but if we define it  as someone who has never authored a commit to the default branch, then we can query for commits on the default branch with the author as the commenter.  If there are no commits, then the commenter is a first time contributor.
> [rebasebot] Add check for first time contributor

- torchci/lib/bot/ciflowPushTrigger.ts
> Add ciflow/inductor-perf-test-nightly

- torchci/lib/JobClassifierUtil.ts
- torchci/lib/jobUtils.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Same as https://github.com/pytorch/test-infra/pull/1057, group all unstable jobs into one persistent group
> Add a persistent group for unstable jobs

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
A follow-up to https://github.com/pytorch/test-infra/pull/1386 for better debuggability.
> [NovaX] set -euxo pipefail for build scripts in workflows

- torchci/README.md
Documents testing instructions for local development
> [BE] Document how to test files locally

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1
Upgrade cudnn for cuda 11.8
Related to: https://github.com/pytorch/builder/pull/1271
> Upgrade cudnn for cuda 11.8

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Add file path to issues created by flaky test bot
fixes 1440
> [flakybot][ez] Add file path to issue body

- torchci/scripts/updateTestTimes.mjs
Kind of a companion for https://github.com/pytorch/pytorch/pull/93401
Instead of making a new json, use the old json as a base and update the times that we have information for since we might lack information about some test files due to being unable to retrieve the job id.
This does mean that we aren't deleting any test files from the json when we update, but I'm less worried about that than uploading a test times json that lacks a bunch of jobs or files because sharding becomes really unbalanced.  We can also clean it up manually if needed.
> Update test times to update old json instead of making new json

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Reverts pytorch/test-infra#1384
Also part of the retry mechanism revert, follow up to #2442
> Revert "fail scale-up batch when a single instance of the batch fails"

- torchci/pages/kpis.tsx
- torchci/rockset/prodVersions.json
- torchci/rockset/pytorch_dev_infra_kpis/__sql/num_reverts.sql
viewable at https://torchci-git-csl-revertskpis-fbopensource.vercel.app/kpis
> [kpis] Add reverts categories for revert chart

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
Open the floor for art critics.  Do you guys think smooth charts looks better visually?
BEFORE
AFTER
https://torchci-git-fork-huydhn-smooth-chart-fbopensource.vercel.app/metrics
> Use smooth charts

- .github/workflows/build_conda_linux.yml
Build conda Linux for domains. Run smoke tests in separate conda environment
> Build conda linux for domains. Run smoke tests in separate conda environment in Linux

- tools/scripts/generate_binary_build_matrix.py
Change python 3.11 wheel install command, to include domains install
> Change python 3.11 wheel install command, to include domains install

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_linux.yml
- tools/scripts/generate_binary_build_matrix.py
Add conda 3.11 builds for Linux
> Add conda 3.11 builds for Linux

- .github/workflows/build_conda_linux.yml
Use same conda run env to upload to anaconda rather then creating new one
> Use same conda run env to upload to anaconda rather then creating new one

- .github/workflows/build_conda_macos.yml
Followup after https://github.com/pytorch/test-infra/pull/2891 for MacOS
> [Nova] Test conda deps MacOS edition

- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/lib/bot/utils.ts
- torchci/test/ciflow-push-trigger.test.ts
I.e. don't hardcode them
Fixes https://github.com/pytorch/test-infra/issues/1439
> Read ciflow labels from config

- tools/scripts/generate_binary_build_matrix.py
Update test channel remove restriction on 3.11
> Update test channel remove restriction on 3.11

- torchci/rockset/commons/__sql/filter_forced_merge_pr.sql
- torchci/rockset/commons/filter_forced_merge_pr.lambda.json
- torchci/rockset/prodVersions.json
matched pytorchbot but not pytorchmergebot
> Fix regex for highlighting force merged PRs on hud

- .github/scripts/install_torch.sh
Add malfet channel to torch install instructions
> Add malfet channel to torch install instructions

- .github/workflows/build_conda_macos.yml
Fix macos upload step.
Same as: https://github.com/pytorch/test-infra/pull/3769
> Fix macos upload step

- .github/workflows/build_conda_macos.yml
Since we switched to distr we need to use distr folder rather then dist
> Fix Macos and M1 upload folder

- .github/workflows/build_conda_macos.yml
Fix smoke test channel for MacOS
> Fix smoke test channel for MacOS

- .github/workflows/check-alerts.yml
- .github/workflows/update-drci-comments.yml
as with https://github.com/pytorch/test-infra/pull/3789
> Update ubuntu-18.04 to 22.04

- torchci/components/FilteredJobList.tsx
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
* Change link in Dr CI to point to hud, include a small link to github as well to reduce clicks if they want it
* Scroll to failed job when using anchor link
> Dr CI to link to hud, scroll to anchor link

- torchci/rockset/metrics/__sql/tts_percentile.sql
- torchci/rockset/prodVersions.json
Rockset folks reached out and told me this query was making their stuff
sad, so fix it
> improve metrics.tts_percentile query

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
A follow up of https://github.com/pytorch/test-infra/pull/3784 to display a different message for disable job issues such as https://github.com/pytorch/pytorch/issues/94861
> Update bot to handle disabled job issue

- torchci/components/GroupHudTableHeaders.tsx
- torchci/components/GroupJobConclusion.tsx
- torchci/components/TooltipTarget.tsx
- torchci/components/hud.module.css
- torchci/lib/types.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Highlight the row and column of the selected commit, or the column if a job is clicked, or the row when a commit is clicked.
I'm probably the only one that still uses the non grouped view, but this would really improve that view.
> [hud] Add highlight when clicking on cells

- torchci/components/WorkflowBox.tsx
Mostly just makes my life easier
Just adds a link to the raw logs to the jobs in the workflow box
Autoformatter made everything get newlines
> [hud] Add raw log link to jobs in workflow box

- torchci/scripts/backfillJobs.mjs
> Fix for backfill

- torchci/lib/bot/acceptBot.ts
- torchci/test/acceptBot.test.ts
Addresses https://github.com/pytorch/test-infra/issues/3851
Context: It doesn't really make sense to have this + no one is using it
> Remove accept_2_run label

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
Added a separate Dr. CI message for domains
> Added a separate Dr. CI message for domains

- .github/workflows/build_conda_macos.yml
> [Nova] Do not use conda-forge for Mac builds

- torchci/package.json
- torchci/yarn.lock
See https://github.com/nextauthjs/next-auth/security/advisories/GHSA-7r7x-4c4q-c4qf and T147941171
> Update next-auth to 4.20.1

- tools/scripts/generate_binary_build_matrix.py
Release 2.0 matrix modifications
> Release 2.0 matrix modifications

- tools/scripts/generate_binary_build_matrix.py
Remove python 3.11 for release conda builds
> Remove python 3.11 for release conda builds

- tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
Emergency for release, need to do some follow up for nightly
> Export PyTorch version for wheels

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
Copy-n-paste the logic from
https://github.com/pytorch/vision/blob/6c4ff94b56a8a26c150af0cd95f37bf30e1b8eb4/packaging/pkg_helpers.bash#L202-L207
And some minor tweaks:
- `s/CUDA_VERSION/CU_VERSION/`
- Prefix everything with `${CONDA_RUN}`
Also, this reverts https://github.com/pytorch/test-infra/pull/3879
> Setup PYTORCH_VERSION (take 2)

- .github/workflows/build_wheels_macos.yml
From https://github.com/pytorch/test-infra/pull/3880
> [easy] Fix lint

- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
Also fix typo (`s/occured/occurred/`)
Test plan: select any commit from https://hud.pytorch.org/pr/pytorch/vision/7407
> Fix owner/name order in commit dropdown

- .github/workflows/lint.yml
- .github/workflows/test-update-viablestrict.yml
- .github/workflows/tests.yml
- .github/workflows/update-viablestrict.yml
- tools/scripts/fetch_latest_green_commit.py
- tools/scripts/gitutils.py
- tools/tests/test_fetch_latest_green_commit.py
> Update viablestrict branch

- .github/workflows/build_wheels_windows.yml
- .github/workflows/test_build_wheels_windows_with_cuda.yml
- .github/workflows/test_build_wheels_windows_without_cuda.yml
- tools/pkg-helpers/pytorch_pkg_helpers/cuda.py
Windows wheels build fix for Text and Audio
> [Nova] Windows wheels build fix

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Await for async functions completion.
> Recent changes surfaced a bug with sending metrics

- torchci/README.md
Clarify instructions for updating the lambdas
> [BE] Clarify instructions for updating Rockset query lambdas

- aws/lambda/log-classifier/ruleset.toml
fixes https://github.com/pytorch/test-infra/issues/3934
> [log classifier] Decrease priority of nvidia driver installation error

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
small qol thing to make looking at the queue times historical chart easier to read
> [small][hud] Sort series by name for TimeSeriesPanel

- torchci/pages/api/drci/drci.ts
Do not hardcode the head branch name
> Do not hardcode the head branch name

- aws/lambda/log-classifier/src/main.rs
- aws/lambda/log-classifier/src/network.rs
Add `repo` argument to `download_log`, `upload_classification_dynamo` in
`network.rs`
Check for optional `repo` argument in Lamba's function handler.
Test plan: uncomment and run `real_test` with `ShouldUploadToDynamo` set to true. Notice that line appears in the db.
TODO: Modify log-upload lambda to pass repo argument.
> Extend log-classifier to other repos

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_wheels_linux.yml
Added 'Setuo ssh' step to Linux binaru builds workflows
> Added 'Setuo ssh' step to Linux binaru builds workflows

- torchci/pages/api/drci/drci.ts
> Fix HUD Link for Failed Jobs

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
> Add check so that it does not trigger upload to download.pytorch.org from just main or master branch

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
2nd attempt for fixing https://github.com/pytorch/test-infra/issues/3975
> Avoid uploading binaries to nightly for every push to main branch

- .github/workflows/github-status-test-lambda.yml
- aws/lambda/github-status-test/Makefile
- aws/lambda/github-status-test/lambda_function.py
Follow-up after https://github.com/pytorch/test-infra/pull/3977
Create `packages` folder during prepare step 
Put folder search paths in quotes, otherwise it's not getting invoked (see https://github.com/pytorch/test-infra/commit/a0ef6714a32144994084243d65056e418c467e0c )
> Call classifier for all repos

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Similar to https://github.com/pytorch/test-infra/pull/3988
Partially addresses https://github.com/pytorch/test-infra/issues/3979
Test plan: `¯\_(ツ)_/¯`
> Install NVJPEG on Windows

- torchci/lib/bot/retryBot.ts
Do not hardcode head branch name.
> Do not hardcode head branch name

- .github/workflows/build_conda_windows.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
Nova: Vision windows conda build
> [Nova] Vision windows conda build

- torchci/lib/bot/retryBot.ts
- torchci/test/retryBot.test.ts
Rather use `retriable_workflows` property from the respective configs ([pytorch](https://github.com/pytorch/pytorch/blob/d1e7434bcf89b558d371de9101e6a28f611e1b70/.github/pytorch-probot.yml#L16-L21), [vision](https://github.com/pytorch/vision/blob/ce653d8b6e88fbdb4d3523bf677fee71bc594196/.github/pytorch-probot.yml#L5)).
> Do not hardcode retryable workflows

- torchci/pages/kpis.tsx
- torchci/rockset/metrics/__sql/external_contribution_stats.sql
- torchci/rockset/metrics/external_contribution_stats.lambda.json
- torchci/rockset/prodVersions.json
- torchci/rockset/pytorch_dev_infra_kpis/__sql/monthly_contribution_stats.sql
- torchci/rockset/pytorch_dev_infra_kpis/monthly_contribution_stats.lambda.json
Rebase shenanigans screwed up https://github.com/pytorch/test-infra/pull/3974, so just resubmitting it
> External KPIs dashboard update

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/utils.ts
> Enable Dr. CI for torchtext

- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
All repos DrCI works with now take `main` as default branch.
> Change default branch in DrCI

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/utils.ts
> Enable Dr. CI for torchaudio

- torchci/lib/bot/retryBot.ts
Remove unused `ALLOWED_WORKFLOW_PREFIXES`
Rename `master` to `main`
> Retry bot cleanup

- .github/scripts/run_docker_with_env_secrets.py
- .github/workflows/test_linux_job.yml
GPU_FLAG wasn't getting set properly (see [logs](https://github.com/pytorch/audio/actions/runs/4733965450/jobs/8402221728?pr=3271#step:10:160))
> ci: Fix logic to include GPU_FLAG

- torchci/pages/api/drci/drci.ts
extra } was causing the new section to be closed by default
also some random formatting changes due to saving the file
> [easy] Fix small typo in #4068

- .github/workflows/build_conda_windows.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
- .github/workflows/test_build_conda_windows_without_cuda.yml
- .github/workflows/test_build_wheels_windows_with_cuda.yml
[Nova] Windows add smoke test to conda build
> [Nova] Windows add smoke test to conda build

- .github/actions/setup-nvidia/action.yml
Reverts pytorch/test-infra#4128
Broke CI https://github.com/pytorch/audio/actions/runs/4917943491/jobs/8783637657
> Revert "Set GPU `capabilities=all` for Docker"

- torchci/lib/bot/cliParser.ts
Reflect the underlying logic set in https://github.com/pytorch/test-infra/pull/1400
> [BE] Update pytorchbot help text for rebasing

- terraform-aws-github-runner/modules/runners-instances/security-groups.tf
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Relates to: https://github.com/jeanschmidt/terraform-aws-vpc/pull/1
> enables IPV6

- .github/workflows/build_wheels_windows.yml
Setup Pytorch Version, same as https://github.com/pytorch/test-infra/pull/3880
Also upload whel to github after relocate. Make sure, all required dlls are included in the wheel before uploading to github.
> Set windows wheel torch version correctly, upload to github after relocate!

- torchci/lib/bot/autoLabelBot.ts
This goes together with https://github.com/pytorch/pytorch/pull/101026
> Add auto-label rules for Vulkan

- terraform-aws-github-runner/outputs.tf
> Trigger the Workflow

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Add inductor as a test disable group like dynamo, windows, mac, linux etc
corresponds with https://github.com/pytorch/pytorch/pull/101448
> Add inductor as test disable group

- torchci/pages/api/flaky-tests/disable.ts
- torchci/pages/failure/[capture].tsx
- torchci/test/disableFlakyBot.test.ts
* highlight main branch on failures page (fixes https://github.com/pytorch/test-infra/issues/4050)
* query for main to get labels for disabled tests, fix tests
> Some master -> main changes

- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/styles/globals.css
> Add fugly per-commit table on model view

- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
> Fix "Benchmark compiler page links are swapped"

- tools/scripts/generate_binary_build_matrix.py
> Remove CUDA 11.7 builds; replace with 11.8

- tools/flake8-torch/flake8_torch/checker.py
- tools/flake8-torch/pyproject.toml
- tools/flake8-torch/requirements-dev.txt
- tools/flake8-torch/tests/test_flake8_torch.py
Using libcst https://libcst.readthedocs.io/en/latest/ will unlock fixing the issues instead of just flagging them.
> [flake8-torch] Replace manual AST traversal with libcst

- torchci/scripts/check_alerts.py
- torchci/scripts/test_check_alerts.py
forgot this in https://github.com/pytorch/test-infra/pull/4204
> Fix alert after #4204

- .github/workflows/revert-tracker.yml
https://github.com/pytorch/test-infra/pull/4041/files
Clicked merge without thinking...
> Remove accidentally included change in #4041

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
This is to support the new unstable job issue and goes together with https://github.com/pytorch/test-infra/pull/4225
> Handle unstable job issues

- torchci/lib/bot/cliParser.ts
Nudge people towards using `--ignore-current` instead of `--force`
> Improve help text for --force command

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Small request by alban since -ic implies two separate flags, i and c
> Make --ignore-changes flag conform to cli standards

- torchci/lib/bot/cliParser.ts
https://github.com/pytorch/pytorch/pull/97707
> Ignore current ok for no pending jobs

- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
Per title, we want to hide unstable jobs in a collapsible section like flaky and broken trunk.  I opt for an unstable section for clarity but we could also add unstable jobs into flaky section (to reuse the name).  Note that unstable job failures doesn't block merge https://github.com/pytorch/pytorch/pull/102784
> Update Dr. CI to handle unstable jobs

- .github/actions/setup-linux/action.yml
- .github/scripts/run_docker_with_env_secrets.py
- .github/workflows/test_linux_job.yml
This goes with https://github.com/pytorch/pytorch/pull/103216, but it's for Nova
> Cleanup existing Docker containers and images in setup-linux

- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
- .github/workflows/test_build_wheels_linux_with_cuda.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_build_wheels_macos.yml
- .github/workflows/test_build_wheels_windows_with_cuda.yml
Add caching to windows, macos and linux wheels
Follow up: https://github.com/pytorch/test-infra/pull/4261 , make sure new arguments are geeting properly passed
> Add caching to windows, macos and linux wheels

- torchci/lib/bot/autoLabelBot.ts
I just created the optim release notes label for all things optimizer related. Have the bot use it.
> [Autolabel] Add optim release notes label

- aws/ami/windows/windows.pkr.hcl
Doing this before installing sshd causes the latter to fail.  So let's do this last after everything has been setup (May be this is just a one time fluke where running the script locally failed to download sshd)
```
==> amazon-ebs.windows_ebs_builder: Provisioning with powershell script: ./scripts/Installers/Install-SSH.ps1
amazon-ebs.windows_ebs_builder:
amazon-ebs.windows_ebs_builder:
amazon-ebs.windows_ebs_builder: Path          :
amazon-ebs.windows_ebs_builder: Online        : True
amazon-ebs.windows_ebs_builder: RestartNeeded : True
amazon-ebs.windows_ebs_builder:
amazon-ebs.windows_ebs_builder: Start-Service : Cannot find any service with service name 'sshd'.
amazon-ebs.windows_ebs_builder: At C:\Windows\Temp\script-6488e0ef-7a88-2292-98a6-c467fce31a19.ps1:6 char:1 …
```
> Uninstall Windows Defender last

- tools/scripts/generate_binary_build_matrix.py
Use pipy for macos m1 release validations
> Use pipy for macos m1 release validations

- torchci/rockset/nightlies/__sql/nightly_jobs_red.sql
- torchci/rockset/nightlies/nightly_jobs_red.lambda.json
- torchci/rockset/prodVersions.json
Update nightly jobs red lambda - fix repo display
> Update nightly jobs red lambda - fix nightly jobs display

- tools/torchfix/pyproject.toml
- tools/torchfix/torchfix/__main__.py
- tools/torchfix/torchfix/common.py
- tools/torchfix/torchfix/torchfix.py
Split the one large file.
Updated LibCST version (this version uses Rust parser by default).
Bumped TorchFix version to 0.0.2.
> [TorchFix] Refactor a bit and update LibCST

- .github/workflows/tflint.yml
- terraform-aws-github-runner/.tflint.hcl
- terraform-aws-github-runner/main.tf
- terraform-aws-github-runner/modules/download-lambda/.tflint.hcl
- terraform-aws-github-runner/modules/download-lambda/main.tf
- terraform-aws-github-runner/modules/runner-binaries-syncer/.tflint.hcl
- terraform-aws-github-runner/modules/runner-binaries-syncer/main.tf
- terraform-aws-github-runner/modules/runners-instances/main.tf
- terraform-aws-github-runner/modules/runners/.tflint.hcl
- terraform-aws-github-runner/modules/runners/main.tf
- terraform-aws-github-runner/modules/setup-iam-permissions/.tflint.hcl
- terraform-aws-github-runner/modules/setup-iam-permissions/main.tf
- terraform-aws-github-runner/modules/webhook/.tflint.hcl
- terraform-aws-github-runner/modules/webhook/main.tf
This is a required change in order to fix "tflint" CI and update all our infra to the latest versions of clis and packages
> upgrading terraform and tflint versions, and dependent plugins

- torchci/lib/fetchFlakyTests.ts
- torchci/pages/api/flaky-tests/disable.ts
Ignore skipped tests and those from rerun_disable_tests workflow
> Update for disable tests flaky from file reruns

- .github/actions/chown-directory/action.yml
- .github/workflows/linux_job.yml
Use different alpine images for aarch64 linux builds
> Use different alpine images for aarch64 linux builds

- .github/workflows/build_wheels_linux.yml
Fix bug in gpu pass through where container runtime options cannot access env vars
> Fix gpu pass-though

- .github/workflows/torchci.yml
- torchci/pages/nightlies.tsx
I really want to turn format on save again...
Test:
check first commit for failure example, second commit for success example
> Enforce yarn format

- .github/actions/setup-ssh/index.js
- .github/workflows/test-setup-ssh.yml
- setup-ssh/package.json
- setup-ssh/src/main.ts
- setup-ssh/yarn.lock
Add link to wiki to ssh step 
update @vercel/ncc version to deal with ssl error
> Add ssh wiki to log

- .github/actions/trigger-nightly/action.yml
- .github/workflows/trigger_nightly.yml
Nightly builds for vision and audio. Move trigger nightly to action
> Nightly builds for vision and audio. Move trigger nightly to action

- .github/actions/trigger-nightly/action.yml
Fix lint for trigger-nightly action
> Fix lint for trigger-nightly action

- .github/workflows/trigger_nightly.yml
Add checkout test-infra step to trigger nightly. Needed to call action.
> Add checkout test-infra step to trigger nightly

- .github/actions/trigger-nightly/action.yml
Make nightly commit separate step in trigger-nightly action
> Make nightly commit separate step in trigger-nightly action

- .github/actions/trigger-nightly/action.yml
- .github/workflows/trigger_nightly.yml
Test run: https://github.com/pytorch/test-infra/actions/runs/5536788736/jobs/10104904126?pr=4384
> Refactor code for trigger nightly run

- .github/workflows/trigger_nightly.yml
Tune timing for nightly builds to 4:30PST
> Tune timing for nightly builds to 4:30PST

- .github/workflows/trigger_nightly.yml
Add torchrec to nightly trigger jobs
> Add torchrec to nightly trigger jobs

- .github/workflows/trigger_nightly.yml
Add torchdata to nightly trigger
> Add torchdata to nightly trigger

- aws/lambda/log-classifier/ruleset.toml
Fix after https://github.com/pytorch/test-infra/pull/4392 since I spelled improve wrong...
Also add back in the old classifications too because I forgot to save...
> [log classifier] Change inductor model regex again

- README.md
Update readme directory structure
> Update readme directory structure

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Add user-data.sh to lambda logs
> Runner provisioning. Add user-data.sh to lambda logs

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Nvidia driver updateduring runner start. Install required packages
> Nvidia driver update during runner start

- .github/scale-config.yml
> Added linux.arm64.2xlarge

- .github/workflows/generate_binary_build_matrix.yml
Follow up after PR: https://github.com/pytorch/test-infra/pull/4360
> Add with-rocm param to generate_binary_matrix workflow. Cleanup limit-win-builds param

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Add nvidia-docker tools installation to worker provisioning
> Add nvidia-docker tools installation to worker provisioning

- torchci/pages/benchmark/compilers.tsx
To keep up with this update https://github.com/pytorch/pytorch/pull/106009
> clip, sd, whisper, llama2 in dashboard

- torchci/.env.example
- torchci/lib/searchUtils.ts
- torchci/package.json
- torchci/pages/api/search.ts
- torchci/yarn.lock
The failures are indexed, which allows fast full test search.  The initial use case is to find failed jobs with the similar failure across the board during a period of time.
* https://torchci-git-fork-huydhn-search-similar-failures-fbopensource.vercel.app/api/search?failure=torchbenchmark.models.dlrm
* https://torchci-git-fork-huydhn-search-similar-failures-fbopensource.vercel.app/api/search?failure=torchbenchmark.models.dlrm&startDate=2023-08-02T00:00:00Z&endDate=2023-08-03T00:00:00Z
> Add an API endpoint to search for failed jobs with the similar failure

- .github/workflows/test_build_wheels_linux_aarch64_without_cuda.yml
Follow up after https://github.com/pytorch/test-infra/pull/4445
to build torchaudio
> Add aarch64 torchaudio builds

- .flake8
- aws/lambda/opensearch-gha-jobs/Makefile
- aws/lambda/opensearch-gha-jobs/README.md
- aws/lambda/opensearch-gha-jobs/lambda_function.py
- aws/lambda/opensearch-gha-jobs/requirements.txt
- aws/lambda/opensearch-gha-jobs/test_lambda_function.py
This goes with https://github.com/fairinternal/pytorch-gha-infra/pull/232
`make deploy`
> Add a lambda to index torchci-workflow-job table

- torchci/components/JobLinks.tsx
`This test was disabled because it is failing on master`->`This test was disabled because it is failing on main branch`
> Update disable test template

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Update CUDA 12.1.1
Same as: https://github.com/pytorch/test-infra/pull/3994
> Update cuda to 12.1.1

- .github/workflows/linux_job.yml
Trying to mitigate aarch64 clean step failures by cleaning environment before exiting the worker:
https://github.com/pytorch/audio/actions/runs/5862053290/job/15893716047
> Additional clean step before tearing down the environment

- .github/workflows/opensearch-gha-jobs-lambda.yml
Follow up after https://github.com/pytorch/test-infra/pull/4469 with a workflow to test and deploy the lambda.
> Add a workflow to test and deploy opensearch-gha-jobs lambda

- .github/scale-config.yml
Set max_available for linux arm64
> Set max_available for linux arm64

- .github/workflows/build_wheels_linux.yml
Linux aarch64 / Cleanup Previous Artefacts
> Linux aarch64 / Cleanup Previous Artefacts

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
Cherry-pick of https://github.com/pytorch/test-infra/pull/4530 onto release/2.1 branch
> [Cherry-Pick] Support for Conda Test Token

- tools/torchfix/torchfix/__main__.py
- tools/torchfix/torchfix/torchfix.py
There will be a separate PR to do a similar thing for TorchFix in the standalone mode.
> [TorchFix] Disable noisy warnings by default in flake8

- .github/workflows/linux_job.yml
Added linux.arm64.2xlarge to condition for ALPINE_IMAGE
> Added linux.arm64.2xlarge to condition for ALPINE_IMAGE

- .github/scale-config.yml
Dedicate windows GPU for the release process
> Dedicate windows GPU for the release process

- .github/workflows/lintrunner_ci.yml
Addresses https://github.com/pytorch/test-infra/issues/4522
> add macos and windows release to lintrunner

- tools/torchfix/README.md
- tools/torchfix/tests/test_torchfix.py
- tools/torchfix/torchfix/__main__.py
- tools/torchfix/torchfix/torchfix.py
A follow-up to https://github.com/pytorch/test-infra/pull/4533
> [TorchFix] Disable noisy warnings by default in torchfix standalone

- .github/workflows/trigger_nightly.yml
Trigger the nightly push to the nightly branch for tensorrt like the other domain repos.
> TensorRT nightly trigger

- .github/actions/setup-nvidia/action.yml
> Hotfix: don't install nvidia-docker2 package

- .github/workflows/trigger_nightly.yml
Trigger the nightly push to the nightly branch for FBGEMM like the other domain repos.
> Add FBGEMM to nightly trigger

- tools/scripts/generate_binary_build_matrix.py
This fixes nightly conda build failures in domains:
https://github.com/pytorch/audio/actions/runs/6247970861/job/16961628045
Test:
https://github.com/pytorch/test-infra/actions/runs/6254299414/job/16981544906?pr=4581
> Pin conda build images - fix nightly conda failures

- .github/actions/setup-nvidia/action.yml
> Hotfix: don't install nvidia-docker2 package (#4562)

- tools/scripts/generate_binary_build_matrix.py
Adjusted runner type for linux-aarch64 os
> Adjusted runner type for linux-aarch64 os (#4525)

- .github/workflows/linux_job.yml
Added linux.arm64.2xlarge to condition for ALPINE_IMAGE
> Added linux.arm64.2xlarge to condition for ALPINE_IMAGE (#4524)

- .github/workflows/build_wheels_linux.yml
Linux aarch64 / Cleanup Previous Artefacts
> Linux aarch64 / Cleanup Previous Artefacts (#4514)

- torchci/lib/bot/drciBot.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciBot.test.ts
Query rockset for pr body, fall back to GH if needed
Also remove some unused imports
> [dr ci] Query rockset for PR body

- .github/scale-config.yml
> Add `linux.12xlarge.ephemeral`

- .github/actions/setup-binary-builds/action.yml
Follow up on https://github.com/pytorch/test-infra/pull/4606
Causes this failure:
https://github.com/pytorch/TensorRT/actions/runs/6486546804
> Restore special case for python 3.11 in setup-binary-builds. Fix tensorrt 

- torchci/lib/jobUtils.ts
Gonna need @huydhn to confirm that this change makes sense
should fixes https://github.com/pytorch/test-infra/issues/4633
> [dr ci] Fix dup jobs?

- torchci/lib/drciUtils.ts
- torchci/test/drciUtils.test.ts
I forgot to add this in https://github.com/pytorch/test-infra/pull/4636
> Add doc build jobs into the excluded list

- tools/torchfix/tests/fixtures/vision/checker/to_tensor.py
- tools/torchfix/torchfix/torchfix.py
- tools/torchfix/torchfix/visitors/vision/to_tensor.py
Incrementing patch version as 0.1.0 already pushed to PyPI.
> [TorchFix] Fix bug in TorchVisionDeprecatedToTensorVisitor with ImportStar

- torchci/components/NavBar.tsx
- torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
Add executorch to hud navbar
Adds executorch to the hud navbar as it's public now :)
> Add executorch to hud navbar

- torchci/components/JobLinks.tsx
Example crash https://hud.pytorch.org/pytorch/pytorch/commit/108378e2afb24715dba6677175c9005e780bba0b
https://torchci-git-fork-huydhn-fix-hud-crashing-fbopensource.vercel.app/pytorch/pytorch/commit/108378e2afb24715dba6677175c9005e780bba0b
> Fix HUD when there is no captured failure

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/utils.ts
Add the executorch repo to Dr. CI to enable doc previews on in that repo.
> Add ExecuTorch to Dr. CI

- .github/actions/setup-ssh/index.js
- setup-ssh/src/add-github-ssh-key.ts
- setup-ssh/src/github-utils.ts
It should never fail, if for some reason keys could not be fetched, just print an error.
> [BE] Make add-github-ssh-key tolerant to errors

- .github/actions/setup-ssh/index.js
- setup-ssh/src/main.ts
Action should not fail if list of labels can not be fetch
> [setup-ssh] Handle errors in fetching labels

- torchci/components/WorkflowBox.tsx
I think the # of hooks changing was due to the number of jobs changing as jobs got triggered by others finishing, so move the useState hook into the WorkflowBox so that there's only ever one.  
I'm not sure why we don't encounter this error when new workflows get added since I assume that would cause the same problem.  Perhaps this needs to be monitored more, but useSWR, is a hook that retrieves artifacts and is at the same level and existed before didn't cause any problems.
related to https://github.com/pytorch/test-infra/pull/4677 and https://github.com/pytorch/test-infra/pull/4664
> [HUD] Make artifacts inline again

- .github/actions/setup-miniconda/action.yml
- .github/workflows/test-setup-miniconda.yml
These variables could be set on some runners pointing to system brew conda.
https://github.com/pytorch/pytorch/pull/112907
> Set CONDA_EXE and CONDA_PREFIX in setup-miniconda

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/utils.ts
> Enable DR. CI for RL repo

- .github/workflows/lint.yml
- .lintrunner.toml
- torchci/scripts/calculate_file_test_rating.py
- torchci/scripts/compute_correlation.py
- torchci/scripts/get_merge_base_info.py
- torchci/scripts/queue_alert.py
- torchci/scripts/reverts.py
- torchci/scripts/rockset_utils.py
- torchci/scripts/td_heuristic_profiling.py
- torchci/scripts/td_rockset_analysis.py
- torchci/scripts/test_calculate_file_test_rating.py
- torchci/scripts/test_check_alerts.py
- torchci/scripts/test_update_test_times.py
- torchci/scripts/update_test_times.py
- torchci/scripts/utils.py
- torchci/scripts/utils_td_heuristics.py
Adds UFMT to be run in CI on python files in `torchci`.  
Given that it wasn't being run in CI before this, I think it's ok to make the include patterns more restrictive.
> [BE] Enable UFMT on torchci in CI

- tools/scripts/generate_binary_build_matrix.py
Define OS (LINUX, WINDOWS, MAC) and accelerator (CPU, CUDA, ROCM) string contstants and use it throughout the codebase
> [BE] Avoid string literal repetition

- tools/torchfix/tests/fixtures/misc/checker/require_grad.py
- tools/torchfix/tests/fixtures/misc/checker/require_grad.txt
- tools/torchfix/tests/fixtures/misc/codemod/require_grad.py
- tools/torchfix/tests/fixtures/misc/codemod/require_grad.py.out
- tools/torchfix/torchfix/visitors/misc/__init__.py
Fixes https://github.com/pytorch/test-infra/issues/4687
> More assertive require_grad check

- .github/workflows/revert-tracker.yml
- tools/torchci/reverts.py
Forgot about this one in https://github.com/pytorch/test-infra/pull/4703.
Also change _event_time usage to created
> [ez] Fix revert printer after #4703

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/common.ts
- torchci/test/disableFlakyBot.test.ts
- torchci/test/verifyDisableTestIssue.test.ts
> [bot] Disable bot to auto add platforms

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
> Do not label issues with `ciflow/`

- aws/lambda/github-status-test/lambda_function.py
Per our discussion on https://github.com/pytorch/test-infra/pull/4714/files#r1395050162, here is the update to the lambda code to support a backfill action without overwriting the existing event data.
> Support backfilling missing logs

- .github/workflows/generate_release_matrix.yml
- tools/scripts/generate_release_matrix.py
For release matrix generation. Allow empty version as input.
> Output empty json if version not provided to release matrix

- .github/actions/setup-binary-builds/action.yml
This code was added when coda build was not working properly with python 3.11
> Remove exception code for py 3.11

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_macos.yml
Two cherry picks to Move conda and conda builds to latest conda versions.
> Move conda and conda-builds to latest conda versions

- .github/workflows/clang-tidy-linux.yml
- .github/workflows/clang-tidy-macos.yml
- tools/clang-tidy-checks/17.x-patches/0003-Do-not-use-pthread_rwlock_wrlock.diff
- tools/clang-tidy-checks/Dockerfile.cilint-clang-tidy
- tools/clang-tidy-checks/setup.sh
As first steps towards may be addressing https://github.com/pytorch/pytorch/issues/114913
> Update clang-tidy to 17.0.6

- torchci/lib/bot/cliParser.ts
- torchci/lib/bot/pytorchBot.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/closeCommands.test.ts
- torchci/test/labelCommands.test.ts
Allowing closing or prs and issues  through pytorchbot
Deals with https://github.com/pytorch/test-infra/issues/4738
Specifically deals with the suggestion to add closing functionality to PRs/issues from pytorchbot.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/4781).
* __->__ #4781
* #4780
> Allowing closing or prs and issues  through pytorchbot

- .github/workflows/backfill-workflow-job.yml
- torchci/scripts/backfillJobs.mjs
Permissions for this workflow are in : https://github.com/pytorch-labs/pytorch-gha-infra/pull/303
> backfill-workflow-job.yml to use OIDC to authenticate to AWS

- .github/workflows/pr-dependencies-check.yml
use inputs instead of github.events.inpugs as the latter does not work for workflow calls
> use inputs instead of github.events.inputs as the latter does not work for workflow calls

- .github/workflows/build_wheels_linux.yml
Reverts pytorch/test-infra#4839 . Nightlies for vision are failing. Need to tweak something on infra side.
> Revert "[oidc] Update linux wheels job to use oidc"

- .github/workflows/build_wheels_linux.yml
This reverts commit 06fa1167c9bc1b41c9306ed3c305b58784d6ee87.
> Revert "Revert "[oidc] Update linux wheels job to use oidc" (#4840)"

- .github/workflows/build_wheels_linux.yml
Reverts pytorch/test-infra#4841
> Revert "Revert "Revert "[oidc] Update linux wheels job to use oidc" (#4840)""

- .github/workflows/update-test-times.yml
- .github/workflows/update_disabled_tests.yml
content write permissions so it can upload files to repo
> Write permissions for update-test-times and update_disabled_tests

- torchci/rockset/commons/__sql/test_time_per_class_periodic_jobs.sql
- torchci/rockset/prodVersions.json
Dunno how this didn't fail immediately, will need to investigate later
> [ez] Update rockset query for test class times

- .github/workflows/update-s3-html.yml
Follow up after https://github.com/pytorch/test-infra/pull/4879
> Correct account id for s3 update job

- .github/workflows/pr-dependencies-check.yml
[BE] Make merge conflict workflow failure case more descriptive
Test: https://github.com/pytorch/test-infra/actions/runs/7509086081
> [BE] Make merge conflict workflow failure case more descriptive

- .github/workflows/pr-dependencies-check.yml
- aws/lambda/log-classifier/ruleset.toml
Make logviewer aware of mergability failures
Adds a rule/some text to help the logviewer understand mergability errors
> Make logviewer aware of mergability failures

- .github/workflows/check-alerts.yml
- .github/workflows/revert-tracker.yml
* `.github/workflows/revert-tracker.yml` needs `content: write`, same as update slow test, update test time, and several other workflows.
* `.github/workflows/check-alerts.yml` needs `issues: write` to create and update the alerts.
> Grant the permissions to revert tracker and check alerts workflows

- tools/torchci/download_logs.py
Add option for downloading artifacts to the download logs script
Copied from my local scripts folder, I have no idea what env vars are needed to run this
This is just a utility script, not actually called anywhere
> Download artifacts script

- torchci/pages/api/flaky-tests/disable.ts
- torchci/pages/api/flaky-tests/flakytest.ts
- torchci/pages/flakytest.tsx
- torchci/test/disableFlakyBot.test.ts
I mean it shows stuff now, but it's not quite the same as what it showed before
Pros: it works now
Cons: I can't remember what it used to look like since I'm pretty sure the current pages don't load and I put this together in like 30 min so i have no idea if this is a step in the right direction or if its going to need to go through more changes later
https://torchci-git-csl-flakytestspage-fbopensource.vercel.app/flakytest?name=test_large_block_sizes_dynamic_shapes_cuda&suite=DynamicShapesCodegenCudaTests
https://torchci-git-csl-flakytestspage-fbopensource.vercel.app/flakytest?name=test_dynamic_stride_nobreak_cuda&suite=TestInductorDynamicCUDA
> [HUD] Fix (?) flakytests page

- .github/actions/calculate-docker-image/action.yml
Check if image exists (as push attempt might have failed silently for some reason)
> Improve error checking in `calculate-docker-images`

- .github/workflows/github-status-test-lambda.yml
- .github/workflows/log-classifier-lambda.yml
- .github/workflows/opensearch-gha-jobs-lambda.yml
Update the following workflows for the corresponding lambda:
* .github/workflows/github-status-test-lambda.yml
* .github/workflows/log-classifier-lambda.yml
* .github/workflows/opensearch-gha-jobs-lambda.yml
> Update lambda deployment workflow with OIDC

- .github/actions/setup-binary-builds/action.yml
- .github/actions/setup-binary-upload/action.yml
- .github/workflows/_binary_conda_upload.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
- .github/workflows/test_build_conda_linux_with_cuda.yml
- .github/workflows/test_build_conda_linux_without_cuda.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
- .github/workflows/test_build_conda_windows_without_cuda.yml
- .github/workflows/test_build_wheels_linux_aarch64_without_cuda.yml
- .github/workflows/test_build_wheels_linux_with_cuda.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_build_wheels_macos.yml
- .github/workflows/test_build_wheels_windows_with_cuda.yml
- .github/workflows/test_build_wheels_windows_without_cuda.yml
The list includes:
* https://github.com/pytorch/test-infra/pull/4870
* https://github.com/pytorch/test-infra/pull/4877
* https://github.com/pytorch/test-infra/pull/4882
* https://github.com/pytorch/test-infra/pull/4886
* https://github.com/pytorch/test-infra/pull/4891
* https://github.com/pytorch/test-infra/pull/4893
* https://github.com/pytorch/test-infra/pull/4894
* https://github.com/pytorch/test-infra/pull/4901
> Cherry pick a bunch of OIDC changes for 2.2.1 release

- aws/lambda/github-status-test/lambda_function.py
Follow up to #4971
Gzip wants bytes, not str
I can't use boto3 atm so I didn't catch this
> Follow up to #4971

- torchci/lib/fetchS3Links.ts
> [ez][HUD] Sort artifacts

- .github/arc-node-config.yaml
- .github/arc-runner-config.yaml
This adds new runner nodes that support NVIDIA GPUs.
> Add GPU runner nodes

- .github/arc-runner-config.yaml
* Removed useless runners;
* Removed unused parameters;
Tested on the ci-infra side:
> Cleanup ARC configs

- .github/actionlint.yaml
> Removed macos-m1-12 label

- torchci/pages/benchmark/compilers.tsx
> Add sam_fast to dashboard

- torchci/pages/benchmark/compilers.tsx
> Add sam_fast to dashboard (#4983)

- .github/actions/calculate-docker-image/action.yml
- .github/actions/pull-docker-image/action.yml
Reverts pytorch/test-infra#4991
Reason: https://github.com/pytorch/test-infra/pull/4991#issuecomment-1991892394
> Revert "Forces docker login on calculate-docker-image and pull-docker-image"

- .github/arc-node-config.yaml
- .github/arc-runner-config.yaml
Relates to pytorch/ci-infra#89.
> Update nvidia nodetype to be more specific

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
Do not add `ciflow/trunk` if there is no write permission for approval of codev PRs.  Instead, post a link to the wiki that has instructions for how to get write permissions.
Helps to reduce bot fighting in the below case:
> [bots] Do not add trunk label if codev but no workflow running permissions

- aws/lambda/github-status-test/lambda_function.py
Add ability to read a list of tokens and selected a random one as a temporary measure for hitting rate limits while downloading logs
> [lambdas][github-status-test] Select random token

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Fixes https://github.com/pytorch/pytorch/issues/122407
> [BE] Add message about skip ci decorators

- torchci/components/WorkflowDispatcher.tsx
> [ez] Support trigger ROCm workflow in trunk

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
It's not working but I can't tell why
It's probably the refs thing
> [bots] Add logging to rerunGithubInfraErrorWorkflow

- tools/torchci/requirements.txt
- torchci/package-lock.json
- torchci/package.json
- torchci/yarn.lock
Dump them all into one PR just in case something breaks.  If something breaks, we can just revert this one PR instead of digging through a bunch.
Sanity checked that hud was ok
Should cover:
https://github.com/pytorch/test-infra/pull/5050
https://github.com/pytorch/test-infra/pull/5022
https://github.com/pytorch/test-infra/pull/4990
https://github.com/pytorch/test-infra/pull/4961
https://github.com/pytorch/test-infra/pull/4960
https://github.com/pytorch/test-infra/pull/4361
https://github.com/pytorch/test-infra/pull/4704
> [torchci] Aggregate dependabot changes into one PR

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Delete tag on workflow completion so we don't get clogged with tags
Also figured out which action it is when a workflow fails to start: requested
> [bots] Rerun github infra failure bot - delete tag on workflow completion

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Reset the dictionary every week ish to prevent unbounded memory usage?
tbh idk how concurrency + caching works for this...
I'll figure this out tomorrow
#5060
> [bots] Follow up for #5060

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
#5061
Probably going to do some random cache updates when months switch, but I'm ok with that
> [bots] Fix after #5061

- torchci/README.md
Made https://github.com/pytorch/test-infra/wiki/Testing-Probot-Locally with steps I followed to get probot working locally on real data since the last time I managed to do it, I forgot and had to figure it out all over again
> [bots] Local testing wiki link

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
- torchci/test/utils.ts
Corresponds to https://github.com/pytorch/pytorch/pull/122976
> [TD][bots] Auto add TD rollout label

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
> Windows AMI - add cuda 12.4

- aws/lambda/log-classifier/fixtures/request.json
- aws/lambda/log-classifier/ruleset.toml
This is to separate the ExecuTorch failure in https://github.com/pytorch/pytorch/pull/123326 with another unrelated failure from from https://github.com/pytorch/pytorch/actions/runs/8621802302/job/23632191816#step:18:10348
I test this out on the PR itself https://github.com/pytorch/pytorch/pull/123326.
> Add rules for Python ValueError and TypeError

- torchci/lib/bot/index.ts
- torchci/lib/bot/statefulBot.ts
I can't figure out if probot is stateful or not, so I want to do an actual test on https://github.com/malfet/deleteme/issues/83
I thought they were serverless but I see some logging that indicates that it's maybe not stateless?
I will revert this soon after I figure it out
> This is a test for whether or not probot is stateful

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
Cherry-pick #5095 into release/2.3
> cherry-pick: Add `submodule` input for build_wheels_*.yaml (#5095)

- .github/arc-node-config.yaml
- .github/arc-runner-config.yaml
Adds additional nodes for Nvidia A10G and M60 GPUs. Resolves pytorch/ci-infra#130
> Add support for Nvidia A10G and M60

- .github/actions/setup-nvidia/action.yml
The driver version has been tested in https://github.com/pytorch/pytorch/pull/121684/files#diff-29beca0a6918592fa0a11a880d16819b877a7bfcede2747ee3c588f64e65d7cf 
cc @ptrblck @atalman @malfet @huydhn @seemethere
> Update default nvidia driver version for incoming CUDA 12.4

- s3_management/manage.py
Follow up after https://github.com/pytorch/test-infra/pull/5145
> Use antlr4 as allowed package

- s3_management/manage.py
This reverts commit 696afdccf1a2028735f14c0d28e48036feebfdbb. As is not required
> Revert "Use antlr4 as allowed package (#5147)"

- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
> [hud][ez] Add tooltip (title) to the force-merged pr numbers

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
way too aggressive for PRs as it is right now
> [bot] Turn of label_to_label config for pull requests

- torchci/lib/bot/autoLabelBot.ts
First commit is just moving functions outside of the bot and into global
Second commit has actually real changes
* Moves functions outside of function myBot to be global (imo makes functionality easier to read)
* Removes function `addLabel` and individual calls to `addLabels` in favor of `addNewLabels`
* Attempts to use `existingLabels`, `addedLabel` instead of `labels`, `label` everywhere to make things clearer
* More stuff I'm too lazy to specify
Should have no impact on functionality, I'm just shifting things around
> [bot][ez] Refactor autolabel bot

- torchci/components/additionalTestInfo/TestInfo.tsx
Display test counts + times info 
Maybe add skips in a future PR?
https://torchci-p0oj9kqfs-fbopensource.vercel.app/pytorch/pytorch/commit/e10b2ba357f7998edaec5a181352c02ae503ccb9
> [TDB] Test counts + times info

- torchci/components/JobLinks.tsx
- torchci/components/WorkflowBox.tsx
controversial change
I dislike mentally converting between something like 110 min and 1hr 50min, so change all time displays to use durationDisplay 
for 90 min:
durationHuman: 1h 30min
durationDisplay: 1.5h
> [HUD] Consistent time display

- torchci/pages/api/drci/drci.ts
https://github.com/pytorch/test-infra/pull/5192
I didn't realize there were more :clown_face:
Rip easy info into how many people this affects lol
> [DrCI] Link to hud instead of gh issue for related disabled test pt2

- torchci/components/additionalTestInfo/RerunInfo.tsx
- torchci/components/additionalTestInfo/TestInfo.tsx
Group reruns by flaky/failing/succeed but rerun anyways
Incidentally fixes error w/ showing traceback
Add some text to explain what's going on
https://torchci-git-csl-tdafixreruns-fbopensource.vercel.app/pytorch/pytorch/commit/0116ffae7f94f35a2c712e186a0b371959b68c64
> [TDB] Better rerun display

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
Let's align around single naming
> `topic: bc_breaking` -> `topic: bc breaking"

- torchci/pages/failure.tsx
Ex https://hud.pytorch.org/failure?name=pull%20%2F%20linux-focal-cuda12.1-py3.10-gcc9-sm86%20%2F%20test%20(default%2C%204%2C%205%2C%20linux.g5.4xlarge.nvidia.gpu)&jobName=undefined&failureCaptures=%5B%22test_public_bindings.py%3A%3ATestPublicBindings%3A%3Atest_correct_module_names%22%5D
New (adds the blue link):
It links to https://hud.pytorch.org/flakytest?name=test_correct_module_names&suite=TestPublicBindings&limit=100
Non test page looks the same
> [HUD] Add link from more like this/failures page to flakytest/test failure page it looks like a test

- torchci/components/GroupJobConclusion.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
https://github.com/pytorch/test-infra/assets/108101595/e58327bc-3856-4b33-82e2-788843787452
> Expand grouped cells on doubleclick

- terraform-aws-github-runner/modules/runners-instances/policies/instance-role-trust-policy.json
> Remove sts:AssumeRole for arn:aws:iam::391835788720:root on *-github-action-runners-runner-role

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Fixes: https://github.com/pytorch/test-infra/issues/5191
> Update cuda driver to NVIDIA-Linux-x86_64-550.54.15

- .github/workflows/torchci.yml
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Highlights the relevant command to make it pop
And also share installation steps in case it still doesn't work
> [BE] Make prettier's linting command easier to notice when it fails in CI

- torchci/components/DynamicTitle.tsx
- torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/_app.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Tried using `useEffect(()=> { document.title = "..."; }, []};` trick initially, but this does not seem to work reliable, so end up adding `DynamicTitle` component that defines a context(thank you ChatGPT for the hint on how to read React docs), and define `useSetTitle(title:string)` hook to update page title from the components
Also make title of top level HUD pages smaller
> [HUD] Add PR title to the page title

- .github/workflows/update-drci-comments.yml
> Enable Dr.CI on pytorch/data

- torchci/README.md
> [BE] Fix path to code in readme

- .github/lf-canary-scale-config.yml
Relates to pytorch/ci-infra#199 and pytorch/ci-infra#201.
> Create a scale config for canary

- torchci/components/CommitStatus.tsx
- torchci/components/WorkflowBox.tsx
- torchci/components/additionalTestInfo/RerunInfo.tsx
- torchci/components/additionalTestInfo/TestCounts.tsx
- torchci/components/additionalTestInfo/TestInfo.tsx
- torchci/lib/GeneralUtils.ts
- torchci/lib/bot/utils.ts
- torchci/lib/githubFunctions.ts
- torchci/pages/api/auth/[...nextauth].js
- torchci/pages/api/github/dispatch/[repoOwner]/[repoName]/[workflow]/[sha].ts
- torchci/pages/api/log_annotation/[repoOwner]/[repoName]/[annotation].ts
Click the button to regenerate test info.  Works even if job is pending, but data may be incomplete
> [TDB] Add button to regenerate test info

- s3_management/manage.py
Required for rocm-triton workflows
> Update manage.py - add llnl_hatchet package

- aws/lambda/log-classifier/ruleset.toml
Make the FAILED/SUBFAIL non capturing
> [log classifier][ez] After #5289: make failed/subfail group non capturing

- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
- torchci/lib/benchmark/compilerUtils.ts
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/torchao.tsx
- Remove the incorrect HTTP request to compiler_benchmark_performance
- Fix the GraphPanel on the summary page.
> [torchao] Fix torchao GraphPanel

- torchci/components/benchmark/common.tsx
- torchci/components/benchmark/compilers/ModelGraphPanel.tsx
- torchci/components/benchmark/compilers/ModelPanel.tsx
- torchci/components/benchmark/compilers/SummaryPanel.tsx
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/torchao.tsx
Fix Model Graph Panel for TorchAO dashboard.
> [torchao] Fix the model graph panel

- torchci/components/benchmark/compilers/ModelPanel.tsx
- torchci/rockset/inductor/__sql/torchao_query.sql
- torchci/rockset/inductor/torchao_query.lambda.json
- torchci/rockset/prodVersions.json
There is a bug in the RockSet SQL query parameter type. Need to update the SQL version to fix it.
> [torchao] Update torchao_query version

- s3_management/manage.py
- s3_management/update_dependencies.py
Follow up after https://github.com/pytorch/test-infra/pull/5315
> Add zipp s3 packages

- tools/scripts/generate_binary_build_matrix.py
- Add support for CUDA 12.4 in `test` channel
> [cuda] Add support for CUDA 12.4 in `test` channel

- .github/scripts/anaconda-prune/prune.sh
Simplify logic, remove everything but last two versions for torch.
Follow up after: https://github.com/pytorch/test-infra/pull/5332
> Adjust anaconda prune logic

- torchci/components/WorkflowDispatcher.tsx
Trying to figure out when those started to fail
> Add `linux-aarch64` dispatch

- torchci/components/NavBar.tsx
add Testing overhead dashboard to navbar
> add Testing overhead dashboard to navbar

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
We introduced a retry mechanism, once we found that a few yum commands could fail temporarily and at random due to intermittent locking failures.
The problem is that we're relying in a blind non-tagged version of a 3rd party code, and running it:
```
sudo sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"
```
this was flagged as a security risk, and a breaking dependency on our infra to external resource that can go offline without previous notice.
So, as the retry code should be very simple, we opted to implement a retry function directly in the script itself.
thanks @malfet and @seemethere for the improvement proposal.
Full logs of the test can be seen P1449499724 (internal only)
> Replaces the retry mechanism from a reusable code to a function for user-data.sh

- .github/scale-config.yml
Reverts pytorch/test-infra#5382
> [Reland] "Add linux.g6.4xlarge.experimental.nvidia.gpu runner type"

- aws/ami/windows/scripts/Installers/Initialize-Python3.ps1
- aws/ami/windows/scripts/Installers/Install-Choco-GenerateProfile.ps1
- aws/ami/windows/scripts/Installers/Install-Miniconda3.ps1
- aws/ami/windows/windows.pkr.hcl
Update Miniconda on Windows AMI
> [Windows AMI] Bump minconda to 24.4.0

- tools/scripts/generate_binary_build_matrix.py
add cuda aarch64 build for torchvision and torchaudio
> [aarch64] add cuda aarch64 torchvision and torchaudio

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
> Fallback to Node16 while upgrading runner to AmazonLinux2023

- s3_management/manage.py
> Add pytorch_triton_xpu to list of allowed packages

- .github/workflows/lambda-release-tag-runners.yml
> Fix typo preventing auto-creation of release labels

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
Fix bug accidentally added in https://github.com/pytorch/test-infra/commit/a979143061ac9dd94156c61f32b77dab828e0f95#diff-02a306e6041fa6fa0fe21f565eed9d406b885edcbdf2aab57eb7db2fc66296b0L89
> Fix bug with emitting logs from runners

- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/rockset/metrics/__sql/workflow_load.sql
- torchci/rockset/prodVersions.json
Adds a few workflows to some charts
> [ez][HUD] TTS, workflow load chart: add rocm, rocm periodic, inductor periodic

- torchci/components/JobLinks.tsx
- torchci/components/ReproductionCommand.tsx
Fixes https://github.com/pytorch/pytorch/issues/131657
Example: 
```
PYTORCH_TEST_WITH_SLOW=1 python test_testing.py -k test_cuda_assert_should_stop_common_device_type_test_suite_cuda
```
* fixes repro command
* change icon from link to copy
* attempts to include some env vars in repro command
This doesn't use the repro command given in the logs (which is more accurate) because I still haven't figured out a way to hook into the logs + xml
> [HUD] Fix repro copy paste

- torchci/lib/bot/cliParser.ts
- torchci/test/mergeCommands.test.ts
To prevent things like https://github.com/pytorch/pytorch/pull/133247#issuecomment-2284725996
> Require white space after pytorchbot

- .github/workflows/build_wheels_linux.yml
This is failing in trunk atm https://github.com/pytorch/test-infra/actions/runs/10424834270/job/28874449614
> Fix SC lint failure after #5557

- torchci/clickhouse_queries/queued_jobs_by_label/query.sql
> [CH migration] Add queued_jobs_by_label

- torchci/clickhouse_queries/master_commit_red_avg/params.json
- torchci/clickhouse_queries/master_commit_red_avg/query.sql
- torchci/pages/metrics.tsx
TSIA.
https://torchci-git-fork-huydhn-migrate-master-comm-fa10f7-fbopensource.vercel.app/metrics
> Migrate master_commit_red_avg query

- torchci/clickhouse_queries/last_branch_push/params.json
- torchci/clickhouse_queries/last_branch_push/query.sql
Tested in ClickHouse Cloud UI
Does not include changes to make HUD actually invoke this query
> Add ClickHouse version of last_branch_push query

- .github/actions/setup-nvidia/action.yml
- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Cherry pick https://github.com/pytorch/test-infra/pull/5330 to release branch to resolve Amazon Linux 2023 issues
> [cherry-pick] Adds kernel-modules-extra and fixes nvida yum repo url for amazon linux 23

- .github/scale-config.yml
To be used in binary build workflow
> Add linux.24xlarge.ephemeral runner

- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/rockset/metrics/__sql/workflow_load.sql
- torchci/rockset/prodVersions.json
Corrects a typo in https://github.com/pytorch/test-infra/pull/5502
> [ez][HUD] TTS, workflow load chart: rocm-periodic

- s3_management/manage.py
Mirror to hold only index.html files. The structure should be exactly the same as download.pytorch.org
> Add mirror of download.pytorch.org to pytorch-test

- s3_management/manage.py
Reverts pytorch/test-infra#5599
Need to change OIDC settings first. Will reland after OIDC cahange is done.
> Revert "Add mirror of download.pytorch.org to pytorch-test"

- torchci/components/metrics/panels/ScalarPanel.tsx
> [hud][ch] Metrics page scalar panel can toggle ClickHouse

- torchci/lib/clickhouse.ts
- torchci/pages/metrics.tsx
The query was added by @ZainRizvi in https://github.com/pytorch/test-infra/pull/5573/.
This PR just enables it in HUD
> [hud][ch] Enable CH for last_branch_push

- s3_management/manage.py
Reland of original PR: https://github.com/pytorch/test-infra/pull/5599
underlining issue should be fixed
> Reland "Add mirror of download.pytorch.org to pytorch-test"

- aws/lambda/log-classifier/ruleset.toml
> [ez] Add a log classifier rule for check-labels

- aws/lambda/log-classifier/src/bedrock.rs
Should fix the problem seen in https://github.com/pytorch/test-infra/issues/5613 as we now enforce that constraint in make_query.
> [log classifier] fix https://github.com/pytorch/test-infra/issues/5613

- .github/actions/setup-binary-builds/action.yml
Refer the xpu torchaudio nightly build failure https://github.com/pytorch/audio/actions/runs/10700830894/job/29665444924
> fix xpu torchaudio wheel build failure

- torchci/clickhouse_queries/commit_jobs_query/query.sql
- torchci/clickhouse_queries/hud_query/query.sql
- torchci/lib/fetchHud.ts
Also adds in materialized view optimization for commit_jobs_query
> [ch][hud] Hud query

- torchci/clickhouse_queries/commit_failed_jobs/query.sql
- torchci/clickhouse_queries/pr_commits/query.sql
- torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
- torchci/lib/fetchPR.ts
- torchci/lib/fetchRecentWorkflows.ts
- torchci/pages/api/drci/drci.ts
the dr ci queries are a bit slow (15s for the recent jobs query)
still gated, did some brief checking on Dr. CI comments but I think it could use more checking
Dr. CI tests will need to be rewritten for clickhouse mocks
I'm a little tempted to just switch over and not gate keep for dr. ci
For comparing:
```
curl "http://localhost:3000/api/drci/drci" --data 'repo=pytorch' > new.json
```
```
--url 'https://www.torch-ci.com/api/drci/drci' \
--header 'Authorization: i9ju23nf39nunu3asn' \
--data 'repo=pytorch' > orig.json
```
```
import json
from library import REPO_ROOT
import re
def failures(thing):
for pr_num in thing:
for classification in thing[pr_num]:
thing[pr_num][classification] = sorted(thing[pr_num][classification], key=lambda x: x["id"])
for failure in …
```
> [ch] pr_commits, some dr ci queries

- tools/scripts/generate_binary_build_matrix.py
- tools/scripts/generate_release_matrix.py
> Release 2.5 advance release versions

- .github/workflows/clickhouse-replicator-dynamo-lambda.yml
- .github/workflows/clickhouse-replicator-s3-lambda.yml
- aws/lambda/clickhouse-replicator-dynamo/Makefile
- aws/lambda/clickhouse-replicator-dynamo/README.md
- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
- aws/lambda/clickhouse-replicator-dynamo/requirements.txt
- aws/lambda/clickhouse-replicator-s3/Makefile
- aws/lambda/clickhouse-replicator-s3/README.md
- aws/lambda/clickhouse-replicator-s3/lambda_function.py
- aws/lambda/clickhouse-replicator-s3/requirements.txt
Copied from huys PR since idk if i can commit directly to a fork
https://togithub.com/pytorch/test-infra/pull/5419
> [ch] Add lambda functions for upload from s3/dynamo -> CH

- torchci/pages/metrics.tsx
Removes the failure chart since that was just the inverse of the success chart
> [EZ] Remove failure rate from LF metrics

- torchci/pages/metrics.tsx
- torchci/rockset/metrics/__sql/lf_rollover_percentage.sql
- torchci/rockset/metrics/lf_rollover_percentage.lambda.json
- torchci/rockset/prodVersions.json
Adds a graph showing the percentage of jobs on the linux foundation
> [HUD] add percentage for linux rollover

- torchci/components/ErrorBoundary.tsx
- torchci/components/JobArtifact.tsx
- torchci/components/JobLinks.tsx
- torchci/components/JobTooltip.tsx
- torchci/components/LoggedInMenu.tsx
- torchci/components/LoginSection.tsx
- torchci/components/PageSelector.tsx
- torchci/components/ReproductionCommand.tsx
- torchci/components/TestInsights.tsx
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/pages/[repoOwner]/[repoName]/issues/[issueNumber].tsx
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/torchao.tsx
- torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/pages/login_test.tsx
- torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
- torchci/pages/torchbench/userbenchmark.tsx
- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
ran `yarn format` so it doesn't create annoying changes when trying to lint in future prs
> Run yarn format

- torchci/lib/bot/index.ts
- torchci/lib/bot/triggerInductorTestsBot.ts
- torchci/test/triggerInductorTestsBot.test.ts
Fix spurious errors from https://github.com/pytorch/test-infra/pull/5662
We use @pytorch instead of @pytorchbot so actual pytorchbot doesn't get confused and we don't have a race condition. We can change this later
> [inductor] fix spurious errors

- torchci/lib/bot/triggerInductorTestsBot.ts
- torchci/test/triggerInductorTestsBot.test.ts
A nice quality of life change as we work on testing
> [inductor] react on workflow trigger comments

- torchci/clickhouse_queries/job_duration_avg/query.sql
- torchci/clickhouse_queries/job_duration_percentile/query.sql
- torchci/clickhouse_queries/last_successful_jobs/query.sql
- torchci/clickhouse_queries/last_successful_workflow/query.sql
- torchci/clickhouse_queries/master_commit_red_avg/query.sql
- torchci/clickhouse_queries/queue_times_historical/params.json
- torchci/clickhouse_queries/queue_times_historical/query.sql
- torchci/clickhouse_queries/queued_jobs/query.sql
- torchci/clickhouse_queries/queued_jobs_by_label/query.sql
- torchci/clickhouse_queries/tts_avg/query.sql
- torchci/clickhouse_queries/tts_percentile/query.sql
- torchci/clickhouse_queries/workflow_duration_avg/query.sql
- torchci/clickhouse_queries/workflow_duration_percentile/query.sql
- torchci/clickhouse_queries/workflow_load/params.json
- torchci/lib/clickhouse.ts
- torchci/pages/metrics.tsx
- torchci/rockset/metrics/__sql/workflow_duration_percentile.sql
- torchci/rockset/prodVersions.json
With this, I think the top 6 rows on the metrics page all can use clickhouse.
VIsit preview page: https://torchci-git-csl-chmoremetrics-fbopensource.vercel.app/metrics
> [ch][HUD metrics] some more queries

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
Allow for batching dynamo events in the lambda - to actually have larger batches, the lambda triggers need to be changed on their own
Adds async settings
Tested by making a different lambda with this code
> [ch] Allow for batched lambda events for dynamo replicator

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
From https://github.com/pytorch/test-infra/pull/5655/files
> [ez][ch] Fix typo in dynamo replicator 

- .github/actions/setup-miniconda/README.md
Discovered as I was using this workflow :)
> [hygiene] Update typo in setup-miniconda README.md

- torchci/lib/drciUtils.ts
- torchci/lib/fetchIssuesByLabel.ts
- torchci/pages/api/drci/drci.ts
> [ch] Issue query always uses CH

- .github/workflows/build_wheels_windows.yml
Works for https://github.com/pytorch/pytorch/issues/114850
> Fix xpu installation for XPU windows wheel build

- torchci/lib/bot/triggerInductorTestsBot.ts
> Add huydhn to the list of inductor test bot users

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
- aws/lambda/clickhouse-replicator-s3/lambda_function.py
Errors somewhere that I need to check
> Revert "[ch] replicator lambdas: external contribution stats (s3), wait time/pr_stats (dynamo)"

- .github/workflows/build_wheels_windows.yml
Works for pytorch/pytorch#114850
> Fix XPU Windows binary build clean up step

- .github/workflows/build_wheels_windows.yml
Works for pytorch/pytorch#114850
> Fix XPU Windows binary build smoke test failure

- torchci/clickhouse_queries/log_captures_count/query.sql
- torchci/pages/metrics.tsx
Small differences with original that I think are just due to _event_time -> created_at
> [ch] log_capture_count

- .github/workflows/revert-tracker.yml
installs clickhouse and sets up environment variables
> revert printer: fix clickhouse usage in workflow

- torchci/lib/bot/autoLabelBot.ts
> Add autolabeling for export

- aws/lambda/clickhouse-replicator-s3/lambda_function.py
I think I had a landrace with myself
Tested by backfilling stable_pushes
> [ch] Fix some s3 replicators

- torchci/clickhouse_queries/oss_ci_benchmark_branches/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
- torchci/components/benchmark/BranchAndCommitPicker.tsx
- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/llms.tsx
- torchci/pages/benchmark/torchao.tsx
TSIA.  Those queries are also outdated locally as I have updated them recently but didn't remember to sync them to `clickhouse_queries` folder.
Lots of casting, it will be a great pleasure to purge Rockset branch logic eventually :)
https://torchci-git-fork-huydhn-migrate-ossci-queries-ch-fbopensource.vercel.app/benchmark/llms
> [CH] Migrate gpt-fast + micro benchmark page

- .github/workflows/update_test_file_ratings.yml
- tools/torchci/clickhouse.py
- tools/torchci/download_logs.py
- tools/torchci/td/get_merge_base_info.py
- tools/torchci/td/historical_class_failure_correlation.py
- tools/torchci/td/td_heuristic_historical_edited_files.py
- tools/torchci/td/utils.py
* Enables caching for query_clickhouse
* Migrate som adhoc queries to clickhouse, mostly TD related queries
* Some random fixes for some things
> [ch] various ad hoc queries, mostly TD related

- .github/scripts/get_tutorials_stats.py
- .github/workflows/upload-tutorials-stats.yml
* Upload to s3 instead of dynamodb
* Output in csv format for easier ingestion internally (csv also lacks header line to make ingestion internally easier)
* Randomly update aws credentials 
* aws credentials were changed in https://github.com/pytorch-labs/pytorch-gha-infra/pull/482
* Related to D63860531
> tutorials stats upload to upload to s3 instead of dynamodb

- torchci/clickhouse_queries/flaky_tests/query.sql
- torchci/lib/fetchFlakyTests.ts
Migrate queries for flaky test bot
Not bothering to gate
Sanity checked that outputs of the queries had same results over the same 3 hour window, but only checked for 1 window
> [ch] disablebot aka flaky test bot

- .github/scripts/get_tutorials_stats.py
Corresponds to D64068999
Adds date file to tutorials filename csv
* Fixes dup bug that case 6k+ rows instead of 4k
* Use UTC timezone
* Use named tuples for readability
> tutorials stats filenames data to also upload date

- s3_management/manage.py
To Fix errors on https://github.com/pytorch/pytorch/pull/137653
> Add nvidia-cusparselt-cu12 to list of allowed packages

- tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
Reverts pytorch/test-infra#5747
Reverting due to: https://github.com/pytorch/ao/issues/1063
> Revert "[Temp] Use Meta CDN for building domain binaries"

- .github/actions/update-viablestrict/action.yml
- .github/workflows/tests.yml
- tools/scripts/fetch_latest_green_commit.py
- torchci/clickhouse_queries/commit_jobs_batch_query/params.json
- torchci/clickhouse_queries/commit_jobs_batch_query/query.sql
Corresponds to https://github.com/pytorch/pytorch/pull/138262
> [ch] viable strict

- .github/workflows/scale_config_validation.yml
We should also trigger the validation workflow when the validation script is updated
> [EZ] [BE] Run workflow when validation script is updated

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> Specify scale-config file used when logging failures

- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/api/[repoOwner]/[repoName]/pull/[prNumber].ts
- torchci/pages/metrics.tsx
* Fixes ttrs scalar panels for CH because using the wrong metric name/column
* fetchPR called from api/.../pr number was not using useCH toggle value
> [ch][hud] Fix some ttrs panels, make api/.../pr number respect use CH toggle

- torchci/package.json
- torchci/yarn.lock
To get rid of dependency on compromised vm2 package, see https://github.com/pytorch/test-infra/security/dependabot/198
> [TorchCI] Update pac-resolver

- s3_management/manage.py
Not that perf matters here, but search in list is O(N), while in set is O(1)
> [BE] Keep `PACKAGE_ALLOW_LIST` as set

- torchci/components/CheckBoxSelector.tsx
- torchci/pages/failure.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
I see this format used a lot, so I decided to make a component for it
> [HUD][BE?] New CheckBoxSelector component

- .github/workflows/build_wheels_linux.yml
Also, error out if conda setup failed
> [AARCH64] Do not depend on builder

- torchci/components/LoadingPage.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
adding LaodingPage to Hub table during data fetching
MUI: MIT LICENSE (Pre-approved oss license)
> [BE] Add rendering loading page in HUD TABLE view

- torchci/components/LogViewer.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
I think this is something we're supposed to do
> [HUD] Remove listeners on unmount

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciBot.test.ts
Get label info from CH instead of Github to reduce usage of rate limit
> [drci][ez] Get label info from CH

- torchci/package.json
- torchci/yarn.lock
Run into similar issue like this: https://github.com/vercel/react-tweet/issues/80
solved by adding
```
"resolutions": {
"@babel/runtime": "^7.24.6"
},
```
Explained in this  [issue](https://github.com/vercel/next.js/issues/35110#issuecomment-2131108641)
> [Add dependency] 

- torchci/components/WorkflowDispatcher.tsx
- torchci/lib/GeneralUtils.ts
- torchci/pages/api/github/dispatch/[repoOwner]/[repoName]/[workflow]/[sha].ts
Dunno when this broke, it was before the next update, but fix workflow dispatcher on HUD
`return void stuff` because after the next update, I was getting `API handler should not return a value`.  Next wanted it to return undefined, and void somethng is the same as evaluate something and then return undefined. Ref: https://github.com/vercel/next.js/discussions/48951
> [HUD] Fix workflow dispatcher

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
related to https://github.com/pytorch/pytorch/issues/138440
cc @atalman
> Windows AMI - Cuda 12.6

- .github/workflows/linux_job.yml
> Turn off fail-fast on Linux workflows

- .github/workflows/linux_job.yml
Reverts pytorch/test-infra#5898
> Revert "Use Almalinux-builder in linux-job by default"

- .github/workflows/linux_job.yml
- .github/workflows/linux_job_v2.yml
Adding Linux job v2 that uses almalinux-builder by default. Will be migrating everyone to this job and depecating old linux-job. 
Testing Error Try/Catch on Commit 2:
```
+ chmod +x /home/ec2-user/actions-runner/_work/_temp/exec_script
+ trap handle_error ERR
+ rm non_existent_file
rm: cannot remove 'non_existent_file': No such file or directory
++ handle_error
++ echo 'An error occurred.'
An error occurred.
```
> Add Linux job v2

- torchci/lib/drciUtils.ts
- torchci/test/drci.test.ts
Ignores the tag when it's commented out.
> Correctly detect "merge blocking" tag in CI sevs

- torchci/clickhouse_queries/issue_query/query.sql
- torchci/lib/drciUtils.ts
- torchci/lib/types.ts
- torchci/test/disableFlakyBot.test.ts
- torchci/test/drci.test.ts
- torchci/test/jobUtils.test.ts
Corresponds to https://github.com/pytorch/pytorch/pull/140636
> [ez][drci] Make merge blocking sevs be based on label instead of string

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
> Windows AMI update cudnn-windows-x86_64-9.5.1.17_cuda12-archive

- tools/scripts/generate_binary_build_matrix.py
After https://github.com/pytorch/test-infra/pull/5922 - We need to exclude only for windows
> Fix adding cuda 12.6 logic

- torchci/pages/api/corresponding_workflow_id.ts
- torchci/pages/api/flaky-tests/flakytest.ts
Checked flakytest still worked by going to https://torchci-git-csl-chrandomadhocqueries-fbopensource.vercel.app/flakytest?name=test_backward_sqrt_cuda_float32&suite=TestNestedTensorOpInfoCUDA&limit=100
Checked curl call still looked the same for corresponding_workflow_id
> [CH] api/flaky-tests/flakytest and api/corresponding_workflow_id

- .github/scripts/install_xpu.bat
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_windows.yml
Depends on https://github.com/pytorch/builder/pull/2038
Works for https://github.com/pytorch/pytorch/issues/139722 and https://github.com/pytorch/pytorch/issues/114850
> [XPU] Upgrade XPU support package version to 2025.0

- torchci/clickhouse_queries/queued_jobs/query.sql
Optimizes the query to use just 10% of the resources compared to before by :
- Adding a max time range to limit results to just the relevant window
- Move the time range filter to the earlier query. Not sure why it makes such a big difference, but it does. Maybe due to the lack of FINAL there? Adding in FINAL tanks the performance
Perf change:
- Memory used: 9.7 GB -> 0.8 GB  
- Elapsed time: 3.5 s -> 0.4s
- Rows read: 12 million -> 8 million
> [BE] [Perf optimization] Speed up queued_jobs query

- torchci/components/DrCIButton.tsx
- torchci/lib/clickhouse.ts
- torchci/lib/rateLimit.ts
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/api/drci/drci.ts
Add button on top right where logged in users can update Dr. CI https://torchci-git-csl-drcibutton-fbopensource.vercel.app/pr/138513
I am failing to log in on the preview, but it works locally, probably due to prod vs preview env vars
Rate limit users to 10 calls / hr
Is this a good idea? No clue
Should this be limited to people with write access?
> [HUD] Button for updating Dr. CI

- .github/actions/binary-upload/action.yml
Followup after: https://github.com/pytorch/test-infra/pull/5968
> Simplify logic authorize and upload files in one step - binary-upload

- .github/actions/binary-upload/action.yml
Seeing issue that nightly branch trying to use test auth:
https://github.com/pytorch/vision/actions/runs/11971829405/job/33403106608#step:19:185
> Update action.yml - fix CHANNEL check

- .github/workflows/_binary_upload.yml
Upload only if on Manylinux 2.28
> Fix binary upload logic

- .github/actionlint.yaml
- .github/workflows/clang-tidy-linux.yml
- .github/workflows/clang-tidy-macos.yml
- tools/clang-tidy-checks/setup.sh
Uploads are likely to fail, but this is to be fixed by https://github.com/pytorch/test-infra/pull/5980
> [tools] Update llvm version from 17.0.6 to 19.0.4

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Reverts pytorch/test-infra#5958
> Revert "Set min_runners for linux.2xlarge to 0"

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Reverts pytorch/test-infra#5979
> Revert "Set min_runners for linux.4xlarge to 0 (#5958)"

- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
- torchci/components/benchmark/compilers/common.tsx
- torchci/lib/benchmark/compilerUtils.ts
This goes together with https://github.com/pytorch/pytorch/pull/142034.  MPS benchmark is running in eager mode at the moment.
> Display MPS benchmark results in eager mode

- .github/workflows/backfill-workflow-job.yml
- torchci/scripts/backfillJobs.mjs
As in title, remove Rockset from the backfill script.
Do this ahead of time since there is no toggle like on HUD, so if the Rockset API stops working, this script will stop working immediately too.
> Remove Rockset from backfill script

- tools/torchci/check_alerts.py
- torchci/lib/fetchHud.ts
- torchci/lib/types.ts
- torchci/lib/useHudData.ts
Part of an effort to remove rockset and all related code after the migration is done
Changes api/hud to always use ClickHouse.  Remove the param that allows you to toggle between ClickHouse and Rockset since it won't be used
> [HUD][CH] api/hud to only use ClickHouse

- torchci/components/WorkflowDispatcher.tsx
- torchci/lib/fetchCommit.ts
- torchci/lib/fetchPR.ts
- torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/api/[repoOwner]/[repoName]/commit/[sha].ts
- torchci/pages/api/[repoOwner]/[repoName]/pull/[prNumber].ts
- torchci/pages/api/drci/drci.ts
Similar to https://github.com/pytorch/test-infra/pull/6034 but for api/.../commit and api/.../pull
> [HUD][CH] api/.../commit and api/.../pull to only use ClickHouse

- torchci/pages/metrics.tsx
Part of an effort to remove all references to rockset after the migration
> [HUD][CH] Some assorted components on metrics page to always use ClickHouse

- torchci/pages/metrics.tsx
Fixes a bug @clee2000 pointed out in https://github.com/pytorch/test-infra/pull/6039/files#r1879220367 (that PR got merged before I could push the fix)
> [EZ] Metrics page bugfix

- tools/scripts/generate_binary_build_matrix.py
Move current release candidate and configuration to 2.6.0
> Move current release candidate to 2.6.0

- torchci/pages/cost_analysis.tsx
there was an unhealthy mix of 'stopDate' and 'endDate' that broke the links. Also update the visual daterange / allow urls to contain daterange now
> fix date displaying on link copying

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Fix a potential bug from https://github.com/pytorch/test-infra/pull/6058, here is what I see in the CI when it happens https://github.com/pytorch/pytorch/actions/runs/12360769784/job/34497379880?pr=143316#step:5:165
> Clean up existing swapfile before trying to allocate a new one

- tools/scripts/generate_binary_build_matrix.py
Follow up after: https://github.com/pytorch/pytorch/pull/142294
> Enable rocm support on 3.13 python

- tools/scripts/generate_binary_build_matrix.py
Cherry-Pick https://github.com/pytorch/test-infra/pull/6062 to release
> [cherry-pick] add cu126 torchvision and torchaudio aarch64 build

- tools/scripts/generate_binary_build_matrix.py
Cherry-Pick https://github.com/pytorch/test-infra/pull/6070 to release
> [cherry-pick] Enable rocm support on 3.13 python

- torchci/clickhouse_queries/oss_ci_benchmark_branches/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
- torchci/components/NavBar.tsx
- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
A simple change to add the initial version of TorchAO LLM benchmark dashboard.
https://torchci-git-fork-huydhn-add-ao-llm-dashboard-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fao
> Add TorchAO LLM benchmark dashboard

- torchci/components/JobLinks.tsx
Previously it only used up if the job was failing, but when the job is no longer failing, the button goes away, making it hard to track down the issue
How to check preview: look for an unstable job (as of writing this, there is one) check that the button shows up.  Also check that the button doesn't show up on other jobs
> [HUD] Show the unstable button even if the job is successful

- torchci/.env.example
- torchci/README.md
> [HUD] Update README with info about getting access to Vercel

- torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
- torchci/lib/fetchPR.ts
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/pages/api/drci/drci.ts
Fixes https://github.com/pytorch/test-infra/issues/6106.  The issue is caused by an closed empty pull request with no commit https://github.com/pytorch/pytorch/pull/143615.
* Handle a PR with no commit in `fetchPR`. This function is used by Dr.CI to get all the commits in a pull request.
* Make sure that  Dr.CI only queries for open pull requests.
* Fix the broken HUD PR page https://hud.pytorch.org/pr/143615
Both
```
--url 'http://localhost:3000/api/drci/drci' \
--header 'Authorization: <REDACTED>' \
```
and
```
--url 'http://localhost:3000/api/drci/drci?prNumber=143615' \
--header 'Authorization: <REDACTED>' \
```
are working ok now.
https://torchci-git-fork-huydhn-fix-drci-issue-6106-fbopensource.ver …
> Handle closed pull requests and empty pull requests with no commit

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Same change as #6124 but for ARM systems.
> Update AMZN2023 version for ARM

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/metrics/panels/TimeSeriesPanel.tsx
TSIA
https://torchci-git-fork-huydhn-improve-ao-speedup-geomean-fbopensource.vercel.app/benchmark/llms?startTime=Mon%2C%2030%20Dec%202024%2019%3A35%3A02%20GMT&stopTime=Mon%2C%2006%20Jan%202025%2019%3A35%3A02%20GMT&granularity=day&lBranch=main&lCommit=dd82365333c66bc5f75e44411005fe3480fb9c3a4a6c702cff4247f5920ede5a&rBranch=main&rCommit=67bc310737b1d559087a12b1c5c9d5821db88207fa05a2fe6e4877d08580e81f&repoName=pytorch%2Fao&modelName=All%20Models&backendName=All%20Backends&dtypeName=All%20DType&deviceName=All%20Devices
> Compute geomean speedup metric for different quantizations

- .github/workflows/lint.yml
- .github/workflows/tflint.yml
- .lintrunner.toml
- terraform-aws-github-runner/modules/runner-binaries-syncer/variables.tf
- tools/rockset_migration/README.md
- tools/self-hosted-runner-utils/list-vpc-dependencies.sh
- torchci/clickhouse_queries/cost_job_per_gpu/query.sql
- torchci/clickhouse_queries/cost_job_per_owning_account/query.sql
- torchci/clickhouse_queries/cost_job_per_platform/query.sql
- torchci/clickhouse_queries/cost_job_per_provider/query.sql
- torchci/clickhouse_queries/cost_job_per_runner_type/query.sql
- torchci/clickhouse_queries/cost_job_per_workflow_name/query.sql
- torchci/clickhouse_queries/duration_job_per_gpu/query.sql
- torchci/clickhouse_queries/duration_job_per_job_name/query.sql
- torchci/clickhouse_queries/duration_job_per_owning_account/query.sql
- torchci/clickhouse_queries/duration_job_per_platform/query.sql
- torchci/clickhouse_queries/duration_job_per_provider/query.sql
- torchci/clickhouse_queries/duration_job_per_repo/query.sql
- torchci/clickhouse_queries/duration_job_per_runner_type/query.sql
- torchci/clickhouse_queries/duration_job_per_workflow_name/query.sql
* Copy over newlines_linter.py from https://github.com/pytorch/pytorch/blob/a94ec0a9a5ac91fcd9f69d6640ab0fe1efd068ae/tools/linter/adapters/newlines_linter.py
* Enable NEWLINE linter in CI
* Adds some files to the ignore list that probably shouldn't be changed
* Applies the linter `lintrunner -a --all-files --take NEWLINE`
We should move some of the adapter to some common place at some point, or make it so that init will take them from pytorch automatically
> [CI] Enable NEWLINE linter

- .github/workflows/_binary_conda_upload.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/_upload_docs.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
- .github/workflows/linux_job.yml
- .github/workflows/linux_job_v2.yml
- .github/workflows/macos_job.yml
- .github/workflows/update_disabled_tests.yml
- .github/workflows/windows_job.yml
Cherry pick of https://github.com/pytorch/test-infra/pull/6151
To fix failures building rc for vision and audio: https://github.com/pytorch/audio/actions/runs/12813180000
> [Cherry-Pick] upgrade download/upload artifact to v4

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/assets/build_matrix_linux_wheel_cuda.json
- tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
- tools/tests/assets/build_matrix_linux_wheel_nocpu.json
- tools/tests/assets/build_matrix_linux_wheel_xpu.json
- tools/tests/assets/build_matrix_macos_wheel.json
- tools/tests/assets/build_matrix_windows_wheel_cuda.json
- tools/tests/assets/build_matrix_windows_wheel_xpu.json
Required for Validations and generating new getting started page
> [Validations] Advance release config to 2.6

- tools/scripts/generate_binary_build_matrix.py
> only skip Win build for CUDA 12.8 for now

- aws/ami/windows/windows.pkr.hcl
Original Issue: https://github.com/pytorch/pytorch/issues/128835
Follow up on PR: https://github.com/pytorch/pytorch/pull/145319
> remove visual studio 2019 install in test infra

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
- aws/ami/windows/windows.pkr.hcl
https://github.com/pytorch/pytorch/issues/145570
CUDNN 9.7.0.66
CUDA 12.8.0
cc @atalman @ptrblck @nWEIdia
> Add CUDA 12.8 Windows AMI

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
https://github.com/pytorch/pytorch/issues/145570
follow up to https://github.com/pytorch/pytorch/pull/146717
cc @atalman
> update cudnn 9.7.1.26 for cuda 12.8 windows

- torchci/components/charts/line_rect_chart/component/RenderLinePickerOptions.tsx
- torchci/components/charts/line_rect_chart/component/helpers/DropList.tsx
- torchci/components/utilization/UtilizationPage.tsx
- torchci/components/utilization/components/TestSectionView/SingleTestView.tsx
- torchci/components/utilization/components/TestSectionView/TestSectionView.tsx
- torchci/components/utilization/components/TestSectionView/ToggleTestsGroup.tsx
- torchci/components/utilization/components/UtilizationJobSummary/UtilizationJobSummary.tsx
- torchci/pages/utilization/[workflowId]/[jobId]/[attempt]/[[...page]].tsx
fix the frame to fit chart, and modify content for sections
> [Utilization] Fix bugs and context

- torchci/clickhouse_queries/build_time_metrics/overall/params.json
- torchci/clickhouse_queries/build_time_metrics/overall/query.sql
- torchci/clickhouse_queries/build_time_metrics/sccache_stats/params.json
- torchci/clickhouse_queries/build_time_metrics/sccache_stats/query.sql
- torchci/clickhouse_queries/build_time_metrics/steps/params.json
- torchci/clickhouse_queries/build_time_metrics/steps/query.sql
- torchci/components/NavBar.tsx
- torchci/components/common/CheckBoxList.tsx
- torchci/pages/build_time_metrics.tsx
General part for viewing build time + how long the major steps take
Sccache stats for a certain job:
> [HUD] page for CI build metrics

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/assets/build_matrix_windows_wheel_cuda.json
- tools/tests/assets/build_matrix_windows_wheel_xpu.json
Fix lint by following lintrunner
Fix the tests by running `python -m tools.tests.test_generate_binary_build_matrix --update-reference-files`
> [ez] Fix lint and tests after #6298

- torchci/components/benchmark/llms/SummaryPanel.tsx
To hide the empty `speedup` metric
https://torchci-git-fork-huydhn-temp-fix-for-cacheb-8ebff1-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fpytorch&benchmarkName=TorchCache+Benchmark
> Add a temp fix to hide empty metric on CacheBench

- torchci/components/common/TextFieldSubmit.tsx
- torchci/components/tests/TestSearchForm.tsx
- torchci/lib/GeneralUtils.ts
- torchci/pages/build_time_metrics.tsx
- torchci/pages/failure.tsx
- torchci/pages/flakytest.tsx
- torchci/pages/tests/search.tsx
- torchci/pages/tests/testInfo.tsx
- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Just some generalizations + reorg of some functions
* New TextFieldSubmit component that is just a text field that takes an input, and a button for submitting the input. In the future, maybe this should be generalized to have more fields?
* Move encodeParams field to GeneralUtils
* Moves a useClickHouse useSWR wrapper to GeneralUtils
* Adjust some spacing for one of the components
> [ez][HUD] Move some functions around, new TextFieldSubmit component

- .github/actionlint.yaml
- .github/workflows/backfill-workflow-job.yml
- .github/workflows/log-classifier-lambda.yml
- .github/workflows/revert-tracker.yml
- .github/workflows/torchci.yml
- .github/workflows/update-queue-times.yml
- tools/linter/adapters/s3_init_config.json
- torchci/lib/utilization/fetchUtilization.test.ts
See https://github.com/pytorch/pytorch/pull/148469 for context
Also fix failing test, maybe package update changed the error string?
> Upgrade github ubuntu-20.04 runners to ubuntu-24.04

- .github/scripts/install_xpu.bat
Align with https://github.com/pytorch/pytorch/pull/148313
> [XPU] Upgrade XPU support packages version on Windows

- .lintrunner.toml
- torchci/clickhouse_queries/external_contribution_stats/query.sql
- torchci/clickhouse_queries/get_workers_on_period/query.sql
- torchci/clickhouse_queries/last_branch_push/query.sql
- torchci/clickhouse_queries/log_captures_count/query.sql
- torchci/clickhouse_queries/master_commit_red/query.sql
- torchci/clickhouse_queries/monthly_contribution_stats/query.sql
- torchci/clickhouse_queries/num_reverts/query.sql
- torchci/clickhouse_queries/queue_times_historical_pct/query.sql
- torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
- torchci/clickhouse_queries/reverts/query.sql
- torchci/clickhouse_queries/testStatsDistinctCount/query.sql
- torchci/clickhouse_queries/tts_avg/query.sql
- torchci/clickhouse_queries/unique_repos_in_runnercost/query.sql
Finish linting existing files. Broken down into 3 PRs just to be cautious
This is stacked on top of #6373. Is there a way to show the dependency in the PR UI?
> Apply SQLFLUFF linter to existing clickhouse queries (part 3/final)

- tools/scripts/generate_binary_build_matrix.py
Required to build the domain libraries correctly
> Cherry-Pick of #6401

- clickhouse_db_schema/oss_ci_queue_time_histogram/schema.sql
Doc Design: https://docs.google.com/document/d/1OiPv-ku_NvMgvnaMIbtnIEHTixJY28CBaKeMKJtglEk/edit?tab=t.0\
Add table schema for queue_time_histogram
> [Queue Time Historgam] add schema for QueueTimeHistorgam

- torchci/clickhouse_queries/workflow_load/query.sql
working preview:
https://torchci-git-addworkflowload-fbopensource.vercel.app/metrics
> [Metirc page] Add Rocm mi300 workflow to Workflow Per load metric graph

- torchci/.env.example
Vercel is no longer a valid place to get these creds from
> [BE] Update location to get sensitive credentials for

- torchci/lib/useScrollTo.ts
- torchci/styles/globals.css
Makes the highlight color for scroll to dark blue.  Feel free to suggest other colors
Light mode is unchanged
Old
New
> [ez][HUD] Add darkmode for scroll to highlight

- .github/workflows/lambda-do-release-runners.yml
add deployment for release
https://github.com/pytorch/test-infra/actions/workflows/lambda-release-tag-runners.yml
> [Queue Time Histogram] Add deployment step

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
- aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
add histogram generator, and logics to write to db table
remove s3 boto since we upload to db table directly. Currently write to fortesting db for testing.
Once it's complete, change to misc one
> [Queue Time Histogram] Add Histogram Generator

- torchci/components/CheckBoxSelector.tsx
- torchci/components/SettingsPanel.tsx
- torchci/components/hud.module.css
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
It's starting to get cluttered, so let's clean up the view
Before:
After:
> [BE][HUD] Clean up UI by adding a dropdown for settings

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
should comment this since this is only for some testing
> [type] Disable the local test without verify

- torchci/clickhouse_queries/experiment_rollover_percentage/query.sql
Those changes reflect the ones in https://github.com/pytorch/test-infra/pull/6493 so more description can be seen there.
> Fixes for query 'experiment_rollover_percentage' introduced on lf_rollover_percentage

- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/lib/benchmark/llms/common.ts
- torchci/lib/benchmark/llms/utils/llmUtils.ts
accidently merged it into the depended branch this is same as 
Fix bug for the failure handling
https://github.com/pytorch/test-infra/pull/6517
> Git Job Level Failure

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
This is the second part of https://github.com/pytorch/test-infra/pull/6530
> Update NVIDIA driver to 570.133.07 when launching the runner

- .github/workflows/build_wheels_linux.yml
Same as https://github.com/pytorch/pytorch/pull/150786
Wheel filename should be:
linux_aarch64 -> manylinux_2_28_aarch64
linux_x86_64 -> manylinux_2_28_x86_64
Test in CI
> Manylinux 2.28 make sure wheels are renamed

- .github/workflows/build_wheels_linux.yml
Cherry-Picks of https://github.com/pytorch/test-infra/pull/6538
> [Cherry-Pick] Manylinux 2.28 make sure wheels are renamed

- .github/scripts/get_tutorials_stats.py
- .github/workflows/upload-tutorials-stats.yml
- Modify the script to get last_updated for the file in pytorch repo under the docs directory.
> Expand script to collect dates for the pytorch/docs dir

- torchci/components/SevReport.module.css
- torchci/styles/globals.css
> [ez][HUD] Set color for darkmode sev banner

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
add setLogger() so in lambda it can display the INFO level log
> Fix log in lambda

- .github/scripts/repair_manylinux_2_28.sh
- .github/workflows/build_wheels_linux.yml
Make sure WHEEL tags follow manylinux 2.28 standart
> [Cherry-PIck] Repair Manylinux 2.28 wheels #6549

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
1. Provide more details using tooltip for the columns to reduce confusion
2. add clickable link to workflow job
Demo:
https://torchci-git-investigate-fbopensource.vercel.app/benchmark/llms?startTime=Tue,%2015%20Apr%202025%2021:57:10%20GMT&stopTime=Tue,%2022%20Apr%202025%2021:57:10%20GMT&granularity=day&repoName=pytorch%2Fexecutorch&benchmarkName=&modelName=mv3&backendName=xnnpack_q8&modeName=inference&dtypeName=&deviceName=Google%20Pixel%203%20(Rooted)%20(Android%2012)&archName=All%20Platforms
> Single View Table Improvement for benchmark

- torchci/components/queueTimeAnalysis/components/charts/QueueTimeCharts.tsx
- torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
- torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeCheckBoxList.tsx
> Wdvr/darkmode fix queuetime dark mode colors 

- terraform-aws-github-runner/README.md
Add a link to these recordings we did a year ago as a reference for onboarding folks to this tool.
> Add deep dive videos for the autoscaler

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/test_generate_binary_build_matrix.py
for issue https://github.com/pytorch/pytorch.github.io/issues/1993
> update quickstart UI to remove conda

- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
- torchci/lib/benchmark/llms/common.ts
- torchci/lib/benchmark/llms/utils/llmUtils.ts
add group_key to combine (deviceId, and display name) if any for dp visualizaition
rename additional_info to metadata_info
> [Device ID] visualize benchmark graph with group_key

- torchci/clickhouse_queries/get_workflows_for_commit/params.json
- torchci/clickhouse_queries/get_workflows_for_commit/query.sql
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Addresses issue https://github.com/pytorch/pytorch/issues/152718
Made workflow query generic in case it will be used in the future
> [Mergebot] Adding ciflow/pull in PR without pull and lint workflows

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
Fix bug that broke the torch ao UI due to the device_Id is not existed
> [bug] logic handle device_ID

- aws/lambda/log-classifier/fixtures/request.json
- aws/lambda/log-classifier/ruleset.toml
https://hud.pytorch.org/pr/151317
> Update pr_time_benchmarks log classification rule

- .github/actions/setup-binary-builds/action.yml
Cherry Pick https://github.com/pytorch/test-infra/pull/6624 to release
> [Cherry-Pick] Fix python 3.13t builds on aarch64 #6624

- torchci/pages/api/flaky-tests/disable.ts
Make the hud view more discoverable!
> Link to hud disabled view in GH issue

- .github/actions/setup-nvidia/action.yml
Cherry pick of https://github.com/pytorch/test-infra/pull/6637
> [Cherry-Pick] ci: Pin more nvidia-container dependencies #6637

- .github/actions/setup-windows/action.yml
Apply similar logic as in:
https://github.com/pytorch/pytorch/blob/main/.github/workflows/_win-build.yml#L74-L84
> Setting Windows Long Path

- torchci/pages/cost_analysis.tsx
allow AMD to be selected as a provider / owning account for the cost dashboard
> AMD (rocm) in cost dashboard

- torchci/components/metrics/panels/TimeSeriesTable.tsx
- torchci/pages/cost_analysis.tsx
> allow users to export cost table as csv

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
- torchci/components/metrics/panels/TimeSeriesTable.tsx
- torchci/lib/csvUtils.ts
- torchci/package.json
- torchci/yarn.lock
follow up on https://github.com/pytorch/test-infra/pull/6672#issuecomment-2914001188
> [BE] refactor csv export for cost dashboard & benchmark

- torchci/components/metrics/panels/TimeSeriesTable.tsx
- torchci/lib/csvUtils.ts
- torchci/styles/globals.css
Color fixes for dark mode cost table and cleanup of some unhelpful comments
> Color fixes for dark mode cost table

- s3_management/manage.py
This should allow fbgemm_gpu_genai to be visible on nightly index
> Add fbgemm_gpu_genai to allow list

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
> [EZ] Minor typo fix

- s3_management/manage.py
To unblock https://github.com/pytorch/pytorch/pull/154568
> Add nvidia_nvshmem_cu12 to list of allowed files

- aws/lambda/oss_ci_cur/lambda_function.py
was use clickhouse_connect=0.8.14 locally, but deployed 0..8.5, the  newer version does not accept string as datetime64. fixed the issuie
> [Fix the date conversion issue] [CUR]

- torchci/components/NavBar.tsx
- torchci/components/benchmark/llms/components/LLMsReport.tsx
- torchci/lib/benchmark/llms/utils/llmUtils.ts
https://torchci-git-aoui-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fao&benchmarkName=micro-benchmark+api
> AO Benchmark

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Update AMI for cuda 12.6 and 12.8. Linux cudnn update is here: https://github.com/pytorch/pytorch/pull/155576/
Remove CUDA 11 artifacts
> Windows AMI Update cudnn for cuda 12.6 and 12.8

- aws/ami/windows/windows.pkr.hcl
Something that https://github.com/pytorch/test-infra/pull/6742 missed.
> [AMI] Remove CUDA 11.8 install

- aws/lambda/oss_ci_cur/lambda_function.py
since our clickhouse data is replaceingMergeTable, it is safe to fetch the partial latest data for current day, and refetch data from previous day
> Overlap date for oss_ci_cur

- torchci/lib/datamodels/benchmark_group_request.ts
- torchci/lib/datamodels/zodUtils.ts
- torchci/package.json
- torchci/pages/api/benchmark/group_data.ts
- torchci/yarn.lock
The result will similar to, but with all unique models and configurations
> API to fetch all data in the format of data table for benchmark result

- torchci/pages/api/grafana_mcp/index.ts
To store history later on. Note username is only injected @ api level, so can't be adjusted from the frontend
> [torchagent] add username to lambda call

- torchci/components/queueTimeAnalysis/components/QueueTimeChartPage.tsx
- torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
- torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeCheckBoxList.tsx
- torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeSearchBar.tsx
- torchci/components/uiModules/UMCopyLink.tsx
- torchci/components/utilization/UtilizationReportPage/UtilizationReportPage.tsx
- torchci/components/utilization/UtilizationReportPage/hepler.ts
Add sym link  for queue time analysis
also improve the UmCopyLink to handle list of string with spaces and special charaters, 
https://torchci-git-addsylink-fbopensource.vercel.app/queue_time_analysis
> Add sym link for queue time analysis

- torchci/pages/api/benchmark/group_data.ts
the timestamp should not be granularity bucket but metadata_info.timestamp
> [benchmark] Fixbug to able to fetch nested fields

- aws/lambda/README.md
As in title, update readme after #6809 
I forgot I said I would do this in that PR... but on the bright side I can now include permalinks to code on the main branch
> [ez][lambdas] Update readme after #6809

- release/cut-release-branch.sh
> change instructions for running cut-release-branch script

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
- aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
- torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/query.sql
- torchci/clickhouse_queries/oss_ci_util/oss_ci_util_metadata/query.sql
- torchci/clickhouse_queries/oss_ci_util/oss_ci_util_ts/query.sql
- torchci/clickhouse_queries/queue_time_analysis/queue_time_query/query.sql
- torchci/clickhouse_queries/queue_time_analysis/queue_time_search_items/query.sql
Cleanup to sync everything in misc instead of fortesitng tables
> [Cleanup]move to existing misc instead of fortesting db table

- .github/workflows/build_wheels_macos.yml
Cherry Pick of M1 build: https://github.com/pytorch/test-infra/pull/6847
> Cherry Pick of M1 build #6847

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/flakyBotTests/flakyBotUtils.test.ts
The deduper was closing them automatically, ex the action right above this comment: https://github.com/pytorch/pytorch/issues/157070#issuecomment-3012384895
> [disablebot] Fix aggregate issues getting auto closed 

- .lintrunner.toml
- s3_management/backup_conda.py
- s3_management/manage.py
- s3_management/update_dependencies.py
Also applies all PYFMT patches to s3_management
> lint: Add s3_management to PYFMT

- torchci/clickhouse_queries/hud_query/query.sql
Follow up to https://github.com/pytorch/test-infra/pull/6884, see that one for context
> [ez][HUD] Filter out more workflow_event trigger jobs from hud query

- .github/workflows/check-alerts.yml
This repo is deprecated, don't monitor it for alerts any longer
> [BE] Stop monitoring builder job status

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
This log message was driving me insane and causing a lot of useless noise in the logs. Removing so I can preserve my sanity.
> runners: Remove debug logging for listRunners

- .github/scripts/benchmarks/gather_runners_info.py
- .lintrunner.toml
I noticed that some files weren't getting getting checked, so I am adding them here
> [ez][lint] Make inclusion path for mypy slightly broader

- torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_stats/query.sql
- torchci/components/utilization/JobUtilizationPage/JobUtilizationPage.tsx
- torchci/components/utilization/JobUtilizationPage/helper.ts
- torchci/components/utilization/WorkflowUtilizationPage/WorkflowUtilizationPage.tsx
- torchci/components/utilization/components/TestSectionView/RankTestView/RankTestView.tsx
- torchci/lib/utilization/fetchListUtilizationMetadataInfo.ts
- torchci/lib/utilization/fetchUtilization.ts
- torchci/lib/utilization/types.ts
UI fix to include the mem allocation and mem bandwidth for gpu
> Util UI for allocated memory

- .github/workflows/build_wheels_macos.yml
> Revert "Cherry Pick of M1 build #6847"

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/assets/build_matrix_linux_wheel_cuda.json
- tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
- tools/tests/assets/build_matrix_linux_wheel_nocpu.json
- tools/tests/assets/build_matrix_linux_wheel_xpu.json
- tools/tests/assets/build_matrix_macos_wheel.json
- tools/tests/assets/build_matrix_windows_wheel_cuda.json
- tools/tests/assets/build_matrix_windows_wheel_xpu.json
Advance version and configuration ahead of release 2.8
> Release 2.8 Update matrices

- torchci/pages/metrics.tsx
Adds correct sorting by default & color coding.
Before:
After:
> [HUD] Enhance queue time visualization with color coding and sorting

- torchci/components/benchmark/BranchAndCommitPicker.tsx
- torchci/components/benchmark/HighlightMenu.tsx
Made with Claude code.  This is a small feature to highlight the selected commit.  This is useful the dropdown list is long.
The branch and commit are bold when they are selected on https://torchci-git-fork-huydhn-highlight-selected-83f4be-fbopensource.vercel.app/benchmark/llms?repoName=vllm-project%2Fvllm
> [BE] Highlight the selected branch and commit

- s3_management/update_dependencies.py
Adding dependencies to unblock https://github.com/pytorch/pytorch/pull/160956
> Update nvidia cuda 13.0 dependencies

- s3_management/manage.py
Related to https://github.com/pytorch/pytorch/pull/160956
follow up for https://github.com/pytorch/test-infra/pull/7038
cc @atalman
> fix cudnn naming for CUDA 13 package

- s3_management/manage.py
follow up for https://github.com/pytorch/test-infra/pull/7038/files
nccl-cu13 is another exception
> Add nvidia-nccl-cu13 pkg

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
Current sorting uses the workflow dispatch time, what does not match the order for commit sequence. The correct approach is to sort by merge timestamp for all workflows.
This was causing errors in the detection logic, as it was mixing the order of jobs for commit evaluation, detecting rules where it should not.
```
==================================================
SUMMARY STATISTICS
==================================================
Workflow(s): Lint, trunk, pull, inductor, linux-binary-manywheel
Timeframe: 4380 hours
Commits checked: 33873
Auto revert patterns detected: 560
Actual reverts inside auto revert patterns detected (%): 204 (36.4%)
Total revert commits in period: 601
Revert categories:
nosignal: 215 (35.8%)
ghfirst: 151 (25.1%)
uncategorized: 105 (17.5%)
ignoredsignal: 70 …
```
> [autorevert] fix query sorting

- tools/rockset_migration/s32ch.py
As in title
Reason:
I use this script to check that the adapters in the s3 clickhouse replicator lambda work, but it's annoying to keep making stored data files when I usually mean to run the script on everything in the bucket/prefix. In this case, the stored data file doesn't really matter and you want a new one each time
This makes it so that a stored data file will automatically get created if one is not provided
> [ez][CH] s32ch script: automatically create a stored data file if not given

- .github/scripts/install_xpu.bat
- .github/workflows/build_wheels_windows.yml
Follow https://github.com/pytorch/pytorch/pull/158733
> [BE] Upgrade XPU support package to 2025.2 in Windows CICD

- terraform-aws-github-runner/variables.tf
This is the only var missing documentation
> [BE][EZ] Document what the enable_organizations_runner param does

- torchci/components/metrics/panels/TablePanel.tsx
> [BUG]The title are missing in compiler page

- torchci/components/metrics/panels/TablePanel.tsx
https://github.com/pytorch/test-infra/issues/7084
> fix bug for graph display

- s3_management/manage.py
A follow-up after https://github.com/pytorch/pytorch/pull/162000 to surface these wheels on PyTorch index
> Surface vLLM wheels (vllm, flashinfer_python, and xformers)

- torchci/components/layout/NavBar.tsx
> Remove sglang/vllm dashboard

- .github/workflows/update-s3-html.yml
- s3_management/manage.py
Reverts pytorch/test-infra#7185 as potential fix for https://github.com/pytorch/pytorch/issues/163756
> Revert "[BE] Split up download.pytorch.org index update job"

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Changes:
- Failure side now requires 3+ failure events; if less than that, it schedules restarts on the first (oldest) failed commit sequentially (allowing pending events to resolve)
- Success and failed sides now issue restarts independently (should speed up the whole process a bit)
> [autorevert] update failure threshold to 3 for autorevert eligibility

- tools/pkg-helpers/pytorch_pkg_helpers/cuda.py
Add sm_110 to CUDA 13.0 SBSA wheels, as it is needed for Thor
cc @atalman @ptrblck @nWEIdia
> Add Thor support to 13.0 aarch64 domain builds

- torchci/components/layout/NavBar.tsx
Stacked PRs:
* __->__#7197
--- --- ---
> [Easy] Add Helion to hud navbar

- .lintrunner.toml
- tools/linter/adapters/pip_init.py
- tools/linter/adapters/pyfmt_linter.py
All this does is copy stuff 
from https://github.com/pytorch/pytorch/tree/adc11a7634c1b5879b649ee86b6cea43a94961d7
* pip init script
* pyfmt script
* pyfmt args
Commit is just what my main happened to be at this time
Main reason I want this is to get the uv changes in pip_init, which ended up wanting the updates for pyfmt
This lets you use `pytorch/scripts/setup_hooks.py` on test-infra
1. Mangle that script to use 3.13 instead of 3.9 (idk if that's necessary but it's what my test-infra lintrunner env was on and I haven't had issues before)
2. Call that script inside test-infra (ex `python ../pytorch/scripts/setup_hooks.py`)
3. Go to the newly created file `test-infra/.git/hooks/pre-push` and change replace `test-infra/scripts/lintrunner.py` with `pytorch/scripts/lintrunner.py` to just use …
> [ez][lint] Update pip init and pyfmt

- torchci/components/benchmark/v3/components/common/SelectionDialog.tsx
- torchci/components/benchmark/v3/components/common/styledComponents.tsx
- torchci/components/benchmark/v3/configs/teams/compilers/CompilerPrecomputeConfirmDialogContent.tsx
change the color of navitem to indicate it's clickable
demo:
https://torchci-git-makeoptionmoreclear-fbopensource.vercel.app/benchmark/compilers_regression
> Make the click item more obvious as link

- torchci/components/benchmark/v3/components/benchmarkList/BenchmarkCategoryCard.tsx
https://torchci-git-fixcss-fbopensource.vercel.app/benchmark/benchmark_list
> Add wrap so when user shrink the screen, all info and chip buttons are not out of card scope

- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
To be used by forge and torchcomms
> Allow custom s3 upload path within pytorch

- torchci/components/benchmark/v3/components/benchmarkList/BenchmarkCategoryCard.tsx
- torchci/components/benchmark/v3/components/benchmarkSideBar/components/SideBarMainSection.tsx
fix share link:
1. should be time.start and time.end instead of timerange
2. add lcommit and rcommit
> [BUG]Fix share link

- .github/scripts/validate_binaries.sh
- .github/workflows/validate-aarch64-linux-binaries.yml
> [cherry pick] add cuda validation to linux aarch64 binary validation (#7220)

- .github/workflows/trigger_nightly.yml
Add https://github.com/meta-pytorch/forge to nightly trigger
> Add forge to nightly trigger

- tools/torchci/test_insights/file_report_generator.py
If no good sha found for date, don't do anything
TODO handle what happens if all jobs are broken
> [ez][testing] file report: handle no sha found for date

- torchci/pages/tests/fileReport.tsx
> [testing] file report: add permalink

- .github/workflows/validate-linux-binaries.yml
> cherry pick #7319 
