pytorch/test-infra

- .github/workflows/build_wheels_linux.yml
This reverts commit 1fe7f4d28018acf9ebfe08925b34edf29e0d12d5.  Not needed anymore.
> Revert "Temporarily add a debug message for OIDC in Nova workflow (#4871)"

- .github/actions/setup-binary-builds/action.yml
- .github/actions/setup-binary-upload/action.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
To run the upload part in a separate upload job on GH ephemeral runners, we need:
1. Specific artifact name for each binary, so the upload job could find the correct one.
2. Create a new GHA `setup-binary-upload` to:
1. Download the artifacts from GitHub 
2. Running `pkg-helpers` is needed to figure out the correct S3 bucket and path to upload to.
3. Create a new GHA reusable workflow `_binary_upload` to upload the artifacts to S3.
1. Run on GH ephemeral runner `ubuntu-22.04`.
2. Only this job has access to the credential, the build job doesn't have that privilege anymore.
A small caveat here is that the upload job will depend on the build job with all its configuration matrix, so it can only be run after all build configurations finish successfully, not when individual builds finish.
The …
> Refactor wheel upload job to a separate job running on GH ephemeral runner

- .github/actions/setup-binary-upload/action.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
I made a mistake in https://github.com/pytorch/test-infra/pull/4877 when not explicitly select `test-infra` as the repo to checkout for the GHA.  When running on domains, the default repos are domains, i.e. `pytorch/vision`, and they don't have the GHA we need, namely `setup-binary-upload`.
An example failure when testing on vision nightly https://github.com/pytorch/vision/actions/runs/7533535440/job/20506343331
> Correctly checkout test-infra on Nova _binary_upload job

- .github/actions/update-commit-hash/action.yml
- .github/scripts/update_commit_hashes.py
- .lintrunner.toml
So that it can be re-used by ExecuTorch to update PyTorch pinned commits.  This is a close 1:1 copy of the GHA and the script from `pytorch/pytorch`.  A small modification is made in the `source-repo` parameter to allow the pinned commit files from other repo, i.e. `pytorch/executorch`.
Migrate and test the new GHA on pytorch https://github.com/pytorch/pytorch/pull/117506:
* ExecuTorch PR already exists https://github.com/pytorch/pytorch/actions/runs/7534593538/job/20509371346#step:2:1114
* Audio has no new commit https://github.com/pytorch/pytorch/actions/runs/7534593538/job/20509371162#step:2:1107
* Vision has a new commit and a PR should be created, but GH correctly reject `git push` to create a new remote branch https://github.com/pytorch/pytorch/actions/runs/7534593538/job/20509371569 …
> Migrate update-commit-hash GHA to test-infra

- .github/workflows/_binary_conda_upload.yml
- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
Similar to https://github.com/pytorch/test-infra/pull/4877, this moves conda upload into a separate job on GH ephemeral runner:
* I need a new `_binary_conda_upload` reusable workflow because conda upload uses anaconda client to upload to conda, not awscli to upload to S3.
* The build job doesn't have access to `pytorchbot-env` anymore, thus it has no access to `CONDA_PYTORCHBOT_TOKEN` and `CONDA_PYTORCHBOT_TOKEN_TEST` secrets.  Only the upload job has this access.
> Refactor conda upload job to a separate job running on GH ephemeral runner

- .github/workflows/_binary_conda_upload.yml
- .github/workflows/test_build_conda_linux_with_cuda.yml
- .github/workflows/test_build_conda_linux_without_cuda.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
- .github/workflows/test_build_conda_windows_without_cuda.yml
I tested https://github.com/pytorch/test-infra/pull/4886 with vision nightly and found out that I need to set the path to anaconda on GH ephemeral runner used by the upload job. 
It would fail otherwise, i.e. https://github.com/pytorch/vision/actions/runs/7550404642/job/20556529100#step:7:121
https://github.com/pytorch/test-infra/actions/runs/7550720719/job/20557072841?pr=4891#step:7:117 shows that conda can find anaconda client version correctly.
> Fix anaconda path in conda environment on GH ephemeral runner

- .github/actionlint.yaml
- .github/workflows/clang-tidy-macos.yml
- .github/workflows/test-setup-miniconda.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_macos_job.yml
- tools/scripts/generate_binary_build_matrix.py
- torchci/test/drci.test.ts
Changed the label for the macOS runners to `macos-m1-stable`.
> Change the label for the macOS runners

- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/lib/bot/utils.ts
- torchci/test/ciflow-push-trigger.test.ts
Instead of checking whether or not user contributed to the repo in the
past, check that workflows triggered on pull_request has been approved
This fixes a bug where ciflow workflows would still be scheduled for the first time contributors, but adapts it to a scenario when scheduling can be done only after workflow is approved
If workflow is not approved, it will have `action_require` conslusion for `pull_request` event, for example see:
```
[
{
id: 7546214676,
name: 'Check mergeability and dependencies for ghstack prs',
node_id: 'WFR_kwLOA-j9z88AAAABwcoZFA',
head_branch: 'export-D52808000',
head_sha: '8e3a8e0458354194e6683f804e3c6964b9f1b238',
path: '.github/workflows/check_mergeability_ghstack.yml',
display_title: 'Reland D52653337',
run_number: 7682,
event: 'pull_request',
status: …
```
> [PyTorchBot] Limit CIFLow tags assignment

- torchci/.env.example
- torchci/lib/drciUtils.ts
- torchci/lib/opensearch.ts
- torchci/pages/api/search.ts
Following https://docs.aws.amazon.com/opensearch-service/latest/developerguide/fgac-http-auth.html, the other option to query OpenSearch here is to use HTTP basic auth.  Although the method is dated, it's ok because we only need read access query.
This change requires:
###
Testing, once https://github.com/pytorch-labs/pytorch-gha-infra/pull/316 is merged, search for similar failure on HUD should just work, i.e. https://torchci-git-fork-huydhn-remove-opensearch-a-4880e9-fbopensource.vercel.app/failure?name=Lint+%2F+lintrunner+%2F+linux-job&jobName=undefined&failureCaptures=%5B%22%3E%3E%3E+Lint+for+test%2Fquantization%2Fpt2e%2Ftest_xnnpack_quantizer.py%3A%22%5D.  Atm, I modify the policy manually to test this change.
> Use HTTP basic auth when querying OpenSearch

- .github/workflows/build_conda_windows.yml
In the new setup, the conda upload job will just upload any `tar.bz2` packages it finds because it doesn't have any additional information about the target.  This leads to the wrong and duplicated upload of vs2019 conda package in Windows build job, i.e. https://github.com/pytorch/vision/actions/runs/7555102811/job/20584135167#step:7:170.
I'm not sure what's the best way to fix this here, but removing this file explicitly helps.  Also, this only happens on Windows.
> Fix the wrong upload of vs2019 conda package on Windows

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
Fixes: https://github.com/pytorch/vision/issues/8219
We need to upload to Github and then do repo after post script is competed. In Case of vision wheels it does wheel relocation.
> Move upload step to github after post-script

- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/disableFlakyBot.test.ts
Only impacts disable bot, there might be other bots that auto add triaged label but I can't find them
> [ez][bot] Disable bot to not add triaged if oncall: pt2 label is present

- s3_management/manage.py
https://github.com/pytorch/executorch/issues/1663.  The indexing script was migrated recently from builder to test-infra in https://github.com/pytorch/test-infra/pull/4879.  But there was a mistake in which my [recent change](https://github.com/pytorch/builder/commit/6f3cb2ba1753c5ecade8b800c29fc18d18d149db) to keep nightly 20231010 for ExecuTorch wasn't copied over.
So, this PR copies the missing logic https://github.com/pytorch/builder/pull/1642.  It also fixes some linter issues flagged by test-infra lintrunner.
> Keep nightly 20231010 for ExecuTorch alpha 0.1 for now

- .github/actions/calculate-docker-image/action.yml
IIRC, we used to have this option, but nothing was using it.  I have found an use case for this in https://github.com/pytorch/executorch/pull/1335#discussion_r1448247422 where ExecuTorch team copies the content of `examples/arm` into `.ci/docker` before starting the build https://github.com/pytorch/executorch/blob/main/.ci/docker/build.sh#L40-L46:
* The docker image was rebuilt, but its hash tag remained the same because the copy step above is not version tracked.
* The new image was not pushed.
I have tried to move `examples/arm` into `.ci/docker` and setup softlinks, but the result looks weird https://github.com/pytorch/executorch/pull/1574#discussion_r1447762323, so I'll probably drop that approach.
The remaining option here is to add a `force-push` flag that can be used to, well, …
> Resurrect the option to force push the Docker image

- .github/actions/calculate-docker-image/action.yml
I broke it in https://github.com/pytorch/test-infra/pull/4866 with a pair of redundant square brackets (ouch)
```
#!/bin/bash
DOCKER_IMAGE="308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-py3:7b353c02302e5478ea0db69cdfeae5cef6ee2dec"
if [! docker manifest inspect "${DOCKER_IMAGE}" >/dev/null 2>/dev/null] || [ "${DOCKER_FORCE_PUSH:-false}" == "true" ]; then
echo "THERE"
fi
```
returns `debug.sh: line 5: /dev/null]: Permission denied`
while 
```
#!/bin/bash
DOCKER_IMAGE="308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-py3:7b353c02302e5478ea0db69cdfeae5cef6ee2dec"
if ! docker manifest inspect "${DOCKER_IMAGE}" >/dev/null 2>/dev/null || [ "${DOCKER_FORCE_PUSH:-false}" == "true" ]; then
echo "THERE"
fi
```
works correctly.
Bash …
> Fix wrong bash if condition in calculate docker image

- .github/actions/update-viablestrict/action.yml
- .github/scripts/fetch_latest_green_commit.py
- .github/scripts/gitutils.py
- .github/scripts/test_fetch_latest_green_commit.py
- .github/workflows/tests.yml
This will be needed by ExecuTorch too. So, I think it's time to move this to test-infra as a generic GHA.  The list includes:
* The `update-viablestrict` GHA that could be used by PyTorch and ExecuTorch.
* The `fetch_latest_green_commit.py` script and its unit tests.  I also refactor the `is_green` function to accept a list of required jobs that need to be pass before marking a commit as green.  Before this, the list is fixed https://github.com/pytorch/pytorch/blob/main/.github/scripts/fetch_latest_green_commit.py#L89-L94 to match what we have on PyTorch.
* Also move the test script and run it on CI.
Locally on PyTorch:
```
(py3.11) huydo@huydo-mbp pytorch % python ~/Storage/mine/test-infra/.github/scripts/fetch_latest_green_commit.py --requires '["pull", "trunk", "lint", "linux-binary"]' …
```
> Migrate update-viablestrict to test-infra as a generic GHA

- .github/workflows/pr-dependencies-check.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- torchci/lib/drciUtils.ts
In pytorch/pytorch#118258 mergeability check job was renamed to `ghstack-mergeability-check`. This PR updates flakiness exclusion accordingly.
> [ez] Update mergeability check job name in the flakiness exclusion list

- .github/workflows/generate_binary_build_matrix.yml
- tools/scripts/generate_binary_build_matrix.py
- tools/tests/test_generate_binary_build_matrix.py
Add option to use only our custom index download.pytorch.org. This will be used in validations in cases when pypi binaries are not published yet.
Test
```
python generate_binary_build_matrix.py --channel release --use-only-dl-pytorch-org true
{"include": [{"python_version": "3.8", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_8-cpu", "validation_runner": "linux.2xlarge", "installation": "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu", "channel": "release", "upload_to_base_bucket": "no", "stable_version": "2.2.0"}, {"python_version": "3.8", "gpu_arch_type": "cuda", "gpu_arch_version": "11.8", "desired_cuda": …
```
> Add use-only-dl-pytorch-org option to release matrix

- s3_management/update_dependencies.py
That will update common dependency of Torch + ecosystem libraries from
PyPI to it's mirror on download.pytorch.org
Accepts following arguments:
- `--dry-run` do not actually download or upload packages, just scan indices
- `--include-stable` update packages in stable index as well
> [S3] Add `update_dependencies` script

- s3_management/manage.py
According to [PEP508](https://peps.python.org/pep-0508/#names) package names should match case insensitive regex, i.e. both `Pillow-10.1.0` and `pillow-10.2.0` should be part of the same index
Achieve it by adding `.lower()` to `obj_to_package_name` method
Test Plan: `manage.py --generate-pep503 --do-not-upload whl/test` and observe that PEP503 index generated for pillow includes both old a new packages
> Fix indexes for mixed upper/lower case names

- .github/workflows/upload-tutorials-stats.yml
This fixes the broken workflow after https://github.com/pytorch-labs/pytorch-gha-infra/pull/342 lands
Manually update gha_workflow_upload-tutorials-stats with the content of https://github.com/pytorch-labs/pytorch-gha-infra/pull/342 and let the CI run the job https://github.com/pytorch/test-infra/actions/runs/7750598806/job/21137192582?pr=4918
> Replace AWS credentials on upload-tutorials-stats with OIDC

- aws/lambda/log-classifier/ruleset.toml
ExecuTorch failures in trunk are not well captured atm, for example https://github.com/pytorch/pytorch/actions/runs/7742624704/job/21112923644
`cargo lambda invoke --data-file=fixtures/request.json` locally with an example in trunk https://hud.pytorch.org/pytorch/pytorch/commit/4a5a3bcc89c7658499aa36f24b02ec4648f41220
> Add log classifier rule for ET model tests

- stats/flaky-rules.json
Detect only real flaky issues, like this https://github.com/pytorch/pytorch/actions/runs/7745629309/job/21122066764
(it's very rare, only one instance in the recent week)
Other mergeability failures are ligitimate:
https://github.com/pytorch/pytorch/actions/workflows/check_mergeability_ghstack.yml
> Update ghstack-mergeability-check flakiness rules

- .github/scale-config.yml
Distributed team need a runner with 8 GPUs o test different types of parallelism.
> Add a runner with 8 GPUs for Distributed team

- torchci/pages/benchmark/compilers.tsx
Update the correct path for the performance-dashboard documentation page
> Fix path for dashboard link page

- .github/workflows/usage-log-aggregator-lambda.yml
- aws/lambda/usage-log-aggregator/Makefile
- aws/lambda/usage-log-aggregator/lambda_function.py
- aws/lambda/usage-log-aggregator/test_lambda_function.py
- torchci/components/TestInsights.tsx
- torchci/pages/test/insights.tsx
Fixes https://github.com/pytorch/test-infra/issues/4933.  There are several issues with the page:
1. The workflow ID regex was wrong with an extra `s` in `jobs`.  Thus the link fails to find the workflow ID.  I'm not sure why it was missed earlier (blaming myself)
1. The artifact `usage-log-test-` is now called `logs-test-`.  The filename was wrong
1. The script failed to handle `None` values in some cases, i.e. `{'pid': 260046848, 'gpu_memory': None}`, and ended up with `TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'` error
1. The script failed to handle retried job because it hardcoded the run attempt to 1
1. S3 NoSuchKey error wasn't handled correctly by the lambda and surfaces as 500 Internal Server Failure
1. Handle invalid JSON in the log when …
> Fix test insight page

- .github/workflows/build_conda_windows.yml
This is fix for windows conda failures:
https://hud.pytorch.org/hud/pytorch/vision/nightly/1?per_page=50
> Fix vision windows conda nightly. Remove pinned conda version

- .github/workflows/tests.yml
Namely;
- When this workflow (`tests.yml`) is modified, it should be run
- When tests assets are modified, they should be run as well, otherwise one can not really tell whether changes to the assets really do anything, for example see CI (as screenshot below) run for https://github.com/pytorch/test-infra/pull/4942)
> [CI] Run `tests.yml` more

- torchci/components/LogViewer.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Double clicking in the job tooltip (the blue box that comes up on the main page of hud when you click a job conclusion) opens up a the gh job page for that job.  This also applies to the log viewer in the tooltip, which can be really annoying when you are trying to highlight something in the log, so this PR stops the gh page from opening when you double click on the log viewer in the tooltip
Also remove some unused imports
Set the function twice separately instead of in parent element because I want the blue space after the log toggle to still trigger opening the gh job page, see image for area
> [HUD][ez] Double click log viewer in job tooltip (hud main page) no longer opens gh job 

- torchci/components/metrics/panels/TablePanel.tsx
- torchci/pages/torchbench/userbenchmark.tsx
When the number of metrics exceeds a threshold (100), enable paging and DataGrid footer to view all metrics.
> Enable footer for the DataGrid widget to enable paging 

- torchci/components/JobLinks.tsx
This happened in https://github.com/pytorch/pytorch/pull/119774#issuecomment-1942910517 where the bot failed to create the comment due to a GitHub hiccup losing the event.
Atm, the comment is only created by the bot when the PR is opened or sync https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/drciBot.ts#L6.
When a workflow finishes, making an API call to Dr.CI returns early when there is no Dr.CI comment https://github.com/pytorch/test-infra/blob/main/torchci/pages/api/drci/drci.ts#L136-L141
Not sure how to test this because there is no mock setup.  But this looks benign enough to jump the bullet?
> Create Dr.CI comment if it doesn't exist

- torchci/components/metrics/panels/TablePanel.tsx
- torchci/pages/torchbench/userbenchmark.tsx
https://github.com/pytorch/test-infra/pull/4745 changed the behavior of the DataGrid table to show the footer and pagination by default and this breaks exiting table like https://hud.pytorch.org/benchmark/compilers where the summary table now include pagination.
This change switches the default behavior back to what is was before of not showing and also allow the user benchmark table from https://github.com/pytorch/test-infra/pull/4745 to show the footer it needs
The summary table on the dashboard is back without footer https://torchci-git-fork-huydhn-fix-dashboard-summa-7ec9fd-fbopensource.vercel.app/benchmark/compilers
While the user benchmark table has footer and pagination https://torchci-git-fork-huydhn-fix-dashboard-summa-7ec9fd-fbopensource.vercel.app/torchbench/userbenchmark
> Keep the behavior of DataGrid table to hide the footer by default

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
- torchci/test/drciBot.test.ts
- torchci/test/drciUtils.test.ts
This is to address https://github.com/pytorch/test-infra/issues/4938 where Dr.CI will hide bc linter failures on a PR if the PR has `suppress-bc-linter` or `suppress-api-compatibility-check` labels.  This is done dynamically whenever Dr.CI is run (periodically and during merge).
The only supported use case atm is bc linter.
https://github.com/pytorch/pytorch/pull/118857 has a bc linter failure that has been suppressed.  Running the following curl command locally will update Dr.CI and hide the bc linter failure there.
```
--url 'http://localhost:3000/api/drci/drci?prNumber=118857' \
--header 'Authorization: TOKEN' \
```
---
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/118857/index.htm …
> Hide suppressed bc linter failure on Dr.CI (and mergebot)

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
Using `always()` allows binary upload to run even if some binary builds fails, i.e. text conda 3.12
https://github.com/pytorch/text/actions/runs/7975119767/job/21772574739. The upload job will also fail expectedly because it couldn't find any artifacts on GitHub. However, any working combinations will still be uploaded normally.
~~I also update the test script to test both minimum (3.8) and maximum (3.12) versions.~~
https://github.com/pytorch/test-infra/actions/runs/7979242479/job/21786218059?pr=4958 shows that the upload job is run and failed because it couldn't find the artifacts on GH
> Always run binary upload

- torchci/lib/jobUtils.ts
- torchci/pages/api/drci/drci.ts
This fixes the wrong path used by `hasS3Log` and also disables similarity search on non PyTorch repos.  There is nothing wrong with this feature but I don't think it works well with non-PyTorch repo where there is no dedicated log classifier support.  Specifically, ExecuTorch has lots of generic failures `failed with exit code N`, i.e. https://github.com/pytorch/executorch/pull/1964.  This can be turned back on later when we have a better log classifier.
> Fix hasS3Log and disable similarity search on non-PyTorch repos

- tools/torchci/check_alerts.py
We hit the comment threshold of 2500 and no new commends could be made, and the alert couldn't be updated.
This change closes alert issues with >2400 comments and forces the script to make a new issue instead.
Still investigating why the alert/task syncing isn't working for the new issue
> [alerts] Close issue if there are too many comments

- .github/arc-runner-config.yaml
Since we decided to move forward with the dind-rootless setup let's remove the runners for k8s and dind modes.
> ci: Use dind-rootless only

- .github/arc-runner-config.yaml
Change our minimum runners to 0 to lower costs during times of low usage. In my own testing it takes only a few minutes for a node to come online if there isn't already one and Karpenter keeps nodes online if there is continued usage. We can revisit the minimum if it causes us grief in the future but choosing 0 is likely the right choice at the moment while we build out the ARC infra.
> ci: Set minimum ARC runners to 0

- .github/actions/calculate-docker-image/action.yml
- .github/actions/pull-docker-image/action.yml
Docker login is required if the goal is to instead of relying on EC2 node permission, use OIDC to login instead.
> Forces docker login on calculate-docker-image and pull-docker-image

- .github/actions/calculate-docker-image/action.yml
- .github/actions/pull-docker-image/action.yml
This reverts commit 41e8b20.
Avoiding logging out docker registry, as other workflows assume we're already logged in.
Testing infra changes in [the pytorch/pytorch PR](https://github.com/pytorch/pytorch/pull/121729).
> Reland "Forces docker login on calculate-docker-image and pull-docker-image" (#4999)"

- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/utils.ts
- torchci/package.json
- torchci/test/autoLabelBot.test.ts
- torchci/yarn.lock
Attempts to mimic the behavior of https://github.com/pytorch/pytorch/blob/89add71168faf48ea408829678897befcf0136b4/.github/workflows/labeler.yml
* Downloads the config based on a "labeler_config" key in .github/pytorch-probot.yml.  By nature of `context.config`, it looks in .github/ + configfile for the config file
* Uses minimatch (linked in https://github.com/actions/labeler/blob/83720bce8638d1b5b7b15ae76465522ca7ea2eec/README.md) to match the paths against globs
* Adds pull_request.synchronize to list of event types the labeler is run on
Other
* Adds check for ciflow label (no idea why this wasn't done before) 
Want to test this on malfet/deleteme before actually enabling on pytorch
> [bots] Move labeler action to test-infra

- torchci/lib/drciUtils.ts
- torchci/test/drciUtils.test.ts
Fixes https://github.com/pytorch/test-infra/issues/4987
Dr.CI logic to detect `isInfraFlakyJob` and `isLogClassifierFailed` has a FP where it misclassifies the GH failure to dispatch the whole workflow as flaky, for example https://github.com/pytorch/pytorch/pull/121317.
These logic should only be applicable to workflow job, not workflow run.  The way to separate them is to check the `workflowId` field where it is set to `null` whenever it is a workflow run.
Unit test + local curl command will mark them as legit failures:
```
--url "http://localhost:3000/api/drci/drci?prNumber=121317" \
--header "Authorization: TOKEN" \
```
> Fix Dr.CI flaky FP when GH fails to dispatch the workflow

- .github/workflows/trigger_nightly.yml
I have the approval from ExecuTorch to onboard to Nova binary build workflows https://github.com/pytorch/executorch/pull/2363.  That covers wheel first.  Once the PR lands, we can add a nightly trigger to start generating ExecuTorch wheels.
I'm seeing pytorchbot with write access to the repo from `bunnylol oss pytorch/executorch`, so I think this is the only step needed.
> Add nightly trigger for executorch

- torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
- torchci/rockset/prodVersions.json
Some Dr. CI queries are failing due to too much resource utilization according to the new query_logs table
To improve speed + reduce memory utilization, I move tables in joins around to be larger table join smaller table and use the broadcast join strategy.  
Approximate improvements according to the query profiler:
All PRs (past 30 minutes):
max memory of a step: 37GB -> 500 MB
time: ~8s -> ~2s
Single PR (used 121717)
max memory of a step: 37GB -> 200 MB
time: ~6s -> ~1s
> [drci] Optimize sql query for recent workflow jobs

- .github/workflows/mobile_job.yml
- .github/workflows/trigger_nightly.yml
My copy/paste mistake.  ExecuTorch wants to have `nightly` off `viable/strict` branch like PyTorch instead of `main`
> Trigger executorch nightly off viable/strict

- .github/arc-runner-config.yaml
Allows arc-runner-config to set the number of Nvidia GPUs for a compute-gpu runner.
Relates to pytorch/ci-infra#89
> ci: Option to set number of Nvidia GPUs in ARC

- tools/scripts/generate_binary_build_matrix.py
Another follow-up for 2.3 release
> Remove ROCm 5.6 and add ROCm 6.0

- s3_management/manage.py
TSIA. ExecuTorch nightly wheel builds are now running https://hud.pytorch.org/hud/pytorch/executorch/nightly
> Publish ExecuTorch wheel on download.pytorch.org

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/bot/utils.ts
- torchci/test/autoLabelBot.test.ts
- torchci/test/common.ts
- torchci/test/labelCommands.test.ts
- torchci/test/mergeCommands.test.ts
- torchci/test/utils.ts
Do not add ciflow/trunk on merge if the author has no write permission. Instead, abort merge (it would have failed anyways) and post a comment about seeking approvals
Change -i permission to check for write permissions instead of write permissions OR has other commit on main 
Attempts to move some common mocks to be functions so I don't need to stare at urls as much
Helps reduce bot fighting in the below case:
> [bots] Do not add ciflow/trunk label if the author does not have permissions

- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/codevNoWritePermBot.ts
- torchci/lib/bot/index.ts
- torchci/test/autoLabelBot.test.ts
- torchci/test/codevNoWritePermBot.test.ts
- torchci/test/utils.ts
Comments on PRs in pytorch/pytorch that look like they were exported from phab but the author doesn't have write permissions.
Changed check for Differential Revision string to also take ones that have markdown links (like `[D11111](link)`) I've seen them around, I think they're usually ghstack/stacked diff PRs
> [bots] Bot to comment wiki link on codev PRs with no write permissions

- torchci/rockset/commons/__sql/pr_commits.sql
- torchci/rockset/prodVersions.json
- torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql
Small optimizations for some queries, not super necessary 
TTRS:
The query_logs table claims it takes ~17000ms on avg, but in the console it usually takes ~5000ms.  Using lookup brings to about ~1000ms on the console
PR commits (used on HUD PR page to fetch previous commits)
This was already pretty fast, but its one of the most used queries.  Original time: ~1500ms.  Moving the joins brings it to ~100ms
> [ez][HUD] Optimize query for TTRS, previous commits on PR

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
Fixes https://github.com/pytorch/test-infra/issues/5028
This is a regression after https://github.com/pytorch/test-infra/pull/5005 and I should have document the way Dr.CI checks for similar failures better.  Here is what happens:
1. A known fact is that Dr.CI won't be able to find the merge base for ghstack PRs and https://github.com/pytorch/test-infra/pull/5005 fixes the way this is handled
2. The issue, however, comes from the fact that `pr_info.merge_base_date` is default to `0` instead of an empty string or an undefined value
3. The date of the merge base is used to limit the range of the similar search query here https://github.com/pytorch/test-infra/blob/main/torchci/lib/drciUtils.ts#L263-L264.  This is used exactly to avoid FP.  If the merge base date is not set, it will fall back …
> Do not set the merge base date to the mock value of 0

- torchci/scripts/uploadQueryLambda.mjs
Sometimes the description from the query lambda on rockset is null and the local description is empty, and the script attempts to update the lambda.  This made me hit rate limits when trying to update from local.
I assume this is just a typing thing and that this is just two different ways of saying that there is no description, so add a check for that.
> [ez] uploadQueryLambdas - Allow description for lambdas to be different types

- torchci/lib/types.ts
- torchci/pages/api/drci/drci.ts
- torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
- torchci/rockset/prodVersions.json
- torchci/test/drci.test.ts
`workflow_run.workflow_id` seems to uniquely identify workflow jobs based on their files
Use the above to tell that `.github/workflows/trunk.yml` is a failed version of `trunk`
Based on this, take the most recent workflow (based on workflow_run.id) and its corresponding jobs to be the truth
Example
> [drci] Remove failed workflows if there is a succeeding one

- torchci/lib/bot/index.ts
- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
https://support.github.com/ticket/personal/0/2690822
I've been doing this manually for commits on main to get signal: make tag, trigger workflow dispatches on the tag.
> [bots] Bot to rerun workflows that fail due to weird infra error 

- aws/lambda/log-classifier/ruleset.toml
This might be too specific...
Should give better matches for:
https://github.com/pytorch/pytorch/actions/runs/8454738001/job/23160545092
https://github.com/pytorch/pytorch/actions/runs/8425535599/job/23071873165
> [ez][log classifier] More specific bazel build failure rule

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
https://github.com/pytorch/test-infra/pull/5052
I can't even find the relevant logs on vercel, so remove the restriction on the type of event its run on
> [bots] Continuation of #5052 ( adding logging )

- .github/workflows/mobile_job.yml
- .github/workflows/test_mobile_job.yml
- tools/device-farm-runner/run_on_aws_devicefarm.py
Running ExecuTorch tests with the `XCTEST_TEST_PACKAGE` option has a problem finding the tests.  As suggestion from AWS support, we should try to use `APPIUM_NODE_TEST_SPEC` with a custom test spec instead. The test spec is at s3://ossci-assets/default-ios-device-farm-appium-test-spec.yml.
The test is finally being discovered correctly now https://us-west-2.console.aws.amazon.com/devicefarm/home#/mobile/projects/02a2cf0f-6d9b-45ee-ba1a-a086587469e6/runs/c492a3e2-11a9-456b-82c6-3a92602e8ecf
https://us-west-2.console.aws.amazon.com/devicefarm/home#/mobile/projects/02a2cf0f-6d9b-45ee-ba1a-a086587469e6/runs/0ceff628-2b76-4283-8efa-3e50b2bbe3c1
The tests are now discovered and run correctly.
* Successful run https://github.com/pytorch/test-infra/actions/runs/8399363992/job/23006159012?pr=5041 …
> Use APPIUM_NODE_TEST_SPEC custom test spec to support test discovery

- torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Turns out you don't need the initial `refs`
#5059
<clown>
Also attempts to prevent too many reruns per sha
> [bots] Fix #5059

- .github/workflows/generate_docker_release_matrix.yml
- tools/scripts/generate_binary_build_matrix.py
- tools/scripts/generate_docker_release_matrix.py
Workflow introduced by this PR: https://github.com/pytorch/pytorch/pull/115949/
We want to make it generic and call it from validation jobs as well as build jobs.
Test:
```
python generate_docker_release_matrix.py --channel nightly
{"include": [{"cuda": "11.8", "cuda_full_version": "11.8.0", "cudnn_version": "8", "image_type": "runtime", "platform": "linux/arm64,linux/amd64"}, {"cuda": "11.8", "cuda_full_version": "11.8.0", "cudnn_version": "8", "image_type": "devel", "platform": "linux/arm64,linux/amd64"}, {"cuda": "12.1", "cuda_full_version": "12.1.1", "cudnn_version": "8", "image_type": "runtime", "platform": "linux/arm64,linux/amd64"}, {"cuda": "12.1", "cuda_full_version": "12.1.1", "cudnn_version": "8", "image_type": "devel", "platform": "linux/arm64,linux/amd64"}]}
```
Will be …
> Add docker release matrix workflow 

- .github/workflows/build_wheels_linux.yml
The current method by which NOVA workflows build Python wheels [is deprecated](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#should-setup-py-be-deleted). Instead of calling `python setup.py bdist_wheel`, all building should be done by the Python Packaging Authority's [build tool](https://build.pypa.io/en/stable/mission.html). Here are a couple more links about the topic:
- https://packaging.python.org/en/latest/discussions/setup-py-deprecated/ 
- https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
**This only fixes the NOVA Linux workflow, not macOS or Windows**
- Add step in Linux workflows to pip install the `build` tool
- Remove the "clean" command as it is no longer needed
- Change the build step to utilize the build command
- CI green
1. …
> Utilize Python build package instead of setup.py

- .github/workflows/test_build_conda_linux_with_cuda.yml
- .github/workflows/test_build_conda_linux_without_cuda.yml
- .github/workflows/test_build_conda_m1.yml
- .github/workflows/test_build_conda_macos.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
- .github/workflows/test_build_conda_windows_without_cuda.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_build_wheels_macos.yml
- .github/workflows/test_build_wheels_windows_without_cuda.yml
TorchText tests are constantly failing. The development of torchtext is on hold currently. Hence stopping the CI test for torchtext
> Remove torchtext tests from CI

- .github/workflows/build_wheels_linux.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
It was brought up [here](https://github.com/pytorch/test-infra/pull/5071#issuecomment-2046202327) that various workflows may still be reliant on the old way of installing python packages (invoking setup.py directly). 
While these workflows *should* enable their packages to work with `build` eventually, they should have ample time to do so. Therefore, this change established a default for the build command on Linux workflows. Therefore, newer packages can start to specify `python -m build --wheel`, without disrupting the other workflows reliant on Nova.
> Allow old packages to default to setup.py-based build

- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
- tools/scripts/generate_binary_build_matrix.py
- tools/tests/test_generate_binary_build_matrix.py
Adds the ability to generate the binary build matrix with a singular version of python to account for packages that only need to build a package that looks similar to:
`torchtune-0.0.1-py3-none-any.whl`
> tools: Add ability to build a python only package

- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/windows_job.yml
This should fix a bug where the blank repository field didn't work as expected for executing checkouts / scripts correctly.
Should correct errors where users had to fill out the repository section where they should not have had to do that
> .github: Fix blank repository variable

- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/windows_job.yml
This is to support a new use case where I need to upload different Android and iOS apps instead of the regular wheel files as the artifacts of Nova Linux job.  It looks like the easiest way is to have a folder `artifacts-to-be-uploaded` in the current workspace, and let the job script moves any artifacts it needs to persist there.
> Support the upload of custom artifacts from artifacts-to-be-uploaded folder

- .github/workflows/mobile_job.yml
- .github/workflows/test_mobile_job.yml
- tools/device-farm-runner/run_on_aws_devicefarm.py
This extends the current mobile job workflow to support instrumentation tests on Android https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-instrumentation.html.  As part of this change, I also add the support to upload an extra data archive to the device to be used by the test.  In the context of performance benchmark, the extra data archive usually contains exported models that the benchmark needs to cover.
I'm using ExecuTorch llama2 demo app as inputs of the test https://github.com/pytorch/executorch/tree/main/examples/demo-apps/android/LlamaDemo.  It uses the exported llama2 7B model.
The script can be run locally as follows and its inputs can be downloaded from S3 `ossci-assets` bucket:
```
python run_on_aws_devicefarm.py \
--project-arn …
```
> Add Android support to mobile job workflow

- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
Let users of `build_wheels_*.yml` override the `submodules` input of `setup-binary-build`.
pytorch/executorch does not need (or want) to do a full recursive submodule checkout.
> Add `submodule` input for build_wheels_*.yaml

- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/index.ts
- torchci/lib/bot/utils.ts
Two refactorings in this PR, setting the stage for a follow up:
- Extract a method to get a list of files changed in the given PR
- Sort all bots alphabetically (fixing an eyesore)
> [Refactor] Extract out a utility function: getFilesChangedByPr 

- .github/arc-node-config.yaml
This should help mitigate https://github.com/pytorch/ci-infra/issues/118
> Use ON_DEMAND instances for ARC nodes config to avoid disruptions

- .github/workflows/build_wheels_macos.yml
Cherry-pick https://github.com/pytorch/test-infra/pull/5107 into release/2.3
Give clients a way to disable wheel delocation.
This step is only run on macOS, so there's no equivalent change necessary in the linux or windows workflows.
> cherry-pick: Add inputs.delocate-wheel to build_wheels_macos.yaml

- .github/workflows/build_wheels_macos.yml
Give clients a way to disable wheel delocation.
This step is only run on macOS, so there's no equivalent change necessary in the linux or windows workflows.
https://github.com/pytorch/executorch/actions/runs/8759506663/job/24042678714?pr=3049 is an example run using a forked copy of this file (see https://github.com/pytorch/executorch/commit/aca550bf97e86415a66194b7e8ddd0f608562ad6). It successfully skips the "Install delocate-wheel" and "Delocate wheel" steps.
While on the testing for this PR, both of those steps run by default: https://github.com/pytorch/test-infra/actions/runs/8759967852/job/24044074480?pr=5107
> Add inputs.delocate-wheel to build_wheels_macos.yaml

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
This is to address some new comments on https://github.com/pytorch/test-infra/issues/5063.
1. Exclude `backwards_compat` from Dr.CI flaky check, as this job is deem stable enough most of the time.
2. Lint jobs have already been excluded, but there is a bug when it would still be treated as flaky when there is no associated log on S3.  This case surfaces in https://github.com/pytorch/pytorch/pull/124321 where there is a mix of signals from `pytorch` and` pytorch-canary` for the same commit. For example, there is no https://ossci-raw-job-status.s3.amazonaws.com/log/pytorch/pytorch-canary/24002161738 for the lint job there
```
{
workflowId: 8745622961,
workflowUniqueId: 13175283,
id: 24002161738,
runnerName: 'i-0cdd9180550988c58',
authorEmail: 'ZainR@meta.com',
name: 'Lint / workflow-checks …
```
> Exclude lint and backwards_compat from Dr.CI flaky check

- .github/arc-runner-config.yaml
Relates to https://github.com/pytorch/ci-infra/issues/94.
During the CI Runners standup call on 2024-04-22 we made a decision that setting the minimum runners to 0 allowing the Karpenter autoscaler to handle scale would be a better approach to ensure that nodes eventually get cleaned up.
(cloning https://github.com/pytorch/test-infra/pull/5111 by @zxiiro)
> Set minimum ARC runners to 0

- torchci/components/metrics/panels/TablePanel.tsx
Fixes https://github.com/pytorch/test-infra/issues/5054
Probably due to https://github.com/pytorch/test-infra/pull/4745, the tables on the metrics page where not scrollable 
This change makes them scrollable and also preserves the footer behavior introduced by the above PR for the benchmarks page
Pages of interest in preview: 
https://torchci-git-csl-fixmetricstablegridscroll-fbopensource.vercel.app/metrics
https://torchci-git-csl-fixmetricstablegridscroll-fbopensource.vercel.app/torchbench/userbenchmark
> [HUD] Fix DataGrid widget not scrolling on metrics page

- .github/workflows/update_ci_wait_time_metric.yml
The old way of getting AWS creds is no longer supported
Should fix https://github.com/pytorch/test-infra/issues/5113
Unfortunately there's no way to test this without merging it to main first since the role policy requires [the environment](https://github.com/pytorch/test-infra/pull/5115/files#diff-dc712cd14c95e5480d9dd162a6bc2d804eeedd03155533176d23a363fe99c744R17) to be set to pytorchbot-env, and github rules are configured to only allow workflows merged into main to be run with this environment.  
But the workflow is already broken, so I don't feel to bad about it
> Fix AWS credentials for update_ci_wait_time_metric.yml workflow

- .github/workflows/anaconda-prune.yml
It looks easy enough, the conda token used for `pytorch-test` is not the correct one.  I temporarily add `fix-anaconda-token` to the env, run the test, then remove it after.
Fixes https://github.com/pytorch/test-infra/issues/5114
https://github.com/pytorch/test-infra/actions/runs/8793196628/job/24130887625?pr=5116
> Use the correct conda token for pytorch-test channel

- .github/workflows/update_ci_wait_time_metric.yml
https://github.com/pytorch/test-infra/pull/5115 solved the assume role part, but even with that role the upload still fails with:
```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the UpdateItem operation: User: arn:aws:sts::749337293305:assumed-role/gha_workflow_update_ci_wait_time_metric/GitHubActions is not authorized to perform: dynamodb:UpdateItem on resource: arn:aws:dynamodb:us-east-1:749337293305:table/torchci-metrics-ci-wait-time because no identity-based policy allows the dynamodb:UpdateItem action
```
That's weird because that permission appears to be given.  After comparing this against a workflow that works, trying to upgrade boto library to see if that was the problem
Testing: As explained in the [other …
> [EZ] update boto3 (Fix AWS credentials for update_ci_wait_time_metric.yml workflow)

- .github/workflows/update_ci_wait_time_metric.yml
Part of fixing https://github.com/pytorch/test-infra/issues/5113 by correcting a mismatch between the role's account  dynamodb table's account. 
- The role now points to a different role (of the same name) in the dynamodb table's account. This new role already existed in aws, but had the [wrong perms](https://github.com/pytorch-labs/pytorch-gha-infra/pull/381)).  
- Since the new role didn't need an environment set, removed that as well (the role instead expects the workflow to always be running on `main`)
Temporarily edited the role to
1. Apply the desired permissions 
2. Remove the `main` branch only protection and verified that [the workflow ran successfully](https://github.com/pytorch/test-infra/actions/runs/8840055206/attempts/9)
Those changes have now been reverted
Will need to run …
> [EZ] Use correct account (Fix AWS credentials for update_ci_wait_time_metric.yml workflow)

- torchci/lib/fetchCommit.ts
- torchci/lib/jobUtils.ts
- torchci/test/jobUtils.test.ts
Fixes https://github.com/pytorch/test-infra/issues/5103
I think the wrong match is fixed by setting the separator correctly to `/`.  I also add a test to make sure that the final list looks correct and the latest run of `pull / linux-jammy-py3.8-gcc11 / build` job is not removed.
`linux-jammy-py3.8-gcc11 / build` and `linux-focal-cuda12.1-py3.10-gcc9 / build` are showing up correctly on the preview page now https://torchci-git-fork-huydhn-fix-missing-jobs-on-hud-fbopensource.vercel.app/pr/124281
Also spot check some commits https://torchci-git-fork-huydhn-fix-missing-jobs-on-hud-fbopensource.vercel.app/pytorch/pytorch/commit/0ca1ff3dce71b3fa4a905512ec7be381be753240
> Fix missing job on HUD due to wrongly trie match

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
- torchci/test/drciBot.test.ts
This is the next part of https://github.com/pytorch/test-infra/pull/5122 where Dr.CI also uses the list of unstable issues to check if a job is an unstable job.  The same function `isUnstableJob` that powers HUD from https://github.com/pytorch/test-infra/pull/5122 is used.
Mark a job on ET as unstable https://github.com/pytorch/executorch/issues/3344 as shown on HUD https://hud.pytorch.org/hud/pytorch/executorch/main and Dr.CI applies the same logic on a PR https://github.com/pytorch/executorch/pull/3318 to show the job as unstable.
```
--url "http://localhost:3000/api/drci/drci?prNumber=3318" \
--header "Authorization: TOKEN" \
--data 'repo=executorch'
```
* :page_facing_up: Preview [Python docs built from this …
> Update Dr.CI to use the list of unstable issues

- torchci/lib/bot/autoLabelBot.ts
- torchci/lib/bot/utils.ts
- torchci/test/autoLabelBot.test.ts
Pt1 of https://github.com/pytorch/pytorch/issues/117051 but doesn't handle the topic: not user facing thing
Reads a config to add labels based on other labels added.
Config currently only supports if any -> add, if all -> add
Ex if you say if any of (A, B, C), then add (D), then D gets added if an issue or PR gets B
Only adds based on the currently added label in an attempt to prevent concurrency problems
Planning on testing on malfet/deleteme
TIL: if you add a label while making a PR or issue, two webhooks get issued: one for the PR/issue creation, one for the labeling event
Example config:
```
- any:
- "module: custom operators"
- "module: aotdispatch"
then:
- "module: pt2-dispatcher"
- any:
- "module: dynamo"
- "module: pt2-dispatcher"
- "module: inductor"
- "module: custom operators" …
```
> [bots] Autolabeler: label to label 

- .github/workflows/update_test_file_ratings.yml
- tools/torchci/td/calculate_file_test_rating.py
- tools/torchci/td/utils.py
It's been broken for 3 months...
Also:
* Reduce data range (last 90 days instead of everything)
* Reduce # test to run evaluate on, since it takes a long time
> [ez] Give content write permissions for update td rating files workflow and reduce data range

- torchci/components/TimeUtils.tsx
When hovering over a timestamp, you can see how long ago it was
Ironically this is opposite behavior from github: they like to show how long ago by default and the timestamp on hover
> [HUD] Add tooltip on timestamps for how long ago

- torchci/components/JobLinks.tsx
- torchci/components/JobTooltip.tsx
- torchci/components/ReproductionCommand.tsx
- torchci/components/TestInsights.tsx
- torchci/components/WorkflowBox.tsx
- torchci/package-lock.json
- torchci/package.json
- torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/yarn.lock
Not sure if this is good practice.  I take advantage of null + functional components to see if components render anything since renderToString and renderToStaticMarkup result in a lot of warnings
Puts the additional info into a list and concats the list with the separator so we don't have to worry about whether or not elements exist
Very minimal changes visually.  This is meant to maintain all old visuals other than:
* Adds commit link to job tooltip on HUD
Old vs new
* Removes the raw logs link in the pull box for https://torchci-git-csl-betterseparatorsforsubinfo-fbopensource.vercel.app/pr/124851
> [HUD] Better separators for job info, do not show raw log link if no raw link provided, add commit link to job tooltip

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/test_build_conda_windows_with_cuda.yml
Torchvision recently started to fail:
https://github.com/pytorch/vision/actions/runs/8894055247/job/24422954630
Rerun on test-infra was successful here:
https://github.com/pytorch/test-infra/actions/runs/8896788801/job/24430237844?pr=5152#step:10:51
Difference between successful run and failed one was found to be conda and conda-build version:
```
2024-04-30T15:02:21.0969669Z     conda-24.4.0               |   py39haa95532_0         950 KB
2024-04-30T15:02:21.0970680Z     conda-build-24.3.0         |   py39haa95532_0         582 KB
```
vs
```
2024-04-30T12:31:24.7113071Z     conda-23.9.0               |   py39haa95532_0         978 KB
2024-04-30T12:31:24.7113738Z     conda-build-3.28.4         |   py39haa95532_0         609 KB
```
> Advance conda and conda-build nightly versions

- torchci/lib/useTableFilter.ts
Before this change, when Esc is pressed to close pinned job tooltip, it also cleared the job filter, which is pretty annoying (imo).
> [hud] when esc pressed, clear pinned tooltip before clearing the job filter

- torchci/pages/benchmark/compilers.tsx
As reported by @eellison.  When we run the benchmark with only selected suites, only logs from these suites are available.  For example, if TIMM was not selected, TIMM logs should be there expectedly.  The page shouldn't crash.
The page is ok now https://torchci-git-fork-huydhn-fix-perf-dashboard-9c59e0-fbopensource.vercel.app/benchmark/compilers?startTime=Wed%2C%2024%20Apr%202024%2019%3A59%3A22%20GMT&stopTime=Wed%2C%2001%20May%202024%2019%3A59%3A22%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/eellison/637/head&lCommit=ce334fe472ee0b9a2c05d8fd4e4913695a2c05b2&rBranch=main&rCommit=0848051844181a7ac816b555f84caf16f20f0256
> Fix perf dashboard crash when there is no log

- torchci/components/CommitStatus.tsx
- torchci/components/WorkflowBox.tsx
- torchci/components/additionalTestInfo/TestInfo.module.css
- torchci/components/additionalTestInfo/TestInfo.tsx
- torchci/components/commit.module.css
Adds small button to toggle additional test info, which can show test reruns and TD exclusions
When toggled, the workflow box becomes wide, meaning it takes up the entire row
Only looks at first run attempt because test stat uploader doesnt really work with it right now and HUD isn't really configured to work with it either
https://torchci-git-csl-tda1-fbopensource.vercel.app/pr/125246
> [TDB] Reruns + TD exclusions

- torchci/components/JobLinks.tsx
Maybe controversial change?  
Change the look of the disable/unstable button that links to the issue that disables the test/marks the job unstable if the issue was not updated recently. Changes it to the style that makes it seem like there is no issue, so you have to click the button to make a new one, but the button will still go to the old issue so you can reopen it.
I keep getting confused since when I see "previously disabled test" I assume that the issue was wrongly closed recently and that I should reopen, but then I discover that the issue is from 3 months ago and that this is a new problem
Results in a change in expectations but it's not like "mark unstable job" or "disable test" imply that a new issue always gets made.
I guess as a side note, if we don't do something like this, …
> [HUD] Disable issue button - specify if issue is recent

- torchci/scripts/downloadQueryLambda.mjs
- torchci/scripts/uploadQueryLambda.mjs
Changes scripts that update the prodversions file to add a new line at the end
Super small thing but I keep thinking I made a change to prodversions but I find out that it's just that I opened up the file and saved, and vsocde and vim automatically add an empty new line on save
> [ez] End prodversions.json with new line

- torchci/lib/ParamSelector.tsx
- torchci/pages/failure.tsx
- torchci/pages/flakytest.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Makes the displays for the failure captures/flaky test name etc into form inputs so you can edit them, hit enter, and it will send you to the new url, which basically lets you search for a different failure without needing to change the url directly.
* hit enter or click away to submit/change url
* hit escape to reset the value to original value and unfocus
Play around on
https://torchci-git-csl-paramselectorfailureflakytest-fbopensource.vercel.app/ (the branch/repo, this previously existed but the PR changes some behavior)
https://torchci-git-csl-paramselectorfailureflakytest-fbopensource.vercel.app//failure?name=periodic%20%2F%20win-vs2019-cuda11.8-py3%20%2F%20test%20(default%2C%201%2C%204%2C%20windows.g5.4xlarge.nvidia.gpu)&jobName=undefined&failureCaptures=%5B%22test_linalg.py%3A%3ATes …
> [HUD] Adds ability to change url for flakytest and failure page from inputs on page

- aws/lambda/log-classifier/ruleset.toml
> [log classifier][ez] Change timed out rule

- torchci/components/additionalTestInfo/TestInfo.tsx
I forgot that reruns get put under their own element
Also say if the test ultimately succeeded or failed
format is usually
```
{
rerun: [{stuff},{stuff}],
failure: {stuff},
job_id: jobid
}
```
> [TDB] Better rerun info 

- tools/scripts/generate_docker_release_matrix.py
As a followup after: https://github.com/pytorch/pytorch/pull/125617
Add validation_runner output param to know what validation runner to use
Test:
```
python tools/scripts/generate_docker_release_matrix.py
{"include": [{"cuda": "11.8", "cuda_full_version": "11.8.0", "cudnn_version": "8", "image_type": "runtime", "docker": "ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240507-cuda11.8-cudnn8-runtime", "platform": "linux/amd64", "validation_runner": "linux.g5.4xlarge.nvidia.gpu"}, {"cuda": "11.8", "cuda_full_version": "11.8.0", "cudnn_version": "8", "image_type": "devel", "docker": "ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240507-cuda11.8-cudnn8-devel", "platform": "linux/amd64", "validation_runner": "linux.g5.4xlarge.nvidia.gpu"}, {"cuda": "12.1", "cuda_full_version": "12.1.1", …
```
> Separate arm64 docker builds from amd64

- torchci/lib/ParamSelector.tsx
Sometimes the paramselector doesn't update if you click on the prev page/back button
This fixes that by turning the input into a controlled component https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable
cc @huydhn
> [HUD] Fix paramselector not updating when prev/next page clicked

- torchci/lib/fetchPR.ts
- torchci/lib/jobUtils.ts
- torchci/lib/types.ts
- torchci/pages/api/[repoOwner]/[repoName]/pull/[prNumber].ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
- torchci/test/drciBot.test.ts
- torchci/test/jobUtils.test.ts
This extends Dr.CI to handle disabled test issues in several cases:
1. The closing of disabled test issues whereas a test could start failing on PR after its associated disabled issue is resolved.
2. A disabled test fails on PR where it should be skipped.
In both cases, the failure will be marked as skipped and the reason is provided.
https://github.com/pytorch/pytorch/pull/125656
As of commit 3a1e14cc5b5d44fa1b04561bccf14d832f70eb1d with merge base b6bcd0917310c657fc60bc7b20415f6948524eb8 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1715002918?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details open><summary><b>NEW FAILURE</b> - The following job has failed:</summary><p>
* [pull / linux-focal-cuda12.1-py3.10-gcc9 / test (default, 5, 5, …
> [Dr.CI] Handle the closing of disabled test issues

- torchci/components/additionalTestInfo/TestCounts.tsx
- torchci/components/additionalTestInfo/TestInfo.tsx
- torchci/pages/api/corresponding_workflow_id.ts
Adds the ability to compare the test counts and times with another run of the workflow for a different sha.
Assumes the most recent workflow is the best (probably not ideal)
first commit is moving stuff into a different file, second commit is real changes
https://torchci-git-csl-tdatestcountscomparison-fbopensource.vercel.app/pr/125114
and then put in some random shas from anything
> [TDB] Compare test/time counts with a sha

- torchci/pages/api/drci/drci.ts
After https://github.com/pytorch/test-infra/pull/5186
Link to hud which then redirects to the issue to prevent the PR getting included in the issue's events like the below 
Ran on one of my PRs, worked fine
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/125799/index.html)
* :page_facing_up: Preview [C++ docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/125799/cppdocs/index.html)
* :question: Need help or want to give feedback on the CI? Visit the [bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) or our [office hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)
Note: Links to docs will display an error until the docs builds have been completed.
As of commit …
> [DrCI] Link to hud instead of gh issue for related disabled test

- torchci/.prettierignore
Super minor but but I have a local .next folder that prettier doesn't ignore
> [ez] Add .next to prettierignore

- torchci/components/additionalTestInfo/RerunInfo.tsx
Forgot that reruns can sometimes not be an array. 
pr/125931
> [TDA] Fix reruns 

- .github/arc-runner-config.yaml
The 4 GPU setting was a mistake and should have been set to 1 GPU.
> fix: Reduce GPUs for 4xlarge system to 1

- torchci/lib/bot/autoLabelBot.ts
Adding automated release note tagging for `distributed/elastic` per instructions on https://github.com/pytorch/pytorch/wiki/PyTorch-AutoLabel-Bot#why-categorize-for-release-notes-and-how-does-it-work
> Added 'distributed (torchelastic)' release notes label tagging

- .github/scale-config.yml
Currently the largest instance is g5.12xlarge and it is only 4-gpu.  We need 8-gpu for 3D parallelism tests.
> Add g5.48xlarge (8gpu) instance type

- aws/websites/download.pytorch.org/meta_cdn_whl_redirect.js
This incorporates : https://github.com/pytorch/test-infra/blob/main/aws/websites/download.pytorch.org/pep503_whl_redirect.js
Also adds Country based redirect, currently set to 'CA' for testing purposes
> Update Meta cdn redirect function with latest code

- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/windows_job.yml
This is reported by @wconstab that Nova jobs didn't upload artifacts to GitHub when the test script failed, so it's not possible to access them, for example, to debug the failure.  It makes sense to always try to upload the artifacts instead:
* If the script fails, but there are artifacts, we should upload them
* If the script fails, and there is no artifact, it doesn't matter if the upload step fails or not because the job is going to fail anyway
> Always try to upload artifacts even if Nova jobs fail

- .github/scale-config.yml
Trying to explore options to help land: https://github.com/pytorch/pytorch/pull/126174
Current [manywheel-py3_9-cuda-aarch64-build / build](https://github.com/pytorch/pytorch/actions/runs/9112985273/job/25053413689?pr=126174#logs)
Takes around 6hrs (building only sm90 arch). Hence trying to bring slightly bigger worker, see if we can bring build time to manageable time 3-3.5hrs.
> Add m7g.2xlarge workers for linux-aarch64 gpu builds

- .github/scripts/run_with_env_secrets.py
Generating core dump usually brings more problems than it solves.  Recently, we have an incident when a wip PR from https://github.com/pytorch/TensorRT/actions/runs/9083569083/job/24963212460 crashed multiple times, generated too many core dump, and ran out of space on the runner.  Subsequent jobs on the same runner also ran out of space.  So, instead of complex clean up logic, it's easier to disable core dump completely until it's proven necessary.
> Disable core dump on Nova Linux jobs

- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
This is to support torchao use case where it uploads 12.1 CUDA nightly build to https://pypi.org/project/torchao-nightly
Do some testing on torchao https://github.com/pytorch/ao/pull/250:
* CUDA 12.1 is uploaded https://github.com/pytorch/ao/actions/runs/9144442527/job/25142401608?pr=250 to https://pypi.org/project/torchao-nightly/2024.5.19/#files
* Other CUDA versions are skipped https://github.com/pytorch/ao/actions/runs/9144442527/job/25142401944
> Add the option to upload a selected list of CUDA arch to pypi

- torchci/pages/failure.tsx
Adds a filter/way to select which jobs to show on the failures page
Tiny thing since the keyboard interrupt page is mostly arc jobs but I want to see the ones that aren't arc jobs
https://torchci-git-csl-selectjobsfailurepage-fbopensource.vercel.app//failure?name=periodic%20%2F%20linux-focal-cuda11.8-py3.9-gcc9%20%2F%20test%20(multigpu%2C%201%2C%201%2C%20linux.g5.12xlarge.nvidia.gpu)&jobName=undefined&failureCaptures=%5B%22!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!%20KeyboardInterrupt%20!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!%22%5D
Note the change in the bar graph too
> [HUD] Select jobs to show on failures page

- .github/scale-config.yml
PR introduced https://github.com/pytorch/test-infra/pull/5201 but only with max 2
Adding max of 20 to temporarily mitigate
> Increasing max runners for linux.g5.48xlarge.nvidia.gpu

- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Reduces visual clutter by moving the message to the very bottom of the page
It doesn't need to be made so prominent. Save that real estate for more important stuff
> [EZ] De-emphasize note about the page auto-updating.

- torchci/components/PageSelector.tsx
UX improvement for when you want to scroll back (or "Next") multiple pages.
Previously, when you went to hud, scolled to the bottom, click the "Next" button, and scrolled down again, the "Next" button would have moved to the right because "Prev" suddenly appeared.
You no longer have to do that
Old:
New:
> [EZ] [HUD] Always show a "Prev" button

- torchci/components/JobFilterInput.tsx
The text is no longer accurate. Simply typing something into the filter automatically updates the url
(This is for the job filter box at the top of the HUD home page)
> [EZ] [BE] [HUD] Remove invalid Job filter instructions

- torchci/pages/metrics.tsx
This table on the metrics page (it looks the same, its just that the things it links to changed)
Example
old link: 
https://hud.pytorch.org/failure/%23%23%5Berror%5DThe%20operation%20was%20canceled.
new link:
https://hud.pytorch.org/failure?failureCaptures=%5B%22%23%23%5Berror%5DThe%20operation%20was%20canceled.%22%5D
> [HUD] Fix common log classifications table links to examples of errors

- .github/workflows/_binary_upload.yml
A follow-up after https://github.com/pytorch/test-infra/pull/5217 and https://github.com/pytorch/ao/pull/250, repo like `torch/ao` doesn't have a nightly branch and build nightly directly out of main on a daily schedule.
> Also trigger nightly build on schedule

- torchci/lib/bot/retryBot.ts
- torchci/test/retryBot.test.ts
Currently lint jobs are re-run even if it's an actual lint failure, because `step.name.toLowerCase().includes("(nonretryable)")` doesn't work since moving to Nova.
This PR removes the lint retrying logic in conjunction with removing lint from retryable workflows in https://github.com/pytorch/pytorch/pull/126806
> Remove linter rerun logic

- torchci/components/CopyLink.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Adds a permalink button at the top of the home screen, next to the branch name.
When clicked, the button offers visual feedback that the url was copied to the clipboard. The button resets after 3 seconds.
Extended the existing CopyLink component to support this use case, and also updated the icons it uses to better match standard convention
Button:
When clicked:
> [HUD] [BE] Add permalink to home screen

- torchci/pages/metrics.tsx
- torchci/pages/testing_overhead.tsx
It's a pretty chart
Shuffle the disabled tests chart to the bottom to maintain horizontal alignment/current placement of duration/tts tables
> [HUD] Bring back workflow load chart on metrics page

- .github/workflows/_binary_upload.yml
A follow-up after https://github.com/pytorch/test-infra/pull/5217 and https://github.com/pytorch/ao/pull/250, repo like torch/ao doesn't have a nightly branch and build nightly directly out of main on a daily schedule.  This was missed in https://github.com/pytorch/test-infra/pull/5222.  It's a bit tricky to get this right off the bat.
Also need to land D57657633 to allow nightly upload on the AWS side.
> Connect OIDC when building nightly on schedule

- torchci/lib/useGroupingPreference.tsx
a minor bugfix
I mistook the `override` parameter of `usePreference` for default/initial value, resulting the setting to always be false after refresh.
This change fixes that, and also improves and documents `usePreference` hook API.
> [HUD] fix localStorage persistence of `useMonsterFailures` preference

- torchci/scripts/backfillJobs.mjs
The queue can get quite long, which results in a lot of API usage, leading to getting rate limited, so restrict the number of jobs we check each time
> Limit number of jobs backfilled per run

- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This is tiny but I don't like it when I click on the white space near the checkboxes to escape the job tooltip or something
and it will select the checkbox.
So change the clickable area for the checkboxes to be just the checkbox and the text
> [ez][HUD] Change checkbox clickable area to be smaller

- .github/actions/setup-binary-builds/action.yml
Cherry pick of https://github.com/pytorch/test-infra/pull/5152 to resolve conda failure on release branch
> [Cherry pick] Advance conda and conda-build nightly versions 

- torchci/pages/kpis.tsx
- torchci/rockset/prodVersions.json
- torchci/rockset/pytorch_dev_infra_kpis/__sql/time_to_signal.sql
- torchci/rockset/pytorch_dev_infra_kpis/time_to_signal.lambda.json
Group TTS KPI by branch.
I'm not sure what the reasoning behind the old query was, so I simplified it a lot and only include pull and trunk
Old:
New:
> [HUD] Group TTS KPIS by branch

- .github/scale-config.yml
Increasing the worker size, trying to improve build time for arm64 GPU machines. Here is the issue: https://github.com/pytorch/pytorch/issues/126980
AWS Cost: 0.65c/hour
In comparison to our Linux c5.4xlarge worker, AWS Cost: 0.68c/hour
> Update arch64 worker to m7g.4xlarge

- aws/lambda/log-classifier/fixtures/request.json
- aws/lambda/log-classifier/ruleset.toml
- torchci/lib/drciUtils.ts
From https://github.com/pytorch/pytorch/pull/125946, it looks like build job is stable enough to be excluded from flakiness check.  I also add a rule to capture ninja build failure, it doesn't say much, but it's still better than the misleading sccache error.
On https://github.com/pytorch/pytorch/pull/125946 itself
As of commit 490d2e80af89a6a5506d8908814bcaa4a31c996a with merge base 980f5ac0499447cd6d39b6241ae30ae30937a3e5 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1716299107?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details open><summary><b>NEW FAILURES</b> - The following jobs have failed:</summary><p>
* [pull / linux-focal-py3.8-clang10 / test (dynamo, 2, 3, linux.2xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/125946#25360697493) …
> Exclude build jobs from flakiness check

- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
I added these changes as they are flagged as lint warning in https://github.com/pytorch/test-infra/pull/5256.  However, this is  false positives and causes a regression in the benchmark page where selecting different options doesn't reflect in the URL anymore.
For example, selecting different suites does nothing now on HUD https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2017%20May%202024%2022%3A17%3A06%20GMT&stopTime=Fri%2C%2024%20May%202024%2022%3A17%3A06%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=main&lCommit=aa6de7618139644d440decd824b787add3dc59e5&rBranch=main&rCommit=15ca562f863ffe69d76c0ccaf448b27d18ceb2e8
Working on https://torchci-git-fork-huydhn-fix-use-effect-regression-fbopensource.vercel.app/benchmark/compilers?startTime=Fri%2C%2017%20M …
> Fix useEffect regression on benchmark pages

- torchci/components/TooltipTarget.tsx
Very minor
Changes the tooltip hover area to be just the element that gets shown when not hovering (tooltip target)
Previously, if you were fast enough, you could get your mouse onto the tooltip content and the content would stay, this makes it so that it updates to the next tooltip content for the tooltip target that is currently under your mouse
I don't think anyone but me notices this lol
Also makes the updating for moving away/moving in slightly faster
> [HUD] Change tooltip mouse hover area

- s3_management/manage.py
This allows 2 build time dependencies in download.pytorch.org, so we can potentially use our index only during the build:
https://github.com/pytorch/vision/blob/main/pyproject.toml#L18
> Update manage.py - add build time dependencies

- aws/lambda/log-classifier/ruleset.toml
* `SUBFAIL` is a new string I saw
* `The following tests failed consistently: ` is printed by run_test when tests fail consistently (mostly a fallback, I don't expect this to match often since the other rules for tests should match instead)
* `Runtime error` is not guaranteed to be raised, but `something/test_something failed! (maybe signal info here)` should still be printed
Example log that got match to the very generic `##[error]Process completed with exit code 1.` that any of the above changes should be able to handle
https://github.com/pytorch/pytorch/actions/runs/9352291906/job/25742364204
```
2024-06-03T15:38:03.2015505Z SUBFAIL [0.0000s] onnx/test_fx_op_consistency.py::TestOnnxModelOutputConsistency_opset_version_18_model_type_TorchModelType.TORCH_NN_MODULECPU::test_output_match__u …
```
> [log classifier] More test failure rules

- torchci/components/NavBar.tsx
- torchci/components/ValuePicker.tsx
- torchci/pages/disabled.tsx
- torchci/rockset/commons/__sql/disabled_test_labels.sql
- torchci/rockset/commons/__sql/disabled_tests.sql
- torchci/rockset/commons/disabled_test_labels.lambda.json
- torchci/rockset/commons/disabled_tests.lambda.json
- torchci/rockset/metrics/__sql/disabled_test_historical.sql
- torchci/rockset/metrics/disabled_test_historical.lambda.json
- torchci/rockset/prodVersions.json
This page displays the total number of active disabled tests and their break down by platforms, labels, and their triaged status.  By default, the table is sorted by high priority status and the issue last updated.  Hopefully, this will allow the test owners to better keep track of active disabled tests assigned to their teams.
The preview is at https://torchci-git-fork-huydhn-add-break-down-disa-507a79-fbopensource.vercel.app/disabled
> Add a page to navigate disabled issues on HUD

- tools/scripts/generate_binary_build_matrix.py
Never seen `sys.modules[__name__].foo` trick before, but it seems to be exactly equivalent to the [global](https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python) keyword
I.e.
```python
import sys
mod = sys.modules[__name__]
def init_x() -> None:
mod.x = 3
if __name__ == "__main__":
init_x()
print(x)
```
is equivalent to
```python
def init_x() -> None:
global x
x = 3
if __name__ == "__main__":
init_x()
print(x)
```
> [BE] Use globals in `generate_binary_build_matrix`

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
Save my life by letting me quickly deselect everything in the historical queue times chart except the g5 runners
Adds all and inverse buttons for selecting the lines in the charts
Useful for charts that have tons of lines and you only care about one.
Most visibly prominent on the kpis page, but this should affect all charts
Ex queue times
https://echarts.apache.org/en/option.html#legend.selector
Can't just use true for some reason, the buttons disappear (on rerender? not sure)
> [HUD] All and inverse buttons for chart legends

- terraform-aws-github-runner/variables.tf
These are used to configure the system that provisions runners. Update the documentation to capture the nuances of the parameters here
> [BE] Improve documentation of somewhat ambiguous terraform variables

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
Fixes https://github.com/pytorch/test-infra/issues/5220
The getExpectedLabels test would return all labels that were expected to be on the issue, risking race conditions.
Now it instead returns:
1. The platform labels that are expected to be on the issue
2. Any platform labels that are erroneously on the issue and should be removed
> Fix labels race condition

- .github/workflows/linux_job.yml
Prints a command one can copy-n-paste to figure out how to access one's build/test during ssh session
> [BE] Print `docker exec` instruction during SSH step

- torchci/pages/api/drci/drci.ts
This groups all cancelled jobs on Dr.CI into a separate collapsible section to avoid clutter the view.  Cancelled jobs are still treated as new failures from mergebot point-of-view.
https://github.com/pytorch/pytorch/pull/126717
As of commit 1509f7c2cc07e9d921d0e9dd66c7435b3f01be52 with merge base a7c596870d92f15cf723f53139bf1a63ac6da4a2 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1717624429?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details ><summary><b>CANCELLED JOB</b> - The following job was cancelled. Please retry:</summary><p>
* [inductor / cuda12.1-py3.10-gcc9-sm80 / test (inductor_torchbench_smoketest_perf, 1, 1, linux.gcp.a100)](https://hud.pytorch.org/pr/pytorch/pytorch/126717#25866261671) …
> Add a new section on Dr.CI for canncelled jobs

- .github/arc-node-config.yaml
- .github/arc-runner-config.yaml
- .github/scale-config.yml
Due to issue [#123224](https://github.com/pytorch/pytorch/issues/123224), we plan to add m4.10xlarge instance for testing inductor CPU FP32 accuracy with AVX2 ISA in Pytorch CI. We collected the time cost for running FP32 accuracy test on both m4.10xlarge and c5.12xlarge, and here is the results.
</head>
<body link=blue vlink=purple>
Config | Runner | Instance type | ISA | Price $/h | TB Acc /h | HF Acc /h | TIMM Acc /h | Total Time /h
-- | -- | -- | -- | -- | -- | -- | -- | -- 
1 | add in this PR | m4.10xlarge | AVX2 | 2 | 1.5 | 0.8 | 1.2 | 3.5
2 | linux.12xlarge | c5.12xlarge | AVX512, AVX2 | 2.04 | 1.5 | 0.5 | 0.6 | 2.6
</body>
</html>
Config 2 depends on PR [#123514](https://github.com/pytorch/pytorch/pull/123514) land, and if the inductor generates code which call oneDNN kernels, …
> Add CPU m4.10xlarge instance type for Inductor CPU FP32 accuracy test with AVX2

- torchci/lib/drciUtils.ts
- torchci/lib/jobUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciUtils.test.ts
I have seen recent cases where Dr.CI returns inconsistent results where a failure was treated as a new failure while other looking exactly the same were either unstable or flaky. This is due to 1) searching for similar flaky failures could miss some and 2) oncall didn't open unstable issues for all cases.  So, the fix here is to do a post processing step to make sure that failures don't match anything that has already been classified as flaky to unstable.
I skip the generic GHA error to avoid false positives.
For example,
https://github.com/pytorch/pytorch/pull/128005
As of commit a80088bd7f862e2f28836eedfc4f88af576897aa with merge base b054470db22a6c8ecba31c44ce54b9ca48159cdd (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1717564884?label=&color=FFFFFF&style=flat-sq …
> Check for similar known unrelated failures in the same PR

- s3_management/manage.py
- s3_management/update_dependencies.py
Additional dependency:
``importlib-metadata``
> Add textx depdendency when python < 3.10

- s3_management/manage.py
- s3_management/update_dependencies.py
Follow up after https://github.com/pytorch/test-infra/pull/5315
metplotlib has : ```Requires-Dist: importlib-resources>=3.2.0; python_version < "3.10"```
> Add importlib-resources

- .github/workflows/linux_job.yml
This seems to work while `{{ env.RUNNER_TEMP }}` is not https://github.com/pytorch/test-infra/actions/runs/9492075721/job/26158612745?pr=5327#step:16:29
> Switch to ${{ runner.temp }}

- .github/scripts/anaconda-prune/prune.sh
While we don't have vision/torch builds properly scync, adding this as mitigation
Help mitigate this issue: https://github.com/pytorch/pytorch/issues/125879
> Allow having 2 versions of torch in nightly for fallback

- aws/ami/windows/scripts/Installers/Install-VS.ps1
See https://github.com/pytorch/vision/pull/8492 for reference
Link taken from here: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history#evergreen-bootstrappers
> Windows AMI Pin vs 2022 to older msvc release

- aws/ami/windows/windows.pkr.hcl
We get a failure during this step:
https://github.com/pytorch/test-infra/blob/main/aws/ami/windows/scripts/Installers/Install-Miniconda3.ps1#L31
``
Miniconda installation failed, no hook found
``
Workaround it to install Miniconda first to get past this error and continue installing everything else.
> Workaround for Windows AMI conda install step failing

- torchci/lib/drciUtils.ts
- torchci/lib/jobUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciBot.test.ts
- torchci/test/drciUtils.test.ts
Fixes https://github.com/pytorch/test-infra/issues/5188
This is to address the mismatch reported in https://github.com/pytorch/test-infra/issues/5188 where some legit failures from the previous merge commit are marked as flaky.  We already have the logic to gate against this in `isFailureFromPrevMergeCommit`.  The bug here is that if a match from a subsequent broken trunk commit was found before `isFailureFromPrevMergeCommit` was applied, the match was returned right away.
There are 2 fixes here:
* Correctly apply `isFailureFromPrevMergeCommit` to all potential matches. Even if one failure shows up from the previous merge commit, the failure will be treated as a new failure.
* I also move the `getPRMergeCommits` function call out of `hasSimilarFailures` because this is the same for all …
> Apply isFailureFromPrevMergeCommit logic to all similar failures

- torchci/components/CommitStatus.tsx
This is a miss from https://github.com/pytorch/test-infra/pull/5122 where I failed to check that the repo field in JobData is optional and wasn't set in HUD commit and PR pages.  So, marking an unstable job link works correctly in main HUD page like https://hud.pytorch.org/hud/pytorch/executorch/main where the data comes from `fetchHud`, but it uses the default link pointing to `pytorch/pytorch` in:
* Commit page https://hud.pytorch.org/pytorch/executorch/commit/7c0f4c2b6f87369ee20544aada33dc55078c6bc6
* and PR page https://hud.pytorch.org/pr/pytorch/executorch/3972
The fix here is to populate the repo field if it's not there
Verify this locally (need to login to HUD)
* http://localhost:3000/pytorch/executorch/commit/7c0f4c2b6f87369ee20544aada33dc55078c6bc6
* …
> Set the correct repo link in mark unstable job button in commit and PR pages

- torchci/lib/bot/pytorchBot.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
- torchci/test/utils.ts
For repos that want to merge via `@pytorchbot merge`, the repo should put `mergebot: True` in their `pytorch-probot.yml`
In preparation for letting torchao trigger their own merges through bot
Risks: 
If we can't query for the config for some reason, it will not merge
todo before this gets merged:
Add `mergebot: True` in pytorch's config file
> [mergebot] Set mergebot to be configured via config

- .github/workflows/linux_job.yml
Cherry pick #5327 onto release branch to fix executorch release CI problems https://github.com/pytorch/executorch/actions/runs/9555791712/job/26339725286?pr=3994
> Switch to ${{ runner.temp }} (#5327)

- .github/workflows/lambda-runners.yml
- terraform-aws-github-runner/modules/runners/lambdas/runners/package.json
- terraform-aws-github-runner/modules/runners/lambdas/runners/yarn.lock
Upgrade from the version of @vercel/ncc which used the legacy ssl provider and required and extra parameter to be passed in.
Requiring this extra parameter to be passed in had broken pytorch/ci-infra's `make link-test-infra-canary` command since that wasn't passing in this new parameter (not to mention it used a less secure form of ssl)
> Remove dependency on legacy ssl

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_llms.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_names.sql
- torchci/rockset/benchmarks/oss_ci_benchmark_llms.lambda.json
- torchci/rockset/prodVersions.json
After https://github.com/pytorch/pytorch/pull/128091, we now have dtype and device columns on the dashboard.  This also fixes the ugly view on https://hud.pytorch.org/benchmark/llms where some older records show up without these two columns.
https://torchci-git-fork-huydhn-update-llms-benchmark-fbopensource.vercel.app/benchmark/llms
> Add dtype and device columns

- .github/actions/setup-ssh/action.yml
- .github/actions/setup-ssh/index.js
- setup-ssh/src/main.ts
And set it to true by default. This will prevent workflow failures due to the network outages
> [BE] Add `fail-silently` option to setup-ssh

- s3_management/manage.py
Add torch_no_python to s3 allow list
Needed for split build as this is the new package it creates
> Add torch_no_python to s3 allow list

- .github/workflows/generate_binary_build_matrix.yml
- tools/scripts/generate_binary_build_matrix.py
Adds split build to binary generation script. The outputs of the json is as follows. We will need to also add it to testing proper.
```
sahanp@sahanp-mbp ~/test-infra> python tools/scripts/generate_binary_build_matrix.py                                                                                                                                                                                    (pytorch)
{
"include": [
{
"python_version": "3.8",
"gpu_arch_type": "cpu",
"gpu_arch_version": "",
"desired_cuda": "cpu",
"container_image": "pytorch/manylinux-builder:cpu",
"package_type": "manywheel",
"build_name": "manywheel-py3_8-cpu",
"validation_runner": "linux.2xlarge",
"installation": "pip3 install --pre torch torchvision torchaudio --index-url …
```
> [Split Build] Add split build to binary build generation

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
A minor fix on Dr.CI to correctly group cancelled timeout step into cancelled group.
https://github.com/pytorch/pytorch/pull/128801
BEFORE
As of commit 3a7846bb10be264306c1b30d43db62f96dfd4788 with merge base f9dae86222aaf15ea085c7774da70781bae46ff9 (<sub><sub><img alt="image" width=70 src="https://img.shields.io/date/1718581874?label=&color=FFFFFF&style=flat-square"></sub></sub>):
<details open><summary><b>NEW FAILURE</b> - The following job has failed:</summary><p>
* [trunk / macos-py3-arm64 / build](https://hud.pytorch.org/pr/pytorch/pytorch/128801#26309349897) ([gh](https://github.com/pytorch/pytorch/actions/runs/9542158142/job/26309349897))
`##[error]The operation was canceled.`
</p></details>
<details ><summary><b>FLAKY</b> - The following job failed but was likely due to flakiness …
> Handle cancelled timeout step on Dr.CI

- aws/ami/windows/windows.pkr.hcl
We only have runners in us-east-1, so there's no reason to upload our AMI to us-east-2 as well.
> [BE][EZ] Reduce unnecessary windows AMI uploading

- .github/scale-config.yml
Which enables one to test float8 dtypes supported by https://www.nvidia.com/en-us/data-center/l4/ GPUs , see https://aws.amazon.com/ec2/instance-types/g6/
> Add g6.4xlarge runner type

- .github/workflows/lambda-release-tag-runners.yml
- terraform-aws-github-runner/README.md
Document and automate the step of tagging updates to the autoscale lambdas in order to actually use them.
The lambdas are what scales our runners up and down. This folder contains code to define those lambdas and a terraform module that provisions them
> Improve autoscale lambda release documentation and ease of use

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
So that runner labels like `foo-metal` will be valid again Test plan:
```
% /opt/homebrew/bin/node
Welcome to Node.js v22.2.0.
Type ".help" for more information.
> const alphaNumericStr = /^[a-zA-Z0-9.\-]+$/;
undefined
> const alphaNumericStr = /^[a-zA-Z0-9.\-]+$/;
> alphaNumericStr.test("foo-bar")
true
> alphaNumericStr.test("foo.bar")
true
> const alphaNumericStrPrev = /^[a-zA-Z0-9.]+$/;
undefined
> alphaNumericStrPrev.test("foo.bar")
true
> alphaNumericStrPrev.test("foo-bar")
false
```
> Add `-` to alphaNum character set

- .github/scale-config.yml
After reaching out to @malfet we agreed to disable this runner by reverting this commit until we evaluate a more reasonable number for max_runners.
> Revert "Add g6.4xlarge runner type"

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
During firefight we changed the package name. But after careful investigation, it seems that the package name is not the issue given its presence is over 2 years old.
So I am returning the package, otherwise next kernel upgrade could cause a big breakage again.
Seems that the main isue is that `$@` and `"$@"` expands differently. Being the 2nd one what we want, as it expands to: `"$1" "$2" "$3" ...` over `$1 $2 $3`. This was causing some parameters to be splitted by space.
> Fixing package name kernel-devel-uname-r on user-data.sh + fix shell expansion

- torchci/pages/api/flaky-tests/flakytest.ts
- torchci/pages/flakytest.tsx
* Requires a more specific search ( cannot do empty name, classname, and file) -  querying for non specific takes a long time
* Includes rerun disabled jobs in results
Mostly looks the same, the content will be different though.  
Normal page with test: https://torchci-git-csl-flakytestspageshowrerundisa-7ca490-fbopensource.vercel.app/flakytest?name=test_aot_module_simplified_fake_tensor_gm_raises&suite=TestAOTModuleSimplified&limit=100
New page with nothing set https://torchci-git-csl-flakytestspageshowrerundisa-7ca490-fbopensource.vercel.app//flakytest?name=%25&suite=&file=%25&limit=100
Old one took forever to load and if it did load, it would look kind of like the previous link
> [HUD] Flaky tests page: Require more specific search, include rerun disabled tests jobs

- torchci/rockset/metrics/__sql/queued_jobs_by_label.sql
- torchci/rockset/prodVersions.json
- torchci/scripts/updateQueueTimes.mjs
Use the machine type and time as the key
> Rockset migration - move upload for queue_times_historical from rockset to s3 

- .github/workflows/update-queue-times.yml
Role defined in https://github.com/pytorch-labs/pytorch-gha-infra/pull/441
Related
* https://github.com/pytorch/test-infra/pull/5398
> Rockset migration - update queue times - set aws permissions in workflow

- .github/workflows/update-queue-times.yml
- torchci/rockset/metrics/__sql/queue_times_historical.sql
- torchci/rockset/prodVersions.json
Related to https://github.com/pytorch/test-infra/pull/5398
Change historical queue times query for HUD metrics page
Looks good
Also change the workflow so we can use workflow dispatch and so that it has the env vars
> Rockset migration - update queue times- explicitly use the new time field instead of _event_time and fix env variables in update queue times workflow

- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Currently, if you click the permalink button on the second page of HUD https://hud.pytorch.org/hud/pytorch/pytorch/main/2?per_page=100
Then the result is https://hud.pytorch.org/hud/pytorch/pytorch/c9dc9887db0deff3ccbebf9b59dcbe79c3bd8a4f/2?per_page=100
Note the difference in first sha shown on the page.  This is because the permalink uses the latest commit sha present on the page (c9dc988), but uses the page param (2 in this example).  
This PR changes it to use the latest commit sha of the branch on page one, so the new permalink is https://torchci-git-csl-permalinkpage1-fbopensource.vercel.app/hud/pytorch/pytorch/29c68df600e6cb8eb61ccfea57d6aa3685b0a30f/2?per_page=100.
The sha is doesn't show up on the original page that we clicked the permalink button on, it's the sha on page 1.  The …
> [ez][HUD] Main page permalink to use sha from page one

- torchci/scripts/updateQueueTimes.mjs
Follow up to https://github.com/pytorch/test-infra/pull/5412
I'm not sure why the env var is not being set https://github.com/pytorch/test-infra/actions/runs/9867482380/job/27247927172#step:5:10 but the other ones are so we can just use those for now
> [queue times] Use correct env vars

- .github/workflows/update-queue-times.yml
- torchci/scripts/updateQueueTimes.mjs
* Follow up to https://github.com/pytorch/test-infra/pull/5417
I think the env var I was missing is the session token, which is needed for temporary credentials.  Instead of specifying that, I choose to not explicitly set the credentials information and the `new S3Client` will know to look for the env vars it needs on its own.  This makes it slightly easier to run locally if you have tokens already
A succeeding run is https://github.com/pytorch/test-infra/actions/runs/9877586518/job/27279561554?pr=5418.  I got this by temporarily adding my branch to the iam trust relationship policy and setting the workflow to run on push trigger. 
I forgot that I could just add my branch there and test on a PR instead of needing to test on the main branch
I don't think the upgrade to v3 is necessary but …
> [queue times] Actually use correct env vars

- .github/workflows/update_test_file_ratings.yml
- tools/torchci/rockset_utils.py
- tools/torchci/td/get_merge_base_info.py
Removes ability to run the update_test_file_ratings on pull request because I don't want to give permissions to write to the bucket to branches
Role defintion in https://github.com/pytorch-labs/pytorch-gha-infra/pull/426
* Companion to https://github.com/pytorch/test-infra/pull/5375
> [RS migration] merge_bases generation script to upload to s3 instead of rockset

- torchci/lib/s3.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drciBot.test.ts
Upload the merge bases to s3 instead of rockset.  Tested locally by running `curl "http://localhost:3000/api/drci/drci?prNumber=130387" --data 'repo=pytorch'` with the part to query rockset commented out and checked that something got put to s3.
Also sanity checked that the bucket could be ingested by rockset
Fixed changed files query (previously it was taking the diff between the PR head and the main branch head, now it does another query for the files between the merge base and the PR head.  I don't know how I didn't miss this before)
* Companion to https://github.com/pytorch/test-infra/pull/5377
> [RS migration][drci] upload merge bases to s3, fix changed files query

- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_llms.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_names.sql
- torchci/rockset/prodVersions.json
`oss_ci_benchmark_v2` is a copy of `oss_ci_benchmark` but it's backed by dynamoDB.  This is not yet out of Rockset, but at least we now have a copy of the database on dynamoDB.
1. I import `oss_ci_benchmark` to dynamo using the script in https://github.com/pytorch/test-infra/pull/5408
2. Then I create a new Rockset called `oss_ci_benchmark_v2` from the new dynamoDB table from the previous step
This also gets rid of the use of the transient `_event_time` field from Rockset.
No change to the HUD page https://torchci-git-fork-huydhn-ossci-queries-to-v2-fbopensource.vercel.app/benchmark/llms
> [Rockset migration] Switch to oss_ci_benchmark_v2 powered by dynamoDB

- aws/lambda/log-classifier/Cargo.lock
- aws/lambda/log-classifier/Cargo.toml
- aws/lambda/log-classifier/src/network.rs
Update aws packages for rust
In order to use the aws bedrock sdk, we need to update the aws packages of this project. This pr does that.
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/test-infra/pull/5413).
* #5414
* __->__ #5413
> Update aws packages for rust

- .lintrunner.toml
- aws/lambda/log-classifier/Cargo.lock
- aws/lambda/log-classifier/Cargo.toml
- aws/lambda/log-classifier/fixtures/error_log1.txt
- aws/lambda/log-classifier/src/bedrock.rs
- aws/lambda/log-classifier/src/bedrock/prompts.rs
- aws/lambda/log-classifier/src/lib.rs
- aws/lambda/log-classifier/src/main.rs
- aws/lambda/log-classifier/src/snapshots/log_classifier__test__create_log_snippet.snap
[hud] Add llm logic to log classifier
Summary:
This pr introduces the logic needed to apply llms to the log classifier.
Specifically the task that we're trying to do is that most of the time we hit the failure case with our log classifier, the actual error is somewhere above that error + nearby. The initial strategy for using llms is as follows.
1) Run the log classifier as normal
2) If we hit the failure case get a snippet of the log which contains n lines above the failure case.
3) Use the llm to find the failure line in the snippet.
4) Check if the failure line is legit otherwise use a better llm
5) If the better llm fails just give up and return the failure case.
This pr adds the logic such that we are able to perform steps 2-4. We still need to integrate this into the log classifier …
> [hud] Add llm logic to log classifier

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
After a few experiments and practical uses I identified a few shortcomings for the new AMI experiment feature, the goal of this PR is to address them:
1 - Metrics are not broken down by runner label + experiment or not. What makes it very hard to detect and understand issues in the experiment instances. New metrics now should include this breakdown;
2 - The failure rate for jobs is >60%, this makes it pointless to make an effort to keep the runner live when it succeed and remove when it fails. It makes more sense to be safe from the start and run the instances in the experiment as ephemeral instances;
> Improves visibility for AMI experiments

- aws/lambda/log-classifier/src/bedrock.rs
- aws/lambda/log-classifier/src/main.rs
- aws/lambda/log-classifier/src/snapshots/log_classifier__bedrock__test__create_log_snippet.snap
[log-classifier] Improve validation logic to check lines in log specifically
Summary:
This pr improves the validation logic for the ai output and enforces that the line created by the llm is in the log per batim
Side quests include some refactoring such that only make_query needs to be called by the client (+ to improve testing)
minor refactoring for clarity.
Test Plan: cargo test (added unit tests)
> [log-classifier] Improve validation logic to check lines in log specifically

- .github/actions/setup-nvidia/action.yml
- aws/lambda/log-classifier/src/bedrock.rs
As reported by @wconstab https://fb.workplace.com/groups/4571909969591489/permalink/7817935518322235
> Run nvidia-persistenced to avoid timeout error when initializing Docker containers

- torchci/lib/JobClassifierUtil.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This is a change to how the unstable & mem leak/rerun disable tests jobs works with the full view.  Previously, if the job was both unstable and mem leak, then it would show up in the main area since unstable jobs show up in the main area and the unstable categorization would take precedence over the mem leak check categorization.  This changes it so that if the unstable group exists, the unstable jobs get put into that group.  However, if it doesn't, then the job goes into the mem leak check group.
Old:
Put under the general area
New:
Put into the mem leak or rerun disable tests group
There is no change.  The unstable jobs get put into the unstable jobs group
There is no change.  The unstable jobs get put into the unstable jobs group
There is no change.  The unstable jobs group …
> [HUD] Main page: better grouping in full view for jobs that are unstable and mem leak check/rerun disabled tests

- torchci/components/JobLinks.tsx
I don't know why it required authentication so I got rid of it
Doesn't include env vars but it is better than what existed previously
Old
`python FAILED [5.4733s] inductor/test_torchinductor_dynamic_shapes.py::DynamicShapesCpuTests::test_upsample_bicubic2d_dynamic_shapes_cpu.py DynamicShapesCpuTests.test_upsample_bicubic2d_dynamic_shapes_cpu`
New
`python inductor/test_torchinductor_dynamic_shapes.py.py -k inductor/test_torchinductor_dynamic_shapes.py::DynamicShapesCpuTests::test_upsample_bicubic2d_dynamic_shapes_cpu`
Old not authenticated:
New not authenticated:
https://torchci-git-csl-fixpytestreprocommand-fbopensource.vercel.app//pytorch/pytorch/commit/8fcb156e8b5697a8f292db6db2a1803c5f4ce2d7
> [HUD] Slightly improved repro copy paste for failure, do not require authentication to see copy paste link

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
This workaround might not be necessary any longer as kernel-devel appears to be available again in package managers. This also fixes the LF ALI runners as they are failing to fetch from the s3://ossci-linux bucket due to no permissions.
I verified by doing a `yum install kernel-devel` on one of the EC2 instances that was stuck and saw that it returned a newer kernel-devel package.
Relates to pytorch/pytorch#129880 and pytorch/ci-infra#244.
> Remove workaround to install kernel-devel

- torchci/rockset/commons/__sql/flaky_tests.sql
- torchci/rockset/prodVersions.json
[0] -> [1] since it is indexed by 1
Idk how this worked before
> [flakybot] Fix sql query

- tools/torchci/check_alerts.py
- tools/torchci/tests/test_check_alerts.py
Made a ton of issues for some reason
This change checks for an open issue made in the last 7 days.  If it sees one, it doesn't make a new one
> Fix alert for no new flaky tests spamming

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
Emits:
- Runner type
- Instance Type
- AMI ID
- AMI Name (if known)
Note: Hard coding the ami id->name mapping isn't ideal, we should get the name dynamically. However, that requires granting the runners extra permissions to read the AMI name so will add that as a follow up.
Sample output:
Testing: https://github.com/pytorch/pytorch-canary/actions/runs/10012762937/job/27679499479?pr=227
> Emit Runner info at the start of every job on self hosted linux runners  

- .github/scale-config.yml
Adding new runner types to limit the blast radius of testing the amazon 2023 ami in pytorch/pytorch
This lets us port individual jobs over to the new AMI instead of an all-or-nothing approach, and also allows other repos to be separately tested.
> Add new runner types for the amazon 2023 ami

- torchci/pages/api/flaky-tests/disable.ts
As in title, increase the number of jobs to count a test as flaky from 2 -> 3
Not sure if I like this but there are a ton of issues being made and this should reduce it a bit
> [flakybot] Increase threshold for number of jobs needed to make a flaky issue to 3

- .github/scripts/run_with_env_secrets.py
See: https://fb.workplace.com/groups/4571909969591489/permalink/7818394354943018/
ExecuTorch CI was running into an issue where non-utf8 print output caused tests to crash. This was resolved by removing the printing in https://github.com/pytorch/executorch/pull/4268. 
This PR updates the error handling to use `backslashreplace`, which should still show us the error/printing, but without crashing the test.
From https://docs.python.org/3.9/library/io.html#io.TextIOWrapper:
```
'backslashreplace' causes malformed data to be replaced by a backslashed escape sequence. 
```
From https://docs.python.org/3/library/subprocess.html#frequently-used-arguments:
If encoding or errors are specified, or text (also known as universal_newlines) is true, the file objects stdin, stdout and stderr will be …
> Add errors="backslashreplace" to run_with_env_secrets.py

- .github/workflows/linux_job.yml
This is currently failing: https://github.com/pytorch/builder/actions/runs/10062669199/job/27817964549
Since we use:
``linux.arm64.m7g.4xlarge``
instead of 
``linux.arm64.2xlarge``
> Fix linux.arm64 GPU validations

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
Adds instructions on how to re enable the test in the validation comment (the comment that gets made after a disable issue gets made) so that manually created disable issues also have instructions
Example:
> [flakybot] Instructions to re-enable test in validation comment

- .github/scale-config.yml
Trying to mitigate https://github.com/pytorch/test-infra/issues/5493
Should replace linux.12xlarge.ephemeral which are often not available
> Add new type of ephemeral runners linux.9xlarge to be used for docker builds

- torchci/pages/api/flaky-tests/disable.ts
There are too many getting made, it's making it hard to debug and to look at other flaky tests
> [flakybot] Temporarily ignore sdpa issues, there are too many

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
1 - increase the time out for instances to be cleaned up if not used from 10 to 60 minutes
2 - increase the timeout to give up if user-data fails from 10 to 20 minutes
3 - Deploy a higher percentage of instances when they are ephemeral.  From up to ~30% minAvailable to ~50%
> Small improvements designed to increase the resiliency of ephemeral instances

- torchci/components/CopyLink.tsx
- torchci/components/JobLinks.tsx
- torchci/components/SmallerEmoji.tsx
Add a button to copy info so you can paste into revert message
Relies on https://github.com/pytorch/test-infra/pull/5432
**Caveat: Changes the icons for other things too** Not sure if this is something we're willing to have
Link:
Old 
new
Copied checkmark:
old
new
Info includes:
if test, testname
GH job link
HUD commit link
ex 
export/test_torchbind.py::TestExportTorchbind::test_export_inplace_custom_op [GH job link](https://github.com/pytorch/pytorch/actions/runs/10077811381/job/27862620615) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/6415c45da5aee538624355fdf5aab8059bf5f98b)
or 
[GH job link](https://github.com/pytorch/pytorch/actions/runs/10074672842/job/27851322465) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/62e566b3455785569c923be304b0701a2cb …
> [HUD] Add button for copying common revert message info/links

- torchci/components/benchmark/ModeAndDTypePicker.tsx
- torchci/components/benchmark/compilers/ModelPanel.tsx
- torchci/components/benchmark/compilers/SummaryPanel.tsx
- torchci/components/benchmark/compilers/common.tsx
- torchci/components/benchmark/torchao/common.tsx
- torchci/lib/benchmark/compilerUtils.ts
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/torchao.tsx
After https://github.com/pytorch/pytorch/pull/131369 lands, we will need this change to surface the the benchmark results from `cpu-x86` device.  This is one of the parameter that I didn't surface before on the dashboard because there is only one device `cuda`.
Selecting `cpu-x86` would show nothing now, but we can wait for https://github.com/pytorch/pytorch/pull/131369 to land and run a few more days to test the UX before landing this change.
https://torchci-git-fork-huydhn-add-cpu-device-pt2-96f356-fbopensource.vercel.app/benchmark/compilers
> Add the list of devices on PT2 inductor perf dashboard

- torchci/components/benchmark/compilers/common.tsx
The corresponding UX update to show cuda (a10g) device after https://github.com/pytorch/pytorch/pull/131816
https://torchci-git-fork-huydhn-perf-dashboard-add-30bec4-fbopensource.vercel.app/benchmark/compilers
> Add cuda (a10g) device to TorchInductor dashboard

- .github/scale-config.yml
We can estimate the maximum number of m4.10xlarge runners based on the max runner number for linux.16xlarge.spr. 
Per our statistic, in one round of CI inductor test, dynamo suites freezing accuracy test and inductor UT test run on m4.10xlarge, they cost ~9h. dynamo suites freezing accuracy test also runs on linux.16xlarge.spr, it cost ~3h. 
Based on the time cost ratio (9/3) and the max runner number for linux.16xlarge.spr (150), 450 should be enough for the maximum number of m4.10xlarge.
> Increase max runners available for m4.10xlarge

- tools/self-hosted-runner-utils/replace_runners_prefix_submit_pr.py
I very quickly hacked a script to help open PRs and test runners in partner repos. 
Yes the code is shi**, I don't care, this was coded just for a fast hack, and I don't want to lose it in case it becomes useful in the future.
> Adds replace_runners_prefix_submit_pr.py to quickly help test new runners in partner repos

- torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql
- torchci/rockset/inductor/__sql/compilers_benchmark_performance_branches.sql
- torchci/rockset/prodVersions.json
Fixes https://github.com/pytorch/test-infra/issues/5520
cuda (a100) uses the original cuda device name while cuda (a10g) uses `cuda_a10g` as its device name. The issue here is that both of them has `cuda` prefix, so the current query for cuda (a100) would wrongly fetch the result for both.  The error observed by the dashboard users is a blank page when the selected device is cuda (a100) and the selected commit is cuda (a10g), a mismatch.
Selecting other devices, cuda (a10g) or cpu (x86), is working fine because their names are unambiguous.
* cuda (a100) https://torchci-git-fork-huydhn-fix-wrong-commits-s-4891ea-fbopensource.vercel.app/benchmark/compilers
* cuda (a10g) https://torchci-git-fork-huydhn-fix-wrong-commits-s-4891ea-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinduc …
> Differentiate between cuda (a100) and cuda (a10g) commits on perf dashboard

- .github/workflows/build_conda_linux.yml
Same fix already applied in conda-build step above: https://github.com/pytorch/test-infra/pull/5527/files#diff-a830234c1ab7788cbd304fa713940ab2393c8da8f7338ff31c0c08c86d9900aeR140
Fixes issue with conda picking up default test env created by:
https://github.com/conda-incubator/setup-miniconda#conda-incubatorsetup-miniconda
Test PR:  https://github.com/pytorch/vision/pull/8562
Failure running conda info before install (2 yrs old conda version 4.12):
```
+ export 'CONDA_RUN_SMOKE=conda run -p /__w/_temp/pytorch_pkg_helpers_10168573792_smoke'
+ CONDA_RUN_SMOKE='conda run -p /__w/_temp/pytorch_pkg_helpers_10168573792_smoke'
+ [[ cpu = \c\u\d\a ]]
+ CONSTRAINTS=cpuonly
+ CONSTRAINT_BUILD=
+ [[ nightly = \t\e\s\t ]]
+ conda run -p /__w/_temp/pytorch_pkg_helpers_10168573792_smoke conda info …
```
> Apply $CONDA_ENV fix for smoke tests

- .github/workflows/build_wheels_linux.yml
The reason why this is useful is sometimes we need to pass in `--no-isolation` to the wheel build command because it needs the packages that are installed in the conda environment.
For example if we are building a C++ extension of pytorch that needs the pytorch headers, we need to pass in `--no-build-isolation` so we can use those headers and dynamically link against the pytorch .so files.
> Added option to pass extra args to python wheel build command

- torchci/components/JobLinks.tsx
Missed this in #5510
Old: makes an issue titled DISABLE [object Object]
New: makes an issue titled DISABLED test_correct_module_names (__main__.TestPublicBindings)
> [HUD][ez] Fix disable test button

- .github/workflows/build_wheels_linux.yml
Well setuptools / python packaging doesn't actually allow you to specify dependencies that come from other index URLs when you are building a package for "security" purposes. Unfortunately for us our nightlies (torch, torchvision, etc.) only exist on download.pytorch.org which means that if our users depend on things like torchvision then they need to have an ability to install these dependencies from download.pytorch.org, as part of the build process which currently the do not have the ability to do through normal means, hence this parameter
Reference: https://discuss.python.org/t/specifying-extra-index-url-in-setup-cfg-option-dependencies/19377
I actually hate that we have to do this but then again I also do not enjoy most of python's packaging ecosystem so I guess it fits with the …
> ci: Add option for torch dependencies from extra-url

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Adds a tag called `variants` in `scale-config.yaml`, that creates a copy of the runner where it is specified on, but with a specific prefix and override any configuration that is supported.
The goal is to reduce clutter and code-duplication on scale-config when running experiments or simply creating small variants of a particular runner.
ex:
```
linux.4xlarge:
instance_type: c5.2xlarge
os: linux
max_available: 1
disk_size: 150
is_ephemeral: false
variants:
ephemeral:
is_ephemeral: true
ami123:
ami: ami-123
```
this will create runners: `linux.4xlarge`, `ephemeral.linux.4xlarge` and `ami123.linux.4xlarge` with the specified configurations overridden. This is functionally equivalent to defining in the following way:
```
linux.4xlarge:
instance_type: c5.2xlarge
os: linux
max_available: 1 …
```
> Introduce runner variants to help test changes

- tools/torchci/td/get_merge_base_info.py
Example failure https://github.com/pytorch/test-infra/actions/runs/10179085213/job/28154073097
The commit 0df18019c641da816fa16d1cf3111272ae7ad756 doesn't exist anymore, even though rockset claims there were workflows run on it and it is present in the push table
Simple workaround is to add a try catch and then try to pull them individually
> [TD] Update test file ratings: error handling for pulling shas

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
tests explain it by itself
Just runner variants are aware of lf. and lf.c. prefixes, and are introduced after them, so we don't need to make a big effort towards migrating it.
> Runner variants to be aware of the lf. and lf.c. prefixes, to facilitate migrations

- .github/scale-config.yml
- .github/scripts/validate_scale_config.py
- .github/workflows/scale_config_validation.yml
- Makes validate_scale_config to be fully compliant with all the rules of the `scale-config.yaml` configuration file;
- Adds support for runner variants on validate_scale_config;
- Replaces duplicated configuration on `scale-config.yaml` with runner variants
depends on https://github.com/pytorch/pytorch/pull/132918 && https://github.com/pytorch/test-infra/pull/5541
Test for this changes are in this PR: https://github.com/pytorch/test-infra/pull/5542
> Uses variants on scale-config and update validate_scale_config to be fully compliant with autoscaler

- .github/workflows/build_wheels_linux.yml
This PR allows users to override the `python -m build` command when building linux wheels.
I need this for torchcodec for 2 reasons.
1.  We want the build command to be:
```
python -m build
```
instead of the currently hardcoded:
```
python -m build --wheel
```
From the `build` docs, the default behavior is to *not* pass `--wheel`, so that the wheel is built *from* the sdist. This is slightly safer as it ensures that a sdist can indeed be built.
2. We want to pass an environment variable, i.e. we want to write
```
SOME_ENV_VAR=123 python -m build ...
```
I realize this can be done with `env-var-script`. But using `env_var_script` leads to a decentralized build command, and it's more difficult to really understand what command is being used for building. It would be simpler and easier to …
> Allow full control on `python -m build` command

- .github/scale-config.yml
For the next phase of the Amazon 2023 migration we'll be bulk migrating the remaining jobs over to the new AMI by changing the default AMI that we use.
In preparation for that, we're adding the old Linux Amazon 2 ami as a fixed variant for runners, so that if any of the less frequently jobs breaks on Amazon 2023 AMI then they can shift to explicitly using the Amazon 2 AMI temporarily while the underlying problem is debugged and fixed.
This PR is part 2, following up on the scale-config changes made in https://github.com/pytorch/pytorch/pull/133469
The failing CI test should start passing once the above PR is merged
> [EZ] Enable opting into the old Linux Amazon 2 ami - Pt 2

- .github/scale-config.yml
related pytorch PR: https://github.com/pytorch/pytorch/pull/133569
> Bump max runners for linux.24xlarge to 500

- torchci/components/JobLinks.tsx
Allows it to match things like
```
2024-08-14T20:46:39.3465365Z The following tests failed consistently: ['test/profiler/test_cpp_thread.py::CppThreadTest::test_with_enable_profiler_in_child_thread']
```
Previously it only looked for things like
```
2024-08-14T19:39:57.2636076Z FAILED [0.0058s] test_transformers.py::TestSDPACudaOnlyCUDA::test_mem_efficient_attention_attn_mask_vs_math_ref_grads_batch_size_1_seq_len_q_152_seq_len_k_37_head_dim_16_is_causal_False_dropout_p_0_0_float16_scale_l1_cuda_float16 - ValueError: grad_key Test error 0.23132219910621643 is greater than threshold 0.0013792295940220356!
```
Note that this does not change the log classifier rules, it mainly affects the HUD disable test button and revert info button
Old:
New:
The disable test button would generate an issue …
> [ez][HUD] More flexible regex matching for log line display (mainly affects the disable test button)

- .github/workflows/build_wheels_linux.yml
After this change land, we can re-enable xpu nightly wheel build with USE_KINETO. Refer [PyTorch Prerequisites for Intel GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html). Works for https://github.com/pytorch/pytorch/issues/114850
> Add pti env due to kineto xpu enabled

- .github/scale-config.yml
- .github/scripts/validate_scale_config.py
Upgrades the LF scale configs to change the default AMI in accordance with the Amazon 2023 rollout plan.
This PR will be merged on Monday Aug 19 in the morning, and over the next 2-3 days as new linux runners are spun up (and old ones spun down) they'll start using this new AMI
This PR will be paired with https://github.com/pytorch/pytorch/pull/133641, which will be merged first
Note: I had to remove a check that validated that the variant's AMI is different from the base runner type's AMI because we want them to be the same during this rollout
**Rollout steps:**
1. Merge PR1 & PR2 early Monday morning, before folks start using the CI heavily 
2. (To roll out faster) Manually trigger a rollout in gha-labs-infra and ci-infra. This will accelerate the rollout by causing the runner instances …
> Change default runner's AMI to Amazon 2023 - Part 2

- torchci/lib/clickhouse.ts
This fixes the missing SQL files error when running ClickHouse queries on Vercel, i.e. https://vercel.com/fbopensource/torchci/logs?slug=app-future&slug=en-US&slug=fbopensource&slug=torchci&slug=logs&page=1&timeline=past30Minutes&startDate=1724086676515&endDate=1724088476515&levels=error&selectedLogId=1724088099571809957129200000&selectedLogTimestamp=1724088099571&forceEndDate=1724088255973
Using the preview from https://github.com/pytorch/test-infra/pull/5393 https://vercel.live/open-feedback/torchci-git-fork-huydhn-switch-merges-to-cl-55041f-fbopensource.vercel.app?via=pr-comment-visit-preview-link&passThrough=1.  I have set `USE_CLICKHOUSE` to true for preview and dev environments on https://vercel.com/fbopensource/torchci/settings/environment-variables
> Fix missing ClickHouse SQL queries on Vercel

- .github/scripts/run_clickhouse_format.sh
- .gitignore
Adds a script to run the clickhouse formatter on all of our clickhouse queries, in an ideal state this script should run `clickhouse format` on all of our queries (suffixed with `.sql`) in `torchci/clickhouse_queries` and then replace them in place with formatted versions of themselves.
NOTE: This does not install the clickhouse binary for you and will need to install it on their own.
Usage:
```
bash .github/scripts/run_clickhouse_format.sh
```
Example:
```
$ bash .github/scripts/run_clickhouse_format.sh
INFO: The following files have been modified:
M torchci/clickhouse_queries/commit_jobs_query/query.sql
```
> **TODO**: This definitely needs a follow up to automate this into a github actions workflow but don't have the bandwidth to do that right now
* Why are you using a temporary …
> tools: Add script to run clickhouse formatter

- torchci/clickhouse_queries/master_commit_red/params.json
- torchci/clickhouse_queries/master_commit_red/query.sql
- torchci/components/ClickHouseCheckBox.tsx
- torchci/pages/api/clickhouse/[queryName].ts
- torchci/pages/metrics.tsx
This PR:
* Fixes a bug in `torchci/pages/api/clickhouse/[queryName].ts` where the function doesn't parse the JSON parameters (missed in https://github.com/pytorch/test-infra/pull/5563)
* Adds a toggle on HUD metrics page to gradually migrate everything there to ClickHouse
* Migrates an example `master_commit_red` query that is used to generate the red commit histogram on HUD metrics page
https://torchci-git-fork-huydhn-add-api-endpoint-to-8b08ac-fbopensource.vercel.app/metrics
> Migrate master_commit_red query and add a ClickHouse toggle on metrics page

- torchci/clickhouse_queries/commit_jobs_query/query.sql
- torchci/components/JobLinks.tsx
- torchci/components/LogViewer.tsx
- torchci/lib/clickhouse.ts
- torchci/lib/fetchCommit.ts
There's a lot of type casting/changes here because rockset returns slightly different types.
TODO when we switch: get rid of the type changes and just change the code to use the ClickHouse types
The query didn't actually change that much, most of it is formatting
https://torchci-git-csl-workingcommithudquery-fbopensource.vercel.app/pytorch/pytorch/commit/773a782249ebe982996f18988ce6b26c4a786aa3
> [HUD][CH migration] Functioning commit_jobs_query

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/test/verifyDisableTestIssue.test.ts
The disable bot automatically tries to delete labels it thinks is no longer relevant.  Usually it makes sense, like removing module: windows if the platforms change to not include windows.  Unfortunately it also puts oncall: pt2 in this category, but oncall: pt2 can also be a test owner label, so it should stay
> [disablebot] Exclusion for oncall: pt2 as removable platform label

- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
The runner-binaries-syncer fails with missing module "requests". Seems like in the past it worked fine without it but is now showing up as an error.
Relates to pytorch/ci-infra#263.
> fix: runner-binaries-syncer missing requests module

- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/handler.ts
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
- terraform-aws-github-runner/modules/runner-binaries-syncer/policies/lambda-syncer.json
- terraform-aws-github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf
The lambda runner-binaries-syncer is missing code to actually perform the
download for the ARM64 binary despite having the variables in place.
This change resolves that issue so that the syncer actually fetches
the appropriate binary for ARM64.
Closes: pytorch/ci-infra#263
Depends-On: #5569
> fix: Download ARM64 binary

- terraform-aws-github-runner/outputs.tf
The output here is duplicated and is causing TFLint to throw an error.
> fix: TFLint error for duplicate output declaration

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/fixtures/known_labels.json
- torchci/test/labelCommands.test.ts
The `skip-pr-sanity-check` label is meant to skip PR size checks when needed, but it's easy to accidentally abuse it.
Limiting the scope of who can add it to a PR to those with write access
> Enable certain labels to only be added by a select group of people

- .github/workflows/lintrunner_ci.yml
Lintrunner CI / test (macos-latest) has broken for weeks in the "Install and initialize sapling on macos" step. Removing macos to make CI green again.
> Remove macos from lintrunner_ci.yml

- torchci/lib/benchmark/compilerUtils.ts
Summary: Follow up on https://github.com/pytorch/test-infra/pull/5587#discussion_r1727829293 since we need to use `COMPILER_NAMES_TO_DISPLAY_NAMES[record.compiler]` for comparison.
> [dashboard] Update export pass rate calculation

- torchci/pages/metrics.tsx
- torchci/rockset/metrics/__sql/lf_rollover_health.sql
- torchci/rockset/metrics/lf_rollover_health.lambda.json
- torchci/rockset/prodVersions.json
Adds charts that compare stats on jobs when they're run in the Linux Foundation runner fleet vs the Meta runner fleet.
The charts specifically show the difference between the two fleets, not showing absolute values. 
Looking at the charts right now there's a lot of variability in the jobs, both up and down, but mousing over the individual jobs tends to show that the dips in the chart so far tend to be noise that doesn't persist from day to day.
(Unfortunate that the chart runs off over onto the legend.  Seems like there's just a fixed width space for legends and if the legend contains items that are too long then the legend's canvas starts to overlap with the graph canvas)
> Add montoring for Linux Foundation fleet rollover

- terraform-aws-github-runner/main.tf
- terraform-aws-github-runner/modules/runners/scale-down.tf
- terraform-aws-github-runner/modules/runners/scale-up.tf
- terraform-aws-github-runner/modules/runners/variables.tf
- terraform-aws-github-runner/variables.tf
adds `min_available_runners` terraform config to setup environment variable `MIN_AVAILABLE_RUNNERS` on scale lambdas
> Enable setup minimum available runners for scale infra

- torchci/lib/clickhouse.ts
Fixes the issue discussed here https://github.com/pytorch/test-infra/pull/5566#discussion_r1722707100 (ints being converted to string by json)
The behavior is documented here: https://clickhouse.com/docs/en/integrations/language-clients/javascript#integral-types-int64-int128-int256-uint64-uint128-uint256
It is to protect against some datatypes being larger than Number.MAX_SAFE_INTEGER, but this value is 9007199254740991 (2^53 - 1) which is pretty large
Testing out ghstack --direct again
> [ez][hud][ch] Fix numbers being converted to strings

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
This change modifies the check to allow the minimum available runners setting to be 0 while keeping the default value to 10. The sanity check to ensure that at least a positive number is used remains. If an invalid number is passed then the setting is assumed to be 0.
Scale-up function however requires a minimum of at least 1 to be able
to do its calculations on how many runners to scale up. A value of 0
here breaks the logic and causes the function to never create any runners.
So logic is added here to ensure that scale-up's min value is 1.
Issue: https://lf-pytorch.atlassian.net/browse/PC-33
> Allow setting minimum available runners to 0

- torchci/lib/drciUtils.ts
Currently Dr.CI marks this signal as flaky ([example](https://github.com/pytorch/pytorch/pull/133896#issuecomment-2297445921)).
> [ez] Exclude check-labels job from flakiness

- torchci/lib/drciUtils.ts
Related to #5611 
apparently flakiness exclusions use job name instead of id
> [ez] Exclude Check labels job from flakiness (attempt 2)

- torchci/clickhouse_queries/weekly_force_merge_stats/query.sql
- torchci/pages/metrics.tsx
The result changes slightly due to using issue_comment.created_at instead of m._event_time as the threshold for the date
A better timestamp to use would probably be push, but I don't want to do another join right now
> [hud][ch] weekly_force_merge_stats

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
Move check for if something is in the `EXCLUDED_FROM_FLAKINESS` to be earlier and more explicit since some of the checks for flakiness weren't checking if it was on the list first
Some lower/upper case stuff
Tested on https://togithub.com/pytorch/pytorch/pull/135391#issuecomment-2334801691.  
If it's no longer there, it's because it got overwritten, but here's a screenshot
and the output after calling the API (see that it is in the failed list)
```
csl@csl-mbp ~/zzzzzzzz/test-infra/torchci [csl/fix_drci_check_labels_flaky] $                                
(forpytorch) curl "http://localhost:3000/api/drci/drci?prNumber=135391" --data 'repo=pytorch'
{"135391":{"FAILED":[{"workflowId":10745156151,"workflowUniqueId":38959716,"id":29803617987,"runnerName":"linux.20_04.4x_2f4e0a1ae568","authorE …
```
> [drci] Fix check labels being marked as flaky

- .github/workflows/build_conda_linux.yml
- .github/workflows/build_conda_macos.yml
- .github/workflows/build_conda_windows.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
TSIA.  This is a request from fbgemm in which their Linux CUDA build jobs is too close to the 120 minutes threshold and frequently timeout, i.e. https://github.com/pytorch/FBGEMM/actions/runs/10772363019/job/29869849673
> Make Nova build job timeout parameter configurable

- torchci/scripts/backfillJobs.mjs
convert queries to CH, query both rockset and clickhouse in all queries
> [ch] backfill queries

- tools/rockset_migration/rockset_2_dynamodb.py
I use this script to copy the following Rockset collections to dynamoDB tables, so it's a good idea to keep this here for future usage:
* `python rockset_2_dynamodb.py --rockset-workspace benchmarks --rockset-collection oss_ci_benchmark --dynamodb-table torchci-oss-ci-benchmark` (599 records deduped and copied)
* `python rockset_2_dynamodb.py --rockset-workspace inductor --rockset-collection torch_dynamo_perf_stats --dynamodb-table torchci-dynamo-perf-stats` (3.5M+ records)
For some reason, a query like `SELECT * FROM torch_dynamo_perf_stats` returns gibberish in some fields despite my attempt to paginate the results.  So, I need to copy data sequentially by each workflow instead.
> Add a util script to copy Rockset collections to dynamoDB tables

- torchci/clickhouse_queries/workflow_load/query.sql
- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/metrics.tsx
* put utc everywhere to handle the lack of "Z"
* I think its ok to not take timezone into account when calculating the granularity bucket
* the type casting is getting a bit annoying, I'm considering just switching to CH at some point and calling it a day
> [ch][hud metrics] workflow_load

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/build_conda_windows.yml
Fixes: https://github.com/pytorch/vision/issues/8651
Trying to resolve this error during vision and audio windows conda builds: https://github.com/pytorch/audio/actions/runs/10829977489/job/30048718670
```
Traceback (most recent call last):
File "C:\Jenkins\Miniconda3\lib\site-packages\conda\exception_handler.py", line 18, in __call__
return func(*args, **kwargs)
File "C:\Jenkins\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in main_subshell
exit_code = do_call(args, parser)
File "C:\Jenkins\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 176, in do_call
result = plugin_subcommand.action(getattr(args, "_args", args))
File "C:\Jenkins\Miniconda3\lib\site-packages\conda_build\plugin.py", line 15, in build
If submitted, this report will be used by core maintainers …
```
> Pin python-libarchive-c. Pin conda and conda-build for VS2019 conda-build step

- tools/rockset_migration/compare_keys.py
- tools/rockset_migration/create_clickhouse_schema.py
- tools/rockset_migration/dynamo2ch.py
- tools/rockset_migration/rockset_queries.py
- tools/rockset_migration/s32ch.py
A bunch of helper scripts that I've been using for migration that I want to put in the repo for version control and so other people can use them if needed (especially the schema generator)
> [ch] Random helper scripts

- .github/workflows/lambda-do-release-runners.yml
- .github/workflows/lambda-runner-binaries-syncer.yml
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
Currently there is not release distribution for the runner-binaries-syncer which is another lambda function that is deployed as part of the ALI. This change updates test-infra to release these artifacts so that we can fetch and deploy it just like runners.zip and webhook.zip
Issue: https://lf-pytorch.atlassian.net/browse/PC-27
> Release runner-binaries-syncer lambda

- .github/actions/setup-miniconda/action.yml
https://conda.org/blog/2024-07-23-july-releases to support the default conda-libmamba-solver.  There are failures from Nova MacOS job with the newer conda otherwise https://github.com/pytorch/executorch/actions/runs/10838270548/job/30076115714#step:9:77
https://github.com/pytorch/executorch/pull/5322
> Upgrade miniconda to 24.7.1-0

- .github/workflows/build_wheels_linux.yml
Cherry pick #5534 onto release branch to support pip-install-torch-extra-args
> [Cherry-Pick] ci: Add option for torch dependencies from extra-url #5534

- torchci/pages/api/flaky-tests/disable.ts
Made a ton of issues
I'll put in a rate limiter thing in a later PR?  or make the bot create an issue instead of mass disabling
> [disablebot] Stop bot on some inductor mac tests

- .github/scale-config.yml
- .github/scripts/validate_scale_config.py
This PR does the following:
- Remove unused `am2` and `amz2023` variants
- Update the scale config validator to remove checks that are no longer needed 
- Update notes in scale-config.yml
Unused variants were detected by checking these CodeSearch results:
- https://github.com/search?type=code&q=org%3Apytorch+%2F%5Cbamz2023%5Cb%2F
- https://github.com/search?type=code&q=org%3Apytorch+%2F%5Cbam2%5Cb%2F
PRs submitted against the workflows that are still using the deprecated amz2023 variants, since nothing should need to use those anymore.
In addition cleanup, this should reduce costs by reducing the types of runners we keep idle instances for in our fleet
> Cleanup unused variants

- torchci/lib/bot/triggerInductorTestsBot.ts
- torchci/test/triggerInductorTestsBot.test.ts
This pr is the first in a set of PRs to enable inductor testing on the triton-lang/triton repo using pytorch resources. Specially we trigger a workflow in the pytorch repo which runs inductor tests on a specific triton hash against pytorch viable/strict.
Once this pr is merged. I will test it on malfet/deleteme to make sure it works.
> [inductor] add bot to trigger inductor workflows

- .github/actions/setup-miniconda/action.yml
- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/test_linux_job.yml
- .github/workflows/test_macos_job.yml
- .github/workflows/test_windows_job.yml
- .github/workflows/windows_job.yml
For the context, Nova jobs upload the artifacts to GitHub because this works on all runners including non-AWS ones like GitHub runners.  However, there is a scale issue when trying to upload large artifacts (GB in size) to GitHub that the files are too big, so the upload could either:
* Timing out https://github.com/pytorch/executorch/actions/runs/10858058150/job/30136354800
* or just fail in the middle of the upload https://github.com/pytorch/executorch/actions/runs/10856291106/job/30132545832
To address this, I add the option to upload to S3 gha-artifacts bucket here which is direct and more efficient.
> Add option to upload Nova artifacts to S3 directly

- .github/workflows/lambda-do-release-runners.yml
Change #5615 had an incorrect path for the runner-binaries-syncer index.js file. This change fixes the pathing issue.
> Fix incorrect path to runner-binaries-syncer

- torchci/lib/commitUtils.ts
- torchci/lib/drciUtils.ts
- torchci/lib/getAuthors.ts
- torchci/lib/jobUtils.ts
- torchci/test/drciUtils.test.ts
- torchci/test/jobUtils.test.ts
Follow up to https://github.com/pytorch/test-infra/pull/5634.  These are the one off queries that I needed to track down.
Surprisingly, none of the current PRs go through this path, so I used some older PRs, like 135397, 114772, as tests
> [ch] Dr. CI to use CH Part 2

- .github/workflows/update-test-times.yml
- tools/torchci/clickhouse.py
- tools/torchci/requirements.txt
- tools/torchci/update_test_times.py
- torchci/clickhouse_queries/test_time_per_class/query.sql
- torchci/clickhouse_queries/test_time_per_class_periodic_jobs/query.sql
- torchci/clickhouse_queries/test_time_per_file/query.sql
- torchci/clickhouse_queries/test_time_per_file_periodic_jobs/query.sql
Took a brief look to check that results looked similar.  There were differences in decimals, I assume due to floating point stuff, which made it hard to be sure so I'm not entirely sure they're exactly the same
> [ch] update test times

- torchci/lib/fetchHud.ts
According to Vercel log, the GH API link looks wrong with double encoding `https://api.github.com/repos/pytorch/pytorch/commits?sha=viable%252Fstrict&per_page=50&page=1` where it should just be `https://api.github.com/repos/pytorch/pytorch/commits?sha=viable%2Fstrict&per_page=50&page=1` instead.
I suspect that this might be related to Octokit version, or one of its dependencies https://www.npmjs.com/package/octokit?activeTab=versions, as the error is not manifested locally.
https://torchci-git-fix-wrong-branch-name-hud-fbopensource.vercel.app/hud/pytorch/pytorch/viable%2Fstrict/1?per_page=50
https://torchci-git-fix-wrong-branch-name-hud-fbopensource.vercel.app/hud/pytorch/executorch/release%2F0.4/1?per_page=50
> Decode branch name before passing to Octokit

- tools/torchci/reverts.py
Raises an error on unrecognized arguments when parsing the comment body since the default argument parser exits immediately.
This makes it easier to debug what failed as the later try catch in parse_body will print the comment link
Example failure: https://github.com/pytorch/test-infra/actions/runs/10886791088/job/30207637435
The comment it failed on was https://togithub.com/pytorch/pytorch/pull/134968#issuecomment-2348837553
It was edited after the revert to not match the expected revert command.  I edited the comment to make it match again and the revert printer succeeded
> [ez] Revert printer - throw exception on unrecognized arguments in comment

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_llms.sql
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_names.sql
- torchci/rockset/benchmarks/oss_ci_benchmark_branches.lambda.json
- torchci/rockset/benchmarks/oss_ci_benchmark_llms.lambda.json
- torchci/rockset/prodVersions.json
With https://github.com/pytorch/pytorch/pull/135042, there is now information about the device arch from the benchmark to separate different CUDA or CPU types.  Instead of showing device like CUDA, we need to be more specific, for example:
* cpu (x86_64)
* cpu (arm64)
* cuda (NVIDIA A100-SXM4-40GB)
https://torchci-git-fork-huydhn-add-cpu-device-llm-a5f029-fbopensource.vercel.app/benchmark/llms shows different devices and their archs.
> Add arch to the device type on LLMs benchmark dashboard

- .github/workflows/mobile_job.yml
- .github/workflows/test_mobile_job.yml
As reported by @guangy10 in https://github.com/pytorch/executorch/pull/5441#issuecomment-2357004155, it turns out that the job timeout can be set to a higher value (120 minutes), but the AWS credential still expires after 1 hour https://github.com/aws-actions/configure-aws-credentials.
The fix here is to set the role duration correctly.  However, the max that it can go is 18000 seconds.  I believe that's plenty of room already, but if a higher is needed, we will need to update the server side https://github.com/pytorch-labs/pytorch-gha-infra/blob/main/runners/gha_roles.tf#L1425
The role duration is set correctly to 7200 seconds (2 hours) https://github.com/pytorch/test-infra/actions/runs/10916800466/job/30298898748#step:4:4
> Set the AWS credential duration in mobile job

- torchci/lib/drciUtils.ts
- torchci/test/drciUtils.test.ts
This should deal with https://github.com/pytorch/test-infra/issues/4927
> [drci] don't mark jobs with an overly generic error as flaky

- aws/lambda/servicelab-ingestor/lambda_function.py
The lambda has failed to ingest new data since Sep 3rd, and it turns out that the regex it uses to extract the benchmark metadata has become invalid (I will check which change is responsible for that, but it's like something on ServiceLab).
Specifically, the `retry` field on the filename that ServiceLab returns is not there anymore.  Before we have `pytorch/benchmarks/dynamo/manifold/..._1.a-tmp694bm90e.csv`, now it is just `pytorch/benchmarks/dynamo/manifold/....a-tmphjxk9w2x.csv`.  So, I update the regex to make this field optional.  This is not needed anywhere in OSS atm.
Run the lambda with a sample key on S3 `pytorch/benchmarks/dynamo/manifold/4500202979/4500315921/cudagraphs_dynamic-BERT_pytorch-training-performance-benchmark_torchbench_run_bert_pytorch_training.benchmark_torchbench_ …
> Fix ServiceLab ingestion lambda regex

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
This captures the rate limit values from GitHub for the ALI account user/process. We can use this to graph and track how much of the API rate limit is used by the CI infrastructure and flag when we are getting too close to the overall limit.
Closes: pytorch/ci-infra#273
> Add metric for GitHub API Rate Limit

- tools/torchci/reverts.py
* Migrate query to CH syntax
* Use CH only
* Bunch of renames like rockset_result -> db_result 
Tested by running on base and head, got the same results for this week
> [ch] Revert printer

- .github/actions/update-viablestrict/action.yml
Adds the following outputs:
* time: when the push command finished, in seconds from epoch 
* latest_viable_sha: the latest sha that works
* push_result: stdout and stderr of the push
To be used in https://github.com/pytorch/pytorch/pull/136470
> [viable strict] Add some outputs for tracking metrics

- .github/workflows/mobile_job.yml
- .github/workflows/test_mobile_job.yml
As reported by @guangy10 in
https://github.com/pytorch/executorch/pull/5441#issuecomment-2357004155, it turns out that the job timeout can be set to a higher value (120 minutes), but the AWS credential still expires after 1 hour https://github.com/aws-actions/configure-aws-credentials.
The fix here is to set the role duration correctly. However, the max that it can go is 18000 seconds. I believe that's plenty of room already, but if a higher is needed, we will need to update the server side
https://github.com/pytorch-labs/pytorch-gha-infra/blob/main/runners/gha_roles.tf#L1425
The role duration is set correctly to 7200 seconds (2 hours) https://github.com/pytorch/test-infra/actions/runs/10916800466/job/30298898748#step:4:4
> Set the AWS credential duration in mobile job (#5685)

- .github/workflows/linux_job.yml
- .github/workflows/macos_job.yml
- .github/workflows/test_linux_job.yml
- .github/workflows/test_macos_job.yml
- .github/workflows/test_windows_job.yml
- .github/workflows/windows_job.yml
For the context, Nova jobs upload the artifacts to GitHub because this works on all runners including non-AWS ones like GitHub runners. However, there is a scale issue when trying to upload large artifacts (GB in size) to GitHub that the files are too big, so the upload could either:
* Timing out https://github.com/pytorch/executorch/actions/runs/10858058150/job/30136354800
* or just fail in the middle of the upload https://github.com/pytorch/executorch/actions/runs/10856291106/job/30132545832
To address this, I add the option to upload to S3 gha-artifacts bucket here which is direct and more efficient.
> Add option to upload Nova artifacts to S3 directly (#5668)

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
- aws/lambda/clickhouse-replicator-s3/lambda_function.py
Reverts pytorch/test-infra#5709 with correct code
See most recent commit for change (the quotations was wrong)
Testing here: https://github.com/pytorch/test-infra/pull/5711
> Reland "[ch] replicator lambdas: external contribution stats (s3), wait time/pr_stats (dynamo)"

- torchci/clickhouse_queries/recent_pr_workflows_query/params.json
- torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/fetchRecentWorkflows.ts
- torchci/pages/api/drci/drci.ts
Dr. CI updates comments every 15 minutes (done via GHA) and queries for the last 30 minutes of completed jobs in order to account for small errors like Dr. CI not actually running due to GHA not scheduling in time.
However, if Dr. CI fails to run multiple times in a row or webhooks are sent late (ex there was an outage), we can get cases where the job completes but Dr. CI never picks it up, so the comment always says that there is something pending.
One way to solve this (implemented here) is to also query for comments that say there are jobs pending and update those too.
Currently, it searches for any comments that say there are things pending in the last month (do we want to make this interval smaller?) and Dr. CI will update those as well.
Drawbacks:
* additional CH queries
* probably …
> [drci] Update comments that say pending

- .github/scale-config.yml
Validated no jobs use the amz2023 runner variant anymore ([proof](https://github.com/search?type=code&q=org%3Apytorch+%2F%5Cbamz2023%5Cb%2F+&p=1)) so removing all references to it
Note: The Scale Config Validator job will only pass after https://github.com/pytorch/pytorch/pull/136540 is merged
> [EZ] Remove remaining amz2023 runner variant references

- torchci/lib/drciUtils.ts
- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
- torchci/test/drciUtils.test.ts
Fixes https://github.com/pytorch/test-infra/issues/5596
The current log classifier/line capture mechanism allows real failures to be hidden by existing failures, resulting in multiple lint breakages.   Lint is a fast and stable job so we should force people to rebase
> [drci] Exclude lint from broken trunk

- torchci/clickhouse_queries/time_to_signal/query.sql
- torchci/pages/kpis.tsx
- torchci/pages/metrics.tsx
* Add CH query for TTS chart, works with rs/ch toggle button
* CH date_trunc('week') truncates to monday, but toStartOfWeek can let you choose which day to truncate to.  The second keeps the results the same, but date_trunc lets you choose granularities better.  For parity with RS, I am putting this query to trunc to sunday, but we might want to change this later
> [ch][kpis] TTS chart

- .github/workflows/lambda-runner-binaries-syncer.yml
- .github/workflows/lambda-runners.yml
- .github/workflows/lambda-webhook.yml
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/Makefile
- terraform-aws-github-runner/modules/runners/lambdas/runners/Makefile
- terraform-aws-github-runner/modules/webhook/lambdas/webhook/Makefile
Create Makefiles for the ALI lambda functions so that we can make sure that CI and Local dev use the same commands to build and test.
Issue: pytorch/ci-infra#274
> Create Makefiles for test-infra ALI lambdas

- .github/scale-config.yml
Rather than specifying a specific version number for the AMIs, use wildcards for the date section.
Issue: pytorch/pytorch#136762
> Use wildcard for portion of AMI version number

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
- aws/lambda/clickhouse-replicator-s3/lambda_function.py
s3 tested by running locally and seeing if it got inserted
dynamo only checked `python aws/lambda/clickhouse-replicator-dynamo/test_lambda_function.py` to make sure other ingestions didn't break
Also small fix for external_contribution_stats error handler
> [ch] Set up ingestion for benchmarks tables and aggregated_test_metrics

- torchci/components/benchmark/CommitPanel.tsx
- torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
- torchci/rockset/benchmarks/oss_ci_benchmark_branches.lambda.json
- torchci/rockset/inductor/__sql/compilers_benchmark_performance_branches.sql
- torchci/rockset/inductor/compilers_benchmark_performance_branches.lambda.json
- torchci/rockset/prodVersions.json
Fixes https://github.com/pytorch/test-infra/issues/5696
I discover two issues with the current query to get the commits and their date:
* The query inherits the granularity parameter, so when the granularity is set to week, for example, all commit's dates are truncated to the beginning of the week.  This is the root cause of https://github.com/pytorch/test-infra/issues/5696.  For more context, switching to weekly granularity is a hack I have at the moment to be able to reduce the payload side and be able to load last quarter data (https://github.com/pytorch/test-infra/issues/4123).  So the issue only manifests when a time range from last quarter or more is selected.  The fix then is just to truncate commit's dates by day because that's the format displayed in the dashboard (YYYY/MM/DD)
* …
> Fix wrong commit date on benchmark dashboards

- .github/workflows/build_wheels_windows.yml
The smoke test is different with previously steps, which not set working-directory as ${{ inputs.repository }}
Works for https://github.com/pytorch/pytorch/issues/114850
> Fix smoke test path in Windows binary build workflow

- .github/actions/update-viablestrict/action.yml
Fixes output not writing correctly due to multiline string
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
Example 
https://github.com/pytorch/pytorch/actions/runs/11091486634/job/30815281180#step:2:8268
```
+ output=156ca01e51f766b1b069c5c6f3d57112a5c8f9ff
+ echo latest_viable_sha=156ca01e51f766b1b069c5c6f3d57112a5c8f9ff
Run git config --global user.email "pytorchmergebot@users.noreply.github.com"
git config --global user.email "pytorchmergebot@users.noreply.github.com"
git config --global user.name "PyTorch MergeBot"
echo "Set the latest sha variable to be ${LATEST_VIABLE_SHA}"
push_result=$(git push origin "${LATEST_VIABLE_SHA}:${STABLE_BRANCH}" 2>&1 || true)
echo "push_result=$push_result" >> …
```
> viable strict update: fix multiline output 

- .github/workflows/build_wheels_macos.yml
This PR enable the build of M1 wheels to rely on `python -m build` instead of `python setup.py`. The default is still  `python setup.py`.
This is the same as https://github.com/pytorch/test-infra/pull/5071 and https://github.com/pytorch/test-infra/pull/5076 that were landed for linux wheels.
We need this for torchcodec to support M1 wheels https://github.com/pytorch/torchcodec/pull/230
CC @scotts @atalman
> Allow build package to build M1 wheels

- aws/lambda/clickhouse-replicator-s3/lambda_function.py
- tools/rockset_migration/dynamo2ch.py
- tools/rockset_migration/s32ch.py
Refactor the s3 replicator lambda to reduce dup code and have better error handling (upload to same database so we don't have to create a new one each time)
Tested via:
* randomly selecting a key for merges, merge_bases, rerun_disabled_tests, external_contribution_stats and checking that it could be uploaded
* backfilled inductor_torchao_perf_stats and torchbench_userbenchmark
* rebackfilled queue_times_historical and removed dups
* raise an exception to see if the error handler wrote to the database (it did)
Reused logic from lambda replicator in s3 backfill script
> [ch] Refactor/unify s3 lambda, improve s3 backfill script

- aws/lambda/clickhouse-replicator-s3/lambda_function.py
* Renamed metrics table to ossci_uploaded_metrics
* Relevant PR for metrics table: https://github.com/pytorch/pytorch/pull/136799 
* Relevant info for stable pushes table: https://github.com/pytorch/pytorch/pull/136470
---
Tested by running the lambda handler on some docs currently in those bucket/paths
> [ch] set up ingestion for metrics and stable pushes tables

- s3_management/manage.py
torchtune's 0.3.1 release added psutil as a dependency: https://github.com/pytorch/torchtune/blob/main/pyproject.toml#L28
We add it to the list of additional packages for torchtune in `s3_management/manage.py` here.
> Add psutil to torchtune dependencies for v0.3.1 release

- tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
We already use Meta CDN in builder validation as an option:
https://github.com/pytorch/builder/pull/1999
Here is the log from builder:
```
+++ pip3 install --pre torch torchvision torchaudio --index-url https://d3kup0pazkvub8.cloudfront.net/whl/nightly/cu121
Looking in indexes: https://d3kup0pazkvub8.cloudfront.net/whl/nightly/cu121
Collecting torch
Downloading https://d3kup0pazkvub8.cloudfront.net/whl/nightly/cu121/torch-2.6.0.dev20241003%2Bcu121-cp310-cp310-win_amd64.whl (2451.6 MB)
---------------------------------------- 2.5/2.5 GB 45.6 MB/s eta 0:00:00
Collecting torchvision
Downloading https://d3kup0pazkvub8.cloudfront.net/whl/nightly/cu121/torchvision-0.20.0.dev20241003%2Bcu121-cp310-cp310-win_amd64.whl (6.2 MB)
---------------------------------------- 6.2/6.2 MB 31.5 MB/s eta …
```
> [Temp] Use Meta CDN for building domain binaries

- .github/workflows/build_wheels_macos.yml
Reverts pytorch/test-infra#5737
This causes issue: https://github.com/pytorch/torchcodec/actions/runs/11155431850/job/31006353091?pr=230
During build, different Python verison is getting picked up, required 3.9 - version used 3.10:
```
+ __conda_exe run -p /Users/ec2-user/runner/_work/_temp/conda_environment_11155431850 python3 -m pip install build
+ /opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/conda_environment_11155431850 python3 -m pip install build
WARNING: The script pyproject-build is installed in '/Library/Frameworks/Python.framework/Versions/3.10/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Notice:  A new release of pip is available: 23.0.1 …
```
> Revert "Use python3 instead of python for macos wheels build"

- torchci/clickhouse_queries/oss_ci_benchmark_branches/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
- torchci/components/NavBar.tsx
- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
This bases on the current benchmark dashboard on PyTorch with only a different repo name `pytorch/executorch`.  The dashboard is still using `benchmark.oss_ci_benchmark_v2` as I'm setting up the initial version of the dashboard first before looking into consolidating the database schema.
https://torchci-git-fork-huydhn-executorch-benchmark-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fexecutorch 
**Please switch to ClickHouse for testing as it has the latest queries, I will submit a PR to clean up Rockset to avoid further discrepancy**
> Add ExecuTorch benchmark dashboard

- .github/actions/calculate-docker-image/action.yml
I'm frequently seeing network errors when building Docker image which were subsequently fixed by retrying.  So, it's a good idea to support retry in this step.  For example,
* Failure https://github.com/pytorch/pytorch/actions/runs/11329053976/job/31503695304#step:6:5836
* Retry https://github.com/pytorch/pytorch/actions/runs/11329053976/job/31509384226
Using PyTorch PR https://github.com/pytorch/pytorch/pull/137896 to test the change at https://github.com/pytorch/pytorch/actions/runs/11331057887
> Retry docker build step to handle network error

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
This is a follow-up of https://github.com/pytorch/test-infra/pull/5758, let's just keep ClickHouse route going forward as it's tedious to update both ClickHouse and Rockset queries
https://torchci-git-fork-huydhn-cleanup-rockset-llm-e8a0f2-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fexecutorch
and 
https://torchci-git-fork-huydhn-cleanup-rockset-llm-e8a0f2-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fpytorch
> Cleanup Rockset on ET benchmark dashboards

- torchci/clickhouse_queries/compilers_benchmark_performance/params.json
- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
- torchci/clickhouse_queries/compilers_benchmark_performance_branches/params.json
- torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
- torchci/components/benchmark/compilers/ModelGraphPanel.tsx
- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/llms.tsx
This takes much longer than I expect mainly because Rockset has some default values while CH doesn't, so there are many discrepancies in the results to churn through.
https://torchci-git-fork-huydhn-ch-migrate-remainin-10ef8e-fbopensource.vercel.app/benchmark/compilers v.s https://hud.pytorch.org/benchmark/compilers
> [CH] Migrate TorchInductor benchmark page

- .github/workflows/mobile_job.yml
It looks like AWS imposes a rate limit somewhere on the number of requests we can submit to them. So, jobs are failing flakily from time to time, i.e. https://github.com/pytorch/executorch/actions/runs/11352715938/attempts/1.
Also, iOS job seems to suffer more, so maybe AWS has different rate limit for different devices? https://github.com/pytorch/executorch/actions/runs/11357190872/job/31590285863
Let's just slow down a bit here, and also support retry.
> Fix mobile job rate limit failures

- tools/scripts/generate_binary_build_matrix.py
We will be releasing 12.4 builds to pypi. Hence use 12.4 rather then 12.1
> Release 2.5 Use pypi for cuda 12.4 builds

- torchci/components/WorkflowBox.tsx
CH returns job id as a number, not a string, but string is expected in some places
Previously, when using CH, the show artifacts button wouldn't show up, but now it does
> [ch][hud][ez] Fix artifacts under each job

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
- terraform-aws-github-runner/modules/runners/scale-down.tf
- terraform-aws-github-runner/modules/runners/scale-up.tf
- terraform-aws-github-runner/modules/runners/variables.tf
- terraform-aws-github-runner/variables.tf
Enable putting scale-config in test-infra, even for non-organization runners.  Before, only scale-configs for organization-scoped runners could be put in arbitrary repos
Significant change:
- `scale_config_repo` no longer defaults to test-infra. You now _have_ to specify a value if you're using org runners. Non-org runners will default to the job's repo.  pytorch-gha-infra and ci-infra will need to be updated accordingly.
Testing: Deployed these changes to LF canary, terminated all lf-c instances, and verified that creating a new pull request there would still result in instances getting provisioned
> Enable non-org autoscaler to read scale-config from any repo

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Related PR on pytorch/pytorch https://github.com/pytorch/pytorch/pull/138332
> Increase max runners available for linux.12xlarge and windows.8xlarge.nvidia.gpu.nonephemeral

- .github/workflows/test_linux_job.yml
- .github/workflows/test_windows_job.yml
Python 3.8 was deprecated some time ago.
> Switch test-infra workflow tests from 3.8 Python to 3.9

- torchci/clickhouse_queries/tts_duration_historical/params.json
- torchci/clickhouse_queries/tts_duration_historical/query.sql
- torchci/clickhouse_queries/tts_duration_historical_percentile/params.json
- torchci/clickhouse_queries/tts_duration_historical_percentile/query.sql
- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
I need to rewrite parts of the queries to make the page works.  I guess we don't use this as often anymore.
* Add `repo` name to the query to filter jobs from other repos, i.e. ExecuTorch
* Remove some jobs that we don't care about their TTS, i.e. `mem_leak_check`
* Rewrite `percent_rank` with `rank` because the former is not yet available in the current CH Cloud we are using https://github.com/ClickHouse/ClickHouse/issues/46300
https://torchci-git-fork-huydhn-migrate-ttsduration-ec63fe-fbopensource.vercel.app/tts
> [CH] Migrate https://hud.pytorch.org/tts

- .github/scripts/validate_scale_config.py
Part of the workflow to move the LF scale-config.yml files from pytorch/pytorch to test-infra (details in https://github.com/pytorch/test-infra/pull/5767)
This updates the validation script to no longer expect to update the pytorch/pytorch version of these scale configs.  It resulted in many other aspects of that file becoming simpler as well.
> Excpect scale-configs to all live in test-infra now

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
It was incorrectly assuming that the repo that was requesting the new job was from the same repo as the one where scale-config lives.  
Fixing that bad assumption.
> [EZ] Correct the repo that's used when logging the scale-config used

- torchci/pages/api/drci/drci.ts
I dunno how I missed this when I originally made this change
Tested by calling 
`curl "http://localhost:3000/api/drci/drci?prNumber=138513"  --data 'repo=pytorch'`
and
`curl "http://localhost:3000/api/drci/drci"  --data 'repo=pytorch'`
but only verified that clickhouse returned results
> [drci] Fix when calling for single PR

- s3_management/manage.py
Latest pillow releases have changed from 'Pillow'->'pillow'
Please refer: https://pypi.org/project/pillow/11.0.0/#files vs https://pypi.org/project/pillow/10.0.0/#files
hence we should allow both conventions for now.
In Prod for example: https://download.pytorch.org/whl/pillow/ 
As per: https://peps.python.org/pep-0566/ :
All transformed keys should be reduced to lower case. Hyphens should be replaced with underscores, but otherwise should retain all other characters;
> When filtering for allowed packages allow both upper case and lower case packages

- torchci/clickhouse_queries/hud_query/query.sql
It was showing a negative time because completed_at was empty => gets set to default value of 0
Fixes https://github.com/pytorch/test-infra/issues/5807
> [hud][ez] Do not show duration for pending jobs

- torchci/components/UseClickhouseProvider.tsx
After https://github.com/pytorch/test-infra/pull/5778, the amount of queries to Rockset for things like hud_query decreased significantly, but there are still a few stragglers, so this is an effort to force people to re click the toggle to use Rockset explicitly 
One possible cause of this is people toggling to test Rockset queries but I figure this is can be done as well just in case
> [ch] New preference name for useClickhouse

- torchci/clickhouse_queries/failed_workflow_jobs/params.json
- torchci/clickhouse_queries/failed_workflow_jobs/query.sql
- torchci/components/JobAnnotationToggle.tsx
- torchci/pages/api/job_annotation/[repoOwner]/[repoName]/failures/[queryParams].ts
- torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
This is more like a refactoring, not a migration, but it's needed to make the query works.
* `failed_workflow_jobs` runs OOM on ClickHouse trying to load all failed jobs from commits that are having more than N failures.  I rewrite the logic to get rid of N because we only set it to 0 anyway.  The simplified logic can be then be run
* https://hud.pytorch.org/failedjobs/pytorch/pytorch/main has duplicated entries.  This is a subtle bug from `torchci/components/JobAnnotationToggle.tsx` that took me way too long to figure out.
* There are several React warnings on the page, so I fix them too
https://torchci-git-fork-huydhn-ch-migrate-job-anno-45acb4-fbopensource.vercel.app/failedjobs/pytorch/pytorch/main
> [CH] Migrate failure annotation page

- torchci/clickhouse_queries/flaky_workflows_jobs/params.json
- torchci/clickhouse_queries/flaky_workflows_jobs/query.sql
- torchci/lib/bot/retryBot.ts
- torchci/lib/jobUtils.ts
- torchci/test/retryBot.test.ts
This query is used to get flaky jobs in the past 24 hours, which is then used by retry bot.  As part of this, I also need to move `getFlakyJobsFromPreviousWorkflow` from `jobUtils` to the bot itself because `queryClickhouseSaved` can only be used on the server side.
> [CH] Migrate flaky_workflows_jobs and retry bot

- torchci/clickhouse_queries/num_reverts/params.json
- torchci/clickhouse_queries/num_reverts/query.sql
- torchci/pages/kpis.tsx
Switch the # of reverts KPI query & chart to use ClickHouse
Testing: 
- Verified that the CH version of the chart shows the same data as the Rockset version.
- Ensured that the CH query is being run by modifying it and validating that the chart changed
https://torchci-git-zainr-clickhouses-num-reverts-fbopensource.vercel.app/kpis
> Convert num_reverts query to clickhouse

- .github/actions/setup-miniconda/action.yml
Without this there would be cache collisions of different default-packages. i.e. the symptom I was seeing was the cache 
would restore my conda environment but without the packages.
I tested it here with torchcodec https://github.com/pytorch/torchcodec/pull/298
https://github.com/pytorch/torchcodec/actions/runs/11523232397/job/32081186451?pr=298
And it seems to be working fine.
Example the cache key contains the package hashes:
> Add default package hash to cache key

- .github/workflows/trigger_nightly.yml
My miss in reviewing https://github.com/pytorch/test-infra/pull/5814, having torchcodec in the list of options will allow folks to test the nightly build manually.
> Add torchcodec to the list of nightly dispatch options

- torchci/clickhouse_queries/lf_rollover_health/query.sql
- torchci/pages/metrics.tsx
Converts the lf_rollover_health query to use clickhouse.
It also:
- Corrects a bug in the query about how it calculated the average duration by fixing the denominator.
- Removes the temporary amz2023 label prefix handling, since those workflows are obsolete now anyways
Validation:
- Ensured that the ClickHouse query showed the same results as the Rockset query (except for the duration comparison chart, which also shows matching results if I reintroduce the average duration bug)
> [CF] Convert lf_rollover_health query to clickhouse

- s3_management/manage.py
https://github.com/pytorch/test-infra/pull/5814 adds torchcodec nightly wheel upload to test-infra.
This PR adds it to the index.
> Add torchcodec to manage.py for nightly wheel upload

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
Yeah, I decided that having those tests, even if functionally identical, might make some sense.
> adding tests for when max_available is not present in scale-config, not only undefined

- torchci/lib/bot/autoLabelCodevTrunk.ts
- torchci/test/autoLabelCodevTrunk.test.ts
Continuation of https://github.com/pytorch/test-infra/pull/5795
There was a case where the pr body didn't get edited when the PR was imported, so we should also handle this case, which I identify by seeing if the comment got added
I think the rule is :
* ghimport -> pr body gets edited
* normal import using button -> pr body doesn't get edited
Random but I think ghimport uses 2 spaces after the period, but the facebook-github-bot uses 1
> [bots] PR gets ciflow/trunk on import

- torchci/pages/api/drci/drci.ts
I forgot that you can have failing jobs and pending jobs at the same time, and the failing jobs icon will take precedence.  Tested by editing one of my PRs to it's old, pending and failed status and saw that it updated
> [drci][ez] Fix update pending

- .github/workflows/build_wheels_macos.yml
Currently, building Mac wheels has setting up miniconda for binary builds hard-coded to false. I believe this prevents us from doing wheel building on ephemeral runners. When trying to build Mac wheels on ephemeral runners, we run into a [`conda command not found`](https://github.com/pytorch/torchcodec/actions/runs/11580808748/job/32240163090?pr=320) error. Conda is not found because it's not installed. I assume that on our stable runners, it's already there.
This PR adds setting up miniconda as an option. It defaults to `false` because currently everyone is already working without setting it up, so it seems safest to disable it by default. This change mirrors what is currently in building wheels for Linux: https://github.com/pytorch/test-infra/blob/29912dec4567529a8aa7d124b7610c06b1648acb …
> Enable mac wheel building to setup miniconda

- aws/lambda/log-classifier/ruleset.toml
Here is an example misclassification from https://github.com/pytorch/pytorch/pull/139323
* :page_facing_up: Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/139323/index.html)
* :page_facing_up: Preview [C++ docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/139323/cppdocs/index.html)
* :question: Need help or want to give feedback on the CI? Visit the [bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) or our [office hours](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)
Note: Links to docs will display an error until the docs builds have been completed.
As of commit c185cfdfb26bb455800c8613be5fbacba971acb1 with merge base fef5e94657556f6617cb21eeeb494389d297b7d8 (<sub><sub><img …
> Add a rule for pr_time_benchmarks REGRESSION

- .github/actions/setup-nvidia/action.yml
Yesterday's nvidia-container-toolkit v1.17.0 [release](https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.17.0) seems to have broken some of our domain images, causing `docker run --gpus all [image]" to fail with the error:
```
$ docker run --gpus all [IMAGE]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: error parsing IMEX info: unsupported IMEX channel value: all: unknown.
ERRO[0000] error waiting for container: context canceled 
```
Pinning the toolkit to the previous version to …
> Pin nvidia-container-toolkit to version 1.16.2

- torchci/clickhouse_queries/lf_rollover_health/params.json
- torchci/clickhouse_queries/lf_rollover_percentage/params.json
- torchci/clickhouse_queries/lf_rollover_percentage/query.sql
- torchci/pages/metrics.tsx
Removed references to the obsolete amz2023 runner prefixes
Validation: Ensured the data in both CH and Rockset versions of the query return the same data and the charts look the same
> Migrate lf rollover percentage query to CH

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Removing the last am2 variant, which allowed the usage of Amazon Linux 2 amis.
This is needed since github runners are no longer officially supported on those machines and could break at any time.
Note: The am2.linux.9xlarge.ephemeral runner type is still referenced by the release/2.5 branch. This means that if we release 2.5.2 we’ll want to cherry pick in the fix to remove the am2 reference from those workflows to let them actually build
> Remove am2 variant

- torchci/lib/JobClassifierUtil.ts
- torchci/lib/fetchHud.ts
- torchci/lib/types.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
The logic here in HUD is pretty bad...
Merges LF and non LF columns into one column on the man page of HUD to reduce the size of HUD.  Using it is controlled through checkbox like most other settings
This desperately needs a second pair of eyes
> [HUD] Merge LF and non LF columns

- torchci/clickhouse_queries/oss_ci_benchmark_v3/query.sql
As defined in https://fburl.com/gdoc/pczummt2, this doesn't create the table, but I want to start keeping the create table SQL query on git
Manually run the query to create the table on CH https://console.clickhouse.cloud/services/c9b76950-2cf3-4fa0-93bb-94a65ff5f27d/console/database/benchmark/table/oss_ci_benchmark_v3
> Create the new benchmark database

- .github/workflows/linux_job.yml
- .github/workflows/test_linux_job.yml
Use ``pytorch/manylinux-builder`` as default image.
I believe the two secrets failures are expected on PR. Here is another example: https://github.com/pytorch/test-infra/actions/runs/11408487659/job/31746765207?pr=5786
> Use Manylinux Docker image for linux job

- torchci/pages/api/drci/drci.ts
Remove the failure context when updating check run in Dr. CI because it is really big
before
```
{"FAILED":[{"workflowId":11689744970,"workflowUniqueId":16521569,"id":32555466376,"runnerName":"i-0392431e49f4740e6","authorEmail":"[csl@fb.com](mailto:csl@fb.com)","name":"pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, lf.linux.g5.4xlarge.nvidia.gpu)","jobName":"linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, lf.linux.g5.4xlarge.nvidia.gpu)","conclusion":"failure","completed_at":"2024-11-05T21:02:34.000000000Z","html_url":"https://github.com/pytorch/pytorch/actions/runs/11689744970/job/32555466376","head_branch":"csl/always_produce_xml","pr_number":138513,"head_sha":"7fe36acfe3dbdde66a273d5b8b66134ddc18b44f","head_sha_timestamp":"2024-11-05T17:49:16.000000000Z …
```
> [drci][ez] Reduce drci check run update size

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
- .github/scripts/validate_scale_config.py
Add the m7i-flex.8xlarge instance type for Intel test suite to move off of from the c5.12xlarge instance type in use today.
Related: pytorch/pytorch#138476
> Add m7i-flex.8xlarge instance type

- tools/scripts/generate_binary_build_matrix.py
We have 3.13 Aarch64 builds in core for couple of days now : https://hud2.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=3_13&mergeLF=true
Hence enabling for domains.
> Add linux aarch64 Python 3.13 builds for domains

- torchci/clickhouse_queries/external_contribution_stats/query.sql
- torchci/clickhouse_queries/monthly_contribution_stats/query.sql
- torchci/pages/kpis.tsx
The returned data looks different between CH and RS because there are some errors in the RS table (dup rows) that I removed in CH.  This is also why I'm switching entirely to CH
Also removes old time params for the query since it says to remove them (I believe it's because contrb stats were only available after that time)
> [CH] Move external contrib queries on KPIs page to ClickHouse

- tools/torchci/td/historical_file_failure_correlation.py
Move query for getting historical file failure correlations for TD to ClickHouse
Checked by running the script and seeing that it outputted a file.  Unfortunately the data is not comparable to Rockset because the data on Rockset is outdated and incomplete
> [CH] Historical file failure correlation query

- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Fixes errors like
```
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
```
See https://github.com/vercel/next.js/discussions/38256
> [HUD][ez] Fix title element having multiple children warning

- torchci/clickhouse_queries/strict_lag_historical/params.json
- torchci/clickhouse_queries/strict_lag_historical/query.sql
- torchci/pages/kpis.tsx
Switch entirely
We lack data prior to 2024-10-01 due to the old query relying on _event_time, which is not available, so instead I had to make a new table and log data specifically about when viable/strict was updated
Data looks slightly different, my guess would be a combo of date trunc truncating to monday instead of sunday
Uses data from https://github.com/pytorch/pytorch/pull/136470
> [CH] Move viable/strict historical lag query to ClickHouse

- torchci/package.json
- torchci/pages/_app.tsx
- torchci/yarn.lock
Add existing Vercel analytics to track user visit. 
Currently our team has a setting up using google analytics general tracking, but the visit tracking is not very accurate , we found that Vercel has it's own tracking dashboard, but our team does not enable it. this pr add it to our website to see if it can gather some more accurate info.
See official Doc:
https://vercel.com/docs/analytics
> [BE] Add vercel analytics to track user visit

- torchci/pages/api/issue/[label].ts
To reduce warnings about `API response for /api/issue/skipped exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit`
Realistically most of these calls don't need the entire body, which is probably most of the size, but going through and finding all references is a task for another day
Checked that main HUD page still has buttons for "test is disabled" and "disable test"
> [HUD] Compress api/issues/[label]

- .github/actions/setup-miniconda/action.yml
Cherry-pick #5789 and #5821 to release/2.5 branch
This is needed for torchcodec CI to succeed:
https://github.com/pytorch/torchcodec/pull/373
> Added default-packages to setup-miniconda (#5789)

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
This is the fallback we have been using for a while to avoid the upgrade.
> Revert #5397 now that AL2023/Node 20 rollout is done

- tools/scripts/generate_binary_build_matrix.py
Accompanying PyTorch PR: https://github.com/pytorch/pytorch/pull/140743
Aarch64 jobs are passing: https://github.com/pytorch/test-infra/actions/runs/11844478690/job/33007802789?pr=5919
> Update aarch64 jobs to use manylinux2_28_aarch64-builder

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
ExecuTorch is requesting memory intensive R5 instances because they uses lots of memory to export the model while CPU cores stay idle.  Atm, they need to jump from `2xlarge` to `4xlarge` or `12xlarge` (or even `24xlarge`) to get the necessary amount of memory, which is a waste.
I also allocate more disk space to there instances, enough that they could dump the whole memory without running out of space.
cc @guangy10 @dvorjackz
> Add memory intensive R5 instances

- aws/lambda/clickhouse-replicator-s3/lambda_function.py
The schema comes from https://github.com/pytorch/test-infra/blob/main/torchci/clickhouse_queries/oss_ci_benchmark_v3/query.sql.  An example S3 path is `s3://ossci-benchmarks/v3/pytorch/pytorch/11850871071/33027181871/add_loop_eager_dynamic.json`
I think we should figure out how to test changes to these replicator lambdas.  Otherwise, we might lose some data if they break.  Any thoughts?
> Add an adapter for benchmark.oss_ci_benchmark_v3

- torchci/lib/tools/MeasureRenderTimeProfiler.tsx
We want to investigate the performance of components in HUD, [react-profiler](https://react.dev/reference/react/Profiler) is a good tool to give us the render time feedback.
You can def choose the profile tool in Chrome Extension: React Dev Tools, for me this is easy to target.
Only use it during local development. Though react profiler is light-weight, it is still takes memories on application.
Tracking render time for HudTable's  and its children's.
> [Tooling][Hud ]Add Performance Render Profiler wrapper

- .github/workflows/build_wheels_macos.yml
2 cherry-picks below needed for torchcodec.
> [Cherry-pick for release/2.5]

- torchci/components/GroupHudTableHeaders.tsx
- torchci/components/GroupJobConclusion.tsx
- torchci/components/JobFilterInput.tsx
- torchci/lib/GeneralUtils.ts
- torchci/lib/JobClassifierUtil.ts
- torchci/lib/RevertModal.tsx
- torchci/lib/fetchHud.ts
- torchci/lib/types.ts
- torchci/lib/useHudData.ts
- torchci/lib/useTableFilter.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Changes filter input to not update as typing, only updates after hitting enter
Changing this code in the past was really annoying, so I'm hoping that this makes it easier
Now the names array is all the jobs that we want to show, instead of everything or the groupNames.  This also simplifies some of the data passed around by HUD, like getting rid of old job array (data is dup with nameToJobs map), removing groupData (which can be reconstructed from nameToJob, groupNameMapping, and names)
This change made it easier to only render columns that actually pass the filter instead of setting the style to {visibility: "collapse"}, which I think reduces the number of DOM elements
I also added new context for group related data since we sometimes are just passing it from parent to child
> [HUD] Simplify grouping/header logic

- torchci/scripts/backfillJobs.mjs
The primary key has id first and dynamoKey last, so adding j.id = ${id} makes it go faster.
No need for quotes because it's a number and not a string
This is a very rarely used branch in the logic
> [ez] Make a query in the backfill script faster

- .github/actions/upload-benchmark-results/action.yml
It's ok if the benchmark results directory doesn't exists, for example, on non-benchmark job like `doc_test` https://github.com/pytorch/pytorch/actions/runs/11925173700/job/33237580806.  I missed this after landing https://github.com/pytorch/pytorch/pull/140493
> Handle invalid benchmark results directory

- .github/workflows/check-alerts.yml
- .github/workflows/update-queue-times.yml
- tools/torchci/queue_alert.py
- torchci/scripts/updateQueueTimes.mjs
Change the queue times script (which populates the historical queue times table), and the queue alert script (which makes issues about long queues) to ask hud.pytorch.org/api/clickhouse instead of directly asking rockset or clickhouse.
This is how the HUD alert also works already
> [CH] Update queue times script and queue alert script to use api/clickhouse

- torchci/clickhouse_queries/commit_jobs_query/query.sql
- torchci/clickhouse_queries/hud_query/query.sql
Companion to https://github.com/pytorch/pytorch/pull/140453
Exclude this job from HUD to reduce confusion, as it is always going to be red
> Do not show upload test stats while running job on HUD

- .github/actions/binary-upload/action.yml
- .github/actions/setup-binary-builds/action.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
This skip usage of for Manylinux1 images:
``actions/checkout@v4``
``actions/download-artifact@v3``
``actions/upload-artifact@v3``
Uses https://github.com/atalman/checkout-action which does not use nodejs to checkout.
This does not require full rewrite of the Build Linux Wheels at this point and will allow us to use Build Linux Wheels for both Manylinx 2.28 and Manylinx1 images. This should not disrupt any of the existing Domains, since workflow will be exactly the same. Basically instead of complete rewrite, we rewrite only part that failing in Github actions.
Test Workflow: https://github.com/pytorch/test-infra/actions/runs/11937438064/job/33273483586?pr=5941
Please note Linux jobs are using Manylinux2_28 while Rocm are using Manylinux1
This should also fix the SEV, since it bring back …
> Linux Wheel builds for Manylinux1. Use alternative to  actions, checkout, upload

- .github/actions/calculate-docker-image/action.yml
- torchci/next-env.d.ts
This is an attempt to mitigate the rate limit issue we are seeing when pulling the base image from docker.io https://docs.docker.com/docker-hub/download-rate-limit/#rate-limit.
Here is the summary of my support ticket to GitHub about the issue:
1. This behavior is from Docker Hub itself and isn't something GitHub can directly control.  You might consider a paid subscription to Docker Hub which increases the rate limit. You would need to pre-authenticate to Docker Hub on these runners before the job starts as GitHub builds the Docker containers before the first explicit step on the job.
2. Alternatively, we could move the images to https://ghcr.io which does not have such rate limits. 
3. GitHub has an agreement with Docker so that the rate limits do not apply for publicly accessible …
> Login to docker.io

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/utils.ts
- torchci/pages/api/drci/drci.ts
This change fixes a couple of issues with the workflow that refreshes Dr.CI results for all open PRs.  The key take away is that this API call scale on the number of open pull requests on a repo.  And on PyTorch, it now takes longer than 120 seconds to finish.  When that limit is reached, the Vercel function (AWS lambda) will terminate the execution and all PRs that are still in queue will be dropped.  Their Dr.CI comments will surely become stale.
Here is an example of the failure https://github.com/pytorch/test-infra/actions/runs/11943802339/job/33293533522.  The error is FUNCTION_INVOCATION_TIMEOUT (https://github.com/pytorch/test-infra/actions/runs/11964503897/job/33356932041#step:3:136), and it stops at 2 minutes sharp.  It's defined at …
> Mitigate Dr.CI stale comments on PyTorch PRs

- .github/actions/binary-upload/action.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/test_build_wheels_linux_with_cuda.yml
Test PR: https://github.com/pytorch/test-infra/pull/5961
Should resolve issue with torchao: https://github.com/pytorch/ao/actions/runs/11964124387
> Rewrite aws configure credentials without the using aws-actions/configure-aws-credentials. Use actions/checkout@v4 for manylinx 2.28 builds

- .github/workflows/build_wheels_linux.yml
Set Environment for OIDC upload.
Same as in: https://github.com/pytorch/test-infra/blob/main/.github/workflows/_binary_upload.yml#L47
This should allow us to upload when running under Manylinux1: https://github.com/pytorch/test-infra/blob/main/.github/actions/binary-upload/action.yml#L66
> Update build_wheels_linux.yml - set environment

- s3_management/manage.py
- s3_management/update_dependencies.py
Add torch xpu runtime dependencies pypi packages into S3 manage
Works for https://github.com/pytorch/pytorch/issues/139722 and https://github.com/pytorch/pytorch/issues/114850
> [xpu] Add the torch xpu runtime dependencies pypi packages

- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
- torchci/package.json
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/yarn.lock
This is reported by @yf225 and @ezyang  that when selecting dynamic or blueberries suites on the perf dashboard, an empty page is returned, for example https://hud.pytorch.org/benchmark/dynamic/inductor_aot_inductor?dashboard=torchinductor&startTime=Fri,%2015%20Nov%202024%2021:57:42%20GMT&stopTime=Fri,%2022%20Nov%202024%2021:57:42%20GMT&granularity=hour&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=d65f194ab91055d1a104163dce93d5580fec2d28&rBranch=main&rCommit=2b39a8db7741b816b03677a9c6fec1af05640dee
This is a regression bug coming from https://github.com/pytorch/test-infra/pull/5769 where I set the suite parameter incorrectly:
* Rockset set the default of this parameter to query everything.  The CH query missed that.
* The old code didn't set any suite and …
> Fix perf dashboard querying for individual suite

- .github/workflows/build_wheels_linux.yml
Manylinux aarch64 cuda binaries are Manylinux 2.28 based. Hence this change is required.
> Fix for aarch64 cuda binaries

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
Issue: https://github.com/pytorch/pytorch/issues/139492
Add label `ci-no-td` to reland PullRequest.
I split the list for pr and issue regex, this makes us to hand labels in different situations.
> [BOT] Add ci-no-td to reland PRs

- .github/workflows/build_wheels_linux.yml
- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/test_build_wheels_linux_python_versions.yml
- tools/scripts/generate_binary_build_matrix.py
This is a simple tweak to add `python-versions` to `.github/workflows/generate_binary_build_matrix.yml` so that Nova caller can narrow down the python version they want to build.  While PyTorch supports all Python versions from 3.9 to 3.13, not all domain libraries can do so.  So, unsupported Python versions always show up on their nightly branches, for example https://hud.pytorch.org/hud/pytorch/executorch/nightly/1?per_page=50&mergeLF=true.
The rest of the changes are lint fixes.
* https://github.com/pytorch/test-infra/actions/runs/12019554633
* https://github.com/pytorch/executorch/actions/runs/12019498604
> Allow Nova callers to choose Python version to build

- .github/workflows/mobile_job.yml
As the job downloads the link and store the content in a file before continuing, it makes sense to fail it when the link is invalid, i.e. https://gha-artifacts.s3.amazonaws.com/pytorch/executorch/12021308640/artifacts/stories110M_xnnpack/model.zip.  Otherwise, the subsequent test step would fail anyway, but we waste sometimes spinning up those mobile devices
> [EZ] Use curl --fail to correctly fail the job when the link is invalid

- tools/scripts/generate_binary_build_matrix.py
PyTorch PR: https://github.com/pytorch/pytorch/pull/141565/files
> Use cuda 12.6 wheels with Manylinux 2.28. Use Manylinux2014 for CPU, CUDA11.8, CUDA12.4

- .github/actions/clang-tidy-upload/action.yml
- .github/workflows/clang-tidy-linux.yml
- .github/workflows/clang-tidy-macos.yml
- tools/clang-tidy-checks/check_s3.py
The role is defined in https://github.com/pytorch-labs/pytorch-gha-infra/pull/551
This action has only been run 6 times, and has failed 4 of those 6 runs.  The most recent run failed due to lacking credentials, however it doesn't appear that those changes did any functionality change for the files related to these workflows.  The last successful runs where last year
Also
* add a python script for checking if its safe to upload the new binary (overwriting with a new file that has a different sha256 will break lintrunner init if the config is not updated.  It will also require people to pull the new config)
* linux build - only start the container and copy the file, do not upload the image
* upload the artifact to GHA artifacts as well
* Move sanity check s3 python script + all uploads into …
> [oidc] Clang tidy binary upload to use OIDC instead of secrets

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/test_build_wheels_linux_python_versions.yml
Without this option, all the submodule won't be initialized correctly, which leads to build failures like https://github.com/pytorch/executorch/actions/runs/12084054206/job/33698428919
> Pass submodules option to custom checkout

- tools/scripts/generate_binary_build_matrix.py
Fix issue with torchao release: https://github.com/pytorch/ao/actions/runs/12123438304/job/33798926358
> Update generate_binary_build_matrix.py - Restore CUDA 12.1 wheel image

- .github/actions/get-workflow-job-id/action.yml
- .github/actions/upload-benchmark-results/action.yml
It's a silly mistake and I should have used the relative path to the `get_workflow_job_id.py` script here.  Otherwise, this GH action will fail, for example https://github.com/pytorch/executorch/actions/runs/12060055309/job/33630870653.
It works in PyTorch because there is a script with the same name there.  I have done a similar fix before in https://github.com/pytorch/test-infra/blob/main/.github/actions/upload-benchmark-results/action.yml#L59
> Update get-workflow-job-id to use relative path to its script

- torchci/clickhouse_queries/last_successful_jobs/query.sql
Some slight differences but should return same result.  Please see comments for changes
With input: [     'docs push / build-docs-python-true',     'docs push / build-docs-cpp-true',     'docs push / build-docs-functorch-true' ]  (this is the input used on the metrics page)
Original: 
Elapsed: 7.157s
Read: 50,661,037 rows (27.19 GB)
New:
Elapsed: 1.079s
Read: 45,233,361 rows (4.22 GB)
> Make last_successful_jobs query faster

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
This was added when we added the m7i-flex.8xlarge instance type via #5874
> Revert min-available from AMX runners

- torchci/lib/bot/retryBot.ts
- torchci/test/retryBot.test.ts
A request from @laithsakka, we want to retry this job in a different runner as it could fail flakily sometimes
> Retry pr_time_benchmarks when it fails

- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
Discovered by @yangw-dev.  The default list of suites overwrote the selected value on https://hud.pytorch.org/benchmark/compilers, so the charts weren't updated even when a different suite was selected.
https://torchci-git-fork-huydhn-fix-wrong-params-su-ebff9e-fbopensource.vercel.app/benchmark/compilers
> Fix wrong query parameters to TorchInductor summary charts

- .github/workflows/_binary_upload.yml
The PR https://github.com/pytorch/test-infra/pull/5983 fixed binary upload for Linux job, however MacOS and Windows needs to be added to the fix as well.
> Fix binary upload logic after #5983

- torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Changes:
- Rename two columns to make them less confusing
- Replace the full repo name column with one that just has the repo name (without the org) to make just the repo name easier to parse out
This query isn't used anywhere yet so these changes are still safe to make
> [EZ] Tweak queued_jobs_aggregate query columns

- .github/actions/calculate-docker-image/action.yml
- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
This is a short-term mitigation for https://github.com/pytorch/pytorch/issues/141885 in which any changes touching `.ci/docker` would cause all the builds to fail until docker build workflow finishes building the images.
At the moment, we don't have a good way to tell the build workflow to wait for the new docker image, so my fix here attempts to inject a delay when the action is called by `_linux_build`.  It will wait up to 90 minutes for the Docker build to finish
https://github.com/pytorch/pytorch/pull/142177
> Wait for docker build

- torchci/pages/cost_analysis.tsx
> cost dashboard: remove timestamp, add UTC label for tooltip

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Part of https://github.com/pytorch/test-infra/issues/5798
- Fix a big bug with how we provisioned instances for ephemeral instances. In the old code, the fewer ephemeral runners we had available, the _less_ likely we were to overprovision them, which sounds like the opposite of what we actually want to do. Changed that logic to more explicitly give ephemeral runners a 50% chance of overprovisioning the incoming request by two instances, which is what I think [this PR](https://github.com/pytorch/test-infra/pull/5501) was intending to do (we can tweak these numbers as desired).  This fix might handle most of our ephemeral runner woes by itself...
- Extend the allRunnersBusy function to enable it to handle scale up requests of more than a single instance (which will be leveraged in a future …
> Bugfix: Overprovision scaleups on ephemeral instances & extend runner scale up code to enable larger scale ups

- aws/lambda/log-classifier/ruleset.toml
Mitigates https://github.com/pytorch/test-infra/issues/5975
A better (but more involved) fix will be to update the AI part of log classifier to better notice that this line was the real failure
> Add rule to handle missing docs for a new module

- torchci/pages/metrics.tsx
Shrink the title name of the `p50 pull, trunk workflows duration` box to make the box align with the other boxes in the row
An OCD fix
Before:
After:
> [EZ] Slightly less ugly metrics page

- torchci/components/metrics/panels/ScalarPanel.tsx
- torchci/pages/metrics.tsx
Like https://github.com/pytorch/test-infra/pull/6032 but for ScalarPanel
There are no usages of this that have not yet been migrated to ClickHouse
Also changes WorkflowDuration (used in one place) since it's basically a wrapper for ScalarPanel
> [HUD][CH] Move ScalarPanel to only use CH

- torchci/clickhouse_queries/last_successful_jobs/query.sql
- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/kpis.tsx
Fixes 2 charts when using ClickHouse
metrics page: last successful docs push had wrong return value names
kpis page: time to red signal chart to use ClickHouse, also needs some slight changes in formatting of the data to be able to display, as the current panel expects each percentile to be in a different row, but the query returns 1 row for a timestamp with all percentiles in the row
> [HUD] Fix docs push panel when using CH, ttrs kpi to use CH

- torchci/components/metrics/panels/TablePanelRS.tsx
- torchci/pages/metrics.tsx
- torchci/pages/nightlies.tsx
Similar to https://github.com/pytorch/test-infra/pull/6032 but for TablePanel
Only page to still use it and is not migrated is torchci/pages/nightlies.tsx
> [HUD][CH] Move TablePanel to only use CH

- .github/scripts/validate_binaries.sh
- .github/scripts/validate_pipy.sh
- .github/scripts/validate_poetry.sh
- .github/scripts/validate_test_ops.sh
- .github/scripts/xpu_env_helper.bat
- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/generate_docker_release_matrix.yml
- .github/workflows/validate-aarch64-linux-binaries.yml
- .github/workflows/validate-binaries.yml
- .github/workflows/validate-docker-images.yml
- .github/workflows/validate-linux-binaries.yml
- .github/workflows/validate-macos-arm64-binaries.yml
- .github/workflows/validate-nightly-binaries.yml
- .github/workflows/validate-nightly-pypi-wheel-binary-size.yml
- .github/workflows/validate-release-binaries.yml
- .github/workflows/validate-windows-binaries.yml
Moves all the worklfows from builder Validation framework except:
https://github.com/pytorch/builder/blob/main/.github/workflows/validate-repackaged-binary-sizes.yml
Part of https://github.com/pytorch/builder/issues/2054
It needs to be rewritten, followup PR required.
> Move Validation Framework workflows to test-infra

- tools/scripts/generate_binary_build_matrix.py
Move current release candidate and configuration to 2.6.0
> Move current release candidate to 2.6.0

- torchci/clickhouse_queries/cost_job_per_gpu/params.json
- torchci/clickhouse_queries/cost_job_per_gpu/query.sql
- torchci/clickhouse_queries/duration_job_per_gpu/params.json
- torchci/clickhouse_queries/duration_job_per_gpu/query.sql
- torchci/pages/cost_analysis.tsx
This allows the cost analysis to group by gpu/non-gpu:
[https://torchci-git-wdvr-gpu-nongpu-cost-fbopensource.vercel.app/cost_analysis?dateRange=7&granularity=day&**groupby=gpu**&chartType=line&yAxis=cost](https://torchci-git-wdvr-gpu-nongpu-cost-fbopensource.vercel.app/cost_analysis?dateRange=7&granularity=day&groupby=gpu&chartType=line&yAxis=cost)
See on the right 'group by' -> 'GPU'
> allow to group by gpu/non-gpu

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Adds a swap space for the autoscaled runners.
Prints on post_job step if the swap usage was detected during the job running, and sends metrics related to swap usage per job.
> Adds swap space for ALI runners and report to ci and metrics if it is used

- terraform-aws-github-runner/modules/runners-instances/launch-template.tf
This follows the removal of all IMDSv1 calls weeks ago, as well as the upgrade of sccache on all repos that use it.
test plan: 
We'll monitor impact, but current IMDSv1 calls are close to 0, with those left being ones based of a main older than a few weeks.
mitigation in case of failure:
- revert this
- **https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-restore-IMDSv1** for existing runners
> mandate IMDSv2 on all new ec2 runners

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
I made a mistake in https://github.com/pytorch/test-infra/pull/6066 and should have checked if the file exists first.
> Fix a bug when swapfile doesn't exist

- aws/websites/download.pytorch.org/pep503_whl_redirect.js
I am seeing validation error here:
https://github.com/pytorch/test-infra/actions/runs/12357596722/job/34504501590#step:14:2563
Executing:
```pip3 install --force-reinstall torch --index-url https://download.pytorch.org/whl/test/rocm6.2.4```
does not work, accessing https://download.pytorch.org/whl/test/6.2.4 does not work either
> Update pep503_whl_redirect to accomodate for rocm maj.min.patch version

- .github/workflows/validate-aarch64-linux-binaries.yml
- .github/workflows/validate-linux-binaries.yml
- .github/workflows/validate-nightly-binaries.yml
1. Aarch64: Skip docker builds same as here: https://github.com/pytorch/test-infra/blob/main/.github/workflows/validate-linux-binaries.yml#L139
2. Aarch64: Fix script path
3. Aarch64: Add tests to nightly validation trigger
4. XPU: conda install path fix
> Fix logic in validate aarch64 and xpu linux binaries

- .github/scripts/validate_binaries.sh
XPU are compiled with cxx11-abi hence set the correct flag before running the validations.
Test failures are fixed by: https://github.com/pytorch/test-infra/pull/6079
> Use devtoolset x11-abi for XPU builds validations. 

- .github/workflows/build-windows-ami.yml
Add a job to create Windows AMIs in the PyTorch AWS Account.
Issue: pytorch/test-infra#5992
> Add Packer Build job for Windows AMI

- torchci/clickhouse_queries/cost_job_per_repo/params.json
- torchci/clickhouse_queries/cost_job_per_repo/query.sql
- torchci/clickhouse_queries/duration_job_per_repo/params.json
- torchci/clickhouse_queries/duration_job_per_repo/query.sql
- torchci/pages/cost_analysis.tsx
This allows the cost repo to be grouped by repo.
Adds two queries, one for:
https://torchci-git-wdvr-costperrepo-fbopensource.vercel.app/cost_analysis?dateRange=90&granularity=month&groupby=repo&chartType=stacked_bar&yAxis=cost
and one for 
https://torchci-git-wdvr-costperrepo-fbopensource.vercel.app/cost_analysis?dateRange=90&granularity=month&groupby=repo&chartType=stacked_bar&yAxis=duration
> allow  cost dashboard to be grouped by repo

- .github/scripts/validate_binaries.sh
I believe we are testing with numpy 1+ ad 2.0.0. This removes 2.0.0 pin and uses latest numpy
> Use latest numpy 2+ for validaiton of wheels

- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/labelCommands.test.ts
Fixes https://github.com/pytorch/test-infra/issues/5900
When a `ciflow` label is added to a PR, we normally trigger workflows against it. However, if the PR has not yet been authorized to actually run workflows then we do not allow the label to be added. (This feature was added by https://github.com/pytorch/test-infra/pull/4892)
This change improves the reasoning given by the error messages, making it easier for the reviewer to understand why a label was not added to the PR and the steps they need to take to actually add the desired label.
> [BE] [PyTorchBot] More understandable error  message when labels cannot be added

- torchci/components/GroupHudTableHeaders.tsx
Reduce the number of clicks needed to expand/collapse a group by removing the part of the code that ensures that the first click only removes the highlighted component for job names/headers.  This only changes the flow for clicking the headers, clicking jobs or commits still has the same behavior
Example:
Click on group -> group gets highlighted, and group expands
Current behavior:
Click on group again -> group gets unhighlighted
Click on group again -> group gets collapsed
This PR:
Click on group again -> group gets highlighted, and group collapses
This also means if something is highlighted, ex you have a job tooltip open, clicking on a group will highlight and expand that group immediately, while previously it would unhighlight and you would have to click again to expand
Example:
Click …
> [HUD] Reduce number of clicks for expanding grouping

- tools/scripts/generate_binary_build_matrix.py
Forward fix for https://github.com/pytorch/test-infra/pull/6099 which removed pre-cxx-abi config for everything. Instead we skip generating it
Rocm builds pre-cxx11 removed by: https://github.com/pytorch/pytorch/pull/141423
> Remove rocm pre-cxx11 abi

- tools/analytics/cubinsizes.py
- tools/analytics/download_count_wheels.py
- tools/analytics/duplicates_analyze.py
- tools/analytics/github_analyze.py
- tools/analytics/s3_test_stats_analyze.py
- tools/analytics/validate_binaries.py
- tools/analytics/validate_pypi_staging.py
Part of https://github.com/pytorch/builder/issues/2054
> Move analytics scripts from builder

- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
- torchci/pages/benchmark/llms.tsx
ExecuTorch has replaced the backend field with a more generic benchmark configs concept, so the dashboard will display it instead.
* https://github.com/pytorch/executorch/pull/7349
* https://github.com/pytorch/executorch/pull/7433
https://torchci-git-fork-huydhn-add-executorch-backend-fbopensource.vercel.app/benchmark/llms?startTime=Tue%2C%2017%20Dec%202024%2019%3A05%3A31%20GMT&stopTime=Tue%2C%2024%20Dec%202024%2019%3A05%3A31%20GMT&granularity=hour&lBranch=handle-benchmark-config-dashboard&lCommit=c48da2bd2c9a32705db9b1adf638344474c275a4&rBranch=handle-benchmark-config-dashboard&rCommit=c33f815eff17c8890f2c8527dc0f0dbca50b4397&repoName=pytorch%2Fexecutorch&modelName=All%20Models&backendName=All%20Backends&dtypeName=All%20DType&deviceName=All%20Devices
> Add support for benchmark configs on ExecuTorch dashboard

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/aoUtils.ts
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
This is my initial attempt to add the speedup metric for TorchAO. This is done by comparing the gain of `autoquant` v.s. `noquant`.  This is by no means the best approach because it requires custom logic for TorchAO on the dashboard.  On the other hand, it's easy to implement and I think it's better to have the UX done first to gather early feedbacks from @jerryzh168 and the rest of ao team first.
IMO, better approaches would be to either 1) set the speedup metric on TorchAO side or 2) compute the speed up metric on ClickHouse.  Both are more involved and requires further design discussion.
https://torchci-git-fork-huydhn-add-speedup-llm-dashboard-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fao
> Add speedup metric for TorchAO

- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
- torchci/pages/benchmark/llms.tsx
This is the follow-up of https://github.com/pytorch/test-infra/pull/6118 to add an aggregated geomean speedup metric for all models grouped by devices.
I limit this change to TorchAO `speedup` metric for now until I have time to polish the rest of the metrics (or if there is a need to add them at all)
https://torchci-git-fork-huydhn-add-benchmark-summary-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fao
> Add TorchAO aggregated geomean speedup metric

- torchci/components/WorkflowDispatcher.tsx
Previously inductor-periodic could be triggered via ciflow/inductor, but not anymore, so we can remove the workarounds for the dispatching logic related to this
> [HUD] Remove inductor-periodic/inductor related workarounds for workflow dispatcher

- torchci/lib/useGroupingPreference.tsx
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Previously if you clicked the filter search box, it would change HUD to not use groupings.  
This made sense since the filtering was as you type, but it was changed recently to only take place after you hit enter.
Also, afterwards, if you reload the page, it would still not use groupings, even if no filter was applied, which is odd.
Now, if you click the filter, it does not change to use groupings immediately.  It now changes to not use the grouping after you hit enter and the filtering is performed.  When you reload the page, it uses the preference you set before clicking the filter
--
Old old (commit prior to this PRs base commit)
click filter -> turn off use grouping
type -> filter happens as you type, all groups are expanded
reload page with no filter -> grouping preference is to use …
> [HUD] Do not set use grouping preference when using filter

- s3_management/manage.py
Corresponds to https://github.com/pytorch/pytorch/pull/143677
Add support for pep658 and pep714
https://peps.python.org/pep-0658/
https://peps.python.org/pep-0714/
Some of the shas are the same, but this also happens on pypi so I guess the metadata file is just the same for those
Snippet of what the index html looks like:
```
<a href="/whl/nightly/cu126/torch-2.6.0.dev20250102%2Bcu126-cp313-cp313-win_amd64.whl">torch-2.6.0.dev20250102+cu126-cp313-cp313-win_amd64.whl</a><br/>
<a href="/whl/nightly/cu126/torch-2.6.0.dev20250102%2Bcu126-cp313-cp313t-manylinux_2_28_x86_64.whl">torch-2.6.0.dev20250102+cu126-cp313-cp313t-manylinux_2_28_x86_64.whl</a><br/>
<a href="/whl/nightly/cu126/torch-2.6.0.dev20250102%2Bcu126-cp39-cp39-linux_aarch64.whl">torch-2.6.0.dev20250102+cu126-cp39-cp39-linux_aarch64 …
```
> Add pep658 metadata sha to index html

- .github/workflows/tests.yml
- .github/workflows/update-test-times.yml
- .github/workflows/update_test_file_ratings.yml
- aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1
- tools/torchci/queue_alert.py
- tools/torchci/tests/test_queue_alert.py
Remove rockset pip installs + some mentions in variable names
This changes the windows ami scripts.  I'm down to try updating the AMI, but I'm also ok with this change being bundled into the next time the AMI gets changed
> [ez][HUD] Remove rockset pip installs + some variable names

- torchci/lib/clickhouse.ts
Set the query_id to be `query_name-uuid` for named queries or `adhoc-uuid` in the case of adhoc queries. 
This is helpful for getting average time and memory usage for queries and mapping them back to the original query.  The system.query_log table can be used to find this information (https://clickhouse.com/docs/knowledgebase/find-expensive-queries) but when using the ClickHouse javascript package, the query column there is a parsed version of the query which is hard to map back to the original query text.  
The query_id needs to be unique for every query and the docs suggest using a uuid
https://clickhouse.com/docs/en/integrations/javascript#query-id
> [CH][HUD] Set query_id parameter for ClickHouse queries

- torchci/components/LoadingPage.tsx
- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/lib/bot/utils.ts
- torchci/package.json
- torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
- torchci/yarn.lock
This results in a lot of "union too complex to represent" errors, which I solved by separating the context, which was previously typed `Context<webhook type>` to just `Context`, and the payload (if it is used), which is now typed `Context<webhook type>["payload"]`
so functions taking in
`context: Context<"pull_request">`
now take in
`context: Context, payload: Context<"pull_request">["payload"]`
and anything that previously used `context.payload` now just uses `payload`
Some disccusion on this can be found here:
https://github.com/probot/probot/discussions/1966
https://togithub.com/ubiquity-os/ubiquity-os-kernel/issues/31
https://togithub.com/probot/probot/issues/1968
I'm not sure why the import order formatter changed it's mind about what order things should be in, but it seems to still …
> [HUD] Upgrade typescript 4.6.3 -> 5.7.2

- torchci/components/JobLinks.tsx
Fix after #6094 caused the unstable button to stop showing up on failed jobs
> [HUD] Fix unstable button not showing up on failing jobs

- .github/dependabot.yml
I followed https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot but I'm not sure this works since this file only has /setup-ssh for npm and we definitely get dependabot PRs for stuff outside of setup-ssh
After looking at the dependabot config, I think the non setup-ssh updates might come from security updates, not version updates
> Dependabot for GHA

- .github/scripts/test_update_disabled_issues.py
- .github/scripts/update_disabled_issues.py
The expected format of a disable issue for multiple tests is
Title: DISABLED MULTIPLE <can be anything here>
Body:
additional info
disable the following tests:
```
test_name (test_suite): platforms, mac
test_name2 (test_suite):
```
additional info
For example
---
Tested by running old version and new version and diffing the files.  There was no change
> [disablebot] Allow reading of disable issue for multiple tests

- .github/workflows/validate-linux-binaries.yml
To be able to detect issues like these: https://github.com/pytorch/pytorch/issues/144433
Using script from: https://github.com/pytorch/pytorch/issues/138324
> Amazon Linux 2023 validation

- .github/scripts/validate_binaries.sh
- .github/scripts/validate_pipy.sh
- .github/scripts/validate_poetry.sh
- .github/scripts/validate_test_ops.sh
- .github/scripts/xpu_env_helper.bat
- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/generate_docker_release_matrix.yml
- .github/workflows/validate-aarch64-linux-binaries.yml
- .github/workflows/validate-binaries.yml
- .github/workflows/validate-docker-images.yml
- .github/workflows/validate-linux-binaries.yml
- .github/workflows/validate-macos-arm64-binaries.yml
- .github/workflows/validate-nightly-binaries.yml
- .github/workflows/validate-nightly-pypi-wheel-binary-size.yml
- .github/workflows/validate-release-binaries.yml
- .github/workflows/validate-windows-binaries.yml
This should fix Docker release builds . During docker build we try to call: [.github/workflows/validate-docker-images.yml](https://github.com/pytorch/test-infra/compare/release/2.6...atalman:fix_docker_builds?expand=1#diff-f64e270c717ed4139ac5a36998b5d3e88bd35d25af567fbd007fbe0a13ac09ed)
> [Cherry-Pick] Move Validation Framework workflows to test-infra 

- .github/workflows/lint.yml
- .lintrunner.toml
- tools/linter/adapters/grep_linter.py
- torchci/clickhouse_queries/test_time_per_class/query.sql
- torchci/clickhouse_queries/test_time_per_class_periodic_jobs/query.sql
- torchci/clickhouse_queries/test_time_per_file/query.sql
- torchci/clickhouse_queries/test_time_per_file_periodic_jobs/query.sql
- torchci/clickhouse_queries/workflow_duration_percentile/query.sql
Copy over grep_linter from https://togithub.com/pytorch/pytorch/pull/144589.
Enable TABS linter in CI
Add paths to ignore list that don't currently work
Run formatter on clickhouse_queries folder
> [CI] Enable TABS formatter/linter

- .github/actions/bc-lint/action.yml
- .github/actions/binary-upload/action.yml
- .github/scripts/validate_binaries.sh
- .github/workflows/lint.yml
- .lintrunner.toml
- aws/lambda/log-classifier/scripts/download_logs.py
- aws/websites/download.pytorch.org/pep503_whl_redirect.js
- terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/.prettierrc
- terraform-aws-github-runner/modules/runners-instances/policies/instance-ec2-create-tags-policy.json
- tools/analytics/download_count_wheels.py
- tools/analytics/github_analyze.py
- tools/analytics/s3_test_stats_analyze.py
- tools/analytics/validate_pypi_staging.py
- tools/binary_size_validation/README.md
- tools/scripts/generate_binary_build_matrix.py
- tools/tests/README.md
Enables the linter that checks for trailing spaces
Add one file that probably shouldn't be linted
Apply changes via `lintrunner -a --take SPACES --all-files`
> [CI] Enable SPACES formatter/linter

- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
At news year eve, we had an small CI outage. Queue started to grow due to lack of capacity to create new linux instances. After investigating the issue we noticed that this is due to the pinning of labels in the `ami` tag of `scale-config.yml` and its variants. This is due to the fact that for security reasons, Amazon removed the tag on its services, so we could not resolve the AMI ID from the tag search.
The goal of this tag is to enable to migrate to a newer AMI type runner-by-runner, so we can troubleshoot problems and avoid the issue of being stuck in the migration because of a particular job that runs in a particular instance. This was included with the concept of variants.
Now that the migration is complete, the correct approach is to **REMOVE** these labels and rely on the labels …
> Remove ami pinning from scale-config.yml files

- .github/actions/bc-lint/action.yml
- .github/workflows/pr-dependencies-check.yml
We are migrating this action "malfet/checkout@silent-checkout" into test-infra to have all the code hosted in our public repos.
> CI: Migrate malfet/checkout to test-infra

- torchci/clickhouse_queries/queued_jobs/query.sql
- torchci/clickhouse_queries/queued_jobs_by_label/query.sql
Make results for queued_jobs_by_label more similar
* Change queued_jobs_by_label to only look at jobs in the past weekly like the queued_jobs query
* Use job.created_at instead of started_at for queued_jobs_by_label.  I don't think there's a difference for jobs that are queued, only jobs that are running or completed
This helps resolve a problem where a job showed up in one HUD table but not in the other
> [HUD] Look for queued jobs in past month only

- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
Per the char with @zou3519 and @shunting314, I'm adding another chart to show the total number of models covered in the benchmark run.  This is the denominator used to compute the pass rate.  I'm showing this in a separate chart because there is no easy way to include this information in the current pass rate chart given the current implementation.
I also increase the legend padding a bit to make the chart easier to view.
https://torchci-git-fork-huydhn-show-inductor-passr-b83539-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinductor&startTime=Thu%2C%2018%20Jul%202024%2022%3A52%3A52%20GMT&stopTime=Tue%2C%2014%20Jan%202025%2023%3A52%3A52%20GMT&granularity=week&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=1dab79470dbecef79ba4c7d4308d8a181091e58e&rB …
> Add a chart to show the total the number of models

- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
The regression comes from https://github.com/pytorch/test-infra/pull/6006 where I changed `accuracy_results LEFT JOIN performance_results` to `performance_results LEFT JOIN accuracy_results` to accommodate Apple MPS eager benchmark.  The swapped join wrongly returned `model_fail_to_load` and `eager_fail_to_run` models that shouldn't be included in the pass rate calculation because they are not something wrong with pt2.
https://torchci-git-fork-huydhn-fix-pt2-dashboard-p-e92d66-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinductor&startTime=Fri%2C%2019%20Jul%202024%2000%3A29%3A48%20GMT&stopTime=Wed%2C%2015%20Jan%202025%2001%3A29%3A48%20GMT&granularity=week&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=1dab79470dbecef79ba4c7d4308d8a181091e58e&rBran …
> Fix pt2 dashboard passrate calculation regression

- torchci/test/disableFlakyBot.test.ts
- torchci/test/utils.ts
A few testing utilities to hopefully making writing bot tests easier
* Use Partial type for testing helper functions that generate dummy data https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype
* Add mockCreateIssue to mock creating an issue on Github, and use it in flakybot
* Add mockGetRawTestFile for flakybot for mocking retrieving the raw test file for oncall labels
* Use handleScope in flakybot tests
> [bots] Testing utilities: Partial type, some helper functions for flakybot

- .github/scripts/update_disabled_issues.py
- .github/workflows/update_disabled_tests.yml
We don't have access to the environment at PR time, so we don't have the GH_PYTORCHBOT_TOKEN.  Instead we can fallback to GITHUB_TOKEN, but this doesn't have the necessary permissions for getting the correct unstable + disable jobs.  However, being able to test the overall workflow on PR and the disable tests generator is better than nothing
> [disablebot] Fix workflow when run on PR

- .github/workflows/linux_job.yml
- .github/workflows/linux_job_v2.yml
Relates to https://github.com/pytorch/ao/pull/999
Needs https://github.com/pytorch/pytorch/pull/143590
> Enable linux_job_v2.yml workflow for ROCm

- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/components/benchmark/llms/ModelGraphPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/aoUtils.ts
- torchci/pages/benchmark/llms.tsx
Addresses the first part of https://github.com/pytorch/test-infra/issues/6176
This PR adds another speedup metric vs eager.  Because this is TorchAO dashboard, I think it's more appropriate to show TorchAO vs compile and TorchAO vs eager instead of TorchAO vs compile and compile vs eager because the last one (compile vs eager) is a fit for PT2 inductor dashboard instead. @jerryzh168 What do you think?
I also fix another UX issue to show the oldest commit in the time range as the base commit instead.
https://torchci-git-fork-huydhn-improve-ao-speedup-metric-fbopensource.vercel.app/benchmark/llms?startTime=Thu%2C%2009%20Jan%202025%2010%3A21%3A42%20GMT&stopTime=Thu%2C%2016%20Jan%202025%2010%3A21%3A42%20GMT&granularity=day&lBranch=main&lCommit=2cddc67fe700579043e3e2d395d983764298b82e9746e9b266 …
> Add TorchAO speedup metric vs eager

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
fixes #6038 
the -h command is not always taken into account
the argparse library does not always capture the -h flag in all positions. Added 2 tests and an explicit check for the help flag.
> fixes #6038 the -h command not always taken into account

- .github/workflows/validate-pypi-wheel-binary-size.yml
- .github/workflows/validate-repackaged-binary-sizes.yml
Enable to run these workflows on workflow_dispatch
Pass channel to Validate PyPI Wheel Binary Size to be able to validate nightly or test binaries
> Update wheel binary size validations

- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_v3_materialized_views/query.sql
I'm attempting to use a new materialized view called `oss_ci_benchmark_metadata` to make it faster to query benchmark metadata.  I have already added the new view manually but its definition is included in this PR for review.
The old query works, but it's slower because the original table doesn't keep several important columns, i.e. benchmark name, in order https://github.com/pytorch/test-infra/blob/main/torchci/clickhouse_queries/oss_ci_benchmark_v3/query.sql#L98-L107.  According to https://clickhouse.com/docs/en/sql-reference/statements/alter/order-by, it seems that we cannot add existing columns into ORDER BY.
When loading the benchmark metadata:
* Slooooow https://hud.pytorch.org/benchmark/llms?repoName=pytorch%2Fpytorch
* Faster …
> Use oss_ci_benchmark_metadata materialized view

- torchci/pages/api/flaky-tests/disable.ts
When investigating https://github.com/pytorch/pytorch/issues/144964, I notice that `api/flaky-tests/disable` returns 403 error code even when I use the correct credential.  Same goes on 
https://vercel.com/fbopensource/torchci/logs?requestPaths=%2Fapi%2Fflaky-tests%2Fdisable&selectedLogId=cv6z2-1736966788286-ab32c5324f42&timeline=maximum&page=2
> Correctly return 200 in api/flaky-tests/disable

- torchci/pages/sli.tsx
Adding a sharable link is a useful thing for when we want to share and discuss things inside the team (easier than sharing print screens most of the time).
All is not that useful of a metric for us, it include 3rd party provided runners and github runners. This makes the information noisy and non-actionable. To focus on what we manage and provide some useful breakdown I opted to have the following breakdowns by default:
- "pet" - include all our pet instances, macos and the shared instances with A100 and H100;
- "ephemeral" - are all instances that are dynamically scaled both by Meta and LF, that are ephemeral. They are very fragile to stockouts;
- "nonephemeral" - are all instances that are dynamically scaled both by Meta and LF, that are non-ephemeral. They are somewhat resilient to …
> Improves SLI page by adding sharable stateful link and sets 'pet, ephemeral, nonephemeral' as default options

- .github/actions/binary-upload/action.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/update_disabled_tests.yml
This ensures binary uploads to S3 attaches a SHA256 checksum.
I am not familiar with this code base, but from what I can gather the S3 uploads seem to be missing SHA256 for various wheel file URLs. This seem to lead to missing wheel hashes at https://download.pytorch.org/.  My guess is that the checksum is not available when it is retrieved [when the html is generated](https://github.com/pytorch/test-infra/blame/a797a36aab02198636cb2d032f24b894d668cefe/s3_management/manage.py#L535).
With this change, it should ensure that the checksum is calculated before upload and attached to the object.
Relates-to: https://github.com/pytorch/pytorch/issues/76557
> [CI] Add SHA256 checksum for binary uploads to S3

- torchci/clickhouse_queries/master_commit_red/query.sql
Pre filter the commits so we can filter the workflow job and workflow run tables on it later
This improves speed for all time ranges up to 1 year.  I did not check beyond that
I believe the memory used is about the same, but it scans more rows for some reason
This is the query behind this chart
on the metrics page
Tentative wins, sample size 3
```
+------+----------+-----------+-------------+---------------+--------------+---------------+----------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change |   Avg Mem    |    Base Mem   |   Mem Change   | % Mem Change |
+------+----------+-----------+-------------+---------------+--------------+---------------+----------------+--------------+
|  0   |   1163   |   23117   |    -21954   |      -95      | 157241294.6 …
```
> Improve master_commit_red query performance

- .github/actions/binary-upload/action.yml
- .github/workflows/_binary_upload.yml
- .github/workflows/update_disabled_tests.yml
Reverts pytorch/test-infra#6172
Broke download.pytorch.org index. Please see: https://github.com/pytorch/pytorch/actions/runs/12926060185/job/36048291540#step:4:124
> Revert "[CI] Add SHA256 checksum for binary uploads to S3"

- s3_management/manage.py
This to be reverted on Jan 24, 2025
To fix following failure: https://github.com/pytorch/pytorch/actions/runs/12926060185/job/36048291540#step:4:124
Caused by: https://github.com/pytorch/pytorch/pull/144887 and https://github.com/pytorch/test-infra/pull/6172
> Temporary disable including sha256 in nightly packages

- .github/workflows/lint.yml
- .lintrunner.toml
- tools/linter/adapters/exec_linter.py
- tools/linter/adapters/grep_linter.py
- tools/torchci/td/get_merge_base_info.py
Added a bunch of exclusions to get it green.  We should to back at some point and try to remove them
Updated grep_linter (undoes https://togithub.com/pytorch/pytorch/pull/144589)
Updated exec_linter
> Apply the rest of the linters in CI

- .github/actions/update-viablestrict/action.yml
- .github/workflows/revert-tracker.yml
- .github/workflows/tests.yml
- .github/workflows/update-test-times.yml
- .github/workflows/update_test_file_ratings.yml
- aws/lambda/clickhouse-replicator-dynamo/requirements.txt
- aws/lambda/clickhouse-replicator-s3/requirements.txt
- aws/lambda/servicelab-ingestor/requirements.txt
- tools/torchci/requirements.txt
Did some verification for the easier python scripts like the revert tracker and the test time generator
Ran the dynamo replicator on a bit of workflow_job 
Ran the s3 replicator on a bit of merge_bases
Both seemed fine, but we should still monitor just in case
Do not merge until we are awake and able to revert quickly
> Update clickhouse connect to 0.8.14

- .lintrunner.toml
- .sqlfluff
- tools/linter/adapters/sqlfluff_linter.py
- torchci/clickhouse_queries/workflow_load/query.sql
add sqlfluff linter using clickhouse dialect on for use on linting clickhouse queries
> Add SQLFLUFF linter for clickhouse queries

- torchci/components/benchmark/compilers/common.tsx
This is to support ROCm benchmark at https://github.com/pytorch/pytorch/pull/144594
https://torchci-git-fork-huydhn-add-rocm-device-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinductor&startTime=Mon%2C%2020%20Jan%202025%2019%3A06%3A47%20GMT&stopTime=Mon%2C%2027%20Jan%202025%2019%3A06%3A47%20GMT&granularity=hour&mode=inference&dtype=bfloat16&deviceName=rocm&lBranch=144594&lCommit=9f5cb037965aa2990b2e4593610bca92526ebb3b&rBranch=144594&rCommit=9f5cb037965aa2990b2e4593610bca92526ebb3b
cc @jeffdaily @BLOrange-AMD
> Add ROCm device to PT2 inductor dashboard

- release/pypi/promote_pypi_to_staging.sh
- release/pypi/upload_pypi_to_staging.sh
Changes the pypi prep scripts ahead of PyTorch release 2.6.
Main change: Aarch64 wheels are build using manylinux_2_28 Docker now.
> Release 2.6 pypi prep changes

- torchci/components/benchmark/compilers/common.tsx
This was called out by AMD team that the device should be called `rocm (mi300x)` so that we could have different AMD devices in the future.  This is also the same convention used by cuda on the dashboard.
> Correctly use rocm (mi300x) for ROCm device

- .github/actions/calculate-docker-image/action.yml
Reported by @jeffdaily that the build job for ROCm Docker image now takes close to 90 minutes to finish, for example https://github.com/pytorch/pytorch/actions/runs/12998049606/job/36250394659.  So, setting the max waiting time to 90 minute is not sufficient anymore.
> Increase max docker build wait time to 120 minutes

- torchci/clickhouse_queries/testStats3d/params.json
- torchci/clickhouse_queries/testStats3d/query.sql
- torchci/clickhouse_queries/testStatsDistinctCount/params.json
- torchci/clickhouse_queries/testStatsDistinctCount/query.sql
- torchci/clickhouse_queries/testStatsSearch/params.json
- torchci/clickhouse_queries/testStatsSearch/query.sql
- torchci/components/tests/TestSearchForm.tsx
- torchci/package.json
- torchci/pages/api/flaky-tests/3dStats.ts
- torchci/pages/api/flaky-tests/failures.ts
- torchci/pages/api/flaky-tests/search.ts
- torchci/pages/failure.tsx
- torchci/pages/flakytest.tsx
- torchci/pages/tests/search.tsx
- torchci/pages/tests/testInfo.tsx
- torchci/yarn.lock
https://hud.pytorch.org/flakytest?name=test_mm_plus_mm&suite=TestPatternMatcher&limit=100
Changes the flakytest page to redirect to a search page.  Double clicking on a row brings you to a page about the individual test.  The individual test page has a bar chart of runs from the past 3 days, and the info that used to be on the flakytest page (list of jobs the test failed or was rerun)
Old:
New:
https://torchci-git-csl-testx-fbopensource.vercel.app/flakytest?name=test_mm_plus_mm&suite=TestPatternMatcher&limit=100
Double clicking on the row brings you to
https://torchci-git-csl-testx-fbopensource.vercel.app/tests/testInfo?name=test_mm_plus_mm&suite=TestPatternMatcher&file=inductor%2Ftest_pattern_matcher.py
which looks like this after loading
> [HUD] Better test info pages

- torchci/components/benchmark/compilers/CompilerGraphGroup.tsx
- torchci/components/benchmark/compilers/ModelPanel.tsx
- torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
- torchci/components/benchmark/compilers/SummaryPanel.tsx
- torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
- torchci/pages/benchmark/compilers.tsx
- torchci/pages/benchmark/torchao.tsx
Fixes https://github.com/pytorch/test-infra/issues/6221
I keep two dropdown lists, one for the base, and one for the new commit.  All the options are still in the same line, which looks ok in my widescreen. There might be too many for a smaller screen though.
https://torchci-git-fork-huydhn-select-base-new-devices-fbopensource.vercel.app/benchmark/compilers
> Support cross-device comparison

- torchci/components/JobLinks.tsx
- torchci/pages/api/failure.ts
- torchci/pages/failure.tsx
hud.pytorch.org/failure easier to search by doing some parsing into the expected format and putting a search button so it's clearer that you can search.
Search will still work without the [""], which didn't work before.
The `more like this` link will get rid of the [""] if possible to reduce confusion
I don't know what job name actually does so I didn't touch that functionality so there's probably still more parsing that needs to be done there
https://torchci-git-csl-similarfailureeasiersearch-fbopensource.vercel.app//failure?name=pull%20%2F%20linux-focal-cuda12.4-py3.10-gcc9%20%2F%20test%20(default%2C%204%2C%205%2C%20linux.4xlarge.nvidia.gpu)&jobName=undefined&failureCaptures=functorch%2Ftest_ops.py%3A%3ATestOperatorsCUDA%3A%3Atest_jvp_nn_functional_multi_head_attention_forward_cuda_float …
> [HUD] Better similar failure search UI

- s3_management/manage.py
Restores the sha256 hash for binaries if they exist.
In https://github.com/pytorch/pytorch/pull/144887 the sha256 of the binary is manually calculated and uploaded as metadata with the binary because the automatic one given by s3 is wrong (likely due to it being part of a multipart upload https://docs.aws.amazon.com/AmazonS3/latest/userguide/tutorial-s3-mpu-additional-checksums.html).
This PR 
* Attempts to adds a check for multipart upload sha256's and does not show them if they are part of a multipart upload and 
* Surfaces the new metadata given by the above PR
* Restores the sha256 that was previously removed due to being wrong
I also went back and corrected the bad shas from the multi part upload (not that it would have mattered, as this PR wouldn't show them in the index).  The …
> sha256 for binaries index

- .github/workflows/_binary_upload.yml
Equivalent of https://github.com/pytorch/pytorch/pull/144887 for domains
To be used in https://github.com/pytorch/test-infra/pull/6241
> s3 binary upload with sha256 as metadata

- .github/workflows/linux_job_v2.yml
- .github/workflows/test_linux_job_v2.yml
This permission is redundant and can be removed.  Having it here overwrites the permission granted to the workflow by its caller, i.e. https://github.com/pytorch/executorch/blob/main/.github/workflows/doc-build.yml#L88
`content: read` has already been granted by default.
> Remove redundant content permission in linux_job_v2

- .github/workflows/linux_job_v2.yml
This should have been removed in https://github.com/pytorch/test-infra/pull/6250.  We don't need this anymore when there is no OIDC.
AI: Write a lint job to prevent people from changing the permission in linux job sounds like a good idea because doing so requires updating all the callers.
> Remove id-token:write in linux_job_v2

- terraform-aws-github-runner/modules/runners/lambdas/runners/README.md
- terraform-aws-github-runner/tools/aws-ssh-session
- terraform-aws-github-runner/tools/run-aws-lambda-helper
Added a README.md on `terraform-aws-github-runner/modules/runners/lambdas/runners/README.md` with instruction on how to develop and troubleshoot lambdas development.
> Adding documentation to help develop ALI lambdas and some useful scripts

- .github/workflows/lambda-do-release-runners.yml
- aws/lambda/ci-queue-pct/.gitignore
- aws/lambda/ci-queue-pct/Makefile
- aws/lambda/ci-queue-pct/ci_queue_pct.py
- aws/lambda/ci-queue-pct/dorun.sh
- aws/lambda/ci-queue-pct/requirements.txt
Move from meta closed repository to test-infra repository the code for ci-queue-pct lambda. This lambda is the one that computes the queue percentile times used in https://hud.pytorch.org/sli
The reason for this migration is related to start the effort to organize our Lambdas, using this as an example of how we should be moving forward.
Test workflow: https://github.com/pytorch/test-infra/actions/runs/13162528997
Created release: https://github.com/pytorch/test-infra/releases/tag/v20250205-165758
> Adds ci-queue-pct lambda code to aws/lambdas and include it to the release

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/test_generate_binary_build_matrix.py
https://github.com/pytorch/pytorch/issues/145570
Deprecate conda functions meanwhile, as conda builds are gone https://github.com/pytorch/pytorch/issues/138506
cc @atalman @ptrblck @nWEIdia
> [aarch64] Add aarch64 cuda 12.8 domain builds

- tools/torchci/clickhouse_query_perf.py
- torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
Make faster by adding a projection to the table 
```
PROJECTION benchmark_name_projection
(
SELECT *
ORDER BY 
repo,
tupleElement(benchmark, 'name'),
tupleElement(model, 'name'),
tupleElement(metric, 'name'),
timestamp,
head_branch,
head_sha,
workflow_id,
job_id,
servicelab_experiment_id,
servicelab_trial_id
),
```
For some reason, ClickHouse won't use the projection unless t uses `has` instead of `in` and all the other tuple elements are in quotation marks 
We should consider changing the order by key to be this instead since I can't imagine anyone not filtering by benchmark name
Perf results:
```
+------+----------+-----------+-------------+---------------+----------+-----------+------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change | Avg Mem  |  Base …
```
> Make llm benchmarks query faster

- .github/dependabot.yml
It creates a bunch of PRs that we never merge.  I don't know how to test this action and I assume that others are also unsure so they don't merge them either
> Remove setup-ssh from dependabot updates

- aws/ami/windows/windows.pkr.hcl
Using more available g5.4xlarge machine with larger volume
I see following errors during cuda 12.8 installation:
```
ERROR: [NVI2.NVDiskSpaceConstraint] 1206@CNVDiskSpaceConstraint::InvokeCheck : Extra space required on system for packages: "3121.46 MB on Disk (C:)".
amazon-ebs.windows_ebs_builder:   15.000 |   INFO: [NVI2.NVDiskSpaceConstraint] 1212@CNVDiskSpaceConstraint::InvokeCheck : Disk space check complete.
...
amazon-ebs.windows_ebs_builder:     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
```
Failure here: https://github.com/pytorch/test-infra/actions/runs/13184202890/job/36802279658
> Use g5.4xlarge with 128GB volume to build windows AMI

- tools/pkg-helpers/pytorch_pkg_helpers/cuda.py
current torchvision/audio builds missing sm_100 and sm_120
adding to cu128 builds
`cuobjdump -ptx /usr/local/lib/python3.12/dist-packages/torchvision/_C.so | grep "arch = sm_" | sort --unique
arch = sm_50
arch = sm_60
arch = sm_70
arch = sm_75
arch = sm_80
arch = sm_86
arch = sm_90`
cc @atalman @ptrblck @nWEIdia
> add sm_100 and sm_120 to cuda 12.8 domain builds

- torchci/components/utilization/UtilizationPage.tsx
- torchci/components/utilization/components/TestSectionView/RankTestView/RankBar.tsx
- torchci/components/utilization/components/TestSectionView/RankTestView/RankTestView.tsx
- torchci/components/utilization/components/TestSectionView/SingleTestView.tsx
- torchci/components/utilization/components/TestSectionView/TestSectionView.tsx
- torchci/components/utilization/components/TestSectionView/ToggleTestsGroup.tsx
- torchci/components/utilization/components/UtilizationJobSummary/UtilizationJobSummary.tsx
- torchci/components/utilization/components/UtilizationStatsTable.tsx
- torchci/components/utilization/helper.ts
- torchci/components/utilization/styles.tsx
- torchci/components/utilization/types.ts
- add rank table view for choosing the single test
- calculate all gpus' mem and util avg,max to show in rank and stats table
- able to cick on test to show on rank too
https://torchci-1fhqvklex-fbopensource.vercel.app/utilization/13143119394/36681447812/1
> [Utilizaiton] Add RankTable View

- .github/actions/setup-binary-builds/action.yml
- .github/actions/setup-binary-upload/action.yml
- .github/workflows/test_build_wheels_linux_without_cuda.yml
- .github/workflows/test_build_wheels_m1.yml
- .github/workflows/test_build_wheels_windows_with_cuda.yml
As reported by @drisspg where his build fails because the ref includes some forward slashes https://github.com/pytorch/ao/actions/runs/13275832470/job/37065164277
@drisspg I add your ref as a test case, so please keep it around instead of deleting it.  I wonder if this is a smart thing to include.
https://github.com/pytorch/test-infra/actions/runs/13281773348/job/37081535345?pr=6281
> [Nova] Escape forward slashes in ref name

- torchci/pages/api/drci/drci.ts
- torchci/test/drci.test.ts
Jobs only get categorized after they fail, but if a job is marked as unstable, it will always end up in the unstable group. This PR makes it so that unstable pending jobs get put in the unstable group.  I think this should help with trymerge waiting for unstable jobs to finish, since we sometimes mark jobs as unstable if the queue time is very long
Pending unstable jobs still count towards the pending count
This was tested on a random PR on pytorch by curling my local development
Pending jobs will show up in Dr. CI, which might be confusing as people usually expect only failing jobs to show up, so it also adds a hour glass icon to the pending unstable jobs, which looks like
> [drci] Mark unstable pending jobs as unstable

- .github/workflows/linux_job.yml
- .github/workflows/linux_job_v2.yml
- .github/workflows/test_linux_job.yml
- .github/workflows/test_linux_job_v2.yml
related to issue: https://github.com/pytorch/executorch/issues/8125
example run: https://github.com/pytorch/executorch/actions/runs/13275229180/job/37063477575
Set defult warning for missing artifact
add test for no artifacts
> set warning upload artifacts when check-artifact step return error

- aws/ami/windows/windows.pkr.hcl
Reverts pytorch/test-infra#6226
Reverting to unblock Cuda 12.8 migration. Looks like we would need to step back and do some more testing on pytorch-canary before relanding this see the failure: https://github.com/pytorch/pytorch/pull/147053
> Revert "remove visual studio 2019 install in test infra"

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
follow up for https://github.com/pytorch/pytorch/pull/146957
use 9.7.1.26 for CUDA 12.6 too to test the windows AMI
cc @atalman
> Update win cudnn to 9.7.1.26 for CUDA 12.6 as well

- tools/torchci/tests/test_update_test_times.py
- tools/torchci/update_test_times.py
Due to the recent issue with https://github.com/octokit/request-action/issues/315, the workflow to upload test stats was broken for a few days.  The issue has been mitigated by https://github.com/pytorch/pytorch/pull/146940, but we still have a gap in test times until new stats come in.
The test times from the last 3 viable/strict commits were used to compute test times https://github.com/pytorch/test-infra/blob/main/torchci/clickhouse_queries/test_time_per_file/query.sql#L11-L12
The `tools/torchci/update_test_times.py` script had a bug in which it overwrote the default test times even when there was no stats from the above query. The effect of this was that [run_test](https://github.com/pytorch/pytorch/blob/main/test/run_test.py#L1909-L1936) had no default values to use in some cases, …
> Avoid overwriting the default test times if the new default is empty

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
See: https://github.com/pytorch/pytorch/issues/145544#issuecomment-2644049797
We need bigger runner to test these architectures
> Add g4dn.4xlarge runners for testing Cuda 12.8 builds

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/test_build_wheels_windows_without_cuda.yml
- tools/scripts/generate_binary_build_matrix.py
Vision builds passes
For torchaudio we need https://github.com/pytorch/audio/pull/3881
> Build python 3.13t on windows

- .github/workflows/mobile_job.yml
This is the first step to fix https://github.com/pytorch/executorch/issues/7989.  We need to always upload mobile artifacts if they are found.  I think I will also need to update https://github.com/pytorch/executorch/blob/main/.github/scripts/extract_benchmark_results.py after this to handle the failure case, but it can come after this change.
The upload steps are always run but will give a warning if there is no file https://github.com/pytorch/test-infra/actions/runs/13404882215/job/37442926309#step:14:27
> Always upload mobile artifacts if they are found

- torchci/components/benchmark/llms/SummaryPanel.tsx
- torchci/components/benchmark/llms/common.tsx
- torchci/lib/benchmark/llmUtils.ts
Fixes https://github.com/pytorch/executorch/issues/7986 (for real this time)
The problem is that the records in the benchmark database alone don't have the information to differentiate between benchmarks that are failed to run and benchmarks that are not run. Both show up as 0 on the dashboard. Note that we can do a join with `workflow_job` table to get this information, but it's a rather slow and expensive route.  So, I opt for a quicker approach to keep track of the list of valid devices on the dashboard side.  A valid device is one that is run by the selected commit and has at least one non-zero record there.
https://torchci-git-fork-huydhn-better-model-filter-fbopensource.vercel.app/benchmark/llms?repoName=pytorch%2Fexecutorch
> Filter out devices that are not run

- .github/scripts/validate_binaries.sh
- .github/workflows/validate-linux-binaries.yml
For release 2.6 we restricted Manylinux 2.28 builds to cuda 12.6 only. Now its time to remove this restriction and use cxx11-abi=1 by default
> Validate Manylinux 2.28 builds using almalinux-builder image

- s3_management/manage.py
The cloudfront cache sometimes serves old versions of the whl but the index will have the sha of the new wheel, resulting in errors where pip says
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
unknown package:
Expected sha[256](https://github.com/pytorch/FBGEMM/actions/runs/13420201693/job/37492521940#step:14:257) 7dc1686d7207eb3eb340b5bc7e6076d41acebd6013cf4f32d4afbab7c97aa579
Got        fb8cf5ad5e1c2d0fd3a1fb8ad3beec5f86c527d2e7cdb6842226ebf24178d1e0
```
like https://github.com/pytorch/FBGEMM/actions/runs/13420201693/job/37492521940
The error eventually gets fixed when the cache stops serving the old …
> Remove sha256 from index for nightlies

- torchci/components/JobLinks.tsx
- torchci/lib/useScrollTo.ts
Not sure if this is a good idea but
Adds anchor to the link so that it will scroll to the job when the commit link is clicked and the job will get highlighted
For reference, the commit link looks like
in the job tooltip on HUD.  It is also present in a few other places, like the failures page
Clicking on the commit link will now go to the commit page, scroll to the job, and highlight the job
Highlight example:
This will also highlight jobs when clicking on links from Dr. CI:
---
Also fix link for non pytorch repos
> [HUD] Add scroll to for commit link in job links, add highlight, fix commit link for non pytorch repos

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
This runner is to be used for binary builds as identified in https://github.com/pytorch/pytorch/pull/147542
> Adding runner linux.12xlarge.memory.ephemeral

- .github/workflows/trigger_nightly.yml
- s3_management/manage.py
This PR lets nightly builds be triggered for https://github.com/pytorch-labs/torchvision-extra-decoders
I based this PR on what was recently done for TorchCodec: https://github.com/pytorch/test-infra/pull/5814 and https://github.com/pytorch/test-infra/pull/5815.
> Trigger nightly build of torchvision-extra-decoders repo

- torchci/pages/api/flaky-tests/failures.ts
This was an experiment on taking one of our slower queries (identified by the ClickHouse query insights table) and seeing what it would take to bring this into a more reasonable performance level
Perf improvements:
* Duration reduced 91%: 14.5s -> 1.29s
* Memory reduced 96%: 22.63GB -> 0.95GB 
* Rows read reduced 55%: 68.4 million -> 30.7 million
**Naive joins can be incredibly expensive in ClickHouse**. Turns out the biggest chunk of work here was happening in the join between `default.workflow_job` and `default.failed_test_runs`.
An example api call to hit against the prod and test endpoints:
- http://hud.pytorch.org/api/flaky-tests/failures?name=test_Tensor___bool__&suite=TestTorchFunctionOverride&file=test_overrides.py
vs
- https://torchci-git-zainr-optimizeflakytestquery-fbopensource. …
> Optimize query for getting flaky test info

- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/test/ciflow-push-trigger.test.ts
As in title, check that a PR is able to run workflows when syncing (pushing a new commit)
The label stays on the PR, which might be a bit confusing
> [bots] Check for permissions when syncing ciflow

- tools/scripts/identify_and_kill_instances_by_id.sh
This script expects a file named instances.txt with one AWS instance id per line.
It will go through those instances, and kill them if they are running
To be used in case of runner issues or security concerns to quickly kill a subset of runners.
NOTE: this will stop and fail tests that are currently running.
cc @zxiiro
> script to kill ec2 instances by id

- .github/scripts/validate_binaries.sh
- .github/workflows/validate-linux-binaries.yml
- .github/workflows/validate-pypi-wheel-binary-size.yml
- tools/scripts/generate_binary_build_matrix.py
- tools/scripts/get_stable_cuda_version.py
1. Introduce get_stable_cuda, this way we don't need to hardcode current stable cuda version in validations
2. Add py3.13t versions
> Validate framework changes, intorduce get_stable_cuda.py add py3.13t required changes

- torchci/components/benchmark/compilers/ModelPanel.tsx
- torchci/components/benchmark/compilers/SummaryPanel.tsx
This is a bug reported by @malfet where the dashboard only shows the value from the new commit (right) when the left commit and the right commit are the same but on different devices.  This defeats the purpose of comparing different devices.
The bug here is that the `l → r` display worked under the assumption that same commit mean same benchmark, which is not true anymore.  Same benchmark now means same commit plus same device.
https://torchci-git-fork-huydhn-fix-cross-device-sa-e8d1e5-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinductor&startTime=Wed%2C%2019%20Feb%202025%2021%3A06%3A10%20GMT&stopTime=Wed%2C%2026%20Feb%202025%2021%3A06%3A10%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lDeviceName=rocm%20(mi300x)&rDeviceName=cuda%20(a100)&lBranch=main&lCommit=d0adff76 …
> Fix summary table for same commit on different devices

- torchci/lib/bot/utils.ts
- torchci/test/utils.test.ts
If all the runs are startup failure, the function would return true. However, this can hide the need for those runs to be approved. This might result in runs being rejected when they shouldn't, but I doubt an actual PR is going to mangle workflows and still want CI
Err on the side of caution by refusing if any job has a startup failure, even if there are approved runs
Example: https://github.com/pytorch/pytorch/pull/147774
(I am hash update bot, its a poorly named account since I was originally going to use for something else and was the fastest account I could get right now to test this)
There is a startup_failure conclusion, but depending on how you mess up the workflow syntax, you can either get failure or startup_failure (https://github.com/pytorch/pytorch/pull/148016/files), and it …
> [bots] Checking for approved workflow runs: handle runs being startup failure

- torchci/lib/bot/ciflowPushTrigger.ts
- torchci/test/ciflow-push-trigger.test.ts
Follow up to #6328
Remove the ciflow labels on sync to reduce confusion
Cons:
* add more events to the PR timeline
> [bots] Remove ciflow labels on sync if no perms, follow up to #6328

- torchci/clickhouse_queries/tts_duration_historical/params.json
- torchci/clickhouse_queries/tts_duration_historical/query.sql
- torchci/clickhouse_queries/tts_duration_historical_percentile/params.json
- torchci/clickhouse_queries/tts_duration_historical_percentile/query.sql
- torchci/components/common/CheckBoxList.tsx
- torchci/package.json
- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/yarn.lock
A number of changes to the TTS page
ROCm wanted to get TTS info about jobs on pytorch/ao, but because we use an explicit list of supported workflows, they didn't show up.  Instead, use an explicit list of blocked workflows so that we don't need to add every workflow. Some cons of this include: showing way too many jobs, sending too much info over network
Use CheckboxList component as the filterer for the graphs so that you can filter the jobs
Add a permalink, which can handle multiple selected jobs. Previously the filtering list had links and you could choose one, and this changes it to handle multiple at the cost of making the old links stop working
Use SWRImmutable since I don't think its that important that this data but refreshed all the time
Other small changes include:
* Getting rid …
> [HUD] TTS page: use blocklist instead of allowlist for workflow names, use CheckboxList component, permalink of multiple jobs

- torchci/components/utilization/components/UtilizationStatsTable.tsx
- torchci/components/utilization/helper.ts
remove the duration spike since it's not useful,
the gpu_mem_all should aggregated as max instead avg
> [Utilization] fix bugs

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Sometimes SSM parameter is not properly created. After investigation I identified that the promise is not being properly awaited. What could cause some operations to be canceled.
> [Bugfix] wait for ssm parameter to be created

- .github/actions/setup-binary-builds/action.yml
Follow up after:
https://github.com/pytorch/test-infra/pull/6242
Newer conda is having trouble installing py3.13t artifacts, please see:
https://github.com/pytorch/vision/actions/runs/13659383307/job/38186887882#step:10:98
```
Could not solve for environment specs
The following packages are incompatible
├─ libpng =* * is installable with the potential options
│  ├─ libpng 1.6.37 would require
│  │  └─ zlib >=1.2.11,<1.3.0a0 *, which can be installed;
│  └─ libpng 1.6.39 would require
│     └─ zlib >=1.2.13,<1.3.0a0 *, which can be installed;
└─ python-freethreading =* * is not installable because it requires
├─ cpython =3.13.2 *, which requires
│  └─ python =3.13.2 * with the potential options
│     ├─ python 3.13.2 would require
│     │  └─ libzlib >=1.3.1,<2.0a0 *, which requires
│ …
```
> [py 3.13t] Fix for vision nightly failure on MacOS M1 machines

- tools/scripts/fetch_latest_green_commit.py
- tools/tests/test_fetch_latest_green_commit.py
Allows the viable strict promotion script to use unstable issues.  Jobs that have unstable issues open will be ignored in viable strict promotion.  
Tested with 
0ef2e938d0a9a4b90434f98b5e128d0ffacaae26 (passed, only thing failing is libtorch debug build which has an issue right now)
96afa8a2bb78e5410a83038fd1e3f83911601700 (failed since there's something pending)
c5d92edd5acfa56bae4f0c1057d667c6356fd6c1 (failed since lint failed)
> [viable/strict] Ignore failing jobs with unstable issues

- torchci/components/benchmark/llms/components/dashboardPicker/LLMsDashboardPicker.tsx
https://github.com/pytorch/test-infra/issues/6363
this is a typo when refactor the benchmark code, simply remove the [], I think visual studio auto-gen triggered it
> [Fix Bug] remove bug to not parse the rcommit

- .github/workflows/tflint.yml
- terraform-aws-github-runner/Makefile
- terraform-aws-github-runner/README.md
created a Makefile on `./terraform-aws-github-runner` to perform tflint actions, and replaced the tflint calls on CI (`tflint.yml`) with this makefile.
This makes much easier to test locally and make sure to get green signals on CI. Reducing the loop time to fix small syntax bugs.
> Adding tooling and documentation for locally run tflint

- README.md
- torchci/README.md
As in title
* Update the lint/formatter info
* Remove the dup info about development on HUD and link to the torchci README instead
> [BE] [ez] READMEs - update lint/formatter info, remove dup info about hud

- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
The tts and job duration tables in the metrics page use jobName in the link to quickly specify a job.  I got rid of it in https://github.com/pytorch/test-infra/pull/6326 in favor of a compressed list so you could permalink multiple jobs and forgot that the metrics page linked here.  This PR restores the functionality and allows both jobNames and jobNamesCompressed
> [HUD] Restore tts page jobName router query

- tools/torchci/clickhouse_query_perf.py
Disable cache usage in the clickhouse query perf script since it might skew results
Use p50 to prevent outliers from messing up results too much
*  wait longer for the table to populate since I had a case where it didn't get data
* Add wait time arg if people need to wait longer for the stats table to show up
> ClickHouse query perf script - disable cache, use p50, add wait time arg

- tools/scripts/generate_binary_build_matrix.py
- tools/tests/assets/build_matrix_linux_wheel_xpu.json
- tools/tests/assets/build_matrix_windows_wheel_cuda.json
- tools/tests/assets/build_matrix_windows_wheel_xpu.json
As pytorch xpu enabled python 3.13t by https://github.com/pytorch/pytorch/pull/146614, enable python 3.13t for XPU binary build matrix
> [XPU] Enable python 3.13t in binary build matrix

- .github/actions/setup-binary-builds/action.yml
Follow up after https://github.com/pytorch/test-infra/pull/6358
> Add guard for conda unistall of conda-anaconda-telemetry

- tools/device-farm-runner/run_on_aws_devicefarm.py
- tools/device-farm-runner/test_run_on_aws_devicefarm.py
https://github.com/pytorch/test-infra/issues/6294
Details:
- print `os` in test spect printout section
- store os, job_arn (mobile job) and job_conclusion to each artifact metadata. Notice this is not github job conclusion, this is mobile job conclusion.
- wrap post-test logics into ReportProcessor, 
- pass aws client as parameter for test-driven purpose
- add unit test for ReportProcessor
> [Mobile Benchmark Test] Add os, job_arn, and job_conclusion to artifact

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/cost_analysis.tsx
allow user to filter by regex the cost page
Example: https://torchci-git-wdvr-costregexfilter-fbopensource.vercel.app/cost_analysis?dateRange=7&granularity=day&groupby=job_name&chartType=stacked_bar&gpu=1&os=linux%2Cwindows&yAxis=cost&searchFilter=%5E%28%28%3F%21build%7Cbinary%29.%29*%24&isRegex=true
> add regex filter for cost page

- torchci/components/GroupJobConclusion.tsx
- torchci/components/JobConclusion.module.css
- torchci/components/JobConclusion.tsx
show monsterized failures in grouped view in HUD, example:
This makes it easy to see if a failure is repeating and when it started, without having to uncollapse or deal with shifting shard columns
- tooltip shows how many tests per failure type
- nothing changed in the non-grouped view
> monsterized failures in grouped view

- torchci/components/WorkflowBox.tsx
Some build artifacts weren't showing up under the job in the show artifacts button because the types for some things are incorrect, so key was actually a number and not a string, making the later read of the map incorrect.
Old:
Missing build artifact
New:
> [ez][HUD] Fix build artifacts grouping in workflow box

- .github/workflows/mobile_job.yml
- .github/workflows/test_mobile_job.yml
- tools/device-farm-runner/run_on_aws_devicefarm.py
Issue: https://github.com/pytorch/test-infra/issues/6294
Prepare mobile_job yml to generate benchmark record when job fails.
When a git benchmark job failed (or some of the mobile job failed), we need to generate a benchmark record to indicate that model has failures.
For instace, a benchmark job with name:`benchmark-on-device (ic3, coreml_fp16, apple_iphone_15, arn:aws:devicefarm:us-west-2:308535385114... / mobile-job (ios) `
when the whole job failed, we want to indicate that the model ic3 with backend coreml_fp16 and IOS for all metrics is failed
when one of the devices in job is failed, (IPHONE 15 with os 17.1), we want to indicate that  the model ic3 with backend coreml_fp16 for IPHONE 15 with os 17.1 is failed, but others are success
key: always generate the artifact json with git …
> [Benchmark] Prepare for execuTorch failure handling

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
We don't really support well our canary environment with variants, not sure why, but this condition was not present, so variants will get the wrong naming when running at meta canary environment. `variant.c.runner.name` instead of `c.variant.runner.name`. This fix is very low impact and should not change anything in production.
There is a useless `if` that I noticed when reading `getRunnerTypes`. I am removing that conditional;
As we're adding empty variants as part of the ephemeral migration, I want to make sure that we have green tests and we're covering this situation in our unit tests.
The new situations to cover are:
1) Empty variants
2) meta's canary environment naming convention `c.`
> Adds additional tests to getRunnerTypes, simplifies code a bit, adds the support for `c.` runners

- tools/scripts/generate_binary_build_matrix.py
Aarch64 CUDA 12.6 builds where removed from pytorch/pytorch by https://github.com/pytorch/pytorch/pull/148895
> Remove cuda 12.6 aarch

- torchci/components/CheckBoxSelector.tsx
- torchci/components/JobConclusion.module.css
- torchci/components/JobFilterInput.tsx
- torchci/components/NavBar.module.css
- torchci/components/TooltipTarget.module.css
- torchci/components/TooltipTarget.tsx
- torchci/components/hud.module.css
- torchci/components/minihud.module.css
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
- torchci/styles/globals.css
This is the first part of splitting #6392 into three smaller PRs. This PR focuses only on CSS improvements unrelated to dark mode:
* Add CSS variables for all colors in globals.css
* Update component CSS files to use these variables 
* Improve styling and tooltip positioning
* Maintain consistent colors across components
* Fix layout shifts when hovering over elements
This PR provides better maintainability by centralizing color definitions without adding any dark mode functionality.
Part of #6392
> CSS Improvements: Add CSS variables for better color consistency

- torchci/components/TooltipTarget.module.css
tooltip width was no longer wide - side effect of dark mode PRs. This fixes that:
> fix tooltip width

- torchci/.env.example
I moved some env vars to Keeper to enable sensitive env vars for [T212882155](https://www.internalfb.com/intern/tasks/?t=212882155), so this updates the .env.example instructions to also mention Keeper
> [ez][HUD] Update .env.example instructions to mention Keeper

- .github/workflows/validate-linux-binaries.yml
- tools/scripts/generate_binary_build_matrix.py
Remove libtorch PRE_CXX11_ABI from matrix
failures can be seen here: https://github.com/pytorch/test-infra/actions/runs/13906844473/job/38911966250
> [validations] Remove libtorch PRE_CXX11_ABI from matrix. 

- torchci/components/TooltipTarget.module.css
regression after dark mode fixes:
old version (desired behavior):
broken version:
after this PR:
> fix vertical position of tooltip on HUD

- torchci/components/NavBar.module.css
Regression since https://github.com/pytorch/test-infra/pull/6405 - making the dropdown of the navbar hide at times.
> fix dropdown gap causing issues dropping down

- .github/workflows/_binary_upload.yml
- .github/workflows/build_wheels_linux.yml
- .github/workflows/build_wheels_macos.yml
- .github/workflows/build_wheels_windows.yml
Binary build workflows were getting named incorrectly so this should name them the things that they're actually doing.
Example of what our old naming scheme looked like:
> ci: Give correct job names to binary builds

- torchci/lib/benchmark/llms/common.ts
issue: https://github.com/pytorch/test-infra/issues/6430
add indicateor for trimmean_inference_latency
the preview:
[vercel](https://torchci-git-addrate-fbopensource.vercel.app/benchmark/llms?startTime=Thu%2C%2013%20Mar%202025%2001%3A10%3A38%20GMT&stopTime=Thu%2C%2020%20Mar%202025%2001%3A10%3A38%20GMT&granularity=day&lBranch=main&lCommit=0ccf5093823761cf8ad98c75e5fe81f15ea42366&rBranch=main&rCommit=8c03d0453cfe789513e2f3cf9fef1ee4b6a527cd&repoName=pytorch%2Fexecutorch&benchmarkName=&modelName=All%20Models&backendName=All%20Backends&modeName=All%20Modes&dtypeName=All%20DType&deviceName=All%20Devices&archName=All%20Platforms)
> [Benchmark UI] Add indicator for trimmean_inference_latency(ms)

- torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
- torchci/components/metrics/panels/TablePanel.tsx
it is not ideal when a benchmark table has 100 records,  when user scrolls down, they cannot see the column headers
https://github.com/pytorch/test-infra/issues/6430
Preview UI with long data: [vercel](https://torchci-git-benchexfefix-fbopensource.vercel.app/benchmark/llms?startTime=Thu%2C%2006%20Mar%202025%2001%3A42%3A40%20GMT&stopTime=Thu%2C%2020%20Mar%202025%2000%3A42%3A40%20GMT&granularity=hour&lBranch=main&lCommit=51901f3849723b44f3a48768b7a7bf7ffdc08094&rBranch=main&rCommit=b195ed9a2564e5c2cd3554518213c4769d3ad022&repoName=pytorch%2Fexecutorch&benchmarkName=&modelName=All%20Models&backendName=All%20Backends&modeName=All%20Modes&dtypeName=All%20DType&deviceName=All%20Devices&archName=All%20Platforms)
Example with small data
> [Benchmark UI] Make the mui table scrollerable

- torchci/components/commit.module.css
- torchci/components/minihud.module.css
- torchci/components/utilization/components/TestSectionView/ToggleTestsGroup.tsx
- torchci/styles/globals.css
In both commit details and minihud:
move css background colors to vars and add dark versions
before:
after:
> HUD commit details: fix css colors in dark mode

- torchci/components/WorkflowBox.tsx
- torchci/lib/fetchS3Links.ts
- torchci/pages/api/artifacts/s3/[workflowId].ts
Query for the artifacts for all workflow ids in the box.  Previously we assumed that only one workflow would show up in the box at a time, but this might not be true.  
Change the api to accept a list of workflows in the form list.join(",") and get the artifacts for all the workflow ids in that list
https://torchci-git-csl-moreartifacts-fbopensource.vercel.app/pytorch/pytorch/commit/970ac2d907195dc31debe28e9a7ff8f4aa701683
old:
new:
Note that the artifacts button shows up for the first job (non rerun or memory leak one)
Fixes https://github.com/pytorch/test-infra/issues/5298
> [HUD] Query for artifacts of all workflow ids

- torchci/pages/cost_analysis.tsx
Fixed repository filter not being saved in URL parameters on cost analysis page. Added code to ensure filter selections persist when sharing URL or using permalink.
Fixes #6458
> Fix repository filter missing from URL params

- torchci/clickhouse_queries/last_successful_workflow/params.json
- torchci/clickhouse_queries/last_successful_workflow/query.sql
Reduces query:
* Execution time by 84% (4.2s -> 0.7s)
* Memory used by 98% (3.3 GB -> 79 MB)
* Data read by 98% (11.14 GB -> 272.80 MB)
This PR adds multiple optimizations:
* Remove unnecessary FINAL keywords
* Limit the time range that we search workflow queries to just the past two weeks instead of all stored workflows (can be tweaked if necessary) 
* Prefilter tables before the join using the WITH clause.  Note that Claude suggested using the [PREWHERE clause](https://clickhouse.com/docs/sql-reference/statements/select/prewhere) (which was an interesting discovery) but perf was way faster when using WITH instead (and more readable too)
It also updates the params.json file to add the test case used for this query
```
+------+----------+-----------+-------------+---------------+---------- …
```
> [BE] Optimize last_successful_workflow ClickHouse query 

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Adds the runner `linux.4xlarge.for.testing.donotuse` that will be used to test scaleUpChron in production.
The goal is to deploy version of scaleUp lambda that ignores this label, and open a pytorch PR requesting this label. This job will then be queued and never be picked up, until (hopefully) scaleUpChron lambda deploys a runner for it.
After the testing, we can revert this commit.
> Adds linux.4xlarge.for.testing.donotuse for testing

- torchci/clickhouse_queries/master_commit_red_avg/params.json
- torchci/clickhouse_queries/master_commit_red_avg/query.sql
- torchci/lib/clickhouse.ts
Main change is separating out the workflow run, workflow job, and push join so that workflow run and push get joined first, then workflow run and workflow job.  I don't really understand how this leads to less rows read since the filtering remains the same but I guess it's a join thing.
Most other changes are just making it look a bit nicer with things like "in" instead of casing and countIf.  I don't think these impact performance that much
I think sql fluff errors silently on this file
```
> python -m torchci.clickhouse_query_perf --head HEAD --base origin/main --perf --query master_commit_red_avg --results --perf                                                                ✔  forpytorch Py  10:03:31 AM 
Gathering perf stats for: master_commit_red_avg
Num tests: 2
Num times: 10 …
```
> [CH] Improve master_commit_red_avg query perf

- .github/actions/setup-binary-builds/action.yml
- .github/workflows/test_build_wheels_linux_python_versions.yml
We recently noticed that v2.1.1 always uses x86 miniconda even on arm64 macOS runners. [v3.1.1](https://github.com/conda-incubator/setup-miniconda/releases/tag/v3.1.1) includes a fix to support ARM runners.
We use the "latest" version of `miniconda-version` since the [version requires specifying the os and arch](https://github.com/conda-incubator/setup-miniconda/blob/142632f154bced74dde05dfc628e82581df045ac/action.yml#L37-L43) — it's just easier to use latest.
Tested this branch in:
https://github.com/pytorch/executorch/actions/runs/14092157997/job/39471257525?pr=9647
> Update setup-miniconda to 3.1.1

- torchci/clickhouse_queries/weekly_force_merge_stats/params.json
- torchci/clickhouse_queries/weekly_force_merge_stats/query.sql
- Optimize the weekly_force_merge_stats query performance by ~25%
- Maintain identical query output and behavior
1. Reordered time filters for earlier filtering
2. Used startsWith() instead of LIKE for URL prefix matching
3. Added pre-filtering of tables before JOIN operations
4. Simplified column references
- Verified query produces identical output hash (865c23a422cbcf2a3b53ea4d94c38ab656f5e8357e459b1c35bb2d8e9d26a559)
- Reduced average execution time:
```
+------+----------+-----------+-------------+---------------+-----------+------------+-------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change |  Avg Mem  |  Base Mem  |  Mem Change | % Mem Change |
+------+----------+-----------+-------------+---------------+-----------+------------+-------------+----- …
```
> Optimize weekly_force_merge_stats query performance

- tools/torchci/clickhouse_query_perf.py
Now:
```
/clickhouse_query_perf.py --query flaky_workflows_jobs --perf --times 1 --base HEAD
Using unstaged changes for --head
Gathering perf stats for: flaky_workflows_jobs
Num tests: 5
Num times: 1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.26s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ …
```
> Fix `clickhouse_query_perf.py` crash when all samples fail

- tools/torchci/clickhouse_query_perf.py
1. Instead of relying on fixed delay for `system.query_log` population, do a periodic polling. 
2. Add `event_time` filter to make stats query faster
on average, cuts waiting time by half
> clickhouse_query_perf: remove wait-time argument in favour of polling

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/scale-up.tf
- terraform-aws-github-runner/modules/runners/variables.tf
- terraform-aws-github-runner/variables.tf
As noted in [this](https://github.com/pytorch/test-infra/issues/6473) issue, there is a concurrency problem between tryReuse on scaleUp and scaleDown.
This PR addresses this by making sure `tryReuse` will not use 'stale' runners (older than a certain amount), and scaleDown will only remove the ones older than a certain time (logic was already implemented). 
Note that for this PR to properly work, it is expected that the TF variable `minimum_running_time_in_minutes` to be increased. I believe ideally 45 minutes or more.
> [ALI] Fix concurrency issues for tryReuse on scaleUp

- terraform-aws-github-runner/modules/runners/scale-up-chron.tf
- terraform-aws-github-runner/modules/runners/scale-up.tf
`scaleUpChron` lambda requires the same environment variables as `scaleUp` lambda. But by mistake that wasn't the case.
This PR simply make sure that all relevant environment variables are correctly set.
> Fix scaleUpChron environment variables

- torchci/clickhouse_queries/flaky_workflows_jobs/params.json
- torchci/clickhouse_queries/flaky_workflows_jobs/query.sql
1. Pre-filtering tables before joins:
- Added filtering conditions to the workflow_run subquery before joining with workflow_job
- Reduced data volume by filtering early rather than after joins
2. Simplified data structure:
- Separated the original CTE into two steps (dedups_wo_push and latest_attempts)
- The push table is joined only after initial filtering, reducing join complexity
3. Optimized conclusion handling:
- Replaced string comparisons with numeric codes (0 for success, 1 for failure, 2 for other)
- This improves comparison performance in window functions
4. Improved partitioning:
- Changed partition keys from concatenated string "fullname" to separate workflow_name and job_name columns
5. Added test cases:
- Added specific test parameters to params.json for validation testing …
> Optimize flaky_workflows_jobs CH query

- torchci/clickhouse_queries/issue_query/params.json
- torchci/clickhouse_queries/issue_query/query.sql
1. Replacing ARRAY JOIN with arrayExists() function
2. Filtering directly on the nested labels array using the function
```
./clickhouse_query_perf.py --query issue_query --perf --times 3 --base HEAD
+------+----------+-----------+-------------+---------------+-----------+--------------+--------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change |  Avg Mem  |   Base Mem   |  Mem Change  | % Mem Change |
+------+----------+-----------+-------------+---------------+-----------+--------------+--------------+--------------+
|  0   |   558    |    576    |     -18     |       -3      | 479307788 |  1089064486  |  -609756698  |     -56      |
|  1   |   445    |    573    |     -128    |      -22      | 477587555 |  1038871736  |  -561284181  |     -54      |
|  2 …
```
> Optimized issue_query

- .github/actions/pull-docker-image/action.yml
Test: https://github.com/pytorch/pytorch/actions/runs/14118741506/job/39554959976?pr=149536#step:9:44
Not really sure why the prints and commands are interleaved
> Print size of docker image

- .github/workflows/build_wheels_linux.yml
- Some repos (e.g. FBGEMM) can build multiple targets (i.e. packages with different names and functionality altogether, such as FBGEMM-GPU vs FBGEMM-GPU-GenAI), but there is no generic mechanism inside Nova to specify which target to build other than `CU_VERSION` environment variable, which is intended for target variants.  As such, BUILD_TARGET is provided as an environment variable to the Nova build scripts so that it can be leveraged for specifying a build target if needed
> [torch-infra] Support multiple build targets

- torchci/clickhouse_queries/experiment_rollover_percentage/query.sql
Experiment rollout percentage on hud was returning wrong numbers for some cases/hours.
Fixes performed:
* uses `created_at` both for bucket interval AND for for selection of days of reference. Not sure why one is created and another started. Seems more reasonable to query by jobs 'created';
* There was a bug on matching for experiment, the LIKE statement matched only `lf.experiment.runner` because of the preceding `%.`. A regex match is more correct as it can even leverage the existence of multiple experiments;
* Instead of grouping per `job_name`, `workflow_name`, `label` on `success_stats`. I create a reference column for the runner type (ignoring LF/Meta status) and group by `bucket` `label_ref` and `is_ephemeral_exp`. This correctly counts the instances;
* Removed the check of group …
> [HUD] fix query for experiment returning nonsensical numbers

- torchci/lib/JobClassifierUtil.ts
- torchci/lib/fetchHud.ts
- torchci/lib/types.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Change the option that merges lf with non lf columns to also merge ephemeral and non ephemeral columns
old:
new:
> [HUD] Merge ephemeral job columns on HUD with their non ephemeral counterparts

- tools/scripts/generate_binary_build_matrix.py
Cuda 12.6 aarch is not supported in Release 2.7. We release 12.8 aarch
> [Cherry-Pick] Remove cuda 12.6 aarch (#6409) to release 2.7

- tools/analytics/get_s3_bucket_sizes.py
This code was used when recently analyzing our S3 buckets to see which ones were the largest and may have room for optimization (resulting in us setting a new lifecycle policy: https://github.com/pytorch-labs/pytorch-gha-infra/pull/626) 
What it does:
* It gets the size of each bucket using CloudWatch, which is much faster than checking directly in S3. The latter iterates over every item in the bucket and can take hours to complete.
* It sorts the output to show the largest buckets.
Checking in the code in case we want to use it again
Output looks like this (dummy data below):
```
> python bucket_size_metrics.py
🔍 Fetching S3 bucket list...
✅ Found 7 buckets. Fetching storage metrics...
(1/7): Bucket marketing-assets
💿 Storage used: 100.0 GB
(2/7): Bucket devops-tools
💿 Storage used: 50.0 …
```
> Script to get sizes of all s3 buckets

- torchci/lib/bot/cliParser.ts
- torchci/test/cliParser.test.ts
I've been seeing people often try to use --into instead of --onto when using the PyTorch bot's cherry-pick command, as both parameters are semantically reasonable. 
This change adds --into as an alias for the --onto parameter, allowing users to use either version without getting an error.
The implementation leverages the argparse library's ability to have multiple option strings for the same argument. Added tests to verify that both parameter versions work correctly.
> [BE] [Bot] Add --into as an alias for --onto in cherry-pick command

- torchci/lib/bot/autoLabelBot.ts
- torchci/test/autoLabelBot.test.ts
In addition to "reland", also add the ci-no-td label to PRs that have "revert" in the title
> [ez][bot] Add ci-no-td label on PRs titled revert

- torchci/components/JobLinks.module.css
Replaced hardcoded colors with CSS variables in JobLinks.module.css to ensure buttons are properly visible in dark mode. This improves contrast and readability of 'Mark unstable job' and related buttons.
Fixes https://github.com/pytorch/test-infra/issues/6500
Original
New
> [HUD][dark-mode]: Update JobLinks buttons to use theme variables for dark mode visibility

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
Forgot to remove LRU_CACHE, 
this makes threads share same session of clickhouse-client, which should not allow.
Error:
```
clickhouse Attempt to execute concurrent queries within the same session.
Please use a separate client instance per thread/process.
```
> [Remove cache] Fix concurrent issue

- torchci/lib/JobClassifierUtil.ts
Previously they were under periodic, now they're under inductor periodic
old
new
> [ez][HUD] Move inductor periodic workflows into its own group

- .github/workflows/validate-linux-binaries.yml
Set MATRIX_GPU_ARCH_VERSION  to required cuda version. Fixes failure in the validations
> [validations] Set MATRIX_GPU_ARCH_VERSION for amazon linux 2023 test

- .github/workflows/validate-linux-binaries.yml
Logs produced by https://github.com/pytorch/test-infra/actions/runs/14177205860/job/39714879789#step:15:9806 are too long to be viewed, because it preserves progress bar output, which nobody really cares about once the tests were run
> [BE] Do not pollute logs with progress bars

- aws/lambda/oss_ci_job_queue_time/lambda_function.py
- aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
[Bug]
when  call github apiwith path parameter. Only commits containing this file path will be returned (have changes)
`all_commits = self.repo.get_commits(path=self.path)`
This causes issue since the config file fetch will always return empty if there is no cofig file change happen after our time to take snapshot.
Proposal Change
1. find the first commit that is later than start_time -> found, fetch config
2. if nothing find, fetch commits that are before/equal to commit time  -> get the closest commit and fetch config
> [Queue Time Histogran][Fetch Github Config File -> find closest commit config file

- tools/pkg-helpers/pytorch_pkg_helpers/macos.py
We are trying to bump the torchao pin in ExecuTorch, but CI jobs fail: https://github.com/pytorch/executorch/pull/9947.
In particular this job fails: https://github.com/pytorch/executorch/actions/runs/14321828652/job/40140080161?pr=9947
The root cause is "/Users/runner/work/executorch/executorch/pytorch/executorch/third-party/ao/torchao/experimental/../../torchao/experimental/ops/memory.h:22:34: error: 'aligned_alloc' is only available on macOS 10.15 or newer [-Werror,-Wunguarded-availability-new]"
This is because the test infra defines the "export MACOSX_DEPLOYMENT_TARGET=10.13".
> Update MACOSX_DEPLOYMENT_TARGET 10.13 -> 10.15

- tools/device-farm-runner/run_perf_workflow.py
Request from Executorch team to run android-perf or apple-perf workflows via commandline 
https://github.com/pytorch/executorch/actions/workflows/android-perf.yml
https://github.com/pytorch/executorch/actions/workflows/apple-perf.yml
HOW TO: 
1. Make sure you have your GITHUB_TOKEN set (classic personal access token, not fine-grained) (`export GITHUB_TOKEN=<YOUR_TOKEN>`)
2. run  `python run_perf_workflow.py` with either `--android` or `--ios` as a required argument 
3. use `--help` to see other optional arguments (`--branch, --models, --devices, --benchmark-configs`)
> Commandline option for github workflow to run android and apple perf workflows

- .github/scripts/validate_binaries.sh
1. This fixes Macos arm64 validations I am seeing here:
- Failure: https://github.com/pytorch/test-infra/actions/runs/14369578394/job/40289986253
- Success run: https://github.com/pytorch/test-infra/actions/runs/14387119603
3. Adds numpy (optional) depenency validations to binaries with python =<3.12
> [validation] Fix timing out macos validations, add numpy 1.26 validations for python <=3.12

- torchci/components/GroupJobConclusion.tsx
- torchci/lib/jobUtils.ts
> Hud: mark groups with successfully cancelled jobs as warnings

- .github/actions/setup-nvidia/action.yml
This is reported by @jainapurva from TorchAO https://github.com/pytorch/ao/actions/runs/14461343872/job/40554407661 trying to upgrade CUDA from 12.4 to 12.6 https://github.com/pytorch/ao/pull/1962.  It turns out that the NVIDIA driver that we are currently using `550.54.15` is too old.
I grab the latest production driver from NVIDIA which should satisfy not only CUDA 12.6 but 12.8 too:
* https://docs.nvidia.com/cuda/archive/12.8.0/cuda-toolkit-release-notes/index.html
This should help fix the issue on AO, also need to update this driver in a couple of other places too.
* Manual.  I install the driver manually and can start the container fine without any issue `docker run --gpus all -it pytorch/almalinux-builder:cuda12.6 /bin/bash`
* …
> Upgrade NVIDIA driver for CUDA 12.6+

- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Ensures that one review with changes requested can block other approvals from triggering a merge workflow.
This is a feature request from maintainers to ensure that reviews are addressed prior to merging.
> mergebot: Block PR merges if changes requested

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
As part of the infra stress test, we want to introduce the capability of running code experiments leveraging Redis.
This also introduce the checks we are planning to perform for the infra stress test.
> Add experiment/stress test code

- .github/actions/calculate-docker-image/action.yml
Lets you prefix the tag with a custom string, also lets you put a custom path to the build script.
Tested on https://github.com/pytorch/pytorch/pull/151354
custom tag prefix:
Usually docker image names look like docker-image-name:folderhash
This lets you name it docker-image-name:custom-tag-prefix-folderhash
This is used in https://github.com/pytorch/pytorch/pull/150558/files and can help with the issue where we keep needing to make new ecr repositories
Alternate syntax: just include the tag in the docker image name input and parse it out
custom path to build script:
Usually its just build.sh, but https://github.com/pytorch/pytorch/pull/150558/files has a subfolder but wants to still use .ci/docker folder as the folder hash
> Custom script path and tag prefix for calculate docker image

- torchci/lib/bot/autoLabelBot.ts
package is not worked on today + has no real owner so most changes are not user facing (BE). we should stop automating adding such a label
> Remove package/deploy from autolabelbot.ts

- torchci/clickhouse_queries/hud_query/params.json
- torchci/clickhouse_queries/hud_query/query.sql
Utilizing the new dict + aliased column approach to eliminate expensive join.
perf
```./clickhouse_query_perf.py --query hud_query --perf --times 5 --base HEAD
Using unstaged changes for --head
Gathering perf stats for: hud_query
Num tests: 5
Num times: 5
Waiting for metrics to populate, please be patient
+------+----------+-----------+-------------+---------------+----------+-----------+------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change | Avg Mem  |  Base Mem | Mem Change | % Mem Change |
+------+----------+-----------+-------------+---------------+----------+-----------+------------+--------------+
|  0   |   134    |    415    |     -281    |      -68      | 38258808 | 148456303 | -110197495 |     -74      |
|  1   |   155    |    347    |     -192 …
```
> [CH] optimize hud_query by eliminating joins

- torchci/clickhouse_queries/master_commit_red_jobs/params.json
- torchci/clickhouse_queries/master_commit_red_jobs/query.sql
```
./clickhouse_query_perf.py --query master_commit_red_jobs --perf --times 3 --base HEAD
Using unstaged changes for --head
Gathering perf stats for: master_commit_red_jobs
Num tests: 2
Num times: 3
+------+----------+-----------+-------------+---------------+-----------+------------+------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change |  Avg Mem  |  Base Mem  | Mem Change | % Mem Change |
+------+----------+-----------+-------------+---------------+-----------+------------+------------+--------------+
|  0   |   987    |    9401   |    -8414    |      -90      | 271203271 | 803400038  | -532196767 |     -66      |
|  1   |   733    |   10425   |    -9692    |      -93      | 323819095 | 1255600040 | -931780945 |     -74      | …
```
> [CH] optimize master_commit_red_jobs by eliminating join and adding pre-filtering

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Add logging to better be able to track why scale down events occurred.
Specifically tracks the following kinds of issues:
* Calls out the exact reason why a runner might be considered idle for long enough to be decomissioned
* Highlights if an active runner's EC2 instance is somehow lacking EC2 tags that mark it as being active
Part of follow up to sev https://github.com/pytorch/pytorch/issues/151669
> [Autoscaler] Add logging to better understand why a scale down occurred

- torchci/lib/JobClassifierUtil.ts
The job name is so long its getting cut off 
so the regex is returning false.
This is a bad hack which I figure out what to do with the job name so I don't have to stare at those jobs in the normal periodic group of the hud page
> [HUD] Hack for rerun disable tests and mem leak regex

- s3_management/manage.py
By manually adding data-requires-python="&gt;=3.10" there
TODO: Extract this info from metadata and add it for all relevant packages
Test plan: Run `python3 manage.py --do-not-upload whl` and check generated indexes, for example in whl/cu128/networkx/index.html 
Fixes https://github.com/pytorch/pytorch/issues/152191
> [S3] Fix up networkx index for UV

- torchci/components/NavBar.tsx
- torchci/pages/job_cancellation_dashboard.tsx
Adds first Grafana dashboard as iframe in HUD - related to job cancellation counts over time
- embeds an iframe pointing to a cloudfront in front of grafana
- adds theme based on dark theme setting in HUD
See https://torchci-git-wdvr-jobcancellationdashboard-fbopensource.vercel.app/job_cancellation_dashboard
> job cancellation dashboard

- terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
- tools/device-farm-runner/run_on_aws_devicefarm.py
Adding 2 new fields in the job report:
* `is_private_instance`
* and `instance_arn`.  AFAICT, this field is only available for private devices and it contains the device ID showing on AWS
> Add device type (public, private) and id

- torchci/clickhouse_queries/master_commit_red_percent/params.json
- torchci/clickhouse_queries/master_commit_red_percent/query.sql
perf:
```
./clickhouse_query_perf.py --query master_commit_red_percent  --perf --times 1 --base HEAD
+------+----------+-----------+-------------+---------------+-----------+------------+-------------+--------------+
| Test | Avg Time | Base Time | Time Change | % Time Change |  Avg Mem  |  Base Mem  |  Mem Change | % Mem Change |
+------+----------+-----------+-------------+---------------+-----------+------------+-------------+--------------+
|  0   |   1164   |    5585   |    -4421    |      -79      | 160555724 | 7544036697 | -7383480973 |     -98      |
|  1   |   2992   |    5483   |    -2491    |      -45      | 516092615 | 7858494950 | -7342402335 |     -93      |
+------+----------+-----------+-------------+---------------+-----------+------------+-------------+--------------+ …
```
> [ch] optimize master_commit_red_percent query

- tools/scripts/fetch_latest_green_commit.py
- tools/torchci/clickhouse.py
- tools/torchci/tests/test_ch_query.py
- torchci/lib/clickhouse.ts
- torchci/lib/drciUtils.ts
- torchci/lib/fetchHud.ts
- torchci/lib/fetchIssuesByLabel.ts
- torchci/package.json
- torchci/pages/api/drci/drci.ts
- torchci/yarn.lock
As evident from the [hud](https://hud.pytorch.org/query_execution_metrics), issues_query is biggest cumulative time and memory hoggers, simply because it runs too frequently (≈27 times / minute)
Since there are only three parameter values that dominate the executions:
- ci: sev 
- skipped
- unstable
it makes sense to cache this query.
This PR:
* adds parameter to our ch apis to `use_query_cache` (1 minute TTL by default)
* adds a python test (intended to be run locally, as we don't expose CH credentials in CI)
* caches `issues_query` in several places
* updates the ch client node package (the old one didn't expose `use_query_cache`)
---
The intended effect of using query cache is to drop time and memory to 0 for cache hits.
> [hud][ch][drci] add api to cache ch queries + cache issues query

- torchci/components/NavBar.tsx
Because whatever ranges to select it crashes
But if one wants to experience crashes, page is still accessible via https://hud.pytorch.org/torchbench/userbenchmark
Fixes https://github.com/pytorch/test-infra/issues/6567 thru out-of-sight-out-of-mind incantation
> Delete TorchBench from NavBar

- torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
I made a questionable decision when appending the `private` suffix to the device name, i.e. `Apple iPhone 15 (private)`.  The problem here is that a device name already have another suffix in the OS version, i.e. `iOS 18.0`.  Take `Apple iPhone 15 (private) (iOS 18.0)` as an example, it would match both `Apple iPhone 15 (private) (iOS 18.0)`  and `Apple iPhone 15 (iOS 18.0)` because both start with `Apple iPhone 15`.
In hindsight, I should have use a prefix, i.e. `[private] Apple iPhone 15` to indicate a private device.  But as the new name has sticked around for sometimes, it's easier to just tweak the dashboard instead IMO.
https://hud.pytorch.org/benchmark/llms?startTime=Thu%2C%2024%20Apr%202025%2001%3A05%3A16%20GMT&stopTime=Thu%2C%2001%20May%202025%2001%3A05%3A16%20GMT&granularity=day& …
> Separate private and public devices on benchmark dashboard

- torchci/components/benchmark/tritonbench/TimeSeries.tsx
Explicitly exclude low_mem_dropout as its tflops is very low. We will remove this workload from tflops as it is memory bounded and does not make sense to calculate its tflops.
Before:
After:
> [tritonbench] Exclude low_mem_dropout from the data to avoid zeros.

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
The code currently calls:
```
callback(null);
```
before
```
await metrics.sendMetrics();
```
This causes no metrics to actually be sent, unless a timeout or exception happens. This fixe just addresses this to make sure metrics are being sent.
> Send metrics before callback() for scaleUpChron

- torchci/lib/searchLogs.ts
I noticed it wasn't working on tutorials because the url is hardcoded to be one that assumes it is pytorch/pytorch.  Instead, just use the job.logUrl field
> [ez][HUD] Expand log search to other repos

- tools/torchci/clickhouse_query_perf.py
- torchci/clickhouse_queries/test_time_per_class/params.json
- torchci/clickhouse_queries/test_time_per_class/query.sql
- torchci/clickhouse_queries/test_time_per_class_periodic_jobs/params.json
- torchci/clickhouse_queries/test_time_per_class_periodic_jobs/query.sql
- torchci/clickhouse_queries/test_time_per_file/params.json
- torchci/clickhouse_queries/test_time_per_file/query.sql
- torchci/clickhouse_queries/test_time_per_file_periodic_jobs/params.json
- torchci/clickhouse_queries/test_time_per_file_periodic_jobs/query.sql
The update test times workflow was failing due to OOMing on the periodic queries https://github.com/pytorch/test-infra/actions/runs/14788036069/job/41521901353
So I tried to make some improvements:
* Get rid of join with workflow_run table: all information needed from it can actually be gotten from workflow_job table and should be the same
* Get rid of intermediate workflow query: reason is same as above
* Get rid of final: push doesn't really need it, I expect that it's always the same.  The one on workflow job should be ok due to either the group by or the distinct depending on which part of the query
Correctness: 
* non periodic stayed the same
* periodic queries OOMed on base so couldn't actually test.  I did my best to do the minimal changes to get rid of the OOM and check results …
> Improvements to test times queries

- torchci/clickhouse_queries/get_workflows_for_commit/params.json
- torchci/clickhouse_queries/get_workflows_for_commit/query.sql
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/test/mergeCommands.test.ts
Reverts pytorch/test-infra#6604
ret value of queryclickhouse is list of jsons, not list of strs
[ workflow_name: "pull"] not ["pull"]
merge is broken atm, probably due to this
> Revert "[Mergebot] Adding ciflow/pull in PR without pull and lint workflows"

- torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Context: https://github.com/pytorch/pytorch/issues/153155
> Temporarily shrink the interval we wait for during chaos testing

- torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Was a temporary change during testing.  Now it's time to revert this back
> Revert "Temporarily shrink the interval we wait for during chaos testing"

- terraform-aws-github-runner/modules/runners/variables.tf
Our auto-healing scale up chron lambda currently kicks in every 30 minutes, and looks for jobs that have been queuing for at least 30 mins.  This means that a job could potentially be queuing for 59 mins before it is healed.
We want this fallback pattern to be used for jobs that have been queuing for 30 mins, so we ideally want to get jobs retried when they've been queued for exactly 30 mins.  
> **Aside: Why not retry jobs with if they've been queued for even 1 minute?** 
> In order to avoid double-provisioning for a given job, we want to make sure we've given the regular scale-up lambda sufficient time to provision the instance. When a job is queued, it can take ~5 minutes for an instance to be provisioned, and if there are minor infra hiccups that the regular retry logic can catch, it …
> Trigger scale-up-cron lambda more frequently

- .github/actions/setup-binary-builds/action.yml
- tools/scripts/generate_binary_build_matrix.py
Trying to fix 3.13t build failure : https://github.com/pytorch/vision/actions/runs/14936575189/job/41965300242
Log:
```
+ conda install -y conda=24.7.1 conda-libmamba-solver=24.1.0
Channels:
- conda-forge
Platform: linux-aarch64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
LibMambaUnsatisfiableError: Encountered problems while solving:
- package conda-libmamba-solver-24.1.0-pyhd8ed1ab_0 requires libmambapy >=1.5.6,<2.0a0, but none of the providers can be installed
Could not solve for environment specs
The following packages are incompatible
├─ conda-libmamba-solver =24.1.0 * is installable and it requires
│  └─ libmambapy >=1.5.6,<2.0a0 * with the potential options
│     ├─ libmambapy [1.5.10|1.5.11|...|1.5.9] would require
│ …
```
> Fix python 3.13t builds on aarch64

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
As the experiment for ephemeral is successful, we should now start the cleanup process.
The plan is as follows:
* [THIS PR] migrate all base runner types to be ephemeral;
> Make every runner in scale-config.yml to be ephemeral

- s3_management/manage.py
The #6612 had a typo missing comma after ``onemkl_sycl_rng``
> Fix typo after #6612

- .github/scripts/install_xpu.bat
- .github/workflows/build_wheels_windows.yml
Address https://github.com/pytorch/pytorch/issues/151097, followed by https://github.com/pytorch/pytorch/pull/151899
> [BE] Upgrade XPU support package to 2025.1 in Windows CICD

- torchci/components/hud.module.css
No code changes, but the column width of the jobs became smaller.  I think this is a change in my browser (google chrome) or something, since if you go back to old deployments (ex https://vercel.com/fbopensource/torchci/6s4pLsAQTjcmokPfZqQkWYdckXsJ from March) it is also present, even though I only started seeing it this week.
This changes the columns to be wider
Current:
New:
on safari and firefox the width still looks normal, and this pr doesn't seem to change it
> [ez][HUD] Make main page column width wider

- torchci/clickhouse_queries/recent_pr_workflows_query/params.json
- torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
This is the main query used by dr ci to get info on jobs.  It some times OOMs when querying:
```
(while reading column head): (while reading from part ... in table default.pull_request...
```
Remove final for push because it is not needed.
Remove final for pull_request in favor of argmax.
This brings down the time and the memory needed
```
~/zzzzzzzz/test-infra/tools  @c6e2eb46 *129 !2  python torchci/clickhouse_query_perf.py --query recent_pr_workflows_query  --results --perf  --base origin/main --strict                                                                                 ✔  1m 57s  forpytorch Py  09:23:07 AM 
Using unstaged changes for --head
Gathering perf stats for: recent_pr_workflows_query
Num tests: 1
Num times: 10 …
```
> [ez][CH][drci] Improve recent_pr_workflows_query perf

- .github/actions/setup-nvidia/action.yml
This pull request updates the `.github/actions/setup-nvidia/action.yml` file to enhance the NVIDIA container setup process by including additional dependencies for better compatibility and functionality.
Enhancements to NVIDIA container setup:
* Updated the `yum install` command to include additional packages: `libnvidia-container-tools-1.16.2`, `libnvidia-container1-1.16.2`, and `nvidia-container-toolkit-base-1.16.2`, alongside the existing `nvidia-docker2` and `nvidia-container-toolkit-1.16.2`. This ensures a more complete installation of NVIDIA container tools.
> ci: Pin more nvidia-container dependencies

- .github/actions/setup-nvidia/action.yml
follow up on https://github.com/pytorch/pytorch/issues/153760
We run a test container to see if `nvidia-smi` is available with `--gpus all`
> Check if nvidia-container-toolkit is installed correctly

- s3_management/manage.py
To make https://github.com/pytorch/pytorch/pull/153750 pass ExecuTorch tests
> Keep nightly dev20250310 for ExecuTorch

- s3_management/manage.py
Fixes error after #6639
Failure: https://github.com/pytorch/test-infra/actions/runs/15139622052/job/42565306129
```
+ python s3_management/manage.py whl/nightly
File "/__w/test-infra/test-infra/s3_management/manage.py", line 218
KEEP_NIGHTLY_PACKAGES_FOR_EXECUTORCH = {datetime(2025, 03, 10, 0, 0)}
^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```
> Fix s3 update workflow after: #6639

- aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
- torchci/lib/bot/webhookToDynamo.ts
- torchci/test/wehookToDynamoBot.test.ts
only merge this after [pytorch-labs/pytorch-gha-infra#646](https://github.com/pytorch-labs/pytorch-gha-infra/pull/678) has been merged & deployed
Goal is to keep track of when issues are labeled or unlabeled for statistics purposes.
> pr label event table in dynamo

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
- torchci/package-lock.json
- torchci/package.json
- torchci/yarn.lock
Fix the bug to use the first row of the chartData for row rendering, instead find the maximum length one.
Introduce download the data table as excel sheet for convinience
Demo:https://torchci-git-weridtableerrro-fbopensource.vercel.app/benchmark/llms?startTime=Wed%2C%2014%20May%202025%2000%3A42%3A08%20GMT&stopTime=Wed%2C%2021%20May%202025%2000%3A42%3A08%20GMT&granularity=day&lBranch=main&lCommit=4a89327c2ae5767e0755e1d6f3a9fae58da2cebf&rBranch=main&rCommit=da62d5f2badbfbb793ed08366663eba59ece3da3&repoName=pytorch%2Fexecutorch&benchmarkName=&modelName=meta-llama%2FLlama-3.2-1B-Instruct-QLORA_INT4_EO8&backendName=llama3_qlora&modeName=inference&dtypeName=&deviceName=Samsung%20Galaxy%20S22%205G%20(Android%2013)&archName=All%20Platforms
Demo for excel sheet download
> [Improvement] fix row length bug + enable download as excel sheet

- torchci/clickhouse_queries/cost_job_per_instance_type/params.json
- torchci/clickhouse_queries/cost_job_per_instance_type/query.sql
- torchci/clickhouse_queries/duration_job_per_instance_type/params.json
- torchci/clickhouse_queries/duration_job_per_instance_type/query.sql
- torchci/pages/cost_analysis.tsx
Allow the cost dashboard to be filtered by instance type as well as well as the runner_type (for AWS runners) - this allows for an easier comparison with AWS billing dashboard
> cost dashboard: group by instance type (aws runners)

- torchci/pages/cost_analysis.tsx
Add NA as option for most fields in the cost dashboard. This is useful for items that are wrongly classified (in case of bugs such as the one with the experimental prefixes), but also for items that have a duration, but not a cost.
> Add NA as option for most fields in the cost dashboard #6655

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
This would allow us to test on AWS Graviton4 processors. 
Our intention is to add this alongside the existing AWS Graviton3 processors for unit tests.
> Add Amazon EC2 M8g Instances

- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/pages/cost_analysis.tsx
Increase the padding of the legend to not overlap with the graphs in the cost dashboard
> [BE] fix legend overlapping graph

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/lib/flakyBot/singleDisableIssue.ts
- torchci/lib/flakyBot/utils.ts
- torchci/test/common.ts
- torchci/test/flakyBotTests/flakySingleIssue.test.ts
- torchci/test/verifyDisableTestIssue.test.ts
Most of this is moving code around and changing APIs for things
Only major change in e2e behavior is that the fall back for invalid disable test title is to assume its a job name and will attempt to disable the weirdly named job.  Previously it would say the title is malformed for a test
Changes:
* Fall back thing mentioned above
* API/moving code around ex
* Move module label logic moved to other file
* Move parsing of issue body into other file
* Testing
* I converted a lot of tests to be more integration style tests so we change change the api more often and tests will still be valid
> [bots] Change verify disable issues in prep for handling aggregate issues

- torchci/lib/bot/verifyDisableTestIssueBot.ts
- torchci/lib/flakyBot/aggregateDisableIssue.ts
- torchci/lib/flakyBot/singleDisableIssue.ts
- torchci/pages/api/flaky-tests/disable.ts
- torchci/test/flakyBotTests/flakyAggregateIssue.test.ts
- torchci/test/flakyBotTests/flakyBotIntegration.test.ts
- torchci/test/flakyBotTests/flakyBotTestsUtils.ts
- torchci/test/flakyBotTests/flakyBotUtils.test.ts
- torchci/test/verifyDisableTestIssue.test.ts
Requires changes in https://github.com/pytorch/test-infra/pull/6661, please review + merge that one first
Allow flakybot to make aggregate issues, update them, and close them. Also allow the verification bot that comments on each issue to do aggregate issues.
Format should match the one in https://github.com/pytorch/test-infra/pull/6045
We should really make the verification script just the same as the script that updates the json...
No platform module labels are going to be added
There's some weirdness with closing issues / removing tests that are no longer flaky because I think it's hard (read: possible, probably annoying) to determine which test is responsible for an issue getting updated and which are old enough to be removed 
Threshold is 10
> [bots] Allow flakybot to make aggregate issues

- aws/lambda/README.md
Currently we move some of our lambda function in test-infra/aws/lambda, and maintain the infra resources in https://github.com/pytorch-labs/pytorch-gha-infra/.
It's not very straightforward process, so add a guidance:
This readme is based on my experience setup lambda for [oss_ci_job_queue_time]( https://github.com/pytorch/test-infra/tree/main/aws/lambda/oss_ci_job_queue_time),
> [BE] Add guidance to set up new lambda in test-infra

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/variables.tf
- terraform-aws-github-runner/variables.tf
Brings down the minimum_running_time_in_minutes that was earlier increased in https://github.com/pytorch/test-infra/pull/6477
In order to do so, it required a few changes:
1. Remove the check to always treat minimumRunningTimeInMinutes as 5 less than it actually was.  This logic had likely been added to account for the 5 minutes it can take for a runner to be refreshed.
2. Instead, add a buffer of 5 mins to the scale down cron job for when 
3. Handle the case when both EC2 tags, ebsVolumeReplacementRequestTimestamp and ephemeralRunnerFinished, are set during scale down (which happens in a narrow window during refresh)
> [Ephemeral Scale Downs] Reduce min runtime and better track buffer time

- torchci/components/TimeUtils.tsx
- torchci/components/metrics/panels/TimeSeriesPanel.tsx
- torchci/components/metrics/panels/TimeSeriesTable.tsx
- torchci/pages/cost_analysis.tsx
always UTC, not local, to avoid dates being reported as the wrong date
> fix timezone in cost dashboard 

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
These were configurations that had been added back in the days when our autoscaler had to support multiple base linux OS's.  Given that we only use Amazon Linux 2023 now we don't need them any more
A breakdown of the removed entries:
* Some of the removed configs were to support Amazon Linux 2, such as:
* The amz vs amz2023 checks
* The configurable package manager...which was inconsistently used)
* I suspect the nvidia-docker tools being in a conditional was from when we used Ubuntu (based on [this old commit](https://github.com/pytorch/test-infra/commit/fd29941576c2388d5b51f5316cb2484130101869) that added the conditional). Apparently Ubuntu didn't require the same set of dependencies to be installed. 
None of that is needed now, so removing those lines to clean up this file
> [BE] Remove old cruft from user-data.sh file

- torchci/clickhouse_queries/disabled_test_labels/params.json
- torchci/clickhouse_queries/disabled_test_labels/query.sql
- torchci/lib/GeneralUtils.ts
- torchci/pages/disabled.tsx
A lot of small changes
* disabled_test_labels query is only called here and it always sets states: [], so I got rid of the param
* Added config as input for useClickHouseAPI
* Use useClickHouseAPI in disabled page - not sure if this is actually better or worse
* Use encodeParams to get the permalink
* Set query params for disabled_test_labels to be more restrictive.  Previously if you change the label selector or the date selector, the selectors would reload because disabled_test_labels thought it had to requery, but now it doesn't
* Same for the chart and the state, since state doesn't matter to the chart
* Move the state selector from above the chart to be above the table of tests since state doesn't matter to the chart (makes it more clear what things affect what to users)
* Use …
> [ez][HUD] Disabled tests page: Changes to query params and other small things

- torchci/components/additionalTestInfo/RerunInfo.tsx
Also stops displaying tests that got run multiple times but succeeded since it's not that helpful
Old
--------
New
> [HUD] additional test info - better ui for reruns/failures

- torchci/lib/clickhouse.ts
Kept getting
```
[2025-06-03T23:06:31.978Z][WARN][@clickhouse/client][Config] "host" is deprecated. Use "url" instead.
```
when developing locally
typescript says
```
(property) BaseClickHouseClientConfigOptions.host?: string | undefined
@deprecated
since version 1.0.0. Use [url](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) instead. A ClickHouse instance URL.
@default
```
Local seems normal?  Preview looks ok
> [ez][HUD] host -> url for clickhouse client

- torchci/clickhouse_queries/tts_duration_historical/query.sql
- torchci/clickhouse_queries/tts_duration_historical_percentile/query.sql
All the fields for workflow_run can be found in the workflow_job table except run attempt, but I don't really understand why we filter out run attempt so I just got rid of it
Also remove final because I don't think it matters that much when we filter for only stuff that have a completed_at date
I think TTS page was just broken before this due to OOM
> [CH][BE][ez] Make queries on TTS page faster by removing join

- .github/workflows/update_disabled_tests.yml
Missed a step in https://github.com/pytorch/test-infra/issues/6687 for uploading the json as an artifact so the next job could pick it up
Example failure https://github.com/pytorch/test-infra/actions/runs/15471922333/job/43558541041
> [ez][disabled tests] Fix historical records json not being uploaded to s3 in upload disable tests workflow

- .lintrunner.toml
- tools/self-hosted-runner-utils/clear_offline_runners.py
- tools/self-hosted-runner-utils/requirements.txt
We recently had an outage that required that we spin down all instances that were not actively connected to GitHub.
Requirements to run:
* Valid AWS credentials
* GITHUB_TOKEN with permissions to view self hosted runners for an organization
To run you can use:
```bash
pip install -r tools/self-hosted-runner-utils/requirements.txt
python3 tools/self-hosted-runner-utils/clear_offline_runners.py --dry-run pytorch
python3 tools/self-hosted-runner-utils/clear_offline_runners.py pytorch
```
This was used to remediate issues from https://github.com/pytorch/pytorch/issues/155265
> tools: Update clear_offline_runners to clear ec2

- tools/torchci/check_alerts.py
- tools/torchci/queue_alert.py
- tools/torchci/tests/test_check_alerts.py
Similar to https://github.com/pytorch/test-infra/pull/4966
> [queue alert] Close issue if too many comments

- tools/self-hosted-runner-utils/clear_offline_runners.py
I didn't actually run this...
If you query aws for the instances first and the gh runners second, then the gh runner information is more up to date, so you're slightly less likely to cancel jobs on runners that just got spun up?
> [ez] Clear offline runners: fetch from aws first

- aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
follow-up for https://github.com/pytorch/test-infra/pull/6742/files
Also removing the duplicate cudnn_subfolder name, CUDA 12 are all using the same cudnn scripts. 
cc @atalman
> Use 12.6.3 for CUDA 12.6 windows installation script

- terraform-aws-github-runner/modules/runners-instances/launch-template.tf
- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Installs Wiz Runtime Sensor on Linux runners during startup, building on https://github.com/pytorch/test-infra/pull/6739/. This adds a layer of security to our CI jobs and opens up a pathway for code scanning as well.
The wiz runtime sensor requires credentials that it gets from a secret who's name is passed in to the terraform module name.  For environments where that credential is not available, the installation is skipped.
Why only linux? Windows isn't yet supported by the wiz sensor (but is on the way)
Since it's important to make sure the runners can come online even if the wiz runtime sensor installation isn't possible,  this PR contains **multiple graceful failure protocols** to allow the runner to come online even if the agent cannot be installed:
1. If the secret arn was never …
> Install wiz sensor on linux runners

- torchci/lib/bot/cliParser.ts
The command was removed in #6749. This PR removes it from the help section.
cc @clee2000
> [pytorchbot] Remove reference to the `close` command

- torchci/components/githubIncident/GithubIncident.tsx
Purely a personal preference thing
Makes the gh incident banner more like the sev report banner
Old 
New
> [HUD] Make GH incident banner style closer to sev report style

- .github/workflows/update_test_file_ratings.yml
- tools/torchci/td/get_merge_base_info.py
Fix TD file ratings workflow
Example failure:
https://github.com/pytorch/test-infra/actions/runs/15731225202
* upgrade boto3
* make query faster/use less memory
* timezone api is getting deprecated, remove it
Testing:added trigger on push. I saw that the workflow started but it's pretty long so I didn't wait for the entire thing
Might be an issue wrt the timezone thing, I think the format changed
> [TD] Fix file ratings workflow: upgrade boto3, make query faster, timezone api deprecation

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
Windows.9xlarge was added by https://github.com/pytorch/test-infra/pull/6759 and currently not used
Memory optimized r5n.4xlarge add by https://github.com/pytorch/test-infra/pull/6774 is not enough trying with 8xlarge
Error: https://github.com/pytorch/pytorch/actions/runs/15758396612/job/44418951066?pr=156179
> Use windows.8xlarge.memory, remove unused instance windows.9xlarge

- .github/actions/upload-benchmark-results/action.yml
- .github/scripts/benchmarks/gather_runners_info.py
I reverted the first attempt because pip install failed with a memory error only on MI300 runners, for example https://github.com/pytorch/pytorch/actions/runs/15767425131/job/44447322381 (wut? maybe pip version on MI300 ROCm runner is too old).  So, let's try to use `rocminfo` instead.
I create a test PR to run this on ROCm https://github.com/pytorch/pytorch/pull/156468 with some MI300 jobs running at https://github.com/pytorch/pytorch/actions/runs/15772321806
The test looks ok now https://github.com/pytorch/pytorch/actions/runs/15772321806/job/44460624447#step:24:293
> [Reland] Fix gather_runners_info script on ROCm

- .github/actions/calculate-docker-image/action.yml
- .github/workflows/linux_job_v2.yml
We originally tried to simplify the number of parameters users had to pass in to linux_job_v2 by using the existence of the docker build script as a heuristic.
That worked for a while, but that heuristic is now starting to break.  If a repo has an unrelated docker build script located in `.ci/docker/build.sh`, we assume it wants to pull from our custom ECR path instead of docker hub.
Our ideal end state would now look like:
1. Have an explicit parameter that needs to be set if a repo wants to use our ECR registries instead of assuming the desire based on the existence of a specific file. We default to docker hub
2. Migration to this end state would include fix all existing domain repos that have that docker build file defined to pass in that parameter.
That migration requires many repos …
> Enable specifying whether or not to pull the docker image from ECR

- tools/analytics/github_analyze.py
Usage:
```
python github_analyze.py --analyze-missing-reverts-from-branch --repo-path ~/local/pytorch --remote upstream --branch release/2.8
Analyzing reverts in main branch not present in release/2.8 branch
Total commits in main but not in release/2.8: 62
Total commits in release/2.8 but not in main: 1
Found 8 revert(s) in main branch not present in release/2.8 branch:
================================================================================
Commit Hash: 029e2b05c225588098d3eba445fd04189691f77d
Author: PyTorch MergeBot <pytorchmergebot@users.noreply.github.com>
Date: 2025-06-25 06:05:40
Title: Revert "[Quant][CPU] fix fake_quantize_per_tensor_affine of inf values (#155109)"
Reverted GitHub Commit: 19ffb5e6f7606436249742b0f3efc0bab244dc55
Body Preview:     
This reverts commit …
```
> Add method to analyze reverts: analyze_reverts_missing_from_branch

- .github/workflows/build_wheels_macos.yml
Miniconda is required for M1 wheel builds
This action will, by default, activate an environment called test and not activate the base environment. This encourages the recommended practice of not installing workflow packages into the base environment and leaving it with only conda (and/or mamba).
> Add miniconda install=true to build_wheels_macos.yml

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
I had noticed that we were terminating instances 1 by 1 in the original code so this adds batching for terminateRunner calls in order to fix those performance bottlenecks.
As well during the termination we were deleting ssm parameters one by one so this also adds batching to the ssm parameter deletion as well.
Goal here was to implement the performance improvements with minimal changes.
This PR super-cedes #6725
> runners: Add batching for terminateRunner

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
Does the following:
* Removes ssm parameter cleanup from terminateInstances (will be a follow-up PR to add a termination policy to parameters)
* Removed double check for ghRunner calls (was causing performance bottlenecks
* NOTE: We will need to monitor removeGHRunnerOrg calls to see if those introduce another performance bottleneck + job cancellations (if they rise then we revert, dashboard: https://hud.pytorch.org/job_cancellation_dashboard)
> runners: More scale-down perf improvements

- torchci/pages/api/flaky-tests/disable.ts
10 is kind of high, IMO lowering it would be ok since its still annoying if there are >4 issues created at once that all seem related.  The restriction that they all be from the same file is strict enough so that lowering is ok i think
See the successfully created disable issues here: https://github.com/pytorch/pytorch/issues?q=state%3Aopen%20label%3A%22aggregate%20flaky%20test%20issue%22
(Now we just have to see if they also get updated automatically too)
> [ez][disablebot] Lower threshold for creating aggregate flaky issues 10 -> 4

- aws/tools/cleanup-ssm/Cargo.toml
- aws/tools/cleanup-ssm/src/cleanup.rs
- aws/tools/cleanup-ssm/src/client.rs
- aws/tools/cleanup-ssm/src/filter.rs
- aws/tools/cleanup-ssm/src/lib.rs
- aws/tools/cleanup-ssm/src/main.rs
describe_parameters did not have proper pagination so added some with rate limit handling that should gracefully return what we've collected so far.
Also adds some progress bars to make it easier to observe progress over time.
As well this also adds the ability to specify time with human readable types of input like: `--older-than '1h'`
This was tested already on the PyTorch AWS account and has already deleted > 20k parameters with this.
Output looks like:
> aws: Add pagination, progress bars, and human time

- aws/tools/cleanup-ssm/Cargo.toml
- aws/tools/cleanup-ssm/src/client.rs
- aws/tools/cleanup-ssm/src/filter.rs
- aws/tools/cleanup-ssm/src/lib.rs
- aws/tools/cleanup-ssm/src/main.rs
I had noticed that some of the things we were deleting might be useful like:
```
Would delete: pytorch-labs-cloudwatch_agent_config_runner_linux_nvidia
```
So I added pattern matching to only delete things related to runner spin-up.
> aws: Add regex pattern matching to cleanup-ssm tool

- aws/tools/cleanup-ssm/src/filter.rs
- aws/tools/cleanup-ssm/src/lib.rs
This was being repeated in a bunch of places so we should probably just have a constant for it.
Follow up to @malfet's comment on #6870
> aws: Add const for ONE_DAY_IN_SECONDS

- torchci/lib/bot/autoLabelBot.ts
https://github.com/pytorch/test-infra/pull/6833/files gets reverted because we enabled the auto labeling for too broad code path, so we want to narrow down to symmetric memory only PRs.
> Only add symm memory code path for auto labeling of h100-distributed

- aws/lambda/pytorch-auto-revert/.env.example
- aws/lambda/pytorch-auto-revert/README.md
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
Adds revert category extraction from GitHub comments and excludes `ghfirst` reverts from precision/recall metrics.
- New method `extract_revert_categories_batch()` in `autorevert_checker.py`
- Extracts categories (`nosignal`, `ignoredsignal`, `landrace`, `weird`, `ghfirst`) from GitHub issue comments
- Single batch query for performance
- Now includes category information for each revert
- Uses batch extraction for all reverts at once
- Excludes `ghfirst` reverts from recall calculation
- Shows category breakdown in summary statistics
- Per-workflow precision now shows both total and non-ghfirst metrics
- Fixed `AttributeError: 'NoneType' object has no attribute 'head_sha'`
- Created proper mapping between failures and their newer commits
<details>
<summary>Bug Fix Details</summary> …
> Add revert category extractionand exclude `ghfirst` reverts from stats

- torchci/clickhouse_queries/hud_query/query.sql
This should get filtered out by the workflow_event filters but sometimes the field is empty, maybe because the job is too new?  I'm not sure
Each upload test stats job has a different name, based on the job its uploading stats for, so whenever I open the "other" category, which is where these jobs go into, it takes a very long time
> [ez][HUD] Filter out upload test stats in hud query

- aws/lambda/clickhouse-replicator-s3/lambda_function.py
- clickhouse_db_schema/infra_metrics.cloudwatch_metrics/schema.sql
The timestamp used by cloudwatch has milliseconds, so change the timestamp field to match that
Testing: replaced the old table, then ran `python tools/rockset_migration/s32ch.py --clickhouse-table "infra_metrics.cloudwatch_metrics" --stored-data t.json --s3-bucket fbossci-cloudwatch-metrics --s3-prefix ghci-related `
> [ez][CH] Fix infra_metrics.cloud.watch_metrics schema: use DateTime64

- .github/scripts/get_tutorials_stats.py
This PR adds file status information Added (A), Copied (C), Deleted (D), Modified (M), Renamed (R) to the tutorial statistics tracking. The change enhances the `get_tutorials_stats.py` script to capture Git status information using the `--name-status` flag and store it in the `filenames.csv` output.
Changes:
*   Added status field to FileInfo class
*   Modified file parsing logic to extract status information from Git output
*   Status is now included in the **filenames.csv** output for each file
Local test generates this `filenames.csv`:
| commit_id | date | filename | lines_added | lines_deleted | status |
|-----------|------|----------|-------------|---------------|--------|
| 7c45ceb313 | 2025-07-11 | tutorials/index.rst | 17 | 171 | M |
| f4dda5dca1 | 2025-07-10 | tutorials/conf.py | …
> Add file status to tutorial statistics

- .github/workflows/trigger_nightly.yml
Add torchtitan to the nightly build trigger so that every night, `main` is cut into a `nightly` branch, which can then be built and released on the PyTorch Index. 
Pre-reqs: @tianyu-l has already added the pytorch-bot to the torchtitan repo and given it write permissions.
> Update ``trigger_nightly.yml`` to add torchtitan

- .github/workflows/build_wheels_macos.yml
Reverts pytorch/test-infra#6847
I believe revert is required I see its failing quite badly: https://github.com/pytorch/vision/actions/runs/16174574484/job/45656408659
> Revert "Add miniconda install=true to build_wheels_macos.yml"

- torchci/components/commit/WorkflowBox.tsx
Why:
1. Remove custom styling and just have MUI handle it
2. So I can put another drop down on the right without taking up a ton of vertical space
Old:
New:
The pics don't make it super obvious but from what I can tell:
1. heading part (with the buttons + title) became slightly shorter
2. workflow name (ex `pull`) became slightly larger
> [HUD] Use stacks for WorkflowBox

- .github/workflows/check-alerts.yml
- tools/torchci/check_alerts.py
Denoises alerts by limiting them to the most important viable/strict upgrade blocking failures 
Testing: Ran script locally to verify it only considered the expected set of workflows
> [BE] Limit trunk failure alerts to viable-strict breaking failures

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
This is a refactor of scale-down to move the runner removal logic up to the top of the loop. This is done to avoid long wait times between determining if a runner should be removed and actually removing it.
In practice we were observing wait times of up to 7 to 10 minutes.
This might only actually be testable with production traffic / rate limits.
> runners: Move runner removal logic up

- tools/linter/adapters/pip_init.py
Fixes lintrunner init when uv is installed locally and used to generated the venv, porting over `uv` related fixes from https://github.com/pytorch/pytorch/blob/main/tools/linter/adapters/pip_init.py
> [BE] Fix lintrunner init for uv based environments

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
This adds an expiration policy to the SSM parameters for the runners. This is to ensure that the parameters are deleted after 30 minutes.
Github Runner Tokens typically have a 1 hour expiration time, but our runners are typically expected to be up way quicker than that so 30 minutes is a good balance for when we expect the runners to be up.
If a runner isn't conencted to Github by at least 30 minutes we will more than likely have spun it down and it will be deleted.
This is an attempted re-land of 2 commits:
* #6855
* #6858
> runners: Add expiration policy to SSM parameters

- torchci/components/benchmark/compilers/common.tsx
TSIA, running from sample benchmark from https://github.com/pytorch/pytorch/pull/158011
https://torchci-git-fork-huydhn-add-b200-benchmark-fbopensource.vercel.app/benchmark/compilers?dashboard=torchinductor&startTime=Sat%2C%2005%20Jul%202025%2005%3A38%3A21%20GMT&stopTime=Sat%2C%2012%20Jul%202025%2005%3A38%3A21%20GMT&granularity=hour&mode=inference&dtype=bfloat16&deviceName=cuda%20(b200)&lBranch=enable-b200-benchmark&lCommit=5144d1552a4cd59d007f42c3744044cb30b044ed&rBranch=enable-b200-benchmark&rCommit=5144d1552a4cd59d007f42c3744044cb30b044ed
cc @nWEIdia
> [ez] Adding results from B200 benchmark to TorchInductor dashboard

- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
- torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
As reported by @aorenste where [a100 results were not loaded on the dashboard](https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Wed%2C%2009%20Jul%202025%2023%3A22%3A18%20GMT&stopTime=Wed%2C%2016%20Jul%202025%2023%3A22%3A18%20GMT&granularity=hour&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=&rBranch=main&rCommit=).  The bug here is in the SQL queries where `arch` is now set correctly to `a100` by HUD.  On the other hand, this legacy field in the database is empty because `a100` was the only arch in the past and wasn't set explicitly.
With the work that @yangw-dev plans to do, these queries would likely not staying around for much longer.  So, I just opt for the easy fix of handling `a100` explicitly. …
> [EZ] Fix TorchInductor CH queries for A100

- .github/workflows/linux_job_v2.yml
Use `inputs.docker-image` to explicitly provide the docker image to be used.
Relates to: https://github.com/pytorch/ao/pull/2562
> Remove ROCm docker image default in linux_job_v2.yml

- torchci/components/commit/CommitInfo.tsx
- torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
- torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
There's one for commit and one for PR, but they're mostly the same
Only difference I found:
* Commit has commit title - so I added an `isCommitPage` param to CommitInfo (there's already one in the CommitStatus component so I figured why not)
* data fetch in PR checks if sha is null - changed to sha && url to get the same functionality
Should have no UI changes
> [BE][HUD] Create unified CommitInfo component

- .github/workflows/lint.yml
remove sarif upload
I think this causes comments like 
I don't like it because I'd rather just look at the lint job, depending on the linter it puts comments on unrelated lines, and when it does comment on the right line it doesnt suggest changes so you still have to run lintrunner yourself
> [CI] Remove sarif upload in lint

- torchci/clickhouse_queries/commit_jobs_query/params.json
- torchci/clickhouse_queries/commit_jobs_query/query.sql
- torchci/components/commit/CommitInfo.tsx
- torchci/components/commit/CommitStatus.tsx
- torchci/components/commit/WorkflowBox.tsx
- torchci/lib/fetchCommit.ts
- torchci/pages/api/[repoOwner]/[repoName]/commit/[sha].ts
When multiple workflows run on the same commit (ex memory leak check + non mem leak check), HUD tries to filter the results so that only the most recent job is shown, but sometimes I want to find older ones.
An unfortunately large change because we usually query jobs for the entire commit instead of workflow by workflow
I reused the commit query because it already queries the necessary fields (name id time duration etc) and didn't want to write another query that we would have to keep in sync
Open to better solutions for how to get this data b/c imo this is kind of ugly
TODO: also handle reruns, better error handling
New
Probably review https://github.com/pytorch/test-infra/pull/6922 first
> [HUD] Selector for workflow id in commit and PR pages

- torchci/components/layout/NavBar.module.css
- torchci/components/layout/NavBar.tsx
- torchci/styles/globals.css
- Fixed dropdown menus (Metrics ▾, Benchmarks ▾, Dev Infra ▾) that were navigating to pages instead of expanding on mobile
- Resolved z-index stacking issues causing dropdowns to appear behind other menu items
1. Mobile touch handling: Added touch device detection to prevent navigation and enable proper dropdown toggling on mobile devices
2. Z-index fix: Removed z-index: 9999 from navbar <li> elements to prevent stacking context conflicts
- Touch devices now use onClick to toggle dropdowns with preventDefault() to stop navigation
- Non-touch devices continue using hover behavior
- Removing z-index from parent elements allows dropdown z-index to work correctly in the document's root stacking context
---
Before:
https://github.com/user-attachments/assets/f9810299-75b4-47cb-8bb0-f51d0c9b051e …
> [BE][HUD] Improve dropdown behavior on touch devices

- torchci/components/layout/NavBar.module.css
- torchci/components/layout/NavBar.tsx
Made navbar responsive to prevent content cutoff at typical laptop resolutions (~1300-1400px)
---
laptop screen:
shrunk screen:
mobile:
laptop screen:
shrunk screen:
mobile:
> [BE][HUD] Enhance navbar responsiveness

- .github/actions/setup-nvidia/action.yml
Mitigating CVE-2025-23266
Tested by
```
sudo sudo yum install -y \
nvidia-docker2 \
nvidia-container-toolkit-1.17.8 \
libnvidia-container-tools-1.17.8 \
libnvidia-container1-1.17.8 \
nvidia-container-toolkit-base-1.17.8
```
and 
```
docker run --rm --gpus all nvidia/cuda:12.2.0-base-ubuntu22.04 nvidia-smi
```
on a runner, which resulted in
```
Unable to find image 'nvidia/cuda:12.2.0-base-ubuntu22.04' locally
12.2.0-base-ubuntu22.04: Pulling from nvidia/cuda
aece8493d397: Pull complete
9fe5ccccae45: Pull complete
8054e9d6e8d6: Pull complete
bdddd5cb92f6: Pull complete
5324914b4472: Pull complete
Digest: sha256:ecdf8549dd5f12609e365217a64dedde26ecda26da8f3ff3f82def6749f53051
Status: Downloaded newer image for nvidia/cuda:12.2.0-base-ubuntu22.04
Fri Jul 18 18:59:36 2025 …
```
> update nvidia-container-toolkit to 1.17.8

- torchci/lib/JobClassifierUtil.ts
Some pull and trunk jobs had newer naming conventions, so they were getting dumped in the "other" category on HUD where failures are harder to notice.  Creating a new "other" category just for viable/strict blocking jobs in a place where the eye is more easily to notice the failure
Adds a new "Other viable/strict blocking" category for jobs on the HUD home page
New group and the jobs it contains:
> Move all viable/strict blocking jobs closer to the beginning

- tools/scripts/generate_binary_build_matrix.py
``cxx11-abi`` was removed from file name in all libtorch builds.
This should fix validation of these builds here: https://github.com/pytorch/test-infra/actions/runs/16472470897/job/46565023340
> Fix libtorch file naming in matrix

- torchci/pages/sli.tsx
Fix SLI page navigation and scroll issues
This PR fixes two issues on the /sli page:
1. Scroll position was locked at the top of the page
2. Navigation hijacking: Clicking navbar links would briefly navigate away but then immediately return to /sli
Changes:
- Added shallow: true to router.push() to prevent full page re-renders when updating URL parameters
- Added pathname check to prevent the useEffect from running when navigating away from the page
> [HUD] Fix SLI page scroll reset and navigation hijacking

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
It's normal for there not being runners available for reuse, those events should not be logged as errors.
> [BE] Use info logs for normal operations

- .github/workflows/linux_job_v2.yml
This PR is part of a family of PRs that migrate the use of the upload-artifact-s3 action to the new version hosted in this repository. Together, they address step 1 of #6755.
All the PRs are:
> Migrate upload-s3 action for workflow linux_job_v2

- .github/workflows/generate_binary_build_matrix.yml
- tools/scripts/generate_binary_build_matrix.py
We will be removing torchaudio from getting started page. However would still like to include it in validation.
Test:
```
python  tools/scripts/generate_binary_build_matrix.py --getting-started true
{"include": [{"python_version": "3.9", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux2_28-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_9-cpu", "validation_runner": "linux.2xlarge", "installation": "pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly", "upload_to_base_bucket": "no", "stable_version": "2.7.1", "use_split_build": false}, {"python_version": "3.9", "gpu_arch_type": "cuda", "gpu_arch_version": "12.6", "desired_cuda": "cu126", …
```
> Add option to generate matrix for getting started page

- tools/scripts/generate_binary_build_matrix.py
Test :
```
{"include": [{"python_version": "3.9", "gpu_arch_type": "cpu", "gpu_arch_version": "", "desired_cuda": "cpu", "container_image": "pytorch/manylinux2_28-builder:cpu", "package_type": "manywheel", "build_name": "manywheel-py3_9-cpu", "validation_runner": "linux.2xlarge", "installation": "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu", "channel": "nightly", "upload_to_base_bucket": "no", "stable_version": "2.7.1", "use_split_build": false}, {"python_version": "3.9", "gpu_arch_type": "cuda", "gpu_arch_version": "12.6", "desired_cuda": "cu126", "container_image": "pytorch/manylinux2_28-builder:cuda12.6", "package_type": "manywheel", "build_name": "manywheel-py3_9-cuda12_6", "validation_runner": "linux.g5.4xlarge.nvidia.gpu", …
```
> Fix libtorch nightly binaries links 2

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/do_restart.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
- aws/lambda/pytorch-auto-revert/requirements.txt
Adds workflow restart capability to the PyTorch auto-revert tool, enabling automatic re-running of workflows for commits that match autorevert patterns but haven't been reverted yet.
- Added restart methods to WorkflowRestartChecker:
- restart_workflow(): Restarts a workflow for a specific commit with duplicate prevention
- Checks ClickHouse for existing restarts before attempting
- Enhanced autorevert-checker command:
- Added --do-restart flag to enable automatic workflow restarts
- Added --dry-run flag to preview restart actions without execution
- Restarts workflows only for non-reverted commits matching autorevert patterns
- Fixed workflow naming consistency:
- Normalized workflow names by removing .yml extension for ClickHouse queries
- Added .yml extension only for GitHub API calls …
> [autorevert] Add workflow restarts

- aws/ami/windows/scripts/Installers/Install-VS.ps1
The old pinned version `ltsc.17.8` will cause an illegal instruction issue, we need to upgrade vs2022 to greater than `17.9.3`: https://github.com/pytorch/pytorch/issues/145702#issuecomment-2863244306
For old pinned version is for https://github.com/nerfstudio-project/nerfstudio/issues/3157, and for cuda 11.8 and 12.1 builds.
1. Currently we already support cuda since 12.6.
2. `nerfstudio` fixed issue since CUDA 12.4: https://github.com/nerfstudio-project/nerfstudio/issues/3157#issuecomment-2166986017.
> update vs2022 to fix illegal instruction.

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
They way that the lambdas are structured and the terraform is setup, it is not possible to pass newlines as environment variables.
So the github app key, that is a private key, needs to be b64 encoded.
> Base64 decode the app secret for pytorch-auto-revert lamba

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
Pending job detection was incorrect.
- Before: `has_pending_jobs` checked `status == "pending"`, which GitHub Actio
ns does not emit; statuses are typically `queued`, `in_progress`, `completed`.
- Now: Treat any job with `status != "completed"` as pending.
> [autorevert] fix pending job check

- torchci/components/common/RegexButton.tsx
- torchci/components/hud/GroupHudTableHeaders.tsx
- torchci/components/job/JobFilterInput.tsx
- torchci/lib/GeneralUtils.ts
- torchci/lib/types.ts
- torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Add a button toggle to filter jobs by regex on the main HUD page based off the one in the cost analysis page
Follow up PR for the cost analysis page to also use the component: https://github.com/pytorch/test-infra/pull/6986
Reason:
* Sometimes I want to search for something kind of specific that the current job filtering doesn't handle, like "linux jobs but only on pull"
Changes:
* Add new component for the regex toggle button
* Changes the styling of the input text box and search button to be larger
* The HUD table is shifted slightly down but not by much
Old:
New:
> [HUD] Add option to filter jobs on main page by regex

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
This table shows the raw data from each commit / workflow / job that the dashboard uses to draw the chart.  However, it screwed up when the same metric appears multiple times on one commit.
For example, there are four `median_itl_ms` metrics on vLLM dashboard for each commit, one for each qps `[1, 4, 16, inf]`, while there is only one latency metric on the commit.  On the [dashboard](https://hud.pytorch.org/benchmark/llms?startTime=Fri%2C%2001%20Aug%202025%2023%3A34%3A26%20GMT&stopTime=Fri%2C%2008%20Aug%202025%2023%3A34%3A26%20GMT&granularity=hour&lBranch=main&lCommit=b2c8ce57c68db0764a49d66f048b8a7a5cef9d13&rBranch=main&rCommit=808a7b69df479b6b3a16181711cac7ca28a9b941&repoName=vllm-project%2Fvllm&benchmarkName=&modelName=meta-llama%2FLlama-4-Scout-17B-16E-Instruct&backendName=All%20Backen …
> Correctly populate metric values for each commit

- aws/ami/windows/scripts/Installers/Install-VS.ps1
- aws/ami/windows/windows.pkr.hcl
I believe we should be good to do another Windows AMI deployment. Hence proposing this PR
> Reapply "Support clang in MSVC and removal of Visual Studio 2019"

- torchci/pages/metrics.tsx
- torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Fixes https://github.com/pytorch/test-infra/issues/6939
Add time range, granularity, percentile to permalink (previously only had job names)
Also fixes percentile picker to use value instead of default value so the values from the router will be used?
Should have no visual changes
Is there a better way to do retrieve the router info?  This seems really annoying
> [HUD][TTS] Add granularity, time, etc to permalink

- torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
- torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
- torchci/lib/benchmark/llms/utils/llmUtils.ts
Fixes https://github.com/pytorch/test-infra/issues/6974
Input and output lengths are new dimensions on the dashboard that needs to be displayed after https://github.com/pytorch/pytorch-integration-testing/pull/42.  This PR also cleans up some old TODO code path for vLLM dashboard.
Different input and output lengths are showing up correctly now with their benchmark results on [the preview](https://torchci-git-fork-huydhn-query-input-output-length-fbopensource.vercel.app/benchmark/llms?startTime=Sat%2C%2002%20Aug%202025%2001%3A35%3A55%20GMT&stopTime=Sat%2C%2009%20Aug%202025%2001%3A35%3A55%20GMT&granularity=day&lBranch=main&lCommit=0edaf752d7482a3c170c25376c466e730ab87ddd&rBranch=main&rCommit=e5ebeeba531755a78f68413e88a23d061404f3e3&repoName=vllm-project%2Fvllm&benchmarkName=&modelName=meta-l …
> Show input and output length on vLLM dashboard

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/event_logger.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
- clickhouse_db_schema/misc.autorevert_events/schema.sql
Core changes:
* add clickHouse event logging: log detection, restart outcomes, and secondary c
onfirmations to `misc.autorevert_events`
* define schema for `misc.autorevert_events`
Misc:
* allow `--dry-run` after the `autorevert-checker` subcommand.
locally:
```
python -m pytorch_auto_revert autorevert-checker inductor --hours 164 --do-restart --do-revert --dry-run
```
patterns were detected, events were logged
> [autorevert] Add event logging for autorevert actions

- .github/workflows/trigger_nightly.yml
- aws/lambda/README.md
- tools/torchfix/README.md
- torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
This PR replaces all instances of `pytorch-labs` with `meta-pytorch` in this repository now that the `pytorch-labs` org has been renamed to `meta-pytorch`
- Replaced all occurrences of `pytorch-labs` with `meta-pytorch`
- Skipped binary files and files larger than 1MB due to GitHub api payload limits in the script to cover all repos in this org. Will do a more manual second pass later to cover any larger files
This PR updates files that contained the target text.
Generated by automated script on 2025-08-12T22:48:48.097834+00:00Z
> [EZ] Replace `pytorch-labs` with `meta-pytorch`

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
fixing a regression from https://github.com/pytorch/test-infra/pull/7013 
Root cause: The `@cached_property` decorator was removed from `WorkflowRestart
Checker.resolver`, but callsites still use `self.resolver.require(...)`, treatin
g it like a property.
<details>
<summary> python -m pytorch_auto_revert</summary>
```
Fetching commits for workflow(s) 'Lint, trunk, pull, inductor' (last 16h)...
Commit data by workflow:
Fetching workflow data for 4 workflows since 2025-08-13T23:02:58.374241...
Found 38 commits with job data for workflow 'Lint'
Found 39 commits with job data for workflow 'inductor'
Found 41 commits with job data for workflow 'pull'
Found 39 commits with job data for workflow 'trunk'
Lint: 38 commits
trunk: 39 commits
pull: 41 commits
inductor: 39 commits
✓ 1 AUTOREVERT …
```
> [autorevert] fix regression

- .github/workflows/check-alerts.yml
- tools/torchci/check_alerts.py
- tools/torchci/requirements.txt
- tools/torchci/tests/test_check_alerts.py
HUD failing job alerts handles failures that move across shards and remove logic that supports features that I don't think are really used effectively
Changes
* Swap runner to 24.04 which has default python version 3.12 so I can take advantage of 3.11 features (StrEnum)
* Upgrade setuptools for 3.12?
* Alert can now track failures that jump shards
* failure -> pending -> failure is now considered a continuous failure
* Remove the flaky stuff (it wasn't doing anything I think)
* Remove tracking which sha it started it (didn't show up in the comment, only the issue body -> doesn't get sent in chat -> basically ignored)
* Remove requirement that failure captures need to be the same for a failure to be considered continuous (I think this is ok to remove because I don't think we see that many …
> [alerts] HUD failing job alerts handles failures that move across shards and a lot of other changes

- .github/scripts/validate_scale_config.py
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
fixes: https://github.com/pytorch/test-infra/issues/6688 allow us to use different AMI for testing
> Windows AMI: Add possibility to use different owners specified in the filter param

- torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
- torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
TIL, these two queries has a bug in which the literal `_`, which is part of the output filename, is actually treated as a wildcard matching one alphanumeric character https://www.w3schools.com/sql/sql_like.asp.  So, a `LIKE` statement such as `%_float16` would match both `abc_float16` and `abc_bfloat16` where the `_` matched with `b`.
Before, broken parsing in `float16` [MPS dashboard](https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Fri%2C%2008%20Aug%202025%2008%3A40%3A45%20GMT&stopTime=Fri%2C%2015%20Aug%202025%2008%3A40%3A45%20GMT&granularity=hour&mode=inference&dtype=float16&deviceName=mps&lBranch=main&lCommit=a7c75ae976ffd3352b68b21fe8300c393c9ea52b&rBranch=main&rCommit=3a562374401113187ce2566b87e3f1d87d7c53aa)
After, [2 inductor …
> Fix float16/bfloat16 mix-up on TorchInductor dashboard

- aws/lambda/pytorch-auto-revert/Makefile
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
There are some pending jobs checks that are overly cautious and could be problematic in case of queuing of some exotic type of runner. This can hold autorevert hostage if there is a long queue or an outage in some type of runner that is unrelated to the patterns we're looking for.
When checking for patterns, we don't really care if there are pending jobs for the older commit, as long it is unrelated to the identified pattern.
Already correctly handled, it should retry jobs at first opportunity of a single repeated breaking job.
`has_rule` already checks for failure conclusion. So it is more correct ignore if jobs are still pending and match in the first confirmation. But it is important to only check for the relevant job names if they finished in base, as any newly job could finish as …
> [autorevert] When checking job status, only expect target job list to be finished, not waiting for all jobs to have finished

- .github/actions/setup-binary-builds/action.yml
- tools/scripts/generate_binary_build_matrix.py
I see 3.14 and 3.14t and 3.13t builds failing for vision: https://github.com/pytorch/vision/actions/runs/17097200564/job/48484314516
This should fix it, prior to this PR: https://github.com/pytorch/test-infra/pull/7022
Please see successful builds here: https://github.com/pytorch/test-infra/actions/runs/17102204277/job/48501597067?pr=7036
> Fix vision build for 3.14 and 3.14t and 3.13t build

- torchci/clickhouse_queries/merge_bases/params.json
- torchci/clickhouse_queries/merge_bases/query.sql
- torchci/components/additionalTestInfo/TestCounts.tsx
- torchci/lib/GeneralUtils.ts
- torchci/pages/api/drci/drci.ts
* Change UI to get rid of nesting structure in favor of one big table. This might make it harder to determine which file caused the overall change in test times?  
* Automatically select a sha to do base comparison with
* Move merge base query that was originally in Dr. CI to named query
Some of the code in this PR isn't directly used here but will be used in a different PR
https://torchci-git-csl-tibettertestcountsprview-fbopensource.vercel.app/pytorch/pytorch/commit/72e4786d1635681b8d053d0168c7d16b980e5124
Old
New
> [HUD][Test Insights] Better PR view for test counts

- .github/actions/calculate-docker-image/action.yml
This annoyance is showing up on all pet instances benchmark jobs, for example https://github.com/pytorch/pytorch/actions/runs/17201748116.  As the failure is ignored anyway, let's just pipe that to `true` to silent it.
https://github.com/pytorch/pytorch/pull/161496
> Silent the annotation error when getting docker_hub_readonly_token secret

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Sketching up the new simplified scalable architecture for autorevert.
Introduces a modular Signal abstraction that cleanly separates signal extraction (from jobs/tests/classifications) from pattern detection.
Decouple “how we extract signal” from “how we detect patterns” so we can:
- Incorporate richer sources (tests, multiple failures, classification) without rewriting pattern logic.
- Handle missing/partial signal more gracefully.
- Iterate on detection rules independently.
- Self-contained code much easier to cover in tests.
What’s Implemented
- New core types in pytorch_auto_revert/signal.py & most of the pattern detection logic (the **new one** that we discussed)
- Tests in tests/test_signal.py pending-only and empty commits).
What’s Not Yet Wired / Behavior Changes
- Existing …
> [autorevert] refactoring: extract Signal, decouple pattern detection

- tools/scripts/generate_binary_build_matrix.py
now that CUDA 13.0 aarch64 build is available, add domain builds too
cc @atalman
> Add sbsa CUDA 13.0 domain builds

- torchci/lib/drciUtils.ts
- torchci/test/drci.test.ts
- torchci/test/drciBot.test.ts
No one really attends these so let's just remove this from drci comment.
Also searched the codebase for more office hours references:
```
❯ rg office torchci
```
> drci: Remove OH link

- torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
- torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
- torchci/components/layout/NavBar.tsx
- torchci/lib/benchmark/llms/common.ts
- torchci/lib/benchmark/llms/utils/llmUtils.ts
These changes include adding a new benchmark dashboard for SGLang framework. Most of the implementation for SGLang is similar 
Verified the changes through the HUD dashboard that the SGLang dashboard is fetching the content from the Clickhouse database.
> [HUD] SGLang benchmark integration

- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
This enables autoscalers to use a scale-config that's located in an organization other than the one they're located in, as long as that scale-config is located in a public repo (which all our scale configs currently are).
Bug it fixes: The old code would create a github client to download the scale-config.yml file, but `createGitHubClientForRunnerOrg` will fail if you try to try to create a client for an org your app doesn't have access to.  Using a full blown git client for a public file also seems unnecessary.
This version uses a normal http request to pull the raw file.  So authentication doesn't matter.  (Aside: I considered keeping the old flow as a backup path for if we ever want the scale config to live in a public repo, but if and when that day comes I'd rather we add the logic …
> [autoscalers] Only use auth to download github files if needed

- torchci/components/commit/WorkflowDispatcher.tsx
This PR fixes the wrong trigger for `ciflow/vllm`, the name needs to be the name of the ciflow tag.  It also adds some more tags from https://github.com/pytorch/pytorch/blob/main/.github/pytorch-probot.yml
> Fix vLLM workflow trigger and add few others

- torchci/test/drciBot.test.ts
Realized this mock doesn't matter since we use `@aws-sdk/client-s3` not `aws-sdk`
Some answers from chatgpt about mocking so I don't forget:
`spyOn().mockImplementation` good for mocking single function in a file (also seems to be stricter typed)
`jest.mock('./s3-wrapper/path/to/import')` + `(getS3Client as jest.Mock).mockImplementation(() => mockS3);` good for mocking entire file
After jest29 (?) `mocked(func)` is basically the same as `(func as jest.Mock)` but with better typing?
> [ez][drci] Remove unused mock in test

- torchci/clickhouse_queries/master_commit_red/query.sql
- torchci/clickhouse_queries/master_commit_red_avg/query.sql
- torchci/clickhouse_queries/master_commit_red_percent/query.sql
- torchci/components/job/GroupJobConclusion.tsx
- torchci/pages/metrics.tsx
- torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
Similar to https://github.com/pytorch/pytorch/pull/162100
Reason:
rocm binary builds should not be included in viable strict upgrades and metrics that look at viable strict.  Also add linux-aarch64 to some since that was missing
Is this the correct way to measure trunk redness?  Idk but I want it be consistent with what it says it is (considers only viable/strict blocking jobs) so we don't get confused
Some have spaces after them b/c thats the easier way to guarantee that we won't accidentally include linux-binary-manywheel-rocm when we do regex for linux-binary-manywheel, and convention states that job names that include workflow is `workflow name / job name`.  The places we don't need it are places that only look at workflow name and look for strict equality
> [HUD] Update some queries and regex for better viable/strict job definitions

- terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json
- terraform-aws-github-runner/modules/webhook/lambdas/webhook/src/kms/index.ts
- terraform-aws-github-runner/modules/webhook/lambdas/webhook/src/sqs/index.ts
- terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock
Similar to #7061 
Mostly just getting rid of `promise()`
Testing:
just `yarn test` but idk how helpful that is since it mocks everything
Deployed to pytorch-canary and it seems ok?
> Upgrade webhook lambda for scale up/down to aws sdk v3

- terraform-aws-github-runner/modules/runners/lambdas/runners/jest.config.js
- terraform-aws-github-runner/modules/runners/lambdas/runners/package.json
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-issues.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/kms/index.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/kms/index.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/sqs.test.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/sqs.ts
- terraform-aws-github-runner/modules/runners/lambdas/runners/yarn.lock
Upgrade to aws sdk v3
Main change is getting rid of the `promise` calls since I think they just directly return promises instead of requests
This changes a lot of mocks in the testing so I'm not sure how good running just `yarn test` is
Testing:
Mangled scaleDown to only run `listInstances` and `listSSMParameters`
In `terraform-aws-github-runner/modules/runners/lambdas/runners`:
```
yarn build; cd dist;node -e 'require("./index").scaleDown({}, {}, {});' > t.log    
```
I also tried to terminate a runner and it worked
Deployed to pytorch-canary and ran some jobs, seems ok
> Upgrade scale up/down lambdas to aws sdk v3

- .github/workflows/linux_job_v2.yml
This sets the upload to S3 for docs previews in PRs to overwrite. This is generally in line with standard S3 behavior and should prevent a CI error where repeated builds in PRs fail to upload after the first run, e.g. [here](https://github.com/pytorch/vision/actions/runs/17506203012?pr=9207).
> Set preview docs in PRs to overwrite

- .github/workflows/build_wheels_linux.yml
Fixes https://github.com/pytorch/torchcodec/issues/863
Test:
```
find . -iname libnvcuvid.so*
./usr/lib64/libnvcuvid.so.1
./usr/lib64/libnvcuvid.so.550.127.05
```
> Add capabilities=all when launching cuda container

- torchci/clickhouse_queries/compilers_benchmark_api_query/params.json
- torchci/clickhouse_queries/compilers_benchmark_api_query/query.sql
- torchci/lib/benchmark/api_helper/compilers/precompute.ts
- torchci/lib/benchmark/api_helper/utils.ts
- torchci/lib/benchmark/compilerUtils.ts
- torchci/lib/types.ts
create a sql for compiler time series fetch. 
1.  use the primary keys arch and device instead of extract info from output string. mapping can be different(see  ` New arch values in table` below for mapping details)
2. we fetch list of commits based on timestamp, instead of fetch data from timestamp, this avoid partial data fetch situation that can creating false alert for regression.
list below is nductor distinct device and arch for Pass 3 month from clickhouse oss_ci_benchmark_torchinductor table
```
SELECT DISTINCT device,arch
FROM oss_ci_benchmark_torchinductor
WHERE timestamp >= toUnixTimestamp(now() - INTERVAL 3 MONTH)
```
| device | arch                   | mapping   |
|--------|------------------------|---------|
| cpu    | x86_64                 | cpu(x86_64）        |
| cpu    | …
> improve time series api 

- .flake8
- pyproject.toml
PYFMT and FLAKE8 in test-infra have conflicting setting regarding whitespace before `:`
see:
https://github.com/pytorch/test-infra/actions/runs/17688919062/job/50279032133?pr=7111#step:5:90
https://github.com/pytorch/test-infra/actions/runs/17687778066/job/50275995128?pr=7111#step:5:87
this disables the check in FLAKE8 but leaves it in PYFMT
```
lintrunner
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
FLAKE8 success!
TYPEIGNORE success!
MYPY success!
NOQA success!
SPACES success!
NEWLINE success!
TABS success!
PYPIDEP success!
ACTIONLINT success!
EXEC success!
LINTRUNNER_VERSION success!
PYFMT failure
COPYRIGHT success!
RUFF success!
SQLFLUFF success!
SQL_PARAMS success!
RUSTFMT success!
>>> Lint for …
```
> [BE] Update flake8 configuration to ignore E203 for Black compatibility

- aws/lambda/pytorch-auto-revert/SIGNAL_EXTRACTION.md
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/hud_renderer.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/job_agg_index.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_types.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/hud.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_extraction.py
Implementation of the signal extraction layer and visual report generation utility.
```
python -m pytorch_auto_revert hud Lint trunk pull inductor  --hours 32  --ignore-newer-than 30e16d638953d2 --out hud01.html
INFO:root:[hud] Start: workflows=Lint,trunk,pull,inductor hours=32 repo=pytorch/pytorch
INFO:root:[hud] Extracting signals ...
INFO:pytorch_auto_revert.signal_extraction_datasource:[extract] Fetching jobs: repo=pytorch/pytorch workflows=Lint,trunk,pull,inductor lookback=32h
INFO:pytorch_auto_revert.signal_extraction_datasource:[extract] Jobs fetched: 30018 rows in 38.83s
INFO:pytorch_auto_revert.signal_extraction_datasource:[extract] Fetching tests for 6899 job_ids (622 failed jobs) in batches
INFO:pytorch_auto_revert.signal_extraction_datasource:[extract] Test batch 1/7 …
```
> [autorevert] add signal extraction layer for transforming CI data into Signal objects

- terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
This updates the nvidia driver to `580.82.07` to add support for CUDA 13.0 runtime.
This is similar to https://github.com/pytorch/pytorch/pull/162531 but for our entire fleet
> Update NVIDIA driver to 580.82.07

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/job_agg_index.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_types.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_dedup.py
**Signal event deduplication and timestamp handling:**
* Added a deduplication step in `SignalExtractor` to remove duplicate signal events within commits, based on identical `(started_at, wf_run_id)` pairs. This addresses issues with "rerun failed" jobs in GitHub workflows that reuse the same underlying job (but reports them with different job ids)
* For test-track signals, extract start_date from the specific job that hosted the test (when available)
* Changed all job and signal timestamp fields (`started_at`, `created_at`) to be non-optional and default
> [autorevert] non nullable dates & dedup

- .lintrunner.toml
- s3_management/manage.py
- s3_management/update_dependencies.py
Enable ruff linter on s3 management scripts.  Some entries are removed from `s3_management/update_dependencies.py` because they are duplicated
> [ez] Apply ruff linter to s3 management scripts

- .github/workflows/update-drci-comments.yml
- torchci/lib/bot/pytorchBotHandler.ts
- torchci/pages/api/drci/drci.ts
Goal: Makes Dr. CI work across both pytorch and meta-pytorch orgs
Fixes:
- Update workflow to include org parameter for each repository
- Dr.CI API replaces hardcoded OWNER references with inputted org (pytorch/meta-pytorch only)
> Extend Dr.CI API to support meta-pytorch org

- aws/lambda/pytorch-auto-revert/SIGNAL_ACTIONS.md
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/utils.py
RevertAction.RUN_LOG  (side-effects=True)
Semantics:
1. provides a production-like deduplication, but doesn't have side effects beyond creating a log record with dry-run=0
2. a default mode for lambda entry point (main call without subcommand)
> [autorevert] introduce RevertAction.RUN_LOG with deduplication on write

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
Explanation from gpt-5-codex:
> Info-level lines from the new flow disappear in Lambda because of how Python logging behaves once the runtime has already attached its own handler. On every cold start AWS sets up the root logger with a handler that streams to CloudWatch and leaves the logger at its default WARNING level. Python’s logging.basicConfig(...) (which setup_logging calls
in pytorch_auto_revert/__main__.py:24) only configures the root logger when it has no handlers; if one is already present, the call is a no-op—no level change, no formatter change. Even though LOG_LEVEL is DEBUG, we never actually lower the root logger’s threshold, so logging.info(...) statements from testers/autorevert_v2.py respect the still-
WARNING root level and get filtered out. The lone line you’re seeing …
> [autorevert] Configure root logger for AWS lambda

- aws/lambda/pytorch-auto-revert/README.md
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/hud_renderer.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/run_state_logger.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert_v2.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/hud.py
features:
1. added ability to render html hud-like signal grid from the timestamp of the autorevert run:
```
python -m pytorch_auto_revert hud "2025-09-17 17:44:14"
python -m pytorch_auto_revert hud "2025-09-17 17:44:14" --hud-html hud01.html
```
2. added optional flag to `pytorch_auto_revert` to render run results in the same format:
```
python -m pytorch_auto_revert --dry-run autorevert-checker Lint trunk pull inductor rocm rocm-mi300 --hours 18  --hud-html hud.html
```
other changes:
1. the old state wasn't logging outcomes cleanly, added that
2. introduced state versioning
3. legacy state format is supported for backward-compatibility (although it's missing some non-critical info)
----
> [!WARNING]
> Disclaimer: the code (in particularly the renderer) is mostly vibecoded and **is …
> [autorevert] Add hud-like HTML grid rendering for the logged state and `autorevert-checker` subcommand

- torchci/components/benchmark/llms/LLMsBenchmarkPage.tsx
- torchci/components/benchmark/llms/components/ProfilingArtifactsTable.tsx
- torchci/components/benchmark/llms/components/VllmArtifactsTable.tsx
- torchci/lib/benchmark/llms/utils/artifacts.ts
- torchci/pages/api/artifacts/index.ts
- Implemented a Generic approach for showing profiling traces for any repository.
- Implemented filters for showing profiling traces based on "time_range", "model_name", "device_type" and "device_architecture".
- Verified through the HUD Dashboard for a scenario when we have profiling traces for a model (i.e. `repo`: `vllm` and `model`: `facebook\opt-125m`) : [link](https://torchci-6vl6o8lmz-fbopensource.vercel.app/benchmark/llms?startTime=Sat%2C%2013%20Sep%202025%2022%3A45%3A56%20GMT&stopTime=Sat%2C%2020%20Sep%202025%2022%3A45%3A56%20GMT&granularity=day&lBranch=main&lCommit=3e903b6cb4292ca1425a37cb809c1e3cddfdadcb&rBranch=main&rCommit=d88918e4c2d189eb25724a6cff9a9028c67daa07&repoName=vllm-project%2Fvllm&benchmarkName=&modelName=facebook%2Fopt-125m&backendName=All%20Backends&modeName=All%2 …
> [HUD] [vLLM Profiling] Fix S3 path and add more filters for vLLM Profiling

- aws/lambda/benchmark_regression_summary_report/common/benchmark_time_series_api_model.py
data model class for api response should not be strict for additional fields
> Make the api response check loose to accept unknown extra keys

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_circuit_breaker.py
This adds a circuit breaker to pytorch autorevert. This can be accomplished by opening an issue on pytorch/pytorch with a tag `ci: disable-autorevert`. 
The decision to NOT gatekeep who are the users that can disable autorevert is based on `ci: sev`. Currently any user that can open a issue in PyTorch can add a `ci: sev` issue that is merge blocking. If we believe this is a safe action and does not require getekeeping, surely it is OK to disable autorevert with the same level of access.
> [AUTOREVERT] Adds circuit breaker with issue in pytorch/pytorch 'ci: disable-autorevert'

- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/validate-binaries.yml
- .github/workflows/validate-linux-binaries.yml
- tools/scripts/generate_binary_build_matrix.py
- tools/tests/assets/build_matrix_linux_wheel_cuda.json
- tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
- tools/tests/assets/build_matrix_linux_wheel_nocpu.json
- tools/tests/assets/build_matrix_linux_wheel_xpu.json
- tools/tests/assets/build_matrix_macos_wheel.json
- tools/tests/assets/build_matrix_windows_wheel_cuda.json
- tools/tests/assets/build_matrix_windows_wheel_xpu.json
I believe split-build was removed from pytorch/pytorch this PR removes some split-build artifacts from test-infra repo
> [BE] Cleanup split-build logic

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Previously the code was trying to group branches for restarts resulting from "infra check" and from "insufficient events", and this was a mistake, resulting in delayed restarts.
Specifically, in this situation:
a restart on the success side is expected, but the system waits for pending job on the failure side.
This PR decouples and simplifies the logic. Now, all restarts are scheduled independently (relying on set deduplication) and all final checks are performed afterwards.
Added a unit test to specifically verify the case above.
> [autorevert] fix handling for insufficient successes

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
Before:
```
(venv) ivanzaitsev@ivanzaitsev-mbp pytorch-auto-revert % python -m pytorch_auto_revert hud
2025-09-29 12:12:37,159 WARNING [pytorch_auto_revert.clickhouse_client_helper] Connection test failed: HTTPDriver for https://hyt81izu0c.us-east-1.aws.clickhouse.cloud:8443 received ClickHouse error code 516
Code: 516. DB::Exception: revert_lambda: Authentication failed: password is incorrect, or there is no user with such name. (AUTHENTICATION_FAILED) (version 25.6.2.6151 (official build))
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/Users/ivanzaitsev/test-infra/aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py", line 336, in <module>
main()
File …
```
> [autorevert] fix local cli

- tools/scripts/generate_binary_build_matrix.py
Only nightly should have been updated in #7237.
> [ROCm] revert binary build matrix for test and release

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
Accidentally noticed another bug introduced by https://github.com/pytorch/test-infra/pull/7241 when testing locally on the large lookback windows:
```
python -m pytorch_auto_revert --dry-run autorevert-checker periodic --hours 256 --bisection-limit 2   --hud-html
2025-09-29 15:56:16,356 INFO [root] [v2] Start: workflows=periodic hours=256 repo=pytorch/pytorch restart_action=log revert_action=log notify_issue_number=163650
2025-09-29 15:56:16,356 INFO [root] [v2] Run timestamp (CH log ts) = 2025-09-29T22:56:16.356213+00:00
2025-09-29 15:56:16,356 INFO [pytorch_auto_revert.signal_extraction_datasource] [extract] Fetching commits in time range: repo=pytorch/pytorch lookback=256h
2025-09-29 15:56:16,909 INFO [pytorch_auto_revert.signal_extraction_datasource] [extract] Commits fetched: 419 …
```
> [autorever] fix indentation in `fetch_tests_for_job_ids`

- torchci/clickhouse_queries/vllm/merges_percentage/params.json
- torchci/clickhouse_queries/vllm/merges_percentage/query.sql
- torchci/components/layout/NavBar.tsx
- torchci/pages/metrics/vllm.tsx
This PR has two parts, the query `vllm/merges_percentage` and a new HUD page `metrics/vllm.tsx` to display vLLM CI metrics.  There are 2 KPIs to start with:
1. The % of force merges with CI failures.  Its meaning is clear.
2. The % of manual merges where a vLLM maintainer merged the pull request manually without using GitHub auto-merge. But there wasn't any failures in the pull request at the time of the merge.
As vLLM CI is on Buildkite, a CI failure means a failed Buildkite job that (1) is not a soft fail, and (2) fails on its latest retry at the time of the merge.  We can get this information by joining the GitHub `pull_request` with Buildkite `vllm_buildkite_jobs` on the pull request number.
https://torchci-git-vllm-metrics-fbopensource.vercel.app/metrics/vllm
cc @rzabarazesh …
> Add vLLM CI metrics

- .github/workflows/update-drci-comments.yml
I noticed that the calls to update dr ci were failing since they are now in the meta-pytorch org.
I did not check that the drci api works after this
> [ez][drci] Switch drci update for data and torchtune to meta-pytorch org

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/hud_renderer.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/job_agg_index.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/run_state_logger.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_actions.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_actions.py
- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/utils.py
Here is an example of how the new links look like:
[2025-09-30T23-38-21.914320-00-00.html](https://github.com/user-attachments/files/22628924/2025-09-30T23-38-21.914320-00-00.html)
autorevert message changes verified with unit tests.
> [autorevert]  add job & hud links to the autorevert message and debug grid

- aws/lambda/pytorch-auto-revert/Makefile
Setting the makefile targets to point to `pytorch/pytorch-canary` as an example.
> [AUTOREVERT] Makefile targets pointing to canary

- aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
see the list of viable strict workflows: https://github.com/pytorch/pytorch/pull/164374/files
testing:
```
HOURS=18 python -m pytorch_auto_revert --dry-run
2025-10-01 11:19:05,293 INFO [root] [v2] Start: workflows=Lint,trunk,pull,inductor,linux-aarch64 hours=18 repo=pytorch/pytorch restart_action=log revert_action=log notify_issue_number=163650 bisection=unlimited
2025-10-01 11:19:05,293 INFO [root] [v2] Run timestamp (CH log ts) = 2025-10-01T18:19:05.293306+00:00
2025-10-01 11:19:05,294 INFO [pytorch_auto_revert.signal_extraction_datasource] [extract] Fetching commits in time range: repo=pytorch/pytorch lookback=18h
2025-10-01 11:19:06,055 INFO [pytorch_auto_revert.signal_extraction_datasource] [extract] Commits fetched: 47 commits in 0.76s
2025-10-01 11:19:06,055 INFO …
```
> [autorevert] Add 'linux-aarch64' to default workflows

- .github/workflows/release-download-pytorch-org.yml
- .github/workflows/release_library_download_pytorch_org.yml
This should allow promotion of ecosystem library from /test/ channel to /prod/
Plan is to allow only certain people to run this workflow.
When triggering the workflow the verison update need to be landed before:
https://github.com/pytorch/test-infra/blob/main/release/release_versions.sh
First run of the workflow needs to be DRY_RUN.
Second run is the promotion
Example of successful run:
https://github.com/pytorch/test-infra/actions/runs/18144952405/job/51644528583
> Enable pytorch ecosystem libraries promotion to prod

- .github/canary-scale-config.yml
- .github/lf-canary-scale-config.yml
- .github/lf-scale-config.yml
- .github/scale-config.yml
This relates to pytorch/test-infra#7175 to add several c7i instance types that we can migrate workflows that currently use c5 instance types over to.
> Add series of c7i instance types

- torchci/clickhouse_queries/compilers_benchmark_api_commit_query/query.sql
- torchci/components/benchmark/v3/components/benchmarkList/BenchmarkCategoryCard.tsx
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/BenchmarkChartSection.tsx
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesChart/BenchmarkTimeSeriesChart.tsx
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesChart/RenderingOptions.ts
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesChartGroup.tsx
- torchci/components/benchmark/v3/components/dataRender/fanout/FanoutComponents.tsx
Add target MarkArea for time series chart when user change the lcommit and rcommit 
Query: compilers_benchmark_api_commit_query
Details: Instead of use distinct, we use GROUP BY to find unique branch, commit, workflowId combo along with a hourly granularity timestamp.
This allow us to target right time range when targeting the MapArea in time series chart and sync with the timeseries data's timestamp
when lcommit and rcommit change, a mapArea in time series chart willl also change. THis helps users to identify where the datapoint they are targeting, reduce confusion.
https://torchci-git-addmarkarea-fbopensource.vercel.app/benchmark/compilers_regression
> Add target MarkArea for time series chart when user change the lcommit and rcommit

- torchci/components/benchmark/v3/components/benchmarkList/BenchmarkCategoryCard.tsx
- torchci/components/benchmark/v3/components/common/navigate.tsx
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesChart/BenchmarkTimeSeriesChartGroup.tsx
- torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesComparisonSection/BenchmarkTimeSeriesComparisonTableSlider.tsx
- torchci/components/benchmark/v3/configs/teams/compilers/CompilerPrecomputeConfirmDialogContent.tsx
- torchci/components/benchmark/v3/pages/BenchmarkRegressionPage.tsx
This just UI render fix when chart has many point, (>40)
make everything dynamically shrink to browser view and no overflow
https://torchci-git-fixwidth-fbopensource.vercel.app/benchmark/compilers_regression
> Fix width for component

- .github/workflows/update_test_file_report.yml
- tools/torchci/test_insights/daily_regression.py
- tools/torchci/test_insights/file_report_generator.py
- torchci/pages/tests/fileReport.tsx
Some small changes bundled together
Fix team name for pytorch dev infra
Remove unused var
Frequency weighting should not include cancelled jobs
Fix file report HUD page overview page calculating averages across commits wrong
When double clicking, set the regex to be false since it's supposed to search for that specific thing (also because the input probably isn't correct regex)
Fix workflow cron if statement
Remove if statement left in from testing
> [ez][testing] file report: route to pytorch-dev-infra team, remove unused var, etc

- .github/workflows/update_test_file_report.yml
- tools/torchci/test_insights/daily_regression.py
- tools/torchci/test_insights/weekly_notification.py
Follow up to https://github.com/pytorch/test-infra/pull/7303 since I fixed the pre-normalized alert thing earlier than expected
Format is a bit weird since the alerting infra isn't really set up for notification style alerts where its never really closed by anything, so it just sends a "resolved" alert right after to prevent open issues from cluttering up the issue list.  Not sure if this is the best way
TODO: move secrets to aws secret manager?  
Testing:
Ran the script a couple of times and saw that issues got created and closed in the alerting repo, also put pull request trigger to see if that would work too and it did
> [testing] file report: notifs go through alerting-infra repo
